### ISSUE TITLE
Clarification about gsl::not_null and tinyxml2 library

### ISSUE THREAD

**Issue by ajtruckle** [microsoft/GSL#1006]
I use the [`tinyxml2`](https://github.com/leethomason/tinyxml2) library and I have a couple of lines of code here:

```
XMLElement* pReminder = m_docReminders.NewElement(CT2CA(rReminder.GetKey(), CP_UTF8));
XMLText *pText = m_docReminders.NewText(CT2CA(rReminder.GetReminder(), CP_UTF8));
```
Code analysis is telling me that these can be defined as `not_null`. So I tried:
```
XMLElement* pReminder = gsl::not_null<XMLElement*>(m_docReminders.NewElement(CT2CA(rReminder.GetKey(), CP_UTF8)));
XMLText *pText = gsl::not_null<XMLText*>(m_docReminders.NewText(CT2CA(rReminder.GetReminder(), CP_UTF8)));
```
And it still flagged them. I was trying to adopt how it was described here https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Ri-nullptr.

What am I doing wrong?

**Comment by dmitrykobets-msft** [comment]
Hi @ajtruckle,
You would want to put `gsl::not_null` around the declared type of the variables, like so:
```
gsl::not_null<XMLElement*> pReminder = m_docReminders....;
gsl::not_null<XMLText*> pText = m_docReminders...;
```
The warning is generated whenever a pointer is dereferenced, but never checked for nullness, in which case it is assumed that the developer intended for the pointer to never be null. `gsl::not_null` communicates this intent better, and also calls `terminate` if it ever does get assigned a `nullptr` value. It might make sense, therefore, to also mark the return type of those two functions (`NewElement` and `NewText`) as `not_null`, if the intent is for their return values to never be null.

**Comment by SloppyJaconda** [comment]
Building upon what @dmitrykobets-msft said above, if those functions have the potential to return null you should not wrap them in not_null and should instead perform a nullness check on variables post assignment.
