### ISSUE TITLE
Split gsl.h

### ISSUE THREAD

**Issue by davidhunter22** [Microsoft/GSL#101]
I noticed that classes like not_null are declared in gsl.h. gsl.h also includes array_view.h and string_view.h. These headers then include a large number of other headers. In the interests of compile times can all the definitions in gsl.h be moved to a separate header file which gsl.h then includes. gslh then becomes a very small file that just includes all the other headers. Users can then choose to use this or the components headers.

**Comment by neilmacintosh** [comment]
It's a reasonable suggestion. The current structure was not particularly carefully designed, and having components that are "more than a using" in their own headers seems sensible. If you have the time and inclination, I would be happy to consider a PR that breaks out the separate headers...

**Comment by neilmacintosh** [comment]
@davidhunter22 PR #215 breaks out more separate headers for a more useful physical design. I'm going to claim that addresses this issue sufficiently for now. Feel free to reopen the issue (or offer a PR) if you think there is further useful decomposition to be done.
