### ISSUE TITLE
narrow casting - please clarify

### ISSUE THREAD

**Issue by ajtruckle** [microsoft/GSL#1018]
Take:

`int iData = gsl::narrow<int>(m_cbAssignment1Type.GetItemData(m_cbAssignment1Type.GetCurSel()));`

`GetItemData` returns a `DWORD_PTR` and in this case the value was `-1`.

I don't understand why the above fails because `int` can accept unsigned values. In teh end I had to use:

`int iData = gsl::narrow_cast<int>(m_cbAssignment1Type.GetItemData(m_cbAssignment1Type.GetCurSel()));`

What am I not understanding?

**Comment by beinhaerter** [comment]
From [MSDN](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/66d61dd8-2191-4a37-b963-e49bf0dc2579):

> A DWORD_PTR is an unsigned long type used for pointer precision. It is used when casting a pointer to an unsigned long type to perform pointer arithmetic. DWORD_PTR is also commonly used for general 32-bit parameters that have been extended to 64 bits in 64-bit Windows. For more information, see ULONG_PTR.

> This type is declared as follows:

> typedef ULONG_PTR DWORD_PTR;

As `DWORD_PTR` is unsigned it cannot be `-1`, it was either 0xffffffffu (x86) or 0xffffffffffffffffu (x64). Both values don't fit into the `int` range (compare `std::numeric_limits<int>::min()` and `std::numeric_limits<int>::max()`.

**Comment by ajtruckle** [comment]
Thank you for the explanation!
