### ISSUE TITLE
Include of <memory> in gsl.h

### ISSUE THREAD

**Issue by davidhunter22** [Microsoft/GSL#102]
Why does gsl.h include <memory> and do
using std::unique_ptr;
using std::shared_ptr;
The gsl.h header does not seem to use anything from <memory> and does not use unique_ptr or shared_ptr decorated with std:: or not.

**Comment by neilmacintosh** [comment]
As per https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#-gslowner-ownership-pointers, these pointers are considered part of the GSL (a minimum set of types required to support the Core Guidelines).

**Comment by davidhunter22** [comment]
If Neil's implication here is that you want unique_ptr and shared_ptr in the Guide namespace that seems reasonable. However I think this should be done in a separate header to gsl.h. Personally I think gsl.h should be split up and gsl.h simply includes all the components. Users should be free to include the sub components of GSL they use. C++ compilation speeds are already horrifically slow without enforcing includes that are not required by end users. If end users don't care about compiles times fine let them include gsl.h but for those of us that do it would be nice to have an alternative.

**Comment by neilmacintosh** [comment]
Your understanding of the reason for their inclusion is correct. The discussion around splitting up headers is probably best continued under your existing issue #101.
