### ISSUE TITLE
Conditional inclusion of <exception> and <stdexcept> in fast_fail.h

### ISSUE THREAD

**Issue by davidhunter22** [Microsoft/GSL#103]
fast_fail.h includes both <exception> and <stdexcept> unconditionally. It should probably be

#if defined(SAFER_CPP_TESTING)
#include <stdexcept>
#else
#include <exception>
#endif

to avoid including unnecessary header files. ( modules any day now!!! )

**Comment by neilmacintosh** [comment]
Yes, it probably should. This would be a simple PR...;-)

**Comment by neilmacintosh** [comment]
Note that <exception> is always required as when not throwing, we call std::terminate(), which is declared in <exception>.

**Comment by neilmacintosh** [comment]
Thanks to Rico's PR this is now fixed.
