### ISSUE TITLE
Remove non-essential null-checking from gsl::not_null 

### ISSUE THREAD

**Issue by dmitrykobets-msft** [microsoft/GSL#1051]
We are thinking of revising the gsl::not_null threat-model to reserve all nullness checking to the constructor, and to trust all created instances post-construction:
```cpp
not_null<int*> a = some_pointer; // check that some_pointer is not null in a's constructor
int* b = a.get(); // no need to check that `a.ptr_` is not null; it's already been checked in a's constructor
not_null<int*> other = a; // no need to check that `a.ptr_` is not null; it's already been checked in a's constructor.  
                          // transitively, `other._ptr_` will now also be trusted
```

This change will remove many existing runtime checks that occur inside `gsl::not_null`, notably the one inside `not_null::get()`, and will overall simplify the design of the `gsl::not_null` type.

**Comment by KindDragon** [comment]
I think the post at the link is relevant to this question https://github.com/microsoft/GSL/issues/930#issuecomment-1347446144
