### ISSUE TITLE
GSL changes that cause ICEs in compilers

### ISSUE THREAD

**Issue by kernhanda** [Microsoft/GSL#108]
What is the suggested approach for changes (my change for #83 in particular is doing this) which are technically correct but cause internal compiler errors in one of the big 3? In this case, I'm seeing issues with VS2015.

**Comment by gdr-at-ms** [comment]
(1) Hopefully, find a repro and report the bug to the compiler vendor.
(2) Suggest a workaround so that GSL continues to "work" on said faulty compiler

**Comment by tamaskenez** [comment]
travis fails also for gcc & clang
