### ISSUE TITLE
About release 4.0.0

### ISSUE THREAD

**Issue by chenrui333** [microsoft/GSL#1080]
👋 while doing [seal 4.1.0 upgrade](https://github.com/Homebrew/homebrew-core/pull/119758), I found the GSL 4.0.0 artifact sha got changed, raising this issue to confirm whether there was git re-tagging happened. Thanks!!

relates to https://github.com/Homebrew/homebrew-core/pull/120029

**Comment by dmitrykobets-msft** [comment]
Hi @chenrui333, indeed there was a retagging in the 4.0.0 release. This wouldn't normally happen but was an exceptional case.

**Comment by chenrui333** [comment]
Appreciate the confirmation, thanks!!
