### ISSUE TITLE
[cmake] GSL.natvis issues

### ISSUE THREAD

**Issue by jpr42** [microsoft/GSL#1084]
Minor problems with the GLS.natvis CMake support

- [ ] find_package isn't supported (IE vpckg, conan, system package managers) don't benefit from GSL.natvis
  - GSL.natvis isn't installed
- [x] Ninja on MSVC isn't supported 
  - https://discourse.cmake.org/t/does-adding-natvis-files-via-target-sources-work-on-ninja/7316
  - This can be solved elegantly with target_link_options (3.13+)

**Comment by dmitrykobets-msft** [comment]
@jpr42 is this issue resolved in #1083?

**Comment by jpr42** [comment]
> @jpr42 is this issue resolved in #1083?

No. I don't have access to a Windows machine so I haven't been able to tackle it.

**Comment by jpr42** [comment]
I recently obtained a Windows laptop. I'll be able to tackle this issue soon.

I'm also asking for general advice on shipping a natvis file from the CMake devs:
https://discourse.cmake.org/t/libraries-and-native-visualization-files-natvis/8069
