### ISSUE TITLE
Design of Final_act is dependent on copy elision to avoid multiple 'final acts'

### ISSUE THREAD

**Issue by jbcoe** [Microsoft/GSL#11]
The move constructor does not flag the moved-from object as non-invokable

    auto invocation_count = 0;
    auto f = finally([&invocation_count]{ ++invocation_count;});
    assert(invocation_count == 1);

If the copy-by-rvalue-reference is not elided (which is possible but not necessary) then the invocation count will be 2. The `final_act` object needs an internal bool to track its state or the C++ standard needs to *require* copy elision. 

See: https://github.com/jbcoe/CppSandbox/blob/master/ScopeGuard/ScopeGuard.cpp

for a similar class.

**Comment by neilmacintosh** [comment]
That's a great point Jonathan. This version of Final_act was just meant to be a initial sketch, and I had a suspicion we'd miss some subtleties in it, like the risk from a lack of copy elision that you point out here.

It would be terrific if you wanted to contribute a PR that improved Final_act to be free of this defect...

**Comment by jbcoe** [comment]
I've added a patch already to fix this and #12

**Comment by neilmacintosh** [comment]
This has now been fixed with PR #90.
