### ISSUE TITLE
CMake Error at CMakeLists.txt:14 (find_package):   Could not find a package configuration file provided by "Microsoft.GSL"

### ISSUE THREAD

**Issue by briviere** [microsoft/GSL#1121]

**Comment by dmitrykobets-msft** [comment]
Hi @briviere could you please point me to the "Chapter02" example you're referring to?

**Comment by briviere** [comment]
Hello Dmitry

I will close this issue.  I created the issue in the wrong git repository (
https://github.com/PacktPublishing/Software-Architecture-with-Cpp/tree/master
).

I did resolve my issue by using the following:

include(FetchContent)

FetchContent_Declare(GSL
    GIT_REPOSITORY "https://github.com/microsoft/GSL"
    GIT_TAG "v4.0.0"
    GIT_SHALLOW ON
)

FetchContent_MakeAvailable(GSL)


thanks

Brian
