### ISSUE TITLE
Missing `swap` for `gsl::not_null` for move-only types

### ISSUE THREAD

**Issue by christianbrugger** [microsoft/GSL#1129]
I want to exchange the content of two `gsl::not_null<std::unique_ptr<int>>`.

I was pretty sure a swap would work, but couldn't get it working. 

```
#include <memory>
#include <algorithm>

#include <gsl/gsl>

auto main() -> int {
    
    auto a = gsl::not_null<std::unique_ptr<int>> {std::make_unique<int>(0)};
    auto b = gsl::not_null<std::unique_ptr<int>> {std::make_unique<int>(1)};

    using std::swap;
    swap(a, b);

    return *a;
}


```
https://godbolt.org/z/64na6e356

This gives an error:
```
no matching function for call to 'swap(gsl::not_null<std::unique_ptr<int> >&, gsl::not_null<std::unique_ptr<int> >&)'
```

I understand that its not possible to move from such a pointer. 
However, not even enabling swap for smart-pointers makes `std::not_null` even less useful.

Is there anything against implementing a custom `swap`, that takes two `not_null` pointers and swaps the underlying, as we know they are both not null?

**Comment by hsutter** [comment]
Maintainers call: Yes, there should be a homogeneous `swap`. We should add a member `not_null<T>::swap(not_null<T>)` and specialize `std::swap(not_null<T>, not_null<T>)`.

**Comment by mbeutel** [comment]
> and specialize `template<typename T> std::swap(not_null<T>&, not_null<T>&)`.

Wait, is specializing function templates from `namespace std` something we do? I thought that was outlawed as a consequence of [P0551](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0551r3.pdf). The current draft [1] only mentions that class templates from `std` may be specialized.

[1] https://eel.is/c++draft/namespace.std#2

**Comment by hsutter** [comment]
Thanks! I think you're correct, we should _overload_ (not specialize) in `gsl::` (not `std::`).
