### ISSUE TITLE
Reproducible build?

### ISSUE THREAD

**Issue by infn-ke** [microsoft/GSL#1137]
I’m seeing build path to gsl appearing in my binary. Does gsl support reproducible builds?

**Comment by hsutter** [comment]
Maintainers call: Sorry for the delay in responding. Can you give any additional information about what kind of paths are showing up in your binaries, or what you'd like this GSL implementation to do different?

**Comment by hsutter** [comment]
Maintainers call: We'll close this for now, but please reopen if there's more information regarding the question above. Thanks!
