### ISSUE TITLE
[Help] About the signed copy of my CLA

### ISSUE THREAD

**Issue by jack17529** [microsoft/GSL#1138]
Hi,

I used to contribute in GSL development some years back and I am unable to find the signed copy of my CLA through DocuSign (It is somehow voided).
I tried emailing at msftclas@microsoft.com but my emails are getting blocked.

I am in an urgent need of showing that to the HR department of my company.

Can somebody please help me in retrieving the document?
If possible can someone please create an Experience letter or Reference Letter?

Thank You

**Comment by dmitrykobets-msft** [comment]
Hi @jack17529, do you know which PR you would have signed the CLA for? I tried searching the PRs with your userid and I don't see any CLA comments. I would expect it to be something like https://github.com/microsoft/GSL/pull/989
