### ISSUE TITLE
C++20 Modules Support?

### ISSUE THREAD

**Issue by Ariaszzzhc** [microsoft/GSL#1139]
At present, the C++ standard has advanced to C++23, and compilers such as gcc, clang, and msvs have already provided support for C++ standard modules, although the support may not be complete. May I ask if there are plans to support C++ modules in this project?

Maybe it will look like:
```cpp
import microsoft.gsl;

int main() {
  gsl::owner<int> value{new int{1}};
  /* ... code ... */
  delete a;
  
  return 0;
}

```

**Comment by soroshsabz** [comment]
I think it is cool feature

**Comment by hsutter** [comment]
Maintainers call: Not at this time. We want this GSL implementation to work portably on all major compilers, so we're waiting for all the three major compilers have non-experimental support for modules.
