### ISSUE TITLE
MSVC: Recent commits break compilation

### ISSUE THREAD

**Issue by diamante0018** [microsoft/GSL#1147]
Hello, I'm afraid one of the most recent commits has broken on MSVC as it now triggers some warnings.

The following does remind me a lot of the first issue I opened on this repo some time ago as it too was an issue with the MSVC preprocessor and the min/max macros. Maybe this is similar?

Dear maintainers, please consider adding an MSVC workflow that tests this repo. I only see one for Android and Ubuntu (Linux)

```
Error: D:\a\DisablePlutoChat\DisablePlutoChat\deps\GSL\include\gsl\util(44,40): error C[22](https://github.com/diamante0018/DisablePlutoChat/actions/runs/8058374482/job/22011065160#step:6:23)20: the following warning is treated as an error [D:\a\DisablePlutoChat\DisablePlutoChat\build\common.vcxproj]
  (compiling source file '../src/common/utils/thread.cpp')
  
Warning: D:\a\DisablePlutoChat\DisablePlutoChat\deps\GSL\include\gsl\util(44,40): warning C4067: unexpected tokens following preprocessor directive - expected a newline [D:\a\DisablePlutoChat\DisablePlutoChat\build\common.vcxproj]
  (compiling source file '../src/common/utils/thread.cpp')
  
Warning: D:\a\DisablePlutoChat\DisablePlutoChat\deps\GSL\include\gsl\util(163,40): warning C4067: unexpected tokens following preprocessor directive - expected a newline [D:\a\DisablePlutoChat\DisablePlutoChat\build\common.vcxproj]
  (compiling source file '../src/common/utils/thread.cpp')
  
Warning: D:\a\DisablePlutoChat\DisablePlutoChat\deps\GSL\include\gsl\span(67,40): warning C4067: unexpected tokens following preprocessor directive - expected a newline [D:\a\DisablePlutoChat\DisablePlutoChat\build\common.vcxproj]
  (compiling source file '../src/common/utils/thread.cpp')
  
Warning: D:\a\DisablePlutoChat\DisablePlutoChat\deps\GSL\include\gsl\span(855,40): warning C4067: unexpected tokens following preprocessor directive - expected a newline [D:\a\DisablePlutoChat\DisablePlutoChat\build\common.vcxproj]
  (compiling source file '../src/common/utils/thread.cpp')
  ```

**Comment by christianbrugger** [comment]
I am having the same issue, it even shows up now in godbolt:

https://godbolt.org/z/cEb1481Yd

The last commit that works for me with gcc is [`caae4dd`](https://github.com/microsoft/GSL/tree/caae4dd0f8343efb879369dcd08a2b18aae59f3b).

I also can confirm that the [pull request](https://github.com/microsoft/GSL/pull/1149) from @beinhaerter fixes the issue for me

**Comment by carsonRadtke** [comment]
@diamante0018 thank you for reporting this issue.

I believe this is a duplicate of https://github.com/microsoft/GSL/issues/1155 and it should be fixed as of https://github.com/microsoft/GSL/pull/1149. Can you confirm?

As for 
> Dear maintainers, please consider adding an MSVC workflow that tests this repo. I only see one for Android and Ubuntu (Linux)

We are currently working on transitioning the test workflows to GitHub Actions. See https://github.com/microsoft/GSL/pull/1159.

**Comment by diamante0018** [comment]
I will check in a few. Thanks for getting back to me

**Comment by diamante0018** [comment]
Seems to have been fixed as my GitHub workflows are now green with latest GSL commit
