### ISSUE TITLE
Turning off clang unsafe buffer warnings fails when compiling with a gcc based compiler

### ISSUE THREAD

**Issue by pirgia** [microsoft/GSL#1148]
The code sections (in span and util)

```
// Turn off clang unsafe buffer warnings as all accessed are guarded by runtime checks
#if defined(__clang__) && __has_warning("-Wunsafe-buffer-usage")
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"
#endif // defined(__clang__) && __has_warning("-Wunsafe-buffer-usage")
```

and (similarly)

```
#if defined(__clang__) && __has_warning("-Wunsafe-buffer-usage")
#pragma clang diagnostic pop
#endif
```

fails when compiling with a GCC-based compiler (the STM compiler for an STM32 microcontroller in this case).
The generated error is:

**missing binary operator before token "("**

I solved this by separating the checks:

```
// Turn off clang unsafe buffer warnings as all accessed are guarded by runtime checks
#if defined(__clang__)
#  if __has_warning("-Wunsafe-buffer-usage")
#    pragma clang diagnostic push
#    pragma clang diagnostic ignored "-Wunsafe-buffer-usage"
#  endif // __has_warning("-Wunsafe-buffer-usage")
#endif // defined(__clang__)
```

There are 4 points that need to be modified:
- span: lines 67 and 855
- util: lines 45 and 163

Thanks for your attention

**Comment by christianbrugger** [comment]
I am having the same issue, it even shows up now in godbolt:

https://godbolt.org/z/cEb1481Yd

The last commit that works for me with gcc is [`caae4dd`](https://github.com/microsoft/GSL/tree/caae4dd0f8343efb879369dcd08a2b18aae59f3b).

I also can confirm that the [pull request](https://github.com/microsoft/GSL/pull/1149) from @beinhaerter fixes the issue for me

**Comment by jackluo923** [comment]
Confirmed to be working for me as well.

**Comment by SunnyPaprika** [comment]
It also shows errors from IntelliSense under VS2022 for this:

![image](https://github.com/microsoft/GSL/assets/43925172/70fb5223-0b7e-4002-8cd9-efd24e80c078)
