### ISSUE TITLE
When will a new version be released?

### ISSUE THREAD

**Issue by sunbibei** [microsoft/GSL#1150]
Hi I notice the latest version was released about two years ago, can i ask when a new verision will be released?

**Comment by tiagomacarios** [comment]
@gdr-at-ms Can you assist?

**Comment by d-winsor** [comment]
We will be preparing a minor release soon once clean on all existing PRs

**Comment by carsonRadtke** [comment]
I will raise this question during today's internal sync.

**Comment by carsonRadtke** [comment]
A new release is available today! https://github.com/microsoft/GSL/releases/tag/v4.1.0
