### ISSUE TITLE
can't compile gsl_tests with VS2022: warning C4067: unexpected tokens following preprocessor directive

### ISSUE THREAD

**Issue by juandent** [microsoft/GSL#1155]
Just cloned gsl and tried compiling project gsl_tests which has /WX option and the error occurs at:

```
#if defined(__clang__) && __has_warning("-Wunsafe-buffer-usage")
```

As far as I know, Visual Studio does not define __clang__ so it should short circuit before testing __has_warning! I understand VS does not define __has_warning correct?

I compiled using /std:c++20 but I think this does not matter

**Comment by zygfrydw** [comment]
I have fixed this issue in [PR1157 ](https://github.com/microsoft/GSL/pull/1157)

**Comment by beinhaerter** [comment]
I fixed that already in #1149 in March - only waiting for it to be merged. I don't know if two PRs with the same fix help.

**Comment by zygfrydw** [comment]
Ohh, I have not noticed your fix, it just has bitten me recently so I fixed it.  Seeing that your PR is not merged either I am afraid that it does not matter as there is not much maintenance going on.

**Comment by carsonRadtke** [comment]
Thank you for the report; this was recently fixed. Closing as "completed". https://github.com/microsoft/GSL/pull/1149
