### ISSUE TITLE
Release version not changed when 4.1.0 was tagged

### ISSUE THREAD

**Issue by HenryHu** [microsoft/GSL#1161]
I noticed that the installed 4.1.0 release is still reported as 4.0.0, then I noticed that this is not changed in CMake file: https://github.com/microsoft/GSL/blob/82ba6c77ceb70cf92add22ca9ecaf0fc7cac99fa/CMakeLists.txt#L3

Please update it to 4.1.0 (and tag again? or tag 4.1.1?).

**Comment by carsonRadtke** [comment]
Thank you for bringing this to our attention. We will update the version and re-tag.

**Comment by beinhaerter** [comment]
@carsonRadtke Side note: the contributors list in the tag note is incomplete. It looks like Mq-b and beinhaerter are missing.

**Comment by carsonRadtke** [comment]
@beinhaerter My fault; I have updated the tag note. Sorry about that.
