### ISSUE TITLE
Use Expects within the GSL for preconditions

### ISSUE THREAD

**Issue by trebconnell** [Microsoft/GSL#119]
fail_fast_assert is used in many places, but I think it'd be preferable to use Expects

This is dependent on #101, as Expects is currently defined in gsl.h, which prevents usage in array_view.h

**Comment by neilmacintosh** [comment]
Expects() should only be used to express a condition that is checkable by the caller. I suspect there are some uses of fail_fast_assert() within gsl.h for which that is not the case. However, where it is, it would be acceptable to make the change.

Note that this would require changes to the current implementation of Expects(), as it will need to support the exceptions-for-testing case.

**Comment by trebconnell** [comment]
Since the current implementation just calls fail_fast_assert I don't think any changes should be necessary.  I'll be careful only to use it for testing pre-conditions checkable by caller.

**Comment by neilmacintosh** [comment]
@trebconnell Thanks for the original report. This now should have been fixed by #215, where I took the opportunity to use `Expects()` where appropriate (some preconditions can be expressed statically...so they show up as `static_assert()`s
