### ISSUE TITLE
finally() mishandles modifiable lvalues

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/GSL#125]
Meng Zhu pointed this out to me.  gsl.h contains:

```
template <class F>
class final_act
{
[...]
private:
    F f_;
    bool invoke_;
};

// finally() - convenience function to generate a final_act
template <class F>
final_act<F> finally(const F &f) noexcept { return final_act<F>(f); }

template <class F>
final_act<F> finally(F &&f) noexcept { return final_act<F>(std::forward<F>(f)); }
```

Given a const lvalue of type `X`, `finally(const F&)` is selected, deducing `F` to be `X`, and it returns `final_act<X>`.

However, given a modifiable lvalue of type `X`, `finally(F&&)` is selected, deducing `F` to be `X&`, and it returns `final_act<X&>`. This appears to be completely undesired.

If `final_act<F>` assumes that `F` is an object type, it should `static_assert` so, and `finally()` should be fixed accordingly.  The most robust fix would be to provide a perfect forwarder only, and use `decay`.

Lastly, all other occurrences of perfect forwarding in the GSL should be audited for this problem, especially when perfect forwarders are overloaded with anything else of the same arity (perfect forwarders are extremely greedy, and will outcompete other overloads, often unintentionally).

**Comment by trebconnell** [comment]
Yes, I noticed this as well.  My PR #118 should fix it.  I'm not using decay at the moment, but I'll update to using that, as it seems more fitting.

**Comment by neilmacintosh** [comment]
Yes, this has been pointed out and is "in the queue" for finally. I like STL's suggestion for the use of `decay`.

**Comment by dineshkwal** [comment]
@trebconnell, how about decaying at the data member level?

```
template <class F>
class final_act
{
public:
    using value_type = std::decay_t<F>;
    [...]
private:
    value_type f_;
    bool invoke_;
};

```
Now,
```
template <class F>
final_act<F> finally(F&& f) noexcept 
{ 
    return final_act<F>(std::forward<F>(f)); 
}
```
And, also it makes writing code like this possible

```
void foo() { }

final_act<decltype(foo)> testFoo {foo}; // will have to use decltype(&foo) otherwise

```

**Comment by JordanMaples** [comment]
Maintainers' call: The code this issue refers to has considerably changed, sorry for the delay.
