### ISSUE TITLE
Rename final_act to final_action

### ISSUE THREAD

**Issue by trebconnell** [Microsoft/GSL#128]

**Comment by khatharr** [comment]
Sorry if I'm butting, but "final" isn't really correct either, is it? As far as I can tell there's nothing to guarantee that the action runs after dtors. For that matter, couldn't you use more than one in the same scope?

**Comment by khatharr** [comment]
Sorry if I'm butting in, but "final" isn't really correct either, is it? As far as I can tell there's nothing to guarantee that the action runs after dtors. For that matter, couldn't you use more than one in the same scope?

**Comment by melak47** [comment]
Isn't this commonly called a scope_guard in boost parlance? :)
