### ISSUE TITLE
Problems with byte definition

### ISSUE THREAD

**Issue by rkawulak** [Microsoft/GSL#130]
There are two problems with the following definition in `array_view.h`:

    enum class byte : std::uint8_t {};

First, `uint8_t` is not the same thing as byte, and moreover – according to the Standard – [it is optional](http://en.cppreference.com/w/cpp/types/integer#Types) and may be missing on platforms not supporting 8-bit integers.

Second, according to the [strict aliasing rule](http://en.cppreference.com/w/cpp/language/reinterpret_cast#Type_aliasing), only pointers to `char` and `unsigned char` may refer to object representation – otherwise the behaviour is undefined.

Therefore the only way `byte` can be defined in a practical, standard-conforming and portable way is:

    using byte = unsigned char;

**Comment by gdr-at-ms** [comment]
We require that target platform supports `uint8_t`, just the way we require the target platform to support `<algorithm>` which is optional on freestanding implementations.  
Furthermore, we require that the implementation aliases `std::uint8_t` to `unsigned char`.  We could update the documentation to state that if that would create less confusion for people.

The second point about 3.10/10 from the standards text, but we view it as a defect in the standards in the sense that that paragraph wasn't updated when scoped enumerations were introduced.  We will raise that point with the committee.

We do want to have a distinct type for 'byte'.  Using a class that contains a simple byte, when a scope enumeration could do, would introduce an abstraction penalty on platforms with ABIs that still fail to support C++ efficiently.

**Comment by rkawulak** [comment]
By "we require" you refer to Microsoft GSL implementation or GSL interface in general? Because the latter (as well as [P0122](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0122r0.pdf) using the same definition) should IMO have as little requirements as possible in order to be portable.

Apart from updating the documentation, a `static_assert(is_same<uint8_t, unsigned char>)` would be useful I guess.

But in the first place why do you require this at all? I don't see a point in using `uint8_t` in place of `unsigned char` when the standard definition of byte for the purposes of handling object storage is (`unsigned`) `char` and you don't need to rely anywhere on bytes having exactly 8 bits. So the current `byte` definition is confusing and unnecessarily constrained for no reason.

As for the second point – even if you do report a defect and it is acknowledged it doesn't change the fact that **currently** using parts of the library yields **undefined behaviour**.

BTW, apart from 3.10/10 it's also 3.8/5.4 (`reinterpret_cast` is defined in terms of `static_cast` for this case, see 5.2.10/7).

**Comment by gdr-at-ms** [comment]
I meant the Core Guidelines.

Also, note that the enumeration and its underlying type are layout-compatible.

**Comment by rkawulak** [comment]
As far as I understand, when you want to treat raw bytes as an object's representation and vice-versa, you do `reinterpret_cast<byte*>(object)`, which is equivalent to `static_cast<byte*>(static_cast<void*>(object))` (5.2.10/7). This, in turn, is undefined behaviour unless `byte` is (`unsigned`) `char` (3.8/5.4). I don't see how layout-compatibility would change this. Or am I missing something?

**Comment by gdr-at-ms** [comment]
I don't know if the format of the comments is getting into the way.  We will clarify the text as avoid confusion of this sort.

**Comment by rkawulak** [comment]
Sorry, but I don't understand what 'comments' and 'text' you refer to.
