### ISSUE TITLE
question: array_view spec

### ISSUE THREAD

**Issue by trebconnell** [Microsoft/GSL#132]
I'm interested in opening and fixing issues with array_view.  I have some questions though.  The isocpp FAQ suggests this is based on the [Multidimensional bounds, offset, and array_view](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4512.html) proposal if I'm understanding?  There're many differences between that spec and the implementation here.  For example the implementation has no offset type with a rank template parameter.

**Comment by neilmacintosh** [comment]
While the array_view in GSL was originally inspired by that proposal, it has diverged from it. I'm in the process of producing an updated specification for array_view (as well as the other parts of the GSL). Together with the updated specification, there will also be implementation changes. To avoid duplicating work, you are best off waiting until the specification appears.

**Comment by trebconnell** [comment]
Makes sense
