### ISSUE TITLE
Comment: size_t for array_view index type a poor choice for dimensions N > 1

### ISSUE THREAD

**Issue by mattnewport** [Microsoft/GSL#133]
The *Multidimensional bounds, index and array_view* proposal has `index::value_type` as `ptrdiff_t` while the GSL version uses `size_t`. An unsigned type is inconvenient for many image processing uses where you commonly want to index with positive and negative offsets relative to the current pixel and then clamp to the valid bounds (or wrap, etc.). This particular difference from the array_view proposal is confusing and in this case I think the proposal makes the right choice here by going with signed `index::value_type`.

More generally I'm a little concerned about the apparent divergence between the `array_view` proposal and `gsl::array_view`. It seems like a recipe for confusion if both become widespread. Is there a plan to try and bring the two closer together?

**Comment by neilmacintosh** [comment]
Thanks for the feedback Matt...very useful information.

We are working on a spec for array_view and the other GSL types. The multidimensional interface on the current implementation has many aspects that will be corrected as part of that process. Allowing signed size types is one of the aspects we want to support and is simply a defect in the current implementation.

The previous proposal you refer to (N3851) was not adopted by the Library Evolution Working Group and is no longer being actively pursued by its authors. Instead, I have a new one in the Kona mailing that suggests the GSL version of array_view for inclusion in the standard library. Hopefully that clears up possible confusion on that score.
________________________________

**Comment by mattnewport** [comment]
The proposal you mention is this one? http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0122r0.pdf

Where's the best place for discussion of GSL in general / this array_view proposal in particular? I like a lot of what's in `array_view` but there appear to be a number of issues with the current proposal that make it not ideal for one of my major use cases which is working with 2D image data. The biggest I'm seeing right now are the signed `index::value_type`, the non-optional bounds checking (this can unfortunately still be a real killer performance-wise for image processing where bounds are rarely static) and (more minor) the lack of convenient ways to initialize a 2D `array_view` with dynamic bounds from a `vector` of elements.

I fear that mandatory bounds checking could kill adoption of this proposal in performance sensitive areas like games. I want the compile time safety `array_view` offers but I don't want the runtime performance cost. I'd really like to see these separated out in the spirit of 'don't pay for what you don't use'. I believe mandatory bounds checking could result in worse overall code quality since it will prevent people from adopting the very desirable compile time safety offered by `array_view`.

**Comment by neilmacintosh** [comment]
Yes, that is the right link to the new proposal to LEWG. Be warned: I'm about to issue a revision that will clean up a few things in there.

The best place for general discussion of GSL today is to raise issues on the Core Guidelines "GSL" section. However, we are working on a more formal specification for the GSL to add to the Core Guidelines. So you may want to wait until that appears and then use that as a discussion vehicle. Remember, this implementation is **not** a specification, and I apologize for any confusion that has caused.

If you have questions about this particular GSL implementation, then raising issues here is the easiest way to start a discussion.

With all that out the way, I'll address your specific issues. As I mentioned in my last reply, the current `array_view` implementation here does not quite describe the multidimensional interface we want for the type long-term. It has a number of known defects from where we would like it to be. Allowing signed `size_type` is one of them. Having more convenient bounds construction from sequences of coordinates sounds like a completely reasonable request to me. Do you have a snippet of code that illustrates what you'd like to do? I like to collect examples ;-)  

I hope that bounds-checking does not prevent people considering `array_view` for use in domains like game development. One of my aims is to demonstrate (with appropriate compiler support) that bounds-checking is not the horror it often appears to be to people.

Finally, it's great to see the interest in `array_view` and appreciation of its safety benefits, thanks for the comments!

**Comment by mattnewport** [comment]
I'm still figuring out the right way to use GSL's `array_view` so I may not be doing everything in the best way but here's an example of what seems like slightly clunky syntax to me.

Here's how I can create a 2D array_view with the Parallel STL `array_view` (`heightfield.heights` is an `std::vector<uint16_t>` and `height` and `width` are `int`s):
```C++
namespace pstl = std::experimental::D4087;
auto heightsView = pstl::array_view<const uint16_t, 2>{{heightfield.height, heightfield.width},
                                                        heightfield.heights};
```

The equivalent code I have for a GSL `array_view`:
```C++
auto heightsView = gsl::as_array_view(
    heightfield.heights.data(), gsl::dim<>(heightfield.height), gsl::dim<>(heightfield.width));
```

Neither of these is ideal - I like that I don't have to respecify `uint16_t` as the type of the view with the `as_array_view` helper but with the Parallel STL version I prefer that I don't have to call `.data()` on the `vector` and that I can just pass an init list of width and height.

**Comment by neilmacintosh** [comment]
Thanks for the feedback Matt, we'll bear this in mind as we look at the multidimensional interface.
________________________________
