### ISSUE TITLE
array_view not making use of empty base optimization

### ISSUE THREAD

**Issue by Horstling** [Microsoft/GSL#136]
[This document](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0122r0.pdf) states that *A fixed-size array_view requires no storage size overhead beyond a single pointer*. This appears not to be true for the current implementation as it makes no use of empty base optimization for both `basic_array_view` and `static_bounds`.

Is there a reasoning behind this (like ABI issues) or is this simply not yet implemented?

**Comment by neilmacintosh** [comment]
Both these classes are just artifacts of a previous implementation that will be cleaned up in the near future.
________________________________
