### ISSUE TITLE
Make operator bool() explicit

### ISSUE THREAD

**Issue by Horstling** [Microsoft/GSL#139]
The current implementation allows code like this to compile:

    gsl::array_view<int> v;
    int i = v * 42;

**Comment by neilmacintosh** [comment]
Thanks for reminding me of its existence in the current implementation.

Actually, I would prefer to remove it altogether from the current implementation. It encourages an unclear usage semantic (is the user testing for a `nullptr`-containing `array_view` or a zero-length `array_view`?).

**Comment by neilmacintosh** [comment]
Whoops, forgot to add: opened #140  to track its removal.
