### ISSUE TITLE
The `final_act` helper function name `finally` is misleading.

### ISSUE THREAD

**Issue by jbcoe** [Microsoft/GSL#14]
The `final_act` helper function function, `finally`, is misleadingly named as it returns an object which, if not captured, will result in instant invocation of the given function object. 

The following code *looks* correct but database lookups and insertions will fail as the 'final-act' was invoked at [1].

    auto db_handle = my_db_api_open_db("My database name");
    finally([db_handle]{ db_api_close_db(db_handle); }); // [1]
    // do some lookups and insertions
  
I propose that `finally` is renamed to `make_final_act` or is replaced by a macro that captures the return value for the user into a uniquely named temporary variable (I prefer `make_final_act`).

**Comment by trebconnell** [comment]
FYI I opened a [matching issue](https://github.com/isocpp/CppCoreGuidelines/issues/141) on isocpp gsl and it was closed.

**Comment by neilmacintosh** [comment]
As per the issue on the Core Guidelines (https://github.com/isocpp/CppCoreGuidelines/issues/141), the name is considered fine as is. Thanks for the suggestion.
