### ISSUE TITLE
Suggestion: replace / augment as_bytes() member with byte_cast() free function

### ISSUE THREAD

**Issue by mattnewport** [Microsoft/GSL#143]
The `array_view::as_bytes()` and `array_view::as_writeable_bytes()` functions seem like they should be free functions rather than members. This follows the general design guideline of preferring free functions over members and also enables slightly more concise code:
```C++
void f(array_view<const byte> av);
vector<int> v{1, 2, 3};
// with free function
f(as_bytes(v));
// with current member function design
f(as_array_view(v).as_bytes());
```
With `as_bytes()` and `as_writeable_bytes` as free functions, it also seems more in keeping with existing C++ practice to use the name `byte_cast`:
```C++
f(byte_cast(v));
```
And perhaps to distinguish writeable vs. non writeable with a template parameter rather than via naming:
```C++
void g(array_view<byte> av);
f(byte_cast<const byte>(v));
g(byte_cast<byte>(v));
```

**Comment by neilmacintosh** [comment]
I agree they should be free functions and the current proposal revision for array_view has already been updated to reflect that. :-)

We discussed the names originally and like the explicit nature of them...it is easy to scan code visually and understand what is happening.
________________________________

**Comment by mattnewport** [comment]
@neilmacintosh 
My concern with the `as_bytes` naming is that when doing safe type punning, `as_x` is a common name and suggests to me a copy, e.g.:
```C++
auto as_uint32_t(float x) {
    uint32_t res;
    memcpy(&res, &x, sizeof(res));
    return res;
}
```
This is a pattern I've observed in code that works directly with floating point representations while trying to not breach strict aliasing rules although I don't know how widespread it is.

To me `byte_cast` is clearer that it's a view over the same underlying memory whereas `as_bytes` suggests that perhaps a copy is happening. I wouldn't say this is such a common naming scheme that confusion is inevitable but it seems worth mentioning.

**Comment by gdr-at-ms** [comment]
Just calling something `xxx_cast` does not mean it doesn't return a value.  `static_cast` can return value (often).  Boot;s `lexical_cast` does return a value.  So, one still has to look it up. I would not say `as_xxx` is uncommon.

It is arguable that the `xxx_cast` naming is overused .

**Comment by galik** [comment]
Is it just adding to the confusion to suggest that `to_bytes()` as a free standing function seems similar to the standard library use of `to_string()`?

**Comment by neilmacintosh** [comment]
We decided against to_bytes for that reason.
________________________________

**Comment by galik** [comment]
to_funny()

**Comment by neilmacintosh** [comment]
Hahaha...no because to_string makes a container and as_bytes does not.
________________________________
