### ISSUE TITLE
Comment: as_bytes() and as_writeable_bytes() don't interoperate ideally with legacy code

### ISSUE THREAD

**Issue by mattnewport** [Microsoft/GSL#144]
Many legacy libraries, in particular the standard library, use plain `char*` in places where they deal in raw bits. This results in a need to `reinterpret_cast` from an `array_view<byte>` on platforms where `char` is signed (which is most platforms I'm familiar with). It seems desirable to be able to write safe interop with such legacy APIs without needing to resort to a `reinterpret_cast` or C style cast since use of a `reinterpret_cast` or C style cast generally suggests unsafe code:
```C++
auto data = std::ifstream{"heightfield.dat", std::ios::in | std::ios::binary};
std::vector<uint16_t> x(size); // assume we know size from somewhere, probably read from the file
auto xView = gsl::as_array_view(x).as_writeable_bytes();
data.read(reinterpret_cast<char*>(xView.data()), xView.size()); // Undesirable reinterpret_cast
```
This seems like a common scenario to encounter in incremental adoption of `array_view`. I don't have an immediate suggestion but I'm curious if you have any thoughts about how to handle this type of scenario.

**Comment by gdr-at-ms** [comment]
It was a deliberate design decision to keep the `byte` type distinct.  We would like to retain that.
If some codes needs `reinterpret_cast` to 'char*`, then even better: it is explicitly called out.

**Comment by neilmacintosh** [comment]
Gaby beat me to it. Plus, you can always write a wrapper function if it is a common need in a legacy code base.
________________________________
