### ISSUE TITLE
bounds_iterator is not ordered

### ISSUE THREAD

**Issue by panacekcz** [microsoft/GSL#148]
The `operator<` of `bounds_iterator` is not antisymmetric, as demonstrated by this program:

``` c++
#include "gsl.h"
#include <iostream>
using namespace std;
using namespace gsl;
int main(){
    static_bounds<size_t, 2, 2> bounds;
    auto i1 = bounds.begin() + 1;
    auto i2 = bounds.begin() + 2;
    cout << (i1 < i2) << endl;
    cout << (i2 < i1) << endl;
}
```

Suggested fix: 1475af7a8095ac2e3195a3e9d3fd01281759764d

**Comment by neilmacintosh** [comment]
Yes, that's a good point.We are doing a bunch of rework to bounds_iterator and friends currently, but it would be good to get this fix in now anyway. Do you want to create a PR for that commit (and add a corresponding test case)?

**Comment by panacekcz** [comment]
OK. There seem to be more issues, but I will wait for the new implementation.

**Comment by JordanMaples** [comment]
Maintainer's call: Closing this because the contents of the multi_span file have all been deprecated.
