### ISSUE TITLE
Visual studio solution does not include library header files

### ISSUE THREAD

**Issue by davidhunter22** [Microsoft/GSL#150]
When generating Visual Studio projects using CMake the resulting projects do not seem to include the headers of the GSL library itself like array_view.h. 

This could be fixed by adding a add_custom_target to the root CmakeLists.txt which wil result in a "GSL" project appearing in the solution containing the headers.

**Comment by neilmacintosh** [comment]
Sure! If people find that useful (and it doesn't interfere with things working on other platforms), then feel free to create a PR with the change.

**Comment by davidhunter22** [comment]
I will create a PR. On platforms other than windows nothing changes as the project is non buildable.

**Comment by neilmacintosh** [comment]
@davidhunter22 I believe I've fixed this with PR #215. Feel free to reopen the issue if I've missed something.
