### ISSUE TITLE
array_view::as_array_view suggested usage invokes undefined behaviour

### ISSUE THREAD

**Issue by mattnewport** [Microsoft/GSL#153]
@neilmacintosh 
In your CppCon presentation "Evolving array_view and string_view" at [around the 17 minute mark](https://youtu.be/C4Z3c4Sv52U?t=17m3s) you have this slide:

![slide](https://dl.dropboxusercontent.com/u/16821859/images/bad_as_array_view.PNG)

With the current implementation of `as_array_view()` this invokes undefined behaviour. Worse, I don't believe it is possible to make this interface not invoke undefined behaviour under the current language rules. Perhaps with suitable heroics using proxies it would be possible but certainly not trivial. 

The issue is with 3.10.10 again:

> If a program attempts to access the stored value of an object through a glvalue of other than one of the following types the behavior is undefined:
- the dynamic type of the object,
- a cv-qualified version of the dynamic type of the object,
- a type similar (as defined in 4.4) to the dynamic type of the object,
- a type that is the signed or unsigned type corresponding to the dynamic type of the object,
- a type that is the signed or unsigned type corresponding to a cv-qualified version of the dynamic type of the object,
- an aggregate or union type that includes one of the aforementioned types among its elements or nonstatic data members (including, recursively, an element or non-static data member of a subaggregate or contained union),
- a type that is a (possibly cv-qualified) base class type of the dynamic type of the object,
- **a `char` or `unsigned char` type.**

But it is harder to fix than the problem with `as_bytes()` which can be made legal C++ by making `byte` a typedef to `unsigned char` or `char`. 

This code on the slide:

```C++
// write foo
auto foo = p.as_array_view<Foo, 1>();
foo[0].someEntry = ...; // write the fields of foo
```

Attempts to access the stored value of objects of type `byte` through a glvalue of type `Foo`. Even if `byte` is a typedef of `char` this is undefined behaviour. 

The only safe way I know of to write code like this is to write this, or a direct equivalent:
```C++
Foo foo{};
foo.someEntry = ...; // write the fields of foo
memcpy(p.data(), &foo, sizeof(foo));
```

There is simply no way in current C++ to access memory as type `Foo` unless it holds an object of type `Foo`. If you want to put a `Foo` into memory that doesn't hold a `Foo` the only way to do it safely is to `memcpy()` into memory that is actually of type `char` or `unsigned char`.

**Comment by mattnewport** [comment]
[Here's](http://coliru.stacked-crooked.com/a/815b4374ca4b0333) an example of this undefined behaviour actually happening when compiling with GCC -O3:

```C++
#include <cstdlib>
#include <cstring>
#include <iostream>

template<typename T>
struct ArrayView {
    ArrayView(T* ptr_, size_t size_) : ptr{ptr_}, size{size_} {}
    T& operator[](size_t i) { return *(ptr + i); }
    T* begin() { return ptr; }
    T* end() { return ptr + size; }
    template<typename U>
    ArrayView<U> as_array_view() { 
        return { reinterpret_cast<U*>(ptr), size / sizeof(U) };
    }
    
    T* ptr;
    size_t size;
};

int main() {
    constexpr int n = 4;
    alignas(float) char storage[n * sizeof(float)] = {};
    float fs[n] = {1.0f, -1.0f, 2.0f, -2.0f};
    memcpy(storage, fs, sizeof(storage));

    ArrayView<char> byteAv = { storage, sizeof(storage) };
    ArrayView<float> floatAv = byteAv.as_array_view<float>();
    ArrayView<uint32_t> uint32Av = byteAv.as_array_view<uint32_t>();
    int i = 0;
    for (auto& x : floatAv) {
        x = -(x + 1.0f);
        uint32Av[i] ^= 1 << 31; // flip the sign bit of the float at this location
        x += 1.0f;
        ++i;
    }

    memcpy(fs, storage, sizeof(fs));
    for (auto x : fs) std::cout << x << ", ";
    std::cout << std::endl;
}
```
Compiled with GCC with -O0 this outputs `3, 1, 4, 0, ` which is the presumably intended output if this didn't invoke undefined behaviour. Compiled with -O3 it outputs `-1, 1, -2, 2, ` because under 3.10.10 GCC assumes that `uint32Av` cannot alias `floatAv` despite the fact that both share the same underlying `char` storage.

This is obviously highly sensitive to exact compiler settings and version etc. but I wanted to demonstrate that this is not a merely theoretical concern. It can be broken in practice on current mainstream compilers.

**Comment by neilmacintosh** [comment]
There is active discussion in the standards committee about allowing this sort of casting from "byte" types. I'll leave this issue open until that is resolved, as it is a common need and may become well-defined behavior.

**Comment by mattnewport** [comment]
@neilmacintosh 
It's hard for me to see how they can change the language of 3.10.10 to allow this without hampering optimization opportunities but I'll leave that discussion to the committee.

I would argue though that an interface that could be written now without invoking undefined behaviour would be a better interface anyway from a design point of view. Something like:

```C++
// write foo
auto foo = Foo{};
foo.someEntry = ...; // write the fields of foo
p.push_back(foo); // probably not the best name but hopefully the intent is reasonably clear

// write bar
// this error-prone line is no longer necessary:
// p = p.sub(sizeof(Foo));
auto bar = Bar{};
bar.someField = ...; // write the fields of bar
p.push_back(bar);
```

Internally this would do the safe thing and memcpy from the local variable into the `char` storage. This is not a fully fleshed out design but hopefully it's reasonably clear what I'm suggesting.

This perhaps requires changing legacy client code a bit more than the current design but that code is broken today and already invokes undefined behaviour so it should be changed.

**Comment by mattnewport** [comment]
@neilmacintosh 
Another possible design would be to have a way of obtaining an [`std::raw_storage_iterator`](http://en.cppreference.com/w/cpp/memory/raw_storage_iterator) from an `array_view<byte>` but that has problems again with bounds checking. If we had something like a a `raw_storage_range` though then that design starts to look more promising as it would also let you use standard algorithms to write directly into an array of bytes with bounds checking. There are some discussions ongoing in SG14 about improving `raw_storage_iterator` which may be relevant here.

**Comment by gdr-at-ms** [comment]
There is a fair amount of confusion here.  I have been refraining from commenting because lot is going on this week.  I am not ignoring the report, we just need to "cool down."

**Comment by mattnewport** [comment]
@neilmacintosh 
You also mention around the 18:30 mark in the video of your talk that there are unresolved issues around alignment with the current design. I think this is another indication of why the current design is fundamentally flawed. In general, you *don't* want the alignment of the `byte` storage to match the alignment of your type. In the common case of building a network packet for example you likely want to pack your data without regard to alignment and reconstitute it at the other end respecting the alignment requirements of the receiving machine (which may not match the sending machine). If you expect people to write directly to the underlying bytes through a glvalue of a type with hardware-enforced alignment requirements however then all kinds of badness can happen if the storage is not aligned. Again, a memcpy is the right thing to do to avoid these alignment issues.

**Comment by OlafvdSpek** [comment]
I too think such casting is inherently wrong and non-portable, though widely used. 

IMO you should use functions to read/write integers of specified size, alignment and endianness.. then no casting is required.

**Comment by neilmacintosh** [comment]
This feature has been removed from the library, so I'm going to close out this issue as now obsolete.
