### ISSUE TITLE
Expose precondition check for array_view::as_array_view

### ISSUE THREAD

**Issue by mknejp** [Microsoft/GSL#155]
Currently the versions of `as_array_view` which cannot be checked at compile time contain `fail_fast_assert` with some sort of precondition and throw on failure. It would be helpful to have these condition checks exposed in the interface. Right now if you want to act differently based on whether the conversion is possible or not the only reliable way is to wrap it in a `try` block and give it a shot. I think if an operation on an object is attached to a precondition of the object's state there should also be a way to test the precondition without actually performing the operation.

**Comment by neilmacintosh** [comment]
it's true that the conditions of conversion should be better specified. As we clean up the interface that should naturally emerge.

**Comment by neilmacintosh** [comment]
@mknejp Preconditions for `span` (formerly `array_view`) are now expressed using the GSL conventions of `Expects()` (and `static_assert()` for those conditions that are checkable statically). Some of the conditions are still a little buried in the implementation for my liking, but hopefully the progress overall addresses this issue.
