### ISSUE TITLE
Missing directory unittest-cpp

### ISSUE THREAD

**Issue by sigfpe** [Microsoft/GSL#16]
The unites-cpp directory should be part of the main repository so that:
   (1) git clone
   (2) cmake configure
succeeds out of the box.

**Comment by AndrewPardoe** [comment]
Unittest-cpp isn't a part of the GSL so it lives in its own repo. Eventually we'd like to not have the Microsoft fork of the UnitTest repo at all--the instructions would point to the [main UnitTest repo](https://github.com/unittest-cpp/unittest-cpp). There are some [changes](https://github.com/unittest-cpp/unittest-cpp/compare/master...Microsoft:master) that we would need to have pulled back first, however.

**Comment by sigfpe** [comment]
Then fix GSL's CMakeList so that it does not error out because it could not find unittest-cpp in its default configuration, following the instruction in the README.  Otherwise, one cannot build GSL without unittest-cpp

**Comment by AndrewPardoe** [comment]
Reopening this issue for comment and assigning to Neil. 

We want to encourage that changes to the repo include testing, but if you just want to build the GSL for usage, tests might not be necessary. Thoughts?

**Comment by neilmacintosh** [comment]
There is no "build" for the GSL - it is entirely contained within four headers (well, today, anyway).

The only thing CMake builds is the test suite - which does require unittest-cpp as that's the framework we used. So having CMake error out on the lack of unittest-cpp seems reasonable to me, in that context.
