### ISSUE TITLE
Add string_view operator<< support

### ISSUE THREAD

**Issue by kevgs** [microsoft/GSL#160]
Right now std::cout << gsl::cstring_view("asdf") doesn't print "asdf". This feature is missing. Something like this would be very useful http://en.cppreference.com/w/cpp/experimental/basic_string_view/operator_ltlt

**Comment by neilmacintosh** [comment]
Agreed @kevgs. In the near future, I'm going to rework `string_view` (now `string_span`) to be its own type (rather than a type alias). When that change goes in then I'll add an output operator. I don't want to do so with the present implementation as it will be the output operator for any `array_view` (now `span`) of `const char`, which may not always be desirable.

**Comment by kevgs** [comment]
Sounds great!

Here is the code is use for a workaround. Maybe it could help someone https://gist.github.com/kevgs/8a5ed24168ea703c3d32

**Comment by MikeGitb** [comment]
@neilmacintosh: Is there any update on this? I think `gsl::[c][z]string_span` could really use an overloaded `operator<<`. 
Unfortunately I don't see a simple way to simulate the exact behavior of `operator<<(ostream&, const string&)` (a formatted output) for the non-zero terminated versions, but in many cases an unformatted output (via `ostream.write`) could be good enough anyway.

**Comment by biocomp** [comment]
@neilmacintosh - updates on the issue? :)

**Comment by neilmacintosh** [comment]
@biocomp I'd be happy to look at a PR to add `operator<<`, but I haven't had time to make any updates to `string_span` lately.

**Comment by PeeyushRawat** [comment]
i want to give a try.

**Comment by JordanMaples** [comment]
Maintainer's call: Sorry for the delayed reply. gsl::string_view has been standardized as std::string_view which has a standard interface now. So that supersedes this issue.

Additionally: gsl::string_span has been removed from the C++ Core Guidelines with isocpp/cppcoreguidelines#1680. 
>Remove string_span, recommend using `std::string_view`, `std:::span,<char>` or `gsl::span<char>` instead
