### ISSUE TITLE
Unclutter array_view.h, string_view.h

### ISSUE THREAD

**Issue by target-san** [Microsoft/GSL#164]
ATM each of those modules is a long source file, with no obvious structure.
Proposals:
1. No `#pragma whatever` in interface headers. Please consider moving all that stuff into some kind of config.h
2. Move everything related solely to implementation into companion INL files, including method bodies, wherever possible. So headers themselves will contain only clean struct interfaces.

**Comment by neilmacintosh** [comment]
Thanks for the suggestions @target-san. The files will naturally evolve over time. It is certainly possible that configuration options might move into a config.h, though we also aim to limit/reduce the amount of of per-compiler or platform configuration. I doubt we'll move implementation into separate files. We are in the process of developing more formal specifications as well as documentation for the interfaces of these classes that will be published along with the Core Guidelines. If people want to inspect interfaces, that is probably a better place to do it.

**Comment by target-san** [comment]
You decide certainly. Though in my practice library interface should be easy to read and inspect if library maintainer wants it to be used by people. Compiler can chew many things. But peoples' brains don't.
