### ISSUE TITLE
Use narrow_cast() in place of static_cast() in span.h and string_span.h

### ISSUE THREAD

**Issue by neilmacintosh** [Microsoft/GSL#167]
This will require a little rejiggering of headers and #include's, so I'm creating this issue to remind me to do it soon.

**Comment by TBBle** [comment]
Conversely, the existing `narrow_cast` in the `as_span` described as
```// convert a span<const byte> to a span<const T>```

seems to fail to be `constexpr` in Visual Studio 2015, while trying to compile the following (roughly)
```c++
using fixed_string_span = gsl::span<const gsl::byte, 0x20>;
fixed_string_span string0;
// Following line fails in VS2015, but passed in clang 3.7.0
auto charstring0 = as_span<const char>(string0);
```

> 2>gsl\span.h(1645): error C2131: expression did not evaluate to a constant
> 2>  gsl\span.h(1645): note: failure was caused by call of undefined function or one not declared 'constexpr'
> 2>  gsl\span.h(1645): note: see usage of 'gsl::narrow_cast'
> 2>  src\AssetName.cpp(17): note: see reference to function template instantiation 'gsl::span<U,32> gsl::as_span<const char,32>(gsl::span<const gsl::byte,32>) noexcept' being compiled
> 2>          with
> 2>          [
> 2>              U=const char
> 2>          ]

That's complaining about the `static_assert` in that method, 
```c++
    static_assert(
        std::is_trivial<std::decay_t<U>>::value &&
            (ConstByteSpan::bounds_type::static_size == dynamic_range ||
             ConstByteSpan::bounds_type::static_size % narrow_cast<std::ptrdiff_t>(sizeof(U)) == 0),
        "Target type must be a trivial type and its size must match the byte array size");
```

**Comment by neilmacintosh** [comment]
Hello @TBBle, the `constexpr` issue is most likely an outcome of the incomplete `constexpr`support in Visual Studio 2015. While it is much better than it was, it still has a little way to go. For now, you sholud be able to leave `constexpr` `#define`d away for the GSL when using Visual Studio 2015. We all look forward to that changing soon.
