### ISSUE TITLE
error C1001: triggered by Visual Studio 2013 code analysis

### ISSUE THREAD

**Issue by dbremner** [Microsoft/GSL#168]
Steps to reproduce. I apologize in advance if these are excessively detailed.
1. Open Visual Studio 2013 Update 5.
2. File\New Project
3. Select Templates\Visual C++\Win32\Win 32 Console Application
4. Enter a project name of your choice and click OK
5. Click Next
6. Uncheck the Precompiled header check box.
7. Check the Empty project check box.
8. Click Finish.
9. Project\Add New Item
10. Click "C++ File (.cpp)" if it isn't already selected.
11. Click Add. The file will be named Source.cpp by default.
12. Enter the following text into Source.cpp and save it.
# include <gsl.h>

int main(void)
{
    return 0;
}
13. Project\Properties
14. C/C++\General
15. Additional Include Directories - add the GSL include directory
16. Build\Run Code Analysis on Solution
I receive the error messages below in the Error List window.
Error   3   error C1001: An internal error has occurred in the compiler.    c:...\gsl\include\span.h   550
Warning 1   warning C4068: unknown pragma   c:...\gsl\include\span.h   1972
Warning 2   warning C4068: unknown pragma   c:...\gsl\include\gsl.h    222

Thanks,
David

**Comment by neilmacintosh** [comment]
Thanks @dbremner, these steps are not too detailed at all, but actually very helpful. I've logged a bug against the compiler and I'll look into workarounds.

**Comment by KrisTC** [comment]
@neilmacintosh: I also get this problem. 
I am trying to promote the use of Core Guidelines and the GSL in our company and modern C++ techniques, but unfortunately we are stuck in VS2013 compiler for 2-3 years :( So a fix for this would be really helpful.

Do you have enough information to fix this defect? I am happy to share any information / test projects etc that will help.

**Comment by KrisTC** [comment]
@neilmacintosh 
I have been playing around with this again recently. And it looks like the latest version of the GSL from GIT works fine in VS2013. The Commit that works is : f3e660a5a535e88e9b77f2c6f57db4c1140530e0 

The version fetched using VS2015 nuget package looks older unfortunately the hash is not recorded along with the nuget. The version that crashes the compiler is: https://www.nuget.org/packages/Microsoft.Gsl/0.1.2.1

Can the nuget be updated with the latest version and have it's hash recorded?

Then this can may be be able to be closed.

**Comment by neilmacintosh** [comment]
@KrisTC, that's great news! Yes, we'll be releasing an updated NuGet package soon. Recording the hash in the NuGet release notes is a very sensible idea. I'll follow-up here once it's done.

**Comment by beinhaerter** [comment]
If I understand correctly MSVC 2013 is not supported any more by GSL, so shouldn't this issue be closed?
