### ISSUE TITLE
Remove use of macro _CONSTEXPR

### ISSUE THREAD

**Issue by gdr-at-ms** [Microsoft/GSL#17]

**Comment by kernhanda** [comment]
Is this an issue to track this for down the line or did you want to remove constexpr support now? Or did you want to force constexpr usage now (in which case VS2013 support will need to get dropped)?

**Comment by viboes** [comment]
Does constexpr works with VS2014?

**Comment by kernhanda** [comment]
@viboes: Yes, according to STL's blog post at http://blogs.msdn.com/b/vcblog/archive/2015/06/19/c-11-14-17-features-in-vs-2015-rtm.aspx

**Comment by gdr-at-ms** [comment]
One can do something like:
```
#if defined(_MSC_VER) && _MSC_VER < 1800
#pragma push_macro("constexpr")
#define constexpr /* nothing */
#endif
```
and the corresponding `pop_macro` at the end of the file.

**Comment by gdr-at-ms** [comment]
Fixed #17.

**Comment by leeter** [comment]
@gdr-at-ms this does not appear to be resolved as `constexpr` is still disabled for VS2015 which supports `constexpr` fully according to the blog linked above

**Comment by gdr-at-ms** [comment]
`constexpr` is disabled wholesale for VS because the current `array_view` implementation uses the C++14 relaxed semantics, whereas VS2015 offers only the C++11 variant.
I suspect it is possible to implement `array_view` with only the C++11 semantics, but it might require some code "damage" that may not be necessary...

Also my original modification uses
```
#if defined(_MSC_VER)
```
so that a version could be restricted later by just appending `&& _MSC_VER < XXX` but that was lost in subsequent edits.  Might be worth reviving.

**Comment by leeter** [comment]
@gdr-at-ms then I would at least update the comment, right now it implies that VS2015 doesn't support any `constexpr` which is not true

**Comment by leeter** [comment]
@gdr-at-ms is it worth revisiting this now that the VS2017 rc is out?

**Comment by gdr-at-ms** [comment]
When VS2017 RTM is out, yes; but I am letting @neilmacintosh run away with it :-)
