### ISSUE TITLE
span<T> is cast to T in unexpected ways

### ISSUE THREAD

**Issue by MatthiasKauer** [Microsoft/GSL#172]
Hi,
I've started to experiment with this library a bit and I've found the following behavior that surprised me. Consider the following snippet (mini repo for this https://github.com/MatthiasKauer/cpp-gsl-experiments). 
It appears that span<double> is cast back to double and successfully calls the function itself. 
Is this the desired behavior? I had to debug this in my actual code to find out :)

Kind regards,
Matthias Kauer

Another thing: I've observed this w/ gcc 5.2.1 and I'm building w/ std=c++14. The library didn't build w/ std=c++11. Is this also as expected or should I try that again?

```
#include <vector>
#include <iostream>

#include "gsl.h"

void not_a_span_function(double x) {
    std::cout << "test func was called" << std::endl;
}

int main() {
    std::vector<double> v{1.0, 1.5, 2.0, 2.5};

    // not_a_span_function(v);     //does not compile as expected

    auto vspan = gsl::as_span(v);
    not_a_span_function(vspan); //gets called unexpectedly
}
```

**Comment by martinmoene** [comment]
Due to non-explicit `constexpr operator bool () const noexcept`?

**Comment by MatthiasKauer** [comment]
```
constexpr operator bool () const noexcept
```
on line 1101 is indeed the first call I get in span.h when stepping into the call in question.

**Comment by neilmacintosh** [comment]
Yep. This is a temporary bug until I clean up the interface as per #140 and remove that operator.

**Comment by MatthiasKauer** [comment]
Ok, I see. Thanks for clearing this up :)
