### ISSUE TITLE
compiling a progrma with visual studio 2015

### ISSUE THREAD

**Issue by luisleonn** [Microsoft/GSL#173]
I am trying to compile a program that calls the gsl library. I am starting with a simple example that one can finds online (see below). I followed 

https://github.com/Microsoft/GSL/ 

and the test passed.
I go to //#C/C++ ->Additional Include Directories->  and type  "C:\GSL\include"

When I compile and this is the error:
Severity	Code	Description	Project	File	Line
Error	C1083	Cannot open include file: 'gsl/gsl_sf_bessel.h': No such file or directory	GSLExample	c:\users\pedro\desktop\gslexample\gslexample\gslexample\main.c	5
What am I doing wrong?

The web page of the link above says at the end
"Just place the contents of the include directory within your source tree so it is available to your compiler, then include the appropriate headers in your program, and away you go!"

but I did not go away. Can somebody tell me with more detail how to include the directory within my source tree and if the headers of my program (below) are appropriate?

//#C/C++ ->Additional Include Directories-> type C : \GSL\include

#include <stdio.h>
#include <gsl/gsl_sf_bessel.h>
     
int main (void)
{
  double x, y;
  x = 5.0;
  y = gsl_sf_bessel_J0(x);
  printf ("J0(%g) = %.18e\n", x, y);
  return 0;
}

**Comment by martinmoene** [comment]
That's about [the other GSL (GNU Scientific Library)](https://www.gnu.org/software/gsl/manual/html_node/An-Example-Program.html#An-Example-Program).

**Comment by gdr-at-ms** [comment]
confused report.

**Comment by luisleonn** [comment]
I just need to compile that program to know that I am able to use the gsl library. But when compiling the error 
Error C1083 Cannot open include file: 'gsl/gsl_sf_bessel.h': No such file or directory GSLExample c:\users\pedro\desktop\gslexample\gslexample\gslexample\main.c 5

comes out

**Comment by luisleonn** [comment]
I need directions to run compile a c program that calls gsl

**Comment by neilmacintosh** [comment]
@luisleonn you are looking for a different library: the GNU Scientific Library. This is not it and not a place where you will find help on how to use that library.
