### ISSUE TITLE
microsoft/GSL How to compile it?

### ISSUE THREAD

**Issue by luisleonn** [Microsoft/GSL#174]
I am new to visual studio. I am using visual studio 2015. I need to use gsl. I would be very happy if I can compile the example program in

https://www.gnu.org/software/gsl/manual/html_node/An-Example-Program.html#An-Example-Program

I followed the directions in https://github.com/Microsoft/GSL/

The test was run successfully in the link above. 
I went to the project properties and typed  C : \GSL\include in
#C/C++ ->Additional Include Directories
But I keep getting the error 

Error C1083 Cannot open include file: 'gsl/gsl_sf_bessel.h': No such file or directory GSLExample c:\users\pedro\desktop\gslexample\gslexample\gslexample\main.c 5

**Comment by gdr-at-ms** [comment]
The GSL in this forum is for "The C++ Core Guidelines Support Library".
That is not the same as the one you quoted.  You need to contact the support forum of that library.
