### ISSUE TITLE
Const by default?

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/GSL#176]
9.5 years ago I wrote const_memory_range, a class like array_view<const byte>. At first the class didn't even support non-const views, now it does (it's called data_ref / str_ref now) but the majority of uses is still const. Would it make sense to have it be const by default?
String_view would be const char*, mstring_view would be the non-const / mutable version.

https://code.google.com/p/xbt/source/browse/trunk/xbt/misc/const_memory_range.h?spec=svn1653&r=1653

**Comment by OlafvdSpek** [comment]
BTW, great talk on C++ Con and great work on GSL!

**Comment by neilmacintosh** [comment]
@OlafvdSpek Thanks very much!

This is feedback we've had from more than one person, and I certainly agree that the majority of uses will tend to be for views over const data. We believe that `span` (the class formerly known as `array_view`) sidesteps this problem by letting people use the `T` argument in `span<T>` to indicate constness/mutability. And this means that declarations also look similar to the old ptr/len usages they replace:
`void f(const T* p, int len);`
becomes
`void f(span<const T>);`

For `string_span`, `cstring_span` and their wide-char variants, however, where we have specified mutable CharT as default for `string_span` I can see that there is a good argument for reversing that position. This is something we'll continue to consider.

**Comment by OlafvdSpek** [comment]
Great! Isn't it possible to do the same for span? span<T> would be const, mspan<T> would be non-const?

**Comment by neilmacintosh** [comment]
For `span` there is no need. The `const` is already clearly carried in the template arguments. For example: `span<const int>`. I think `string_span` is a different case because it only asks for the character type and then makes a mutability decision (and `cstring_span` makes the corresponding `const`-ness decision).

**Comment by offa** [comment]
> And this means that declarations also look similar to the old ptr/len usages they replace:
`void f(const T* p, int len);`
becomes
`void f(span<const T>);`

This feels a bit counter intuitive for `std::array`:

```cpp
const std::array<uint8_t, 3> a = { 1, 2, 3 };

gsl::span<uint8_t> s(a); // Fails to compile
const gsl::span<uint8_t> sc(a); // Fails to compile
gsl::span<const uint8_t> scv(a); // Ok
```

So passing `const std::array<uint8_t, N>&` requires `const gsl::span<const uint8_t>&`.

**Comment by gdr-at-ms** [comment]
Arrays own their elements, which is why the `const` virtually propagates through.
`span<T>` does not own the `T`s. They refer to elements owned by someone else. They aren't like `std::array<T,N>`.

**Comment by offa** [comment]
I know, but I expected a `const span<T>` can view a `const array<T>`. However, the example by @neilmacintosh clarified it a lot.
