### ISSUE TITLE
span::size() returns signed value, causes warnings when comparing it to size_t

### ISSUE THREAD

**Issue by KristofferHenriksson** [Microsoft/GSL#177]
Using VS 2015 RTM the following code produces a warning about comparing signed and unsigned values:

```c++ 
#include <gsl/span.h>

bool compare(size_t expected, gsl::span<int> intSpan)
{
    return expected <= intSpan.size();
}
```

Having it be size_t makes interop with existing code much easier without having to consider each cast carefully.

**Comment by neilmacintosh** [comment]
Hi @KristofferHenriksson! `size_t` might simplify interop with some existing code, but not all. As per the rely to #171, this is an explicit design decision that we are comfortable with. I might create a GSL FAQ for this repo and add this.
