### ISSUE TITLE
gsl.h line 617-620: comparison of `bool` value with `-1`

### ISSUE THREAD

**Issue by vladon** [Microsoft/GSL#178]
constexpr bool contains(const index_type& idx) const noexcept
    {
        return m_ranges.contains(idx) != -1;
    }

m_ranges.contains() returns `bool`, but compared with `-1`

**Comment by neilmacintosh** [comment]
Nice catch @vladon. Did you want to submit a PR to fix the issue?

**Comment by neilmacintosh** [comment]
Corrected by PR #217.
