### ISSUE TITLE
Minimize or remove uses of pragma push/pop_macro

### ISSUE THREAD

**Issue by gdr-at-ms** [microsoft/GSL#18]
A VC extension supported by other compilers for compatibility reasons.

**Comment by neilmacintosh** [comment]
I believe the current uses are under an MSVC preprocessor test and are there to make the GSL effective on one of its (less C++14-compliant) target platforms. So I regard them as minimized. Once we no longer support MSVC versions that are not C++11/14 compliant then they can be removed.
