### ISSUE TITLE
data_span for span<const byte>

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/GSL#182]
The second most used span type (AFAIK) would be span<const byte>.
Could we define data_span as span<const byte> and mdata_span as span<byte>?

BTW, is byte finally going to be an official type(def)?

**Comment by OlafvdSpek** [comment]
Looks like Github eats HTML tags. That'd be:
Could we define data_span as span < const byte > and mdata_span as span < byte > ?

**Comment by neilmacintosh** [comment]
Users of the library would be free to create type aliases like those. I'm not sure they're needed within the GSL itself at this stage. We can always revisit this issue if we hear a lot of people find a need for them.

The intent is certainly that 'byte' becomes aalias in the standard library. When I presented the proposal for `span` at the WG21 meeting in Kona, there was discussion on the `byte` type alias and it was generally seen as being interesting/desirable. A straw poll indicated support for bringing it for discussion in its own proposal. That proposal will be submitted to the next WG21 meeting.
