### ISSUE TITLE
warning C4068: unknown pragma in gsl.h and span.h

### ISSUE THREAD

**Issue by Jormungand999** [Microsoft/GSL#186]
Using VC++ 2013 compiler.
If the GSL_THROWS_FOR_TESTING macro is not defined you get this warning
Causes build failures when warnings are treated as errors.

**Comment by neilmacintosh** [comment]
Thanks @Jormungand999, I'll take a look at this.

**Comment by neilmacintosh** [comment]
@Jormungand999 now that `gsl_assert.h` has been overhauled, I couldn't get this to repro with MSVC 2013 no matter which of the three options I selected for contract violation behavior. So I'm going to close out this issue. Feel free to open a new one if you see the problem recur.
