### ISSUE TITLE
span::as_writeable_bytes() should be spelled "as_writable_bytes"

### ISSUE THREAD

**Issue by elronayellin** [Microsoft/GSL#189]

**Comment by neilmacintosh** [comment]
@elronayellin there was an explicit discussion about this and "writeable" was agreed to be the preferred form. I'm not sure either is more correct English.

**Comment by elronayellin** [comment]
If that was a public discussion, I'd like to read the transcript to understand the rationale.  

"Writeable" is clearly English in the sense that an English speaker can understand what it means.  However, a non-English speaker will not find "writeable" in all dictionaries, online or in print; many non-English speakers may not have the latest dictionaries that contain this newer alternate spelling.  "Writable" is the spelling used in the ISO standard text, and all formal text I've come across.  "Writeable" appears to have only 10% the prevalence in google results (for comparison, the misspelling "recieve" seems to be as common as the correct spelling "receive" in google results).

**Comment by neilmacintosh** [comment]
@elronayellin No, this was not a public discussion. 

This function will probably be removed from the standard `span` in the near future anyway, (maybe left as an "extension" free function in our implementation), as there was some skepticism expressed when I took the `span` proposal to the last WG21 standards meeting about the safety and implementation requirements of such a function for a standardized `span`.
