### ISSUE TITLE
as_span(str) returns cstring_span regardless of constness of str

### ISSUE THREAD

**Issue by elronayellin** [microsoft/GSL#192]
because it is implemented with .data() which has no nonconst overload in std::string, unlike std::vector

**Comment by neilmacintosh** [comment]
Well spotted @elronayellin. I agree that this should be corrected. Did you have a PR you'd like to offer?

**Comment by mkurdej** [comment]
This was closed by #205, wasn't it?

**Comment by JordanMaples** [comment]
Closing `as_span` no longer exists.
