### ISSUE TITLE
Silent truncation of array_view?

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/GSL#194]
IIRC in the video you said it'd be ok to pass an av4 to an av2. Wouldn't this allow for silent data truncation?
IMO this should require an explicit sub operator.

**Comment by neilmacintosh** [comment]
@OlafvdSpek you are correct, this does allow silent data truncation. However the primary focus of `span` is ensuring bounds-safety, rather than catching all logical errors associated with accessing the underlying data.

**Comment by OlafvdSpek** [comment]
Sure, but why opt for less correctness then easily achievable?

**Comment by neilmacintosh** [comment]
@OlafvdSpek this behavior has changed in the most recent specification for `span`. Now, you cannot assign to a fixed-length `span` anything other than a span with the same fixed length or a dynamic-length span (in which case a runtime length-check will be performed).

I think this allows the issue to be closed at this point.
