### ISSUE TITLE
Silent failure if `gsl::ensure_z` is not called

### ISSUE THREAD

**Issue by atilaneves** [Microsoft/GSL#196]
Assigning to a `cstring_span` from a `const char*` should be done with `ensure_z`. If it is forgotten however, the code compiles and runs, and fails silently (tried with clang 3.7.0 and gcc 5.2.0):

    #include <string>
    #include <cassert>
    #include "string_span.h"

    int main( ) {
        std::string str = "foo";
        gsl::cstring_span<> good_span = gsl::ensure_z("foo");
        gsl::cstring_span<> bad_span = "foo";

        assert(str.size() == 3); //ok
        assert(good_span.size() == 3); //ok
        //assert(bad_span.size() == 3); //oops, it's actually 4

        assert(str == gsl::to_string(good_span)); //ok
        //assert(str == gsl::to_string(bad_span)); //oops
    }

**Comment by neilmacintosh** [comment]
@atilaneves thanks for the report. This is a known issue that is an artifact of the current implementation where `cstring_span` happens to be a type alias to `span`. That will change soon as the implementation is mapped to the current design and the `ensure_z` problem can be addressed better at that point.
