### ISSUE TITLE
span construction with rvalues

### ISSUE THREAD

**Issue by zapferl** [Microsoft/GSL#200]
Hi,
it does not seem to be possible to construct a span like this:
```
std::vector<unsigned char> g() { return {1, 2, 3}; }
void f(gsl::span<unsigned char> s) {}
int main()
{
    f(g()); // <- does not seem to work with rvalues
}
```
Is this perhaps intentional to limit the chance of spans referencing soon-to-be-evaporated objects and my sample an unfortunate side effect?

Edit: I should add that it does work in VS 2015 but not in clang++ 3.8.0 for example

**Comment by neilmacintosh** [comment]
Hi @zapferl. Your understanding is exactly correct. Making it easy to bind spans to temporaries is mainly going to cover up lifetime management bugs.

**Comment by mmatrosov** [comment]
See also: https://stackoverflow.com/q/78932834/261217
