### ISSUE TITLE
span should not be assignable from nullptr

### ISSUE THREAD

**Issue by hpesoj** [Microsoft/GSL#202]
This code is currently valid:

    span<int> s = nullptr;

This is confusing because this isn't valid:

    if (span == nullptr)

And rightly so; arrays are not pointers.  `span` exists precisely because we want to move away from the C-ish approach of representing an array of `T` using `T*`.

You appear to be using `nullptr` to mean "empty span":

    if (!span) // i.e. span.empty()

_Incidentally, I think replacing `operator bool()` with `empty()` is preferable for consistency with the standard library (see #140)._

`nullptr` specifically represents a null pointer, _not_ an empty array.  I propose you forbid construction and assignment using `nullptr_t`, and instead replace it with your own `empty_t` and `empty` singleton of that type:

    span<int> s = empty;

[Boost.Optional](http://www.boost.org/doc/libs/1_59_0/libs/optional/doc/html/index.html) uses the same idea with `none_t` and `none`.

Perhaps your reasoning for allowing assignment from `nullptr` is that it is often used to represent an empty array in C (or legacy C++), but this isn't a compelling argument.  An empty array can be represented using either: a pair of identical pointers (perhaps null pointers); a pointer and a zero size; or a single pointer pointing to a zero value (i.e. a null-terminated array).  `nullptr` is not an array, and its use to represent one is incorrect, or at best, hacky.

**Comment by neilmacintosh** [comment]
Thanks for the comment @hpesoj, however, we are happy with the design as it stands.

`nullptr` is often used to signal an absence of elements in existing code that takes pointer+length parameters. So constructing a `span` from an absence of elements sensibly yields an `.empty()` span. This is the same behavior that `span` provides for default construction - another case where there is an absence of elements. Moreover, users can distinguish whether an empty `span` was constructed from `nullptr`, or a valid pointer by testing the `.data()` member.

**Comment by hpesoj** [comment]
Do you have any notable examples of functions taking pointer+length for which a null pointer represents an empty array, particularly from the standard library? I would consider this bad design. Any pointer with a zero length represents an empty array; conversely, any pointer with a non-zero length should represent a non-empty array. Having a null pointer also represent an empty array is not only redundant, it is a special case which must be checked for, increasing code complexity and negatively impacting performance. As I mentioned previously, `nullptr` is not an array type, pointers in general are not array types, and I don't think it is wise to encourage the idea that pointers can represent arrays in modern C++.

There are several more problems with your argument that null pointers are used to represent empty arrays. Firstly, this is only a convention, and not a consistent one at that. I have seen code for which the behavior of a "null" array is different from that of an empty array (one with zero length). If your aim is to ease interoperability between old and modern code, this is a risky path to take. By removing assignment from `nullptr`, you would force users to be explicit about what they mean; this is in the spirit of type safety. Secondly, you are not in fact easing interoperability with old code in many cases. Old code treats pointers containing a null value as empty arrays; `span` does not. What's more, `span` treats only the `nullptr` constant as an empty array; old code will not always use `nullptr`. This is another inconsistency in `span`'s behaviour:

    int* p = nullptr;
    span<int*> s = p; // compile error

In my view, this is reflective of the fact that you are using the `nullptr` constant to represent an empty array, rather than treating all null pointers as empty arrays (of course, this would not be desirable). This is why I suggest a special `empty` singleton analogous to `nullptr`, which will provide the same behaviour you desire, but in a technically correct, type-safe and consistent way.

**Comment by bdeeming** [comment]
I tend to agree with @hpesoj. 
Null pointers (to objects in general) are used to signal the absence of objects to which those pointers point to (ie optional semantics). In the context of old style arrays this is: 
'(`nullptr` + ignore length) -> (no object)'
 '(non-nullptr + zero length) -> (array that exists but has no elements)'

To then represent the equivalent of this in a modern style with `span`'s would be something like creating an `optional<span<T>>`, where:
'(`nullptr` + ignore length) -> (empty optional)'
'(non-nullptr + zero length) -> (initialized optional containing an empty span)'

To me this more intentionally (& clearly) represents the two ideas of 'presence' & 'size', independent of each other.

The caveat of course is that C++14 doesn't have `std::optional` in it...

**Comment by hpesoj** [comment]
@bdeeming I agree.  It's pretty horrible semantic overloading, but a lot of people do it.

@neilmacintosh I forgot to mention is that this is not legal:

    span<int*> s = { nullptr, 1 }; // boom!

So it doesn't seem like your design currently treats `nullptr` as an empty array in general.

**Comment by hpesoj** [comment]
Here is what I'm suggesting: https://github.com/hpesoj/GSL/commit/fedefd03c8a1b41de75f5906a9bd6c53720a4b2a (I used `emptyspan` because `empty` conflicts with `std::empty`).

**Comment by gdr-at-ms** [comment]
@hpesoj 
Wouldn't the default constructor be sufficient?

**Comment by neilmacintosh** [comment]
@bdeeming If someone is passing nullptr together with a size, then it is a logical error, hence the "boom" in your example.

@hpesoj As previously explained, if code wishes to behave differently depending on whether an empty `span` contains a `nullptr` or is empty because it was default-constructed or initialized with `{p,0}` it can do so, by checking the value of `.data()`.

**Comment by hpesoj** [comment]
@gdr-at-ms Yes, I think it would be.  My `emptyspan` idea is probably unnecessary.

@neilmacintosh I was about to answer trying to clarify my argument, but I realised I may be misinterpreting you.

When you say that `nullptr` signals a "lack of elements", is this distinct in your mind from an "empty array/span"?  In other words, are you anticipating that, when `.size() == 0`, users may wish to distinguish between `.data() == nullptr` (a "lack of elements") and`.data() != nullptr` (an "empty array"), and you are providing `nullptr` as a convenient abbreviation for `{ nullptr, 0 }` or `{ nullptr, nullptr }`?  That would explain the implementation of `operator bool()` (removal pending), as it allows `span` to be used much like a pointer in this way:

    void foo(span<int*> s) {
        if (s) { … }
    }
    
    foo(nullptr);

I have a problems with this too, more along the lines of what @bdeeming was saying, but wanted to make sure I understand your rationale.

Thanks for your consideration by the way! :+1:

**Comment by neilmacintosh** [comment]
@hpesoj Thanks for the interest!

Yes, there are two distinct properties that users can test on a `span`: 

1. Was it initialized with a nullptr and zero-length (and there are at least three ways of doing that)?
2. Does it have zero-length?

Sometimes users want to identify 1. distinctly from 2...sometimes not. So the type allows construction from nullptr and provides sufficient enquiry functions that users can decide.

And yes, allowing construction from `nullptr` was designed to be shorthand for `{nullptr, 0}` or `{nullptr, nullptr}`. The shortest version of all is just default construction.

**Comment by hpesoj** [comment]
@neilmacintosh Thanks! I think I understand now.

Fundamentally, an array is a collection of objects which can be referred to by index. The data pointer within `span` and other array types is merely an implementation detail. That is why I say that the `.data()` pointer itself does not affect the _value_ of the array; only the contents of the array (or lack thereof) affects its value. The only reason `.data()` is publically accessible is because permitting low-level access to the internal data is useful enough to justify breaking encapsulation, and any reasonable C++ implementation naturally conforms to this interface.

I am sure none of this is news to you, as `span` already implements equality correctly. My point is that it is bad practice for the behaviour of a program to depend on implementation details of its components. In this case, checking whether `.data()` is null is bad practice; it is a hangover from C-style arrays which _are_ represented by raw pointers.

This is not to say that I consider it good practice to check whether C-style arrays are null.  In my opinion, pointers should represent arrays _or_ optional values, _never_ both at the same time (see @bdeeming's comments).  This is good practice because it means you can implement many array algorithms without having to check for the special case when `arr == nullptr` (which helps complexity and performance).  This is the [Single Responsibility Principle](https://en.wikipedia.org/wiki/Single_responsibility_principle). In our case, an array class should implement _only_ the functionality of an array, not that of an optional value.  If you actually need the array to be optional, use a pointer to an array (e.g. `span<T>*` or `T**`) or another class that provides that functionality (e.g. `optional<span<T*>> or `optional<T*>`).

But at the end of the day, I am not sure any of this is particularly relevant.  I only give my opinion on these things because you seem to be justifying the existence of `span(nullptr_t)` by citing the potential to (mis)use array types in this way.  Personally, I do not see how allowing assignment from `nullptr` has anything to do with this.  If someone _really_ wants to abuse `span` in this way, they can do it without this feature:

    void foo(span<int*> s) {
        if (s.data()) { … }
    }
    
    foo({ nullptr, 0 });

I cannot see them having a problem with this, as it is virtually identical to what they used to write in ye olde days:

    void foo(int* data, size_t size) {
        if (data) { … }
    }
    
    foo(nullptr, 0);

But okay, you said that `nullptr` is just acting as convenient shorthand.  I can think of two reasons you might wish to have this shorthand notation:

1. To facilitate the use of `{ nullptr, 0 }` as a "null array" (your cited reason).
2. To facilitate the use of `{ nullptr, 0 }` as an "empty array".

I have already highlighted why I consider the concept of a "null array" to be bad practice, and I'm sure it goes without saying that officially facilitating bad practice is not a good thing.  Conversely, the concept of an "empty array" is just fine, but I still consider use of `nullptr` as shorthand to be bad for two reasons (note that these apply regardless of your reason for wanting the shorthand):

* Consistency:
 * `s = nullptr` is valid, but `s == nullptr` is not.
 * `s = nullptr` is valid, but `s = ptr = nullptr` is not.
* Correctness:
 * `nullptr` is a pointer type, but `span` is an array type (implicit conversion).

Making `span(nullptr_t)` __explicit__ would go some way towards fixing these issues, as explicit constructors do not have implicit conversion semantics.  That said, the constructor would then be functionally identical to the default constructor.  In addition, there would still be a consistency issue, since `span(nullptr)` would be valid, but `span(ptr)` wouldn't.

As @gdr-at-ms suggested, the default constructor is probably sufficient shorthand (`s = span<int*>()`).  However, if you really want a better shorthand, the `emptyspan` approach gives you one without the consistency and correctness issues.

I hope I have understood your reasoning correctly, and I hope I have made my reasoning clear.  There probably is not much more that I can add after this.  I have spent so much time arguing what may seem to be a relatively minor point because the GSL and the C++ Core Guidelines have the potential to influence how many people write their code, and I think it is important not to encourage bad practice!

**Comment by hpesoj** [comment]
Sorry for coming back to this again; I can't help myself!

I just realised my second point about consistency may not be valid:

* `s = nullptr` is valid, but `s = ptr = nullptr` is not.

This is in fact how the smart pointers behave. It thus follows that adding `operator==(std::nullptr_t)` (as I assume is being considered in https://github.com/isocpp/CppCoreGuidelines/issues/399) would resolve my first point about consistency:

* `s = nullptr` is valid, but `s == nullptr` is not.

However, I think the point about correctness will always apply:

* `nullptr` is a pointer type, but `span` is an array type (implicit conversion).

In fact, I just thought of a practical implication of sacrificing correctness in this way: overload resolution:

    void foo(span<int>) {
        std::cout << "foo(span<int>)\n";
    }

    void bar(int*) {
        std::cout << "bar(int*)\n";
    }

    void bar(span<int>) {
        std::cout << "bar(span<int>)\n";
    }

    int main() {
        std::cout << "foo(nullptr) -> "; foo(nullptr);
        std::cout << "bar(nullptr) -> "; bar(nullptr);
    }

Or even more problematic:

    void foo(span<int>) {
        std::cout << "foo(span<int>)\n";
    }

    void bar(std::unique_ptr<int>) {
        std::cout << "bar(std::unique_ptr<int>)\n";
    }

    void bar(span<int>) {
        std::cout << "bar(span<int>)\n";
    }

    int main() {
        std::cout << "foo(nullptr) -> "; foo(nullptr);
        std::cout << "bar(nullptr) -> "; bar(nullptr);
    }

On its own, I don't think this is a compelling reason to avoid conversion from `nullptr` (e.g. `unique_ptr` and `shared_ptr` would also conflict). However, if sacrificing correctness for practical benefits also has practical disadvantages, it is important to consider what is more important.

I personally consider better overload resolution to be far more important than having a convenient shorthand for a "null array", especially since it's possible to have this without sacrificing overload resolution (i.e. `nullspan` -- though as I've mentioned before, I consider "null arrays" to be conceptually unsound).
