### ISSUE TITLE
Add decay(span) and as_dspan(...) functions

### ISSUE THREAD

**Issue by matus-chochlik** [microsoft/GSL#203]
Hi,

I would like to suggest adding the following two functions to `span.h`:

```
template <typename T, std::ptrdiff_t FirstDimension, std::ptrdiff_t ... RestDimensions>
span<T, dynamic_range, RestDimensions...>
decay(span<T, FirstDimension, RestDimensions...> s)                                                                                       
{                                                                               
        return {s};                                                             
}

// as_decayed_span / as_dynamic_span
template <typename ... P>                                                       
auto as_dspan(P&& ... p)                                                        
{                                                                               
        return decay(as_span(std::forward<P>(p)...));                           
}
```

motivation: function template with 'dynamic' `span<T>` argument

```
template <typename T, std::ptrdiff_t N>
void bar(gsl::span<T, N>)
{
}

template <typename T>
void foo(gsl::span<T>)
{
  // we don't want a separate instantiation of foo for every value of N
}

int main(void)
{
    int ia[7] = {1,2,3,4,5,6,7};

    bar(gsl::as_span(ia)); // OK
    //foo(gsl::as_span(ia)); -- clang: no matching foo, could not match -1 against 7
    foo(gsl::as_dspan(ia)); // OK
    foo(gsl::as_span(ia, 7)); // OK, but prone to errors if dimension of ia changes
    foo(gsl::as_span(ia, sizeof(ia)/sizeof(ia[0]))); // OK, but ugly :)
    foo(gsl::span<int>(ia)); // OK, but ugly

    return 0;
}
```

or is there some other straightforward way for `span<T,N>` to implicitly convert to `span<T>` when calling functions like `foo`?

**Comment by matus-chochlik** [comment]
Alternatively, `decay` could also be implemented as a member function of `span<T>`, which is probably more consistent with the current interface of `span`.

In case there is interest in this addition and there are no objections I can create a PR for this.

**Comment by neilmacintosh** [comment]
@matus-chochlik I haven't had a chance to double-check yet, but I'm pretty sure that what you want `decay` to achieve is already possible using the conversion constructors available on `span` (and if not in the current implementation, it should be). The design always allowed `span<T,N>` to go to `span<T,dynamic_extent>`.

**Comment by matus-chochlik** [comment]
@neilmacintosh I know that there is the constructor accepting `span<T, dynamic_range, RestDimensions...>` and it does work if the function is not templated. For example:

````
void baz(gsl::span<int>){ }

int main(void)
{
        int ia[7] = {1,2,3,4,5,6,7};                                            
        baz(gsl::as_span(ia));
        return 0;
}
````
... compiles without errors and works as expected, but the following ...
````
template <typename T>
void foo(gsl::span<T>){ }

int main(void)
{
        int ia[7] = {1,2,3,4,5,6,7};                                            
        foo(gsl::as_span(ia));
        return 0;
}
````
... does not, at least not with clang++-3.6, which is the only one of the compilers that I have installed which actually can compile GSL at the moment.

**Comment by matus-chochlik** [comment]
OK, I just checked and this:
````
template <typename T, int N = -1>
struct blah
{
        blah(void) { }

        template <int M>
        blah(blah<T, M>)
        { }
};
                                          
template <typename T>
void bleh(blah<T>){ }                                                                               
                                                                                
int main(void)                                                                  
{                                                                               
        bleh(blah<int, 6>());
        return 0;
}
````
does not compile neither with clang++ nor with g++ (4.8.4).

**Comment by neilmacintosh** [comment]
Interesting. So if I understand correctly, you want to have only one instantiation of `foo()` for each `T`, and that instantiation accepts a `span<T,dynamic_extent>` parameter (i.e. dynamic-length, single dimension). 

And you have noted that you can achieve the same effect by just calling the `span<T,dynamic_extent>` constructor explicitly, like so:

`foo(gsl::span<int>(ia))`

So this is just about notation, rather than functionality?
(just trying to make sure I haven't missed anything)

**Comment by matus-chochlik** [comment]
Basically yes, its not much of a problem if the `T` type is an `int` (but its unnecessarily verbose nonetheless), but it gets ugly when the type is something like a instantiation of a template with several parameters.

**Comment by JordanMaples** [comment]
Maintainers' call: Sorry for the delay. Now that span has been standardized, the only delta between `gsl::span` and `std::span` is the bounds checking. We are following the standard interface exactly.
