### ISSUE TITLE
Explicit construction of a span from a temporary

### ISSUE THREAD

**Issue by rkhlebnikov** [Microsoft/GSL#212]
Consider a simple code snippet:

    std::string get_str()
    {
        return{"str"};
    }

    void consume_span(gsl::cstring_span<> sp)
    {
    }

    int main()
    {
        consume_span(get_str());
    }

Clearly, at the moment, this will not compile without Microsoft C++ extensions which allow binding a temporary to a non-const reference. 

It is also clear that constructing spans from temporaries is dangerous - thus the deleted `as_span` version with a forwarding reference to a container (and an overload for l-value reference, effectively deleting the r-value reference overload). However, in cases as described above, this restriction would lead to at least some code bloating, similar to `auto s = get_str(); consume_span(s)`.

My question then is - what do you think about introducing a function that would allow explicitly constructing spans from temporaries for such cases? An example implementation might be:

    template <typename Cont>
    constexpr auto as_temp_span(Cont &&arr)->std::enable_if_t<!details::is_span<std::decay_t<Cont>>::value,
        span<std::add_const_t<std::remove_reference_t<decltype(arr.size(), *arr.data())>>, dynamic_range >>
    {
        Expects(arr.size() < PTRDIFF_MAX);
        return{arr.data(), static_cast<std::ptrdiff_t>(arr.size())};
    }

(Note `add_const_t` to force construction of a span of immutable values).

Then the usage will look like:

    consume_span(gsl::as_temp_span(get_str()));

where the programmer explicitly stated that the span is being constructed from a temporary.

**Comment by neilmacintosh** [comment]
In general, we want the GSL to reflect a minimal set of types and functions. That doesn't restrict people from adding their own helpers, of course. 

In this case, encouraging the construction of spans from temporaries is not something I would want to encourage with a helper in the GSL. Having explicit intermediate variables makes the lifetimes clearer to author and maintainer.

**Comment by rkhlebnikov** [comment]
Makes sense. It is however a little surprising to have the similar code behaving differently when used with MS compiler vs gcc/clang (well, it probably always is, so this case is no different). Thanks anyway!
