### ISSUE TITLE
Is the checker tool already out?

### ISSUE THREAD

**Issue by rhegner** [Microsoft/GSL#213]
I was excited to see Bjarne's and Herb's talks about the new C++ core guidelines. 

I'm wondering if the checker tool is already out? If yes, where can I find it?

**Comment by grahamreeds** [comment]
Neil said it will be out about the same time as Update 1 for VS2015.

GR

**Comment by gdr-at-ms** [comment]
They are coming.

**Comment by neilmacintosh** [comment]
Thanks for the interest @rhegner! @grahamreeds has it right: the first Microsoft implementation of checkers for the core guidelines will be released around the same time as Visual Studio 2015 Update 1. That initial implementation will check (nearly all) the rules contained in the "bounds" and "type" profiles in the guidelines. I believe that @mgehre has also started implementing a number of the same rules in clang-analyze.
