### ISSUE TITLE
span offers less compile-time safety than legacy code

### ISSUE THREAD

**Issue by hpesoj** [Microsoft/GSL#214]
This is a bit of a tentative issue, as I'm not sure of exactly what you are aiming to achieve with the `span` class.

To me, statically sized `span`s are mostly useful if you are concerned with compile time safety.  Take this legacy code:

    void foo(int (&)[3]) { … }

This is safer than taking a pointer, as the size of the array argument must be known at compile time. For example, this code will fail to compile:

    int* values = new int[2];
    foo(values);

As will this code:

    int values[2];
    foo(values);

Even if I know the size of the array pointed to by `values`, there is no way to pass it to `foo`.

If I update this legacy code using `span`, I would hope to get the same compile-time safety:

    void foo(span<int, 3>) { … }

However, that doesn't seem to be the case, as I _can_ pass `values` as long as I purport to know its size:

    int* values = new int[2];
    foo({ values, 2 });

As will this code:

    span<int> values;
    foo(values);

I have watched your [CppCon talk](https://www.youtube.com/watch?v=C4Z3c4Sv52U) and understand the bit about compatibility with legacy code. But it seems to me that this only applies to dynamically sized `span`s. Even if a warning is generated by static analysis, statically sized `span`s seem to offer less compile-time safety than their legacy equivalent.

**Comment by neilmacintosh** [comment]
Hi @hpesoj. It would be possible for a compiler to catch both the examples you give at compile-time as failures, even though they are not strict type violations.

However, in some cases - you are correct - it is not possible to be sure at compile-time that a dynamic-size `span` being passed to a fixed-size `span` argument is going to be sufficiently long. In those cases a compiler could still issue a warning that such code is not provably safe. I think that's a nice aspect of statically-sized `span`: it makes a part of the function's contract very clear, and compile-time tools can then warn whenever they see anyone not clearly ensuring they meet the contract. 

There is a second aspect to `span` that I think you have overlooked here that relates to that contract-checking concept: runtime checking. Part of the design of `span` is that upon construction of the fixed-size `span` argument from the dynamic-size `span` a contract check ensures the dynamic-size `span` has at least 3 elements. This guarantees that access to the parameter within `foo()` is bounds-safe.

**Comment by hpesoj** [comment]
I think I understand your approach more now. How do you determine when to rely on static analysis to highlight questionable code, and when to make it a compiler error?

Also, out of interest, how can you catch the examples I gave at compile time?

**Comment by neilmacintosh** [comment]
@hpesoj regarding warnings vs. errors, I guess the easiest way to think about it is that we always want to issue warnings for misuses that comply with language rules. Whether to treat those warnings as errors (an option most compilers provide) is always up to the user.

The examples can be caught at the point of call because a tool can see that a dynamic-length `span` is being constructed and known (or even suspected if the tool is paranoid) to be out-of-range for the fixed-length of 3, specified by `foo()`. Whether or not such warnings would be annoying is a different issue. Especially given that if built with contract checking enabled in the GSL, both your examples will cause a runtime failure.
