### ISSUE TITLE
inconsistency in span<T> constructors

### ISSUE THREAD

**Issue by dahlheim** [Microsoft/GSL#219]
Currently the span<T> constructors are inconsistent in that the constructors from other spans and containers are enabled only for matching value types (and bounds), while the array constructors are enabled unconditionally (and static_assert on mismatch). I believe this should be resolved in favour of always enabling conditionally, to make using functions overloaded for spans with various value types more convenient.

**Comment by neilmacintosh** [comment]
Agreed @dahlheim. That's my fault and is a legacy of making things convenient for diagnosing failures while I was reworking things. It should be fixed soon.

**Comment by neilmacintosh** [comment]
This issue can be closed out now, as `span` has been voted into C++20 with constructors from spans and containers that have sensible rules for allowing construction of a `span` with an element type that does not necessarily have to be an exact match. Extents are required to match exactly in the case of fixed-extent `span`s as this is a desirable feature for preventing errors.
