### ISSUE TITLE
narrow should throw when casting negative to unsigned

### ISSUE THREAD

**Issue by brunom** [Microsoft/GSL#222]
int i = -42;
    unsigned u = gsl::narrow<unsigned>(i);

runs when it should fail with an exception because -42 is not representable as an unsigned.

**Comment by AndrewPardoe** [comment]
Editors discussed 14 Dec 2015

**Comment by neilmacintosh** [comment]
Agreed @brunom! The initial implementation of `narrow()` (and `narrow_cast()`) was pretty bare-bones. Feel free to offer a PR if you are so inclined. :-)
