### ISSUE TITLE
add a release function and operator bool to final_act

### ISSUE THREAD

**Issue by nolange** [Microsoft/GSL#231]
I like to propose adding a *release* function, which exists in other resource owners (unique_*, shared_*) and final_act could be understood as owning the cleanup code. For a common interface to resource owners, an *operator bool* should denote if the final_act is still active.
The following code currently cant be done without try/catch:

```c++
try {
        std::unique_lock<mutex_t> hold( mtx, std::try_to_lock ); // might throw
        if ( !hold.owns_lock() ) {
            return busy;
        }
        return doStuff();
    } catch (...) {
        warning();
        throw;
    }
```

With a release function, this could be modified into this:
```c++
    auto guard = finally([](){
        warning();
    });
    std::unique_lock<mutex_t> hold( mtx, std::try_to_lock ); // might throw
    guard.release(); // did not throw
    if ( !hold.owns_lock() ) {
        return busy;
    }
    return doStuff();
```

PS. final_act is a rather unfitting name, its acting on leaving the scope, final sounds alot more terminal and lethal than that, and is used for classes you cant extend anymore in C++. Maybe scope_guard or unique_cleanup would fit better in the existing library scheme, particularly if the release function gets added

**Comment by neilmacintosh** [comment]
Thanks for the suggestion @nolange. These changes would conflict with the design goal of `final_act`, which is to provide a very simple, low-cost way to ensure some code is run before a scope is exited. There is nothing preventing users building more complex abstractions than `final_act`, however, as part of the GSL, the aim of `final_act` is to be simple, reliable and easy-to-use.
