### ISSUE TITLE
Add gsl_prolog.h and gsl_epilog.h

### ISSUE THREAD

**Issue by menuet** [Microsoft/GSL#232]
Hi,

First, thank you @neilmacintosh for having merged my requests and thank you @annagrin for having fixed my mess :-)

I wonder if it would be cleaner to create a prolog header file and an epilog header file where we would put all the #ifdef _MSC_VER, so that we can share these prolog/epilog between span.h and string_span.h.
What do you think?

Also, I think there is a small mistake at the end of the file string_span.h:
#define GSL_MSVC_NO_CPP14_STD_EQUAL
instead of
#undef GSL_MSVC_NO_CPP14_STD_EQUAL

Regards

Pascal

**Comment by neilmacintosh** [comment]
Hi @menuet! Thanks for the PRs! In general, I dislike "partial" headers that contain prolog/epilog code as they make files harder to understand. In addition, one of our goals is to ultimately remove the need for #ifdefs and get as close as we can to portable, standard C++.

Thanks for catching the #define that should have been an #undef. I have fixed that with a commit just now.
