### ISSUE TITLE
gsl::span<void>

### ISSUE THREAD

**Issue by jimvonmoon** [Microsoft/GSL#234]
It seems that it's currently impossible to use `gsl::span` in such situation:
```
// before
void setData(void* data, std::size_t size);

// after
void setData(gsl::span<void> data);
```
Using `gsl::span<void>` results in compile error in MSVC 2013:
```
gsl\include\span.h(1242): error C2182: 'data' : illegal use of type 'void'
          see reference to class template instantiation 'gsl::span<void,-1,>' being compiled
gsl\include\span.h(1251): error C2182: 'abstract declarator' : illegal use of type 'void'
```
I guess using `void*` isn't particularly elegant, but sometimes it's convenient, especially when dealing with C libraries. After some research I found that it has been resolved in one implementation of `array_view` in the following way:
https://github.com/jbms/array_view/blob/master/src/jbms/array_view.hpp#L27

If support for `void*` was left out intentionally then please just close this issue.

**Comment by neilmacintosh** [comment]
Hi @jimvonmoon! You are correct, `span<void>` is not a concept that GSL currently supports.

If you want to pass around a pointer to a collection of bytes (which is usually the purpose of passing a `void*`) then you should use `span<byte>` instead.
