### ISSUE TITLE
as_bytes check too strict

### ISSUE THREAD

**Issue by tylorr** [Microsoft/GSL#236]
I'm working with a library that has a struct that looks something like this:
```
struct Vec2
{
    float x, y;
    Vec2() { x = y = 0.0f; }
    Vec2(float _x, float _y) { x = _x; y = _y; }
};
```
The `as_bytes` function checks if the value_type of the span satisfies `std::is_trivial`. This check is very strict and excludes structs as simple as the one above. Are there more permissive checks we could use that are still safe? I know that `reinterpret_cast` in this case requires that the type satisfies `std::is_standard_layout`

**Comment by gdr-at-ms** [comment]
Note that defining `Vec2` as
```
struct Vec2 {
  float x = { };
  float y = { };
};
```
gives you all the benefits.  That might be something your library's author should consider.  Less typing with at least same memory safety.

 PS: The `=` is for buggy parsers.



-------- Original message --------

**Comment by tylorr** [comment]
Yeah, that was my first thought but that struct is initialized using the `Vec2(x, y)` form in 100+ places and they would all have to be updated to use the `Vec2{x, y}` form.

**Comment by gdr-at-ms** [comment]
Yeah, brace-initialization rocks! :-)


-------- Original message --------

**Comment by tylorr** [comment]
Actually, I just checked and that version of `Vec2` is also not trivial and would also fail the check.

**Comment by KristofferHenriksson** [comment]
It's worth noting that only as_bytes fails due to this check. I can still create a span of this type.

    std::vector<Vec2> v;
    auto mySpan = as_span(v); // works
    auto byteSpan = as_bytes(mySpan); // fails

**Comment by neilmacintosh** [comment]
@tylorr we have removed the restriction on `as_bytes()` and `as_writeable_bytes()` in the latest version of the library. It is unnecessary to allow inspection of object representation, which is the aim of `as_bytes()`.
