### ISSUE TITLE
'static_bounds' conversions are very lenient

### ISSUE THREAD

**Issue by Som1Lse** [microsoft/GSL#237]
Namely

``` c++
static_bounds<2,3> b1;
static_bounds<3,2> b2 = b1;
```

is totally fine with the GSL (since 3*2 <= 2*3), but it also allows

``` c++
int a[2][3];
span<int,3,2> s = a;
```

to compile (and run) despite 'a' being an array of size 2 of arrays of size 3 of ints, and the 's' (supposedly) referencing an array of size 3 of arrays of size 2 of ints (the sizes are reversed).

I personally believe that this is much more likely to cause confusion and bugs rather being helpful, as I cannot come up with a realistic case where this would actually be desired.
I would say that this sort of conversion should only be possible with code where you explicitly indicate that you want such a conversion (possibly by calling a function named 'bounds_cast' and/or 'span_cast').

I would be really interested in hearing differing opinions and the reasoning for such opinions.

**Comment by neilmacintosh** [comment]
`span` assumes that its underlying storage is always contiguous. So a `span` of (3,2) and a `span` of (2,3) are just different projections over the same underlying contiguous storage of 6 elements. This is convenient as some users like to change projections over data. For example, you may want to pass a `vector` of 4 elements to a function that will treat them as a 2x2 2D array. 

If we saw a lot of bugs being introduced by accidental conversions, then I guess we would consider an explicit function to assist with conversion. Personally, I find code like your second example pretty clear about what is going on. As long as the conversion rules prevent overrun (and they should, modulo bugs), then the key safety goal of `span` has been achieved.

**Comment by Som1Lse** [comment]
This case is obviously a matter of taste, but I would say that if you wanted the code in my example to compile the correct way to indicate that would be using `as_span`:
```c++
int a[2][3];
auto s = as_span(as_span(a),dim<3>(),dim<2>());
```
The above code is explicit about the fact that you want to have a different projection, over the storage.

Also interestingly:
```c++
vector<int> v(4);

//compiles and fails during runtime if `v` is not large enough as expected
span<int,4> s = v;

//compiles and fails during runtime if `v` is not large enough as expected
span<int,2,2> s2 = v;

//error due to being unable to construct `static_bounds<2,2>` from a `static_bounds<4>`,
//because the latter has fewer dimensions than the former
span<int,2,2> s3 = s;
```
Which seems like an inconsistency to me.

In the end this is a matter of taste, and I happen to be the on that is NOT in charge of the library :)

**Comment by JordanMaples** [comment]
Closing: The code has diverged significantly since this was filed.
- `as_span` doesn't exist.
- `static_bounds` was moved to multi_span and has since been deprecated.
