### ISSUE TITLE
What is the rationnal for using signed integer as size ?

### ISSUE THREAD

**Issue by vlj** [Microsoft/GSL#238]
Hi,

I set visual studio 2015 to treat errors as warning.

With the following code snippets:

void fill_fragment_constants_buffer(gsl::span<float> buffer, const some_pointer_type *) const
{
...
Expects(buffer.size_bytes() >= FragmentConstantOffsetCache.size() * 4u);
...
}

It fails because there's a comparaison between signed and unsigned int, revealing that buffer.size_bytes is signed, it's a ptrdiff_t.
Looking at GSL code it looks like most size_type for span are ptrdiff_t and thus are signed, however if I understand correctly span<> philosophy the size shouldn't be negative.
Can span<> encapsulate "reverse" range ?

**Comment by neilmacintosh** [comment]
Hi @vlj, this was discussed in #171. Essentially, the designers of the GSL believe that a signed integer is the correct choice for the indexing and measurement type. To address your second question, you are correct, the size should not be negative in a `span`. I'm not quite sure what you mean by a "reverse range", though.

**Comment by vlj** [comment]
Thanks.
About reverse range, I was wondering if the possibility of having negative size was kept for span defined by pointer to the last element (and thus offset to the other end of the span is negative).

**Comment by neilmacintosh** [comment]
Ah, I see. No, `span` doesn't support negative indices or that sort of "from the end" reverse span definition.
