### ISSUE TITLE
error: no return statement in constexpr function

### ISSUE THREAD

**Issue by ennis** [Microsoft/GSL#239]
When compiling with clang, I get the following error:
```
GSL/include/string_span.h:435:30: error: no return statement in constexpr function
    constexpr const_iterator cend() const noexcept
                             ^
```
The return statement indeed seems to be missing:
https://github.com/Microsoft/GSL/blob/95776663dc4bcc90b435c95ebc1e7ccc01e269fa/include/string_span.h#L438

**Comment by neilmacintosh** [comment]
Nice catch, @ennis! Thanks for the report...I've checked in a fix.
