### ISSUE TITLE
GSL doesn't work with GCC 4.9 used by travis-pr

### ISSUE THREAD

**Issue by vlj** [Microsoft/GSL#240]
Hi,

there was 3 GCC releases since the 4.9 version but travis-pr (which is used by several projects on github) still uses it. It doesn't support all of c++ 14.

Here is the build log when including gsl.h :
https://travis-ci.org/RPCS3/rpcs3/jobs/100151269

**Comment by vlj** [comment]
nvm it looks like travis ci is actually using 4.6 but it's possible to use newer gcc version.

**Comment by danilaml** [comment]
@vlj It's 4.9 for rpcs3: https://github.com/RPCS3/rpcs3/blob/master/.travis.yml#L81
