### ISSUE TITLE
Unsafely growing the size of a `multi_span` with seemingly safe code

### ISSUE THREAD

**Issue by Som1Lse** [microsoft/GSL#241]
``` c++
int a[1][3] = {{0,1,2}};
auto s = as_span(a);//bounds are 1 and 3
span<int,3,dynamic_range> s2 = s;//bounds are 3 and 3

for(auto &e:s2){
    cout << e << ", ";//prints 0, 1 and 2 followed by six uninitialized values
}
```

This is especially bad if the data after the array is security sensitive data, or if you are writing instead of reading.

**Comment by neilmacintosh** [comment]
Thanks for the report @Som1Lse! After the initialization of `s2` from `s`, the bounds of `s2` should be 3 and 1, so this looks like a bug to me. If you think you have a fix, I'd be happy to review a PR.

**Comment by neilmacintosh** [comment]
I updated the title to reflect that this defect would only apply to `multi_span` and not `span`.

**Comment by JordanMaples** [comment]
Maintainer's call: multi_span is deprecated, closing.
