### ISSUE TITLE
Use of old style cast warning with clang

### ISSUE THREAD

**Issue by garyfurnish** [Microsoft/GSL#242]
GSL/include/span.h:1821:17: error: use of old-style cast [-Werror,-Wold-style-cast]
        return {(OtherValueType*) this->data(), size,```
with 

    clang version 3.8.0 (https://github.com/llvm-mirror/clang.git d9c8a628c1dd52a71b6aa7c22cc94ee74ca609c3) (https://github.com/llvm-mirror/llvm.git e193ff319c736fa0eaeefb8a6dfc900545324faa)
This is not the same as #220 as this is with clang itself, not a 3rd party checker.

**Comment by neilmacintosh** [comment]
Thanks for the PR @garyfurnish! This is fixed now.
