### ISSUE TITLE
C++ feature and compiler detection macros

### ISSUE THREAD

**Issue by chfast** [Microsoft/GSL#244]
It is more like invitation to discussion rather than an issue.

I've spotted this project added some code that detects the compiler and marks some C++ features: https://github.com/Microsoft/GSL/blob/master/include/string_span.h#L34-L40

As GSL is designed to be header-only extension to C++ standard library, can we consider adding also a set of macros helping detecting compiler, operating systems, targets, C++ features? It is probably impossible to match all cases other projects need but creating a good base set and also a good convention would be very helpful.

**Comment by neilmacintosh** [comment]
Hi @chfast! I would not like to see a bunch of macros to detect those platform details.

We have it as an aim for this implementation of the GSL to be written in portable C++. We would like to avoid any compiler or platform-specific workarounds. For the moment, as MSVC is still closing in on C++11 and C++14 compliance, some workarounds are going to be necessary. However, we hope that over time, we can remove the need for any platform-specific code.

**Comment by chfast** [comment]
Thanks @neilmacintosh for the answer.

That sounds reasonable, but still have some side questions.

1. What with compiler-specific features used like https://github.com/Microsoft/GSL/blob/master/include/gsl.h#L106-L111?
2. Would you consider using `#if` instead of `#ifdef` valid and/or more consistent in such cases?. If I'm not wrong, undefined macros used in `#if` should be replaced with 0.

**Comment by gdr-at-ms** [comment]
@chfast 
That is something we would like to see kept to the minimum (e.g. close to zero.)
The fact that we have to use some macros in the current implementation is an embarrassment that we are working hard to fix -- both on the language side (e.g. see contracts), and on the compiler side (MSVC catching up on conformance.)

**Comment by neilmacintosh** [comment]
1. is part of the set of things we hope to one day eliminate with sufficient compiler support for language elements like contracts.
2. I guess I never developed a strong feeling about `#if` versus `#ifdef`, other than my desire to see both eliminated ;-)
