### ISSUE TITLE
Division by zero for empty multidimensional dynamic spans

### ISSUE THREAD

**Issue by gix** [microsoft/GSL#245]
The calculation of extents (and possibly other things) of multidimensional spans with dynamic bounds results in division by zero [in this line](https://github.com/Microsoft/GSL/blob/62b063a27258f8d6344a4ddd49ddd8739f71eb49/include/span.h#L397).

Take for example a 2D view onto a vector:

```
std::vector<int> vec = {};
size_t w = 3; // Arbitrary
size_t h = vec.size() / w;
// Create a (w x h) 2D view
auto view = as_span( as_span( vec ), dim<>( w ), dim<>( h ) );

view.extent<0>(); // Expected to return 0 but crashes.
```

Is this an oversight or not supported?

**Comment by neilmacintosh** [comment]
Looks like a bug to me. Thanks for the report @gix!

**Comment by neilmacintosh** [comment]
@mkurdej I see that you have a commit to fix this issue...I'd be happy to take it as a PR if you're interested in offering it....

**Comment by mkurdej** [comment]
Sure. There is already PR #250.

**Comment by JordanMaples** [comment]
Maintainer's call: Closing. This issue is no longer relevant as the functions referenced no longer exist.
