### ISSUE TITLE
std::copy doesn't work on 2 span

### ISSUE THREAD

**Issue by vlj** [Microsoft/GSL#248]
CppCoreGuidelines rule I.13 mention function 
"void copy(span<const T> r, span<T> r2); // copy r to r2"
but I don't find it it gsl code.
std::copy on the other hand requires 3 arguments and requires iterators.

**Comment by neilmacintosh** [comment]
It's a good point @vlj. It would be nice to add a simpler `copy()` overload to the GSL.

This would presumably become unnecessary once the "ranges" versions of copy makes it into the standard (assuming a simple conversion between `span`s and ranges). 

interested in offering a PR to add `copy()`?

**Comment by chfast** [comment]
Should that be a `std::copy()` overload? Does the standard allow overloading functions from `std` namespace?

**Comment by neilmacintosh** [comment]
@chfast that can't be a `std::copy` overload, as overloading parts of the standard library is not ok. However, there is nothing preventing someone offering a PR with a `gsl::copy` that can be used until ranges makes its way into the standard library.

**Comment by neilmacintosh** [comment]
This has now been addressed in PR #344.
