### ISSUE TITLE
Cannot compile when using *zstring

### ISSUE THREAD

**Issue by theodelrieu** [Microsoft/GSL#249]
Hello! I tried to use the zstring aliases with clang 3.7.1 and gcc 5.3.1 on Debian 8.2 today. (with -std=c++14)

This simple piece of code doesn't compile:

```
#include <gsl.h>

int main()
{
    gsl::zstring s;
}
```

Here is the output I get with gcc: 
> error: missing template arguments before 's'

With clang:
> error: use of class template 'gsl::zstring' requires template arguments

I don't know if default template arguments are allowed in using aliases, but both gcc and clang don't seem to recognize it.

**Comment by mkurdej** [comment]
You should write `gsl::zstring<> s;`. Angle brackets are still required even in the presence of default arguments (and yes,they are allowed in `using` type aliases).

**Comment by elronayellin** [comment]
Can someone explain the rationale for the type parameter?  I see nowhere that is being used.  It is not reflected in CppCoreGuidelines.md:GSL.view

**Comment by neilmacintosh** [comment]
The type parameter allows fixed-size null-terminated strings to be specified (believe it or not, I have seen code that relies on such a concept). Given zstring is really just a convenience typedef for both people and tooling, you are unlikely to see it "used" anywhere. If people find that parameter particularly annoying, then we may well drop it in the future.
