### ISSUE TITLE
Cannot compile with Visual C++ Nov 2013 CTP

### ISSUE THREAD

**Issue by WadeAlex** [Microsoft/GSL#251]
When compiling anything (even an empty main function) with the November 2013 CTP version of Visual C++, I get the following error if I include gsl.h:

    1>------ Build started: Project: test, Configuration: Debug Win32 ------
    1>  test.cpp
    1>c:\development\sandbox\gsl\include\span.h(1034): error C2995: 'enable_if<_Test,_Ty>::type gsl::details::make_stride(const Bounds &)' : function template has already been defined
    1>          with
    1>          [
    1>              _Ty=Bounds::index_type
    1>          ]
    1>          c:\development\sandbox\gsl\include\span.h(1014) : see declaration of 'gsl::details::make_stride'
    1>c:\development\sandbox\gsl\include\string_span.h(332): fatal error C1903: unable to recover from previous error(s); stopping compilation
    1>          c:\development\sandbox\gsl\include\string_span.h(475) : see reference to class template instantiation 'gsl::basic_string_span<CharT,Extent>' being compiled

**Comment by neilmacintosh** [comment]
Hi @WadeAlex! That version of Visual C++ (the CTP) is not supported as a compilation platform. In fact, that CTP has been superseded some time ago. If you want to use the Visual C++ toolchain, then Visual C++ 2015 Update 1 is your best choice.
