### ISSUE TITLE
Support constexpr size_bytes where possible

### ISSUE THREAD

**Issue by TBBle** [Microsoft/GSL#254]
Given

``` c++
  // data is a span<bytes>, in this case statically-sized, but I expect dynamically-sized would work too
  auto known_bytes = data.first<sizeof(uint16_t) * 10>();
  auto known = gsl::as_span<uint16_t>(known_bytes);
```

What I have in `known` is a `span<uint16_t, 10>`, and hence I statically know the byte-size.

However, `static_assert(known.size_bytes() == 20, "10 uint16_ts is 20 bytes");` fails as `size_bytes` calls through to `bounds_.size()` which calls through to `BoundsRange::totalSize()` which is not `constexpr` in any of its three occurrences. I tried marking the two that aren't using `m_range` as constexpr, which worked for clang 3.7, but not MSVC 2015.

So either there's more needed to fix this, or it's an MSVC2015 constexpr limitation?

**Comment by neilmacintosh** [comment]
Thanks for the issue report @TBBle!

You'll notice that constexpr is currently disabled for MSVC 2015. So your fix may well be good (at least your clang result would suggest so), but may have to wait until we have the complete constexpr support we need in MSVC 2015 (it's on the way!).

In the meantime, if you have the time, I would love a PR with the necessary changes and test case.

**Comment by neilmacintosh** [comment]
@TBBle This issue has now been resolved for `span` (where `size_bytes()` is declared `constexpr`).
