### ISSUE TITLE
span::operator() misexpands parameter pack

### ISSUE THREAD

**Issue by TBBle** [Microsoft/GSL#255]
Looks like a minor typo:
```c++
     template <typename FirstIndex, typename... OtherIndices>
     constexpr reference operator()(FirstIndex index, OtherIndices... indices)
     {
-        index_type idx = {narrow_cast<std::ptrdiff_t>(index),
-                          narrow_cast<std::ptrdiff_t>(indices...)};
+        index_type idx = {narrow_caststd::ptrdiff_t>(index),
+                          narrow_cast<std::ptrdiff_t>(indices)...};
         return this->operator[](idx);
     }
```

Interestingly, nothing complained about this in my code, but when I replaced `narrow_cast` with `static_cast` (See my comment on #167), clang 3.7 noticed that you can't call `static_cast` that way. I suspect it would have caused more issues if I had any rank-three spans hitting this code.

> In file included from ../gsl\gsl.h:24:
> ../gsl/span.h:1489:62: error: expected ')'
>                           static_cast\<std::ptrdiff_t>(indices...)};
> ../gsl/span.h:1489:54: note: to match this '('
>                           static_cast\<std::ptrdiff_t>(indices...)};
> ../gsl/span.h:1488:26: error: initializer contains unexpanded parameter pack 'indices'
>         index_type idx = {static_cast\<std::ptrdiff_t>(index),

**Comment by neilmacintosh** [comment]
@TBBle thanks for the report! I believe this is fixed in the latest version of the source code, so I'm going to close out the issue.

**Comment by viboes** [comment]
This is not the case. See https://github.com/Microsoft/GSL/blob/master/gsl/multi_span#L1501

I added another issue https://github.com/Microsoft/GSL/issues/333.

Please be free to reopen this one and close mine as duplicated.

**Comment by viboes** [comment]
Sorry, my issue is a similar one on file multi_span :)

**Comment by neilmacintosh** [comment]
@viboes No problem. I think they are slightly different problems, this one was a genuine syntax error (as well as the misexpansion. I'll keep #333 to track resolving the issue in `multi_span`.

**Comment by TBBle** [comment]
I think #333 is the problem I meant in my original report. The syntax error (`narrow_caststd::ptrdiff_t>`) looks like a typo when I submitted the report, as it isn't there in the original side of the diff.

Apologies for not being clearer in my error description.
