### ISSUE TITLE
build error with clang 3.7 when using span.

### ISSUE THREAD

**Issue by vlj** [Microsoft/GSL#256]
When switching from clang 3.6 to clang 3.7 for our linux build a new error appeared

/home/travis/build/RPCS3/rpcs3/rpcs3/../GSL/include/span.h:1202:51: error: too few template arguments for class template 'span' std::conditional_t<Rank == 1, value_type, span<value_type, RestD...

when instancing "gsl::span<float, gsl::dynamic_range>".

Log is here : https://travis-ci.org/RPCS3/rpcs3/jobs/105912216

**Comment by KristofferHenriksson** [comment]
This is a bug in clang 3.7 with precompiled headers: https://llvm.org/bugs/show_bug.cgi?id=25271

**Comment by neilmacintosh** [comment]
Given this is a clang bug, I'm going to close this issue.
