### ISSUE TITLE
string_span<> is inconvenient

### ISSUE THREAD

**Issue by alexezh** [microsoft/GSL#257]
Having empty <> at the end of every string_span is quite inconvenient. Any chance for making string_span a final type without parameters?

**Comment by neilmacintosh** [comment]
This has been previously discussed as #93. It is still up for discussion, but does allow the definition of fixed-length `string_span` types.

**Comment by alexezh** [comment]
Which is the more common case? In my code all spans are dynamic. If this is true for majority of code, I would rather optimize syntax for it.

**Comment by JordanMaples** [comment]
Maintainer's call: Sorry for the delayed reply. gsl::string_span has been removed from the C++ Core Guidelines with isocpp/cppcoreguidelines#1680. 
>Remove string_span, recommend using `std::string_view`, `std:::span,<char>` or `gsl::span<char>` instead
