### ISSUE TITLE
Reduce minimum required version of CMake for building

### ISSUE THREAD

**Issue by JIghtuse** [Microsoft/GSL#26]
Is there any reason to require CMake 3.2.2? I tried to lower it to 3.0.0 (version I have on my machine) and gsl was built and passed all tests. It probably can be built with even older versions.

I can send a PR to lower it for 3.0.0 for now.

**Comment by tamaskenez** [comment]
I've just lowered it to 2.8.7 for my travis testing PR (see issue #27)

**Comment by neilmacintosh** [comment]
This was fixed by the travis testing commit. Thanks for the observation.
