### ISSUE TITLE
Add char16_t & char32_t support to string_span

### ISSUE THREAD

**Issue by miniak** [Microsoft/GSL#263]
```
template<std::ptrdiff_t Extent = dynamic_range>
using u16string_span = basic_string_span<char16_t, Extent>;

template<std::ptrdiff_t Extent = dynamic_range>
using cu16string_span = basic_string_span<const char16_t, Extent>;

template<std::ptrdiff_t Extent = dynamic_range>
using u32string_span = basic_string_span<char32_t, Extent>;

template<std::ptrdiff_t Extent = dynamic_range>
using cu32string_span = basic_string_span<const char32_t, Extent>;
```

**Comment by miniak** [comment]
I am working on the implementation:
https://github.com/miniak/GSL/commits/string-span

I have to implement char16_t & char32_t versions of strnlen to finish it.

**Comment by miniak** [comment]
And of course add tests :)

**Comment by neilmacintosh** [comment]
@miniak I'd certainly be interested in taking a look at a PR for this support if you have one!

**Comment by miniak** [comment]
https://github.com/Microsoft/GSL/pull/314

**Comment by neilmacintosh** [comment]
Unfortunately #314 got caught behind a merge conflict. But #543 has since been merged, which adds effectively the same functionality. So I'll close this issue out. If something is still missing, feel free to reopen or add a new issue.
