### ISSUE TITLE
size() should be size_t

### ISSUE THREAD

**Issue by alexezh** [Microsoft/GSL#264]
Having size() as a signed type makes things extremely inconvenient to use. It should be size_t to be compatible with all other .size()

**Comment by chfast** [comment]
In general I agree, but what type do you refer to?

**Comment by neilmacintosh** [comment]
@alexezh and @chfast, this was previously discussed in #171 (which reminds me to add an FAQ to this repo soon).

`ptrdiff_t` was carefully selected as the measurement type for `span` and its relatives. There are workarounds possible for interfacing with legacy types that use size_t for measurement.
