### ISSUE TITLE
gsl::as_multi_span<T>(gsl::multi_span<gsl::byte>) instantiation doesn't build with MSVC 2015

### ISSUE THREAD

**Issue by vlj** [microsoft/GSL#266]
When using gsl::as_span<T>(gsl::spangsl::byte) on non const type Visual Studio 2015 update 1 emits the following error :

2>Emu\RSX\Common\TextureUtils.cpp(286): error C2784: 'std::vector<MipmapLevelInfo,std::allocator<_Ty>> `anonymous-namespace'::copy_texture_data(gsl::span<DST_TYPE,-1,>,const SRC_TYPE *,u16,u16,u16,u8,u16,u32)': could not deduce template argument for 'gsl::span<DST_TYPE,-1,>' from 'gsl::span<U,0>'

the gsl::as_span overloads on const type does work as expected however.
It looks like the non const overloads is converting a dynamic range span to a static 0 sized range.
For some reasons  it looks like gsl::narrow_caststd::ptrdiff_t is narrowing -1 to 0 in https://github.com/Microsoft/GSL/blob/master/include/span.h#L1659

Replacing gsl::narrow_cast by static_cast (as done on the const overloads of gsl::as_span) fixes build and apparently makes span behaves as expected.

**Comment by neilmacintosh** [comment]
@vlj, could you provide a specific piece of sample code that reproduces the problem?

**Comment by JordanMaples** [comment]
Maintainer's call: Closing because multi_span is deprecated.
