### ISSUE TITLE
gsl_assert.h only defines gsl::fail_fast exception with GSL_THROW_ON_CONTRACT_VIOLATION

### ISSUE THREAD

**Issue by galik** [Microsoft/GSL#267]
Header file `gsl_assert.h` only defines `gsl::fail_fast` exception with `GSL_THROW_ON_CONTRACT_VIOLATION` defined.

This is a problem because client code needs to be able to compile different library configurations without having to add #ifdef's in its catch blocks.

The macros `Expects` and `Ensures` are defined for all three configurations (even when they do nothing) so it makes sense that `gsl::fail_fast` should be defined for all three as well.

**Comment by gdr-at-ms** [comment]
agreed

**Comment by neilmacintosh** [comment]
I'm not deeply opposed to the change, but I find the usage problem confusing. Wouldn't client code *want* to know that the catch blocks are useless in cases where the relevant symbol is not defined?

**Comment by galik** [comment]
My feeling is that if the policy were to change, a lot of code could need revising. Also you may wish to run two build configurations, one in debug where `Ensures` does something and one in release where `Ensures` does nothing. You still want your debug builds to trap `gsl::fail_fast` exceptions.

**Comment by neilmacintosh** [comment]
Sure. We do that in our codebase: we use the exceptions just to run test cases (where we want to ensure the "right" failure occurs in some circumstances), but in shipping code we fail-fast.

Still, I'd be nervous that those catch blocks are sitting around without some `#define` to make it clear they are not always applicable. They might confuse readers of the code into thinking they actually do something (when in Release mode they do not). I guess that's just me.

As I say...have no objection to defining the types regardless of preprocessor symbol, I was just curious to understand the scenario better, thanks.

**Comment by Som1Lse** [comment]
An alternative would be to `#define` macros based on whether `GSL_THROW_ON_CONTRACT_VIOLATION` is defined like:
```c++
#ifdef GSL_THROW_ON_CONTRACT_VIOLATION
    #define MY_TRY try
    #define MY_CATCH(expr,...) catch(expr) __VA_ARGS__
#else // GSL_THROW_ON_CONTRACT_VIOLATION
    #define MY_TRY
    #define MY_CATCH(expr,...)
#endif // GSL_THROW_ON_CONTRACT_VIOLATION
```

**Comment by tamaskenez** [comment]
@gailk Could you describe a use case where you would base your program's logic on whether a section of code threw gsl::fail_fast or something else?

I think things like gsl::fail_fast must be out of the scope of the program's logic. `Expects` and `Ensures` define the boundaries of the world for the program. Everything else, including gsl::fail_fast is outside of that world and must not be mentioned nor should any decision be affected by them.

**Comment by galik** [comment]
@tamaskenez I completely agree with you.

Program logic decisions should not be made by `gsl::fail_fast` catch blocks.  That is the place for logging, diagnostics and recovering as much information as possible to fix the bug.

This is why I feel that such catch blocks would be innocuous being present even in the absence of the actual exceptions.

The alternative is something like @Som1Lse mentioned - lots of `#ifdef` macros which makes the code harder to read.

Also, what are we to do when linking against some objects that are hardened and have been compiled *without*  `gsl::fail_fast` and other objects that are still regularly developed that are compiled *with*  `gsl::fail_fast`?

We can not necessarily always know whether or not a library, or object file, we link to will throw these exceptions. But we will likely *always* want to run the diagnostic catch block if they are.

**Comment by tamaskenez** [comment]
Isn't it sufficient to catch them as `std::exception`? The message contains the information about where it has been thrown.

**Comment by galik** [comment]
If you are developing with specific diagnostic code targeted for this exception you might not want to put that in a general `std::exception` block. Perhaps you want them written to a specific log file? I'm not really convinced of a down-side to having the exception always defined. Personally I like to avoid conditional compilation as much as possible so `#ifdef` or `#MACRO` catch blocks don't really appeal to me if I can avoid them.

**Comment by tamaskenez** [comment]
Okay, so this is the use case: (disclmr: I know we're bikeshedding)

    } catch(const gsl::fail_fast& e) {
        // all we know is that an assumption has not been met somewhere
        log_fail_fast_exception(e);
    } catch(const std::exception& e) {
        // all we know is that an assumption has not been met somewhere
        // and it doesn't use gsl::fail_fast
        log_unexpected_exception(e);
    } catch(...) {
        // we don't know what this is
        log_non_std_exception();
    }

I think we can agree on that we should do one of the following three options:

- we should not define gsl::fail_fast because APIs should be minimal and this is not a real use case
- we should define gsl::fail_fast because this is a real use case
- we should define gsl::fail_fast because, while this is not a real use case, there could come something later and we'll miss it

(I don't like the #ifdef solutions either)
