### ISSUE TITLE
array_view use case

### ISSUE THREAD

**Issue by gnzlbg** [Microsoft/GSL#269]
I have a 1d array in memory and I would like to view it as a "rectangle/cube" of Rank R (R=1,2,3,...). 

I would like to iterate over a sub-tile of this rectangle. This sub-tile can either be spanned by two coordinates of rank R and a stride of rank R, or from the first element of the sub-tile, the sub-tile lengths (of rank R), and a stride of rank R. 

In some cases I know all of the sub-tile lengths and strides at compile-time and would like to use these as template parameters. In some cases I only know some of them and would like to specify these at compile time (e.g. as template parameters), but some I only know at run-time (and would like to specify them using something like Eigen3's `dynamic` trick.

I am trying to figure out if I can do all of these with `array_view` but it seems that the library and the paper have gone a bit out of sync (array view is now called span?). Is it possible to do all this with array view, and if so, are there anywhere examples of how to do it?

**Comment by neilmacintosh** [comment]
@gnzlbg it sounds as though what you are looking for is the `multi_span` type in the library. If you look at the test suite for that type, it may provide examples that serve as a useful starting point.

**Comment by gnzlbg** [comment]
Thanks @neilmacintosh ! I'll check that out!

I ended up implementing a `tensor_index` generator in range-v3 and just using that as view in case you are interested: https://github.com/ericniebler/range-v3/issues/281
