### ISSUE TITLE
add travis testing

### ISSUE THREAD

**Issue by tamaskenez** [Microsoft/GSL#27]
I added travis testing for gcc5 and clang36 on [my fork](https://github.com/tamaskenez/GSL)
I'm ready to send in a PR if I got approval for this issue.
Let me know I need to add more compilers and which ones.

**Comment by gdr-at-ms** [comment]
That is useful; thanks.  Please do let us know of any issue you find.

**Comment by tamaskenez** [comment]
Well, I thought I would send a PR with the travis.yml which I already have.
