### ISSUE TITLE
No method for creating a subspan until a given index

### ISSUE THREAD

**Issue by hsivonen** [Microsoft/GSL#270]
The `subspan()` method of `span` takes a start index and a length. This may be convenient sometimes, but it's annoying when the subspan you want isn't characterized by length but by start (inclusive) and end (exclusive) indices.

With the current `subspan()` method, you end up writing code of like [`.subspan(start_index, end_index - start_index)`](https://github.com/hsivonen/recode-cpp/blob/3b0a568e595c9f9da76c9a7a99c23e907bac6dd7/recode_cpp.cpp#L111), which is a bit sad.

I suggest adding another method `subspan_until()` that takes the start index and the first index not to be included, so that one could write `.subspan_until(start_index, end_index)` to get a subspan from and including `start_index` up to but not including `end_index`.

**Comment by neilmacintosh** [comment]
Thanks for the issue @hsivonen!

The design approach for `span` is to provide a minimal, useful set of member functions on the type that support desired operations. Unless we provide a very large number of member functions, there will be some scenarios that require slightly more steps to achieve than others. Your inclusive+exclusive indices scenario is one such example.

For the moment - in the absence of compelling data that we are missing a very common scenario - we've chosen to keep the simple version `subspan()` (which conceptually matches the `substr()` function of `std::basic_string`). Of course, this decision can always be revisited in the future.

**Comment by hsivonen** [comment]
:-(

FWIW, regarding common scenarios, what I suggested as `subspan_until()` is an idiom important enough that Rust has a part of the _language_ for its slices (the Rust equivalent of a `span`).

In
````rust
let subslice = &slice[n..m];
````
`n` is the first index included in the subslice and `m` is the first index not included.

**Comment by neilmacintosh** [comment]
@hsivonen there's nothing stopping you from having a free function with this behavior. In fact, I can imagine people will have plenty of favorite ways of slicing and dicing `span` that they will want to wrap up as convenience functions.

For the moment, the `subspan()` interface is simple and consistent with the `substr()` of `std::basic_string`.

If we see some data about usage of particular functions for creating subspans that suggest they are popular "in the wild" in C++ (arguments from other languages are less compelling), then we can revisit the decision to add them to the GSL.
