### ISSUE TITLE
span<char> incompatible with std::regex?

### ISSUE THREAD

**Issue by nholthaus** [Microsoft/GSL#271]
The following code fails to compile on msvc2013, but seems like it should be supported.

    #include <regex>
    #include "gsl.h"

    using namespace std;
    using namespace gsl;

    int main(int argc, const char **argv) 
    {
	    char lat[8] = { '0', '1', '9', '0', '0', '0', '0', 'E' };
	    span<char> s = lat;
	    std::match_results<span<char>::iterator> match;
	    std::regex_match(s.begin(), s.end(), match, std::regex(".*"));
    }

With the errors 

> error C2512: 'gsl::contiguous_span_iterator<gsl::span<const char,-1,>>' : no appropriate default constructor available
> c:\program files (x86)\microsoft visual studio 12.0\vc\include\regex(1081) : while compiling class template member function 'std::match_results<gsl::contiguous_span_iterator<gsl::span<const char,-1,>>,std::allocator<std::sub_match<_BidIt>>>::match_results(void)'
>  with
> [
>    _BidIt=gsl::contiguous_span_iterator<gsl::span<const char,-1,>>
> ]
> c:\users\documents\visual studio 2013\projects\main.cpp(12) : see reference to function template instantiation 'std::match_results<gsl::contiguous_span_iterator<gsl::span<const char,-1,>>,std::allocator<std::sub_match<_BidIt>>>::match_results(void)' being compiled
> with
> [
>   _BidIt=gsl::contiguous_span_iterator<gsl::span<const char,-1,>>
> ]
> c:\users\documents\visual studio 2013\projects\main.cpp(12) : see reference to class template instantiation 'std::match_results<gsl::contiguous_span_iterator<gsl::span<const char,-1,>>,std::allocator<std::sub_match<_BidIt>>>' being compiled
> with
> [
>   _BidIt=gsl::contiguous_span_iterator<gsl::span<const char,-1,>>
> ]

**Comment by galik** [comment]
I assume you mean `std::regex_match(s.begin(), s.end(), match, std::regex(".*"));`?

This also fails on `GCC 5.3.2 Linux`.

From what I can gather this appears to fail on `GCC` because `std::pair` in `GCCs` implementation of `std::match_results` requires default constructed arguments and `contiguous_span_iterator` has no default constructor.

This fails:

```cpp
std::pair<span<char>::iterator, span<char>::iterator> pp;
```
<pre>
/usr/include/c++/5.3.1/bits/stl_pair.h:109:25: error: no matching function for call to 'gsl::contiguous_span_iterator<gsl::span<char, -1l> >::contiguous_span_iterator()'
       : first(), second() { }
                         ^
</pre>

**Comment by neilmacintosh** [comment]
I'm in the process of changing much of `span`'s implementation, including the iterators, so this should be resolved shortly.

**Comment by brucebob** [comment]
Will that fix #252 ?

**Comment by neilmacintosh** [comment]
@brucebob Yes.

**Comment by alfred-bratterud** [comment]
Any news / status on this? Would make gsl::span even more useful for us at IncludeOS.

**Comment by neilmacintosh** [comment]
@nholthaus Thanks for reporting this issue! @nholthaus, @brucebob and @alfred-bratterud, I've added some very basic tests (with PR #321) to ensure that the sample code provided in this issue works. If you still encounter problems using `span` in conjunction with `std::regex`, feel free to offer a PR or open a new issue.
