### ISSUE TITLE
span<T> can be constructed from an rvalue const array

### ISSUE THREAD

**Issue by bogiord** [Microsoft/GSL#272]
The following code compiles with no diagnostics on MSVC 14 (`/W4`), Clang 3.7.0 and GCC 5.2.0 (`-Wall -Wextra -std=c++1z -pedantic`):

```
#include "gsl.h"

int main()
{
   using arr = const int[];
   gsl::span<const int> s = arr{1, 2, 3};
   (void)s;
}
```

The same thing happens for xvalue const arrays (for example, returned from `std::move`).

Adding a deleted rvalue reference overload for this case would ideally fix the problem:

```
    // prevent constructing from temporary array
    template <typename T, size_t N>
    constexpr span(T (&&arr)[N]) = delete;
```

Unfortunately, this only works properly in Clang.

MSVC treats all array rvalues as lvalues; this has been [reported on Connect](https://connect.microsoft.com/VisualStudio/feedback/details/1747933/compilation-error-with-array-rvalues).

GCC treats some const array prvalues as lvalues, so the fix doesn't apply to all cases. I [reported the bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70167).

I still think the fix is worth applying, and hopefully the compiler issues will get solved as well at some stage.

For Clang and GCC, the fix also has the nice side effect of providing a better error message when trying to construct a `span` from a non-const array rvalue.

**Comment by neilmacintosh** [comment]
@bogiord thanks for the report. As part of standardization for `span` it was accepted that having constructors on `span` that can take rvalue references to the various supported container types was a useful feature and warranted inclusion in the type. As a result, the scenario you identify is now officially supported.
