### ISSUE TITLE
Namespace of string_span comparison operators

### ISSUE THREAD

**Issue by gix** [Microsoft/GSL#274]
Is there any reason why the string_span comparison operators are in the global namespace instead of the `gsl` namespace? Currently `string_span.h` must be included first or otherwise the operators might not be found which is kind of annoying.

Example:

    #include <utility>
    #include <string_span.h>

    void f()
    {
        gsl::cstring_span<> l, r;
        std::equal_to<gsl::cstring_span<>>()(l, r);
    }

results in:

    VS2015:
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xstddef(226): error C2678: binary '==': no operator found which takes a left-hand operand of type 'const gsl::basic_string_span<const char,-1>' (or there is no acceptable conversion)

    Clang 3.8:
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xstddef:226:17: error: invalid operands to binary expression ('const gsl::basic_string_span<const char, -1>' and 'const gsl::basic_string_span<const char, -1>')

**Comment by calumr** [comment]
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c5-place-helper-functions-in-the-same-namespace-as-the-class-they-support

**Comment by neilmacintosh** [comment]
@gix it was a genuine mistake on the part of the implementers. As @calumr observes, the operators should be inside the `gsl` namespace together with the types they support. This has been fixed by #309.
