### ISSUE TITLE
Compiler warning if gsl.h is included after windows.h

### ISSUE THREAD

**Issue by dripfeed** [Microsoft/GSL#275]
1. Use Visual Studio 2015.
2. Create new Win32 Console app.
3. Target platform is auto-set to 8.1 (but it doesn't matter if I use v140 or v120).

In **stdafx.h**

### Good
```
#pragma once
#include "GSL-master/include/gsl.h"
#include <windows.h>
```

### Bad
```
#pragma once
#include <windows.h>
#include "GSL-master/include/gsl.h"
```

d:\tmp\gsl-test-1\gsl-test-1\gsl-master\include\span.h(90): warning C4003: not enough actual parameters for macro 'max'

**Comment by neilmacintosh** [comment]
This is not a deficiency in the GSL headers, rather this is a known issue with using `windows.h` from C++. Please refer to #253 for some possible solutions to the problem.

**Comment by dripfeed** [comment]
Wow. In all my years of win32 dev I've never encountered that. Thanks Neil.

**Comment by grahamreeds** [comment]
Really? How long have you been programming Win32 for?

It was a daily occurrence back in the Visual Studio 6 days...

GR

**Comment by dripfeed** [comment]
LOL - I've been on win32 since 1995. I guess I never used min or max very much.
