### ISSUE TITLE
cond unconstrained in Expects(cond) when contracts are unenforced

### ISSUE THREAD

**Issue by scurest** [Microsoft/GSL#278]
This is a very minor enhancement idea.

If `GSL_UNENFORCED_ON_CONTRACT_VIOLATION` is defined, then `Expects(cond)` expands to nothing. This means there's no constraint on `cond`; it doesn't even have to be a legal expression.

It might be better if `Expects(cond)` expanded to

```
static_assert(::std::is_convertible<decltype((cond)), bool>::value,
              "in Expects(cond), cond must be convertible to bool");
```

or something.

(Similarly for `Ensures`, of course.)

**Comment by CaseyCarter** [comment]
I believe this issue was fixed by 16a6a41690325433976d843e13ec676d6f9ab091, which always requires the conditions passed to `Expects` and `Ensures` to be contextually convertible to bool.
