### ISSUE TITLE
Docs do not explain how to use the library

### ISSUE THREAD

**Issue by daixtrose** [Microsoft/GSL#28]
AFAICS the docs are not completely self-contained. At least I was not able to find out within 30 minutes how and when to use the library. I looked at https://github.com/isocpp/CppCoreGuidelines and still did not catch the idea. Are there any short examples?  

I grabbed some ideas from the unit tests, especially `as_array_view`, but reading all unit tests to know about features like `Expect` may be error prone because someone probably confuses test features with GSL features.

Any docs available beyond https://github.com/isocpp/CppCoreGuidelines/blob/master/docs/Lifetimes%20I%20and%20II%20-%20v0.9.1.pdf ?

Another example: What is the semantics of `maybe_null_dbg`? Cannot grab it from this test:
```c++
    TEST(TestMaybeNull1)
    {
        int n = 5;
        maybe_null_dbg<int *> opt_n(&n);
        int result = 0;
        bool threw = false;

        CHECK_THROW(result = *opt_n, fail_fast);
    }
```

**Comment by daixtrose** [comment]
Ok, I missed THAT one:
https://github.com/isocpp/CppCoreGuidelines/blob/master/talks/Sutter%20-%20CppCon%202015%20day%202%20plenary%20.pdf

**Comment by neilmacintosh** [comment]
Yes, the documentation is still a work-in-progress (like the library itself) but the best resources to start with can be found at https://github.com/isocpp/CppCoreGuidelines.
