### ISSUE TITLE
using finally without assigning to variable will not work as intended

### ISSUE THREAD

**Issue by juandent** [Microsoft/GSL#284]
Hi,

If you use finally like so:

void usingFinally() {
     finally(&w);   // where w is a function
     // ... (the final_act object is already gone from here)

   /// ....
}

will construct final_act object but will immediately destroy it (will not wait until end of scope).

This FORCES the assignment to a variable like so:

void usingFinally() {
     auto x = finally(&w);   // where w is a function
     // ...

   /// ....
}

Kind of ugly and need a name for the variable that does not conflict with existing...

Is there a way around this?

Juan

**Comment by capsocrates** [comment]
An ugly way around it that I have considered is a macro that assigns the
result of finally to a uniquely named variable.

#define SCOPE_GUARD(f) auto x = finally(f);

I don't know what kind of macro magic you might use to make 'x' always a
unique name.

**Comment by chfast** [comment]
You can use `__LINE__`, eg. `scope_guard_ ## __LINE__`.

**Comment by chfast** [comment]
The C++17 will have `[[nodiscard]]` attribute. The warning will be raised if an result of an function is imminently discarded by a caller.

Clang and GCC support some version of the attribute already. MSVC has `_Check_return_` annotation.

**Comment by neilmacintosh** [comment]
Thanks for the suggestion @chfast. However, in terms of a solution, I'd prefer to use the C++17 attribute once it becomes available.
