### ISSUE TITLE
Would it be useful to introduce a type to zero-initialize native types?

### ISSUE THREAD

**Issue by janwilmans** [Microsoft/GSL#290]
class Bar
    {
        gsl::zero<int> m_count;
        gsl::zero<Foo> m_foo;
    };

Just a through to avoid uninitialized values, however, maybe it no longer needed because there is also member initializing:

    class Bar
    {
        int m_count = 0;
        Foo m_foo = 0;
    };

which is more explicit (so arguably better).

**Comment by chfast** [comment]
Not worth it. You can have `int m_count = {}`.

**Comment by neilmacintosh** [comment]
thanks for the suggestion @janwilmans, but in this case I would say no. The property of zero-initialization is not something I think would be helpful to have encoded in the type for the lifetime of a variable.
