### ISSUE TITLE
span.h(96): warning C4003: not enough actual parameters for macro 'max'

### ISSUE THREAD

**Issue by LeftBased** [Microsoft/GSL#291]
Get that warning from span.h that came from GSL.

**Comment by emlai** [comment]
Seems like a duplicate of #253.

The solution is to simply `#define NOMINMAX` before including `windows.h` in your project.

**Comment by neilmacintosh** [comment]
Hi @LeftBased, @emlai  is correct. This is not an issue with the GSL but with Microsoft's use of a macro to define `max`. The referenced issues should give you a method to resolve the problem.

**Comment by alexey-malov** [comment]
Pull request #512 fixes this issue by replacing
```c++
static const SizeType max_value = std::numeric_limits<SizeType>::max();
```
with
```c++
static const SizeType max_value = (std::numeric_limits<SizeType>::max)();
```

**Comment by neilmacintosh** [comment]
We've covered this issue before and our position is that this is a problem for the relevant header files that define `max` as a macro, rather than this library.
