### ISSUE TITLE
An implicit conversion from span<T> to span<const T> would be helpful.

### ISSUE THREAD

**Issue by KevinDHall** [Microsoft/GSL#292]
There are times where you have a span<T>, but the function you want to pass the span to won't modify the contents of the span -- in other words it should take a span<const T>.  However, there is no conversion from span<T> to span<const T> (that I can find anyway).  It would make code using spans cleaner if there was an implicit conversion to span<const T> (or span<T>::const_span using the typedefs available in span<T>).

Are there any good reasons for not having such a conversion?

**Comment by neilmacintosh** [comment]
Hi @KevinDHall, there is already a `span<T>` to `span <U>` conversion constructor in the library. It should be used by the compiler implicitly if needed.

You can see a test case that exercises this conversion constructor here: https://github.com/Microsoft/GSL/blob/master/tests/span_tests.cpp#L653

**Comment by KevinDHall** [comment]
Oh, I didn't notice that.  Thanks!
