### ISSUE TITLE
vkCreateShaderModule returns a render pass?

### ISSUE THREAD

**Issue by NicolBolas** [Microsoft/GSL#294]
In Chapter 8.1, in the description of `vkCreateShaderModule`, we get this line:

> `pShaderModule` points to a `VkShaderModule` handle in which the resulting **render pass object** is returned.

Emphasis added. I'm fairly sure you meant "shader module object". A simple copy&paste bug.

**Comment by NicolBolas** [comment]
Oops, wrong repo. Sorry.

**Comment by grahamreeds** [comment]
A simple copy&paste bug indeed!
