### ISSUE TITLE
Strictness of check for iterators referring to same underlying data

### ISSUE THREAD

**Issue by davidhunter22** [Microsoft/GSL#296]
I feel that the check for iterators  pointing into the same instance of a span is too strict. I am using VS 2015. If I write

```
span<int> x = //   something
span<int> y = x;

x.begin( ) == y.begin( )
```

Unlike doing the equivalent above with a std::vector I  would expect this to work. At present I get an Expects failure that the two iterators are to different span instances. I think the check for if this is valid should be whether the two span instances are pointing to the same underlying data.

**Comment by neilmacintosh** [comment]
@davidhunter22 I'm not sure that it would be desirable to promote the idea of mixing and matching iterators from different sources. Can you give an example of how this would be useful?

**Comment by davidhunter22** [comment]
My comment was about mixing and matching iterators from the same source. I would agree that doing so for iterators from different sources would be a bad idea. For instance if you create two spans from exactly the same instance vector<int> I think it would be reasonable to compare the begin( ) iterators of these two spans.

At present the code has a check
        Expects(m_validator == rhs.m_validator);
where m_validator is a pointer to the span instance. I think this check is too strict. I think it would be better to compare that both spans data pointers and sizes are the same. It the data pointers and sizes are the same both spans are "views" onto exactly the same underlying data. In that case I think it is reasonable to allow the iterator comparison.

**Comment by davidhunter22** [comment]
Just to add my understanding is that passing around spans by value is encouraged. This leads to copies of spans with exactly the same underlying data being common.

**Comment by neilmacintosh** [comment]
@davidhunter22, you are correct, passing `span` by-value is definitely encouraged. I understand you want to mix and match iterators from two different `span`s that share the same source (by which I assume you mean the underlying pointer stored by each `span` is the same). However, I would still like to get a clear case for where this would be useful (as opposed to just comparing the values of `.data()` on each `span` to establish that they point to the same underlying sequence).

**Comment by davidhunter22** [comment]
I my case I ran into the assert when porting an existing library to use span. I had a class that was returning a "const std::vector<int>&" to some data the class contained, I had changed this to return a span<int> by value. The old code actually got the vector reference twice and ended up comparing iterators from both references  which may not be ideal but worked. After switching to spans this of course gave me two span instances and the iterator comparisons went bang. This was initially a bit of a surprise to me.

My view is that a span instance should behave as closely as possible as if it was the underlying data, in my case a vector<int>. In other words you should not be able tell tell the difference between two span instances created from the same underlying data.

Yes I could compare the .data() pointers, although I would add in .size() a well but IMHO that is what span equality should be doing anyway. The fact that "view" is often used in the name for classes like these I think implies that. Comparing a "view" to me means are they "viewing" the same thing not whether I have to view instances.

**Comment by viboes** [comment]
@neilmacintosh What is wrong for iterator to store the data() and the index? It seems to me that this is the less confusing behavior.

**Comment by neilmacintosh** [comment]
@viboes @davidhunter22 the sources of the iterators in this case are the spans. The spans are different, therefore the iterators don't want to be compared. This is perfectly reasonable behavior. While there may be a small number of cases where such a comparison may accidentally work, that doesn't make the comparison valid. Sometimes undefined behavior can appear to work too ;-)
