### ISSUE TITLE
Differentiating exception type for Expects and Ensures for option [GSL_THROW_ON_CONTRACT_VIOLATION] 

### ISSUE THREAD

**Issue by vjacquet** [Microsoft/GSL#298]
Both Expects and Ensures throws runtime_error based exception. Shouldn't Expects throw logic_error based exception, defined by the standard to report violations of logical preconditions or class invariants?

**Comment by neilmacintosh** [comment]
Thanks for the feedback @vjacquet! I agree, it should. Feel free to offer a PR that makes this fix.
