### ISSUE TITLE
not_null& operator=(const T& t) does not have strong exception safety

### ISSUE THREAD

**Issue by vjacquet** [Microsoft/GSL#299]
Checking that the pointer is not null is done after assigning it. If Expects is configured to throw, then not_null would end up holding an null pointer.
BTW, shouldn't not_null throw domain_error or invalid_argument instead of using Expects? If Expects is configured to do nothing, the invariant would not hold.

**Comment by neilmacintosh** [comment]
This is not an exception-safety issue, as assigning a null to a not_null object is not a valid operation. If a null is assigned to it, this violates the preconditions (as expressed by the Expects) for that operator. At that point a program has encountered undefined behavior. And the point of undefined behavior is that you can no longer rely on things to be sane (such as a not_null being not null). 

This is the reason the answer to your second question is also "no". Expects is there to help you catch places where your program would encounter undefined behavior. The safest mode to use GSL is to have Expects() configured to terminate. This will stop a user's program immediately in the case of undefined behavior. If the user configures GSL to use exceptions, then as soon as Expects throws, they should understand that invariants in their program can no longer be relied upon. If the user configures it to do nothing, then the user has accepted that if their code leads to undefined behavior, they will likely get odd and unpleasant behavior.

**Comment by vjacquet** [comment]
Then I guess I did not understand how not_null should work. I expected it to always guarantee that it will not contain null, the same way the vector's "at" method throws out_of_range.

**Comment by neilmacintosh** [comment]
Yes, vector's at() method is an example of a type implementing an error handling strategy. not_null has "contracts" (preconditions, postconditions and invariants). The Expects()/Ensures() statements are a mechanism to help you avoid execution continuing when those contracts are violated.

**Comment by vjacquet** [comment]
Then what is the benefit of using a contract for not_null instead of an error handling strategy? 
Why introducing an undefined behavior when we should rely on not_null's invariant?

By design, not_null checks against null on conversion or assignment of a pointer but copy construction or assignment comes at no cost. So, whenever you have to pass a pointer as a not_null, you are encouraged to get it as a not_null. 
In my day job, I work mostly in c# where the code is bloated with guarding againts null. This is what I find really interesting with not_null: the more you use it, the more efficient it gets because you can remove all those checks.

**Comment by vjacquet** [comment]
Finally, I can understand why some might perfer to rely solely on the contracts and not on error handling strategies.
But, I though that throwing was an acceptable strategy for the contracts. Undefined behavior is only one of them. If I choose exception or termination, isn't the behavior perfectly defined? Therefore shouldn't offer strong exception safety whenever we can, for those who choose to to define GSL_THROW_ON_CONTRACT_VIOLATION?
