### ISSUE TITLE
string_span and map

### ISSUE THREAD

**Issue by davidhunter22** [Microsoft/GSL#305]
Should it be possible to use a string_span as a key to a map. So should the following work

`std::map<gsl::cstring_span<>,int> foo = { { "foo", 0 }, { "bar", 1 } };`

Using Visual Studio 2015 Update 3 I get

1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(239): error C2678: binary '<': no operator found which takes a left-hand operand of type 'const gsl::basic_string_span<const char,-1>' (or there is no acceptable conversion)
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(436): note: could be 'bool std::operator <(const std::error_condition &,const std::error_condition &) noexcept'
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(427): note: or       'bool std::operator <(const std::error_code &,const std::error_code &) noexcept'
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(239): note: while trying to match the argument list '(const gsl::basic_string_span<const char,-1>, const gsl::basic_string_span<const char,-1>)'
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(238): note: while compiling class template member function 'bool std::less<_Kty>::operator ()(const _Ty &,const _Ty &) const'
+ more template spew

In general I would have thought that string_spans should be orderable.

**Comment by davidhunter22** [comment]
After a bit more investigation I was wondering why the operator< functions defined in string_span.h were not being used in the map as they work for stand alone instances of gsl::cstring_span. I noticed that they were not defined inside the gsl namespace but in the global namespace so I tried moving them inside the gsl namespace and the map example above then compiled fine. I am no expert in the deep mysteries of things like argument dependent lookup but I suspect it's something to do with that. My guess is the VC compiler is not conformant. 

Anyway I did notice that your test cases don't have any tests where you use string_spans in various STL container types. I may be able to put a few tests together if you want, let me know.

**Comment by neilmacintosh** [comment]
Hi @davidhunter22, thanks for raising the issue! I believe that `string_span` should be safe for use within a `std::map`. Previously the operators for `string_span` were mistakenly declared in the global namespace. This has recently been corrected, so it should resolve the problem you're seeing. I'd welcome a PR that added some tests for `string_span`, and indeed `span` being used in STL containers (where it is sensible to do so).

**Comment by neilmacintosh** [comment]
@davidhunter22 I confirmed that this issue no longer seems to repro since we corrected the declaration of the operators for `string_span` to ensure they are in the `gsl` namespace. I added a basic test based on your code in PR #318 to confirm things work now...feel free to offer a PR to add more.
