### ISSUE TITLE
Constructing a span using gsl::as_span() from std::vector first element's address and too big len doesn't fail

### ISSUE THREAD

**Issue by pmalek** [Microsoft/GSL#306]
I have been experimenting with `gsl::span` class and I have produced the following code snippet:

```cpp
#include <iostream>
#include "span.h"

template <typename T, typename S = typename gsl::span<T, 0>::size_type, S size>
void display(gsl::span<T, size> data)
{
  if(data.empty()) return;

  std::cout << data[0];
  for(int i = 1; i < data.size(); ++i) std::cout << ' ' << data[i];
  std::cout << '\n';
}

int main()
{
  std::vector<int> v{ 1, 2, 3, 4, 5 };
  auto s = gsl::as_span(v.data(), 100);
  display(s);
}
```

which
* compiles, (gcc 5.3.1)
* runs
* doesn't crush nor seg faults!

As far as I can see it triggers the following function's call:

```cpp
template <typename T>
constexpr auto as_span(T* arr, std::ptrdiff_t len) ->
    typename details::SpanArrayTraits<T, dynamic_range>::type
{
    return {reinterpret_cast<std::remove_all_extents_t<T>*>(arr), len};
}
```

Is that the desired behavior? Have bounds checking been removed from here (not put here) on purpose?

**Comment by ilpropheta** [comment]
You should call:

`auto s = gsl::as_span(v);`

Instead, by calling:

auto s = gsl::as_span(v.data(), 100);

you are basically saying: "here is the pointer, here is the size". 
gsl::span does not do black magic under the hood, so in this case it can only check that you are not going over 100 elements. What happens if you build a span with an invalid {ptr, size} correspondence is undefined.

**Comment by neilmacintosh** [comment]
Hello @pmalek, thanks for opening the issue! @ilpropheta is essentially correct. Passing a pointer plus size to a `span` constructor is using a "trust me" method. It is one of the least-preferred methods of constructing a `span`, as the constructor must simply trust you are getting those arguments correct. If you have something like a `std::vector`, then you should simply pass it as the single argument to `span`'s constructor.

So for your code snippet, we anticipate that eventually, tools would warn you that:

a. you are calling the "unsafe" constructor for span unnecessarily. You can just use the "from-container" constructor instead.
b. you cannot guarantee the 100 elements you are promising, so you are violating `span`'s requirements.

**Comment by pmalek** [comment]
Thanks guys for clarifying this up for me :)

**Comment by DaveTallman** [comment]
What happened to as_span for simple containers like vectors? The samples above will no longer compile (after replacing "span.h" with "span").

I see an as_multi_span, but that doesn't seem to do the same thing. Do you really want to break published interfaces for a header library like this?

**Comment by rianquinn** [comment]
@DaveTallman please see the following: https://github.com/Microsoft/GSL/issues/380.
