### ISSUE TITLE
static casting uint64 to uint32 gets a warning.

### ISSUE THREAD

**Issue by TheWisp** [Microsoft/GSL#307]
Seems it wants to dynamic cast between integral types.
warning C26491: Don't use static_cast downcasts. Use dynamic_cast instead.

**Comment by neilmacintosh** [comment]
Is this a bug report against CppCoreCheck when run over the GSL source code?

If so, then Microsoft Connect or writing to the "cppcorecheck" email address @microsoft.com is the best way to report these bugs. Thanks!
