### ISSUE TITLE
Misplaced #pragma warning(pop) in span.h

### ISSUE THREAD

**Issue by LMLB** [Microsoft/GSL#308]
If `GSL_THROW_ON_CONTRACT_VIOLATION` is not defined then the `#pragma warning(pop)` is skipped (it looks like it was accidentally put inside the wrong `#ifdef _MSC_VER` block), causing most of the CppCoreCheck warnings to stay disabled.

**Comment by neilmacintosh** [comment]
Nice catch @LMLB, I believe you're right. This should be fixed by #310.
