### ISSUE TITLE
noexcept in span causing error in gcc 5.4.0

### ISSUE THREAD

**Issue by ZorZor** [Microsoft/GSL#323]
Simple test program 

```
#include "gsl"
#include <iostream>

void test(gsl::not_null<int*> value)
{
   *value = 10;
}

int main()
{
   int* value = new int();
   *value = 0;

   test(value);

   std::cout << "Value is " << *value << " \n";
   delete value;
}
```

Error:
In file included from gsl:25:0,
                 from test.cpp:1:
span: In constructor 'constexpr gsl::details::span_iterator<Span, IsConst>::span_iterator()':
span:182:63: error: expected '{' before 'noexcept'
         constexpr span_iterator() : span_iterator(nullptr, 0) noexcept {}

Putting the noexcept before the : does correct the issue.

`constexpr span_iterator() noexcept : span_iterator(nullptr, 0) {}`

**Comment by nickenchev** [comment]
Having the same problem here when compiling with Clang 3.8.1.
