### ISSUE TITLE
span.data(index)

### ISSUE THREAD

**Issue by rianquinn** [Microsoft/GSL#327]
When writing a custom malloc in C++, you need to be able to index into a memory pool. With the Core Guidelines, you should not be doing pointer arithmetic, so the best way I have found to do this is to:

```
auto sub = pool_span.subspan(index, 1);
return sub.data();
```

This works great, but I think the syntax could be simplified in the GSL by simply providing an index to the data function. This could be done with a default argument, or a second data(index) function so that the syntax was more like:

```
return pool_span.data(index);
```

Under the hood, it could just:

```
T* data(int index)
{
    return subspan(index, 1).data()
}
```

Just my 2 cents

**Comment by rianquinn** [comment]
Likewise (and probably more importantly), there doesn't seem to be a way to do a reverse lookup. Once again, if span is meant to replace pointer arithmetic, there should be a way to perform a reverse lookup. 

Example:
```
uint8_t pool_owner[N] = {}        // Just stores memory, is never actually used
gsl::span<uint8_t> pool(pool_owner, N);   

auto subspan = pool.subspan(10, 5);
auto subspan_ptr  = subspan.data();

// Question: What is the index of subspan / subspan_ptr in pool?
// Answer: 10.... I only know that because that's how I created the subspan. 
// What if I need to get this number at runtime?

// Proposed Additional APIs
auto index_of_span = pool.index_of(subspan);           // 10
auto index_of_span_ptr = pool.index_of(subspan_ptr);   // 10
```

These additional APIs would provide a means to perform this pointer arithmetic safely, and would extend to any T*.

**Comment by neilmacintosh** [comment]
@rianquinn thanks for the issue, it's an interesting use case to bring up! 

I think for the first case, you are fine to simply take the address of the element at the specified index. No need to use a `subspan` at all. So to return the pointer of interest, you would simply do:
````
// presumably here you check that i is in-range,
// and if not you extend the pool, or throw the appropriate exception
return &pool_span[i];
````
This conforms to the guidelines as you are not performing any pointer arithmetic (you are only taking the address of a single element) - and pointers are fine to be used to refer to single elements.

Regarding the second comment: I would think that the `index_of` you propose could be written as a free function, using the existing iterators and `std::find_if`. In general, helper functions like this should at least start life as free functions, unless we see good reason for them to become members.

However, I would suggest a different name like `index_of_ptr`. The comparison operations on `span` are value-based, and I think most users would then expect `index_of` to also be value-based.

**Comment by rianquinn** [comment]
&pool_span[i] works great. 

As for `std::find_if`, I don't think that is going to work. The callback is doing comparisons on the elements in the `span`... not on the pointers themselves (correct me if I am wrong). Given a ptr, I am interested in knowing what is the index that pointer came from in the `span`, the elements in the `span` I never really look at. 

With respect to our use case (writing a hypervisor in c++11/14), malloc can return a position in a memory pool safely using `span`, but free gives back a ptr, and I need to locate the index in the pool given that ptr. I agree that `index_of_ptr` is better for the ptr use case, not sure it describes the subspan use case: `index_of_ptr(subspan)` which is really just calling `index_of_ptr(subspan.data())`.

**Comment by rianquinn** [comment]
To illustrate, this is the code I am currently using as a small patch to `span`

```
constexpr index_type index_of_ptr(pointer ptr) const
{
    Expects(ptr >= data() && ptr < data() + size());
    return ptr - data();
}

constexpr index_type index_of_ptr(const span<ElementType, Extent> &other) const
{
    return index_of_ptr(other.data());
}
```

And this is the basic test:

```
int a[5] = {1, 2, 3, 4, 5};
gsl::span<int> as(a, 5);

std::cout << as.index_of_ptr(as.subspan(0, 1)) << std::endl;
std::cout << as.index_of_ptr(as.subspan(1, 1)) << std::endl;
std::cout << as.index_of_ptr(as.subspan(2, 1)) << std::endl;
std::cout << as.index_of_ptr(as.subspan(3, 1)) << std::endl;
std::cout << as.index_of_ptr(as.subspan(4, 1)) << std::endl;
```

Output is:
```
0
1
2
3
4
```

**Comment by neilmacintosh** [comment]
@rianquinn  whether that implementation is a member or a free function, it is doing pointer arithmetic, so would require a suppression to still be compliant with the Core Guidelines.

But I'm not sure why it would need to be a member, given it only uses the public interface of `span` and reverse-lookup of index from pointer, in particular, is not something I see being a heavy use pattern.

For your case, it sounds like you just need `index_from_ptr` and `index_to_ptr` (or something similar) as free functions, and you're good to go. 

When I mentioned using find_if, I was imagining you would just take the address of the element and compare, something like so (warning: uncompiled/tested code for illustrative purposes only):
````
template <class Span>
typename Span::index_type index_of_ptr(typename Span::pointer ptr, Span span)
{
    auto result = find_if(span.begin(), span.end(), [](const auto& el){ return &el == ptr; });
    return result == span.end() ? -1 : result - span.begin();
}
````
This is a little in the spirit of the Ranges library, where you can transform views. However, I'm going to take a guess that this won't perform as well as the pointer arithmetic version you had.

My suggestion would be to write the free functions and accept that you'll need to carefully check the pointer arithmetic and then bless it with a suppression.

**Comment by rianquinn** [comment]
Huh.... learned something new here. Didn't know you could get the reference of a reference like that, but yeah, I would imagine that would work. It would be linear time vs. mine is O(1). Right now I have it as a patch to the GSL in our tree as I have a couple (clang-tidy gets mad about some GSL code outside of the Core Guideline tests so I added a suppression, and I added an "ignore" to the final_act incase you want to prevent it from executing)

That being said, not sure I understand the argument that this function is not complaint with the Core Guidelines [if included in the GSL code itself]. Based on the GSL code, `span` does a lot of something[], which is pointer arithmetic. My understanding is the `span` is doing the pointer arithmetic for you in a well tested, safe manner... so you don't have to. 

But yeah, I would agree if nobody else sees interest in API it should not be added.

**Comment by neilmacintosh** [comment]
@rianquinn thanks for the valuable discussion! I'll close this issue for now.
