### ISSUE TITLE
Move headers to include/Guide directory to avoid colisions

### ISSUE THREAD

**Issue by viboes** [Microsoft/GSL#33]
It is usual to have the specific files of a library in a specific directory. I will suggest you to move them to include/Guide if this is the name of the library.

**Comment by neilmacintosh** [comment]
@viboes I haven't had a lot of feedback that this is a major issue. Perhaps this is a more an issue for an "install" step to take care of? If I hear differently in the future I'm happy to have the issue reopened.

**Comment by viboes** [comment]
The first feedback I have is there there is not feedback :(
This is not an install issue, as the user needs to be able to identify which header to use without confusion. If all the libraries are done like this one, we will have a lot of clashes.

**Comment by grahamreeds** [comment]
I tend to put all my third party libraries in a separate folder than my own
source. So I have ext/boost, ext/gsl, etc.

GR
