### ISSUE TITLE
strnlen not defined in Cygwin. 

### ISSUE THREAD

**Issue by rianquinn** [Microsoft/GSL#331]
If you try to use the GSL in cygwin, you get:

"error: 'strnlen' was not declared in this scope". 

Looking this up, it appears that strnlen is _not_ a standard function. If this is true, we should either remove it, or provide our own implementation. Note that the link below is for MinGW but I am seeing this with GCC 5.4 in cygwin as well. 

http://stackoverflow.com/questions/35197129/mingw-g-strnlen-was-not-declared-in-this-scope

**Comment by neilmacintosh** [comment]
@rianquinn this is a duplicate of #315, so I'll close it in favor of that issue.
