### ISSUE TITLE
`make install` command not installing all headers

### ISSUE THREAD

**Issue by vdods** [Microsoft/GSL#332]
Not all headers were being installed via the `make install` command run using the Makefile(s) that cmake produced.  This is because an explicit (and obviously outdated) list of the GSL header files was being used in cmake's `install` command in the root CMakeLists.txt.

I have a branch with a fix on my local cloned repo, but I'm unable to push it to origin to make a pull request.

**Comment by neilmacintosh** [comment]
Thanks @vdods. this should be fixed by #341.
