### ISSUE TITLE
function declared to have a not_null argument

### ISSUE THREAD

**Issue by bobofet2** [Microsoft/GSL#336]
From the Core Guidelines
Clarity. A function with a not_null<T> parameter makes it clear that the caller of the function is responsible for any nullptr checks that may be necessary. 

Does this mean that the result of a code analysis where is this rule is violated should indicate a problem. I created a very simple app where I don't get a warning:

// interface
bool RunService( not_null<Service*> s )
{...
}

int main()
{
   Service *sp = nullptr;
   RunService( sp );

Sorry but I can't specify the RunService as having a not_null parameter (new to github) perhaps attaching the file would be better
[gsl-3.1.cpp.txt](https://github.com/Microsoft/GSL/files/429040/gsl-3.1.cpp.txt)

**Comment by neilmacintosh** [comment]
@bobofet2 If you were running an analysis tool that enforces that guideline, then the answer is "yes". Note that (depending on how you have set your GSL build to enforce contracts) you should also see a runtime failure for your test case, generated by the GSL implementation.

However, I am assuming you are specifically asking about the Microsoft code analysis tool "CppCoreCheck" that we have started making available for use with Visual Studio? In that case, this is a rule we do not support enforcing yet. CppCoreCheck is still in its infancy and currently only supports enforcing a small subset of the Core Guidelines. But we are working to add enforcement of more rules. :-)

As an aside, this is not really the right place to ask questions about specific tools, as it's the repository for the Microsoft implementation of the Guideline Support Library. Future questions on tooling would be better directed to the Microsoft Connect site, or directly to the team developing CppCoreCheck via the cppcorecheck@microsoft.com email address.
