### ISSUE TITLE
Typo in GitHub repository description

### ISSUE THREAD

**Issue by slokhorst** [Microsoft/GSL#337]
You use "Guideline Support Library" everywhere, but the description of this GitHub repository is "Guideline**S** Support Library".

**Comment by galik** [comment]
I think the singular is the more proper (and it scans better/easier).

**Comment by neilmacintosh** [comment]
I'm happy with either, so let's leave it as-is.

**Comment by slokhorst** [comment]
Then what about 2d4b552c82a5d4dab19590f086c892f91adf7b03 ?

**Comment by neilmacintosh** [comment]
That was about making the existing scheme consistent, it was a PR with minor changes, so it was accepted.

**Comment by slokhorst** [comment]
Okay.. I would also call updating the description a minor change, so you are consistent everywhere. But it's up to you.
