### ISSUE TITLE
Define constexpr as /*constexpr*/ where applicable

### ISSUE THREAD

**Issue by martinmoene** [Microsoft/GSL#340]
Files gsl, gsl_byte, gsl_util, multi_span, span and string_span contain
```
#define constexpr /* nothing */
```
I'd argue it's more useful to have
```
#define constexpr /*constexpr*/
```
might one want to look at preprocessed code.

Idem for `noexcept`.

**Comment by neilmacintosh** [comment]
@martinmoene 
a perfectly reasonable suggestion! Would you like to provide a PR with the change?

**Comment by martinmoene** [comment]
Created PR #342.
