### ISSUE TITLE
Invalid use  of `typename Container::pointer` and `cont.data()` in span

### ISSUE THREAD

**Issue by viboes** [microsoft/GSL#343]
In https://github.com/Microsoft/GSL/blob/master/gsl/span#L417

```
    // NB: the SFINAE here uses .data() as a incomplete/imperfect proxy for the requirement
    // on Container to be a contiguous sequence container.
    template <class Container,
              class = std::enable_if_t<
                  !details::is_span<Container>::value && !details::is_std_array<Container>::value &&
                  std::is_convertible<typename Container::pointer, pointer>::value &&
                  std::is_convertible<typename Container::pointer,
                                      decltype(std::declval<Container>().data())>::value>>
    constexpr span(Container& cont) : span(cont.data(), cont.size())
    {
}
```

I understand that this is know to be imperfect as for the comment.
The use of `typename Container::pointer` and `cont.data()` are not correct. 

Wondering if instead of using `typename Container::pointer` we shouldn't use `typename Container::value_type*` and instead of `cont.data()` we shouldn't use `&*cont.begin()`?

Alternatively the requirements of the `Container` parameter could be redefined.

**Comment by viboes** [comment]
Instead of `Container::value_type*` it would even be better to use the `std::iterator_traits<Container::iterator>::reference` as this is part of the continuous sequence containers requirements, and remove the reference and the pointer.

**Comment by MikeGitb** [comment]
Isn't the bigger problem that std::is_convertible returns true if the second argument is a pointer to a base class of the type the first argument points to? 

So given a 

    struct Foo{ int i;}; 
    struct Bar : Foo {int z;};

It would be possible to create a `gsl::span<Foo>` from a `std::vector<Bar>` no?

I'm not too proficient in extremley generic programming, but I'd expect something involving `std::is_same` and `std::decay`

**Comment by viboes** [comment]
@MikeGitb Right, the assignment shouldn't cast pointers. The `value_type` should be the same.

**Comment by viboes** [comment]
See also span<T> constructors allow unsafe conversions #313

**Comment by MikeGitb** [comment]
@viboes: Ah, sorry, I overlooked/forgot about that one.

**Comment by neilmacintosh** [comment]
#313 has now been addressed. But I think @viboes makes an excellent point about having a better way to identify the desired type of container (a contiguous one) and its value type. I'll take a look at this (unless someone else would like to volunteer), but I'm not sure that all our compilers will like the proposed solution.

**Comment by JordanMaples** [comment]
Maintainers' call: This has since been addressed, sorry for the delay in reponding.
