### ISSUE TITLE
Getting GSL.Concept into the GSL (concretely)

### ISSUE THREAD

**Issue by cjdb** [Microsoft/GSL#346]
Is there any active development on faking concepts in the GSL? I started toying around with getting the Ranges TS concepts to "work" in C++14 without gcc's Concepts TS implementation turned on today.

As I only started development a few hours ago, it's highly experimental, incomplete, and largely untested. I'd like to know what needs to be done for it to be accepted into the GSL?

**Comment by MikeGitb** [comment]
I haven't had a detailed look at it, but why don't you just use the concepts from Eric Niebler's ranges-v3 library(https://github.com/ericniebler/range-v3)?

**Comment by neilmacintosh** [comment]
@cjdb in answer to your original question: no.
@cjdb @MikeGitb Personally, I think the best way to get concepts for now is to wait for the feature to arrive in the language. I don't think it would be particularly useful for the Microsoft implementation of the GSL to become a vehicle for a not-in-the-language, not-fully-working, implementation of concepts. Though referring to the concepts listed under GSL.Concept in comments seems pretty safe to me. 

If people want to use concepts now (and I am one of them), I believe a better approach is to ask your compiler vendor to implement the TS as gcc has done, and use that. That way the actual feature under discussion by the committee gets more "test-driving" and feedback that drives it forward.

**Comment by MikeGitb** [comment]
@neilmacintosh: I completely agree. 

in case this was not clear, the 
> why don't you just use the concepts from Eric Niebler's ranges-v3 library

was addressed at cjdb not at you (as in the maintainer). Let me also say that I very much appreciate the small size of the gsl (in particular without multi_span, which I haven't used so far), Faked concepts sound like they would be a pretty heavy weight addition (I might be mistaken of course).

**Comment by MikeGitb** [comment]
Ok, actually I don't agree completely ;):

> If people want to use concepts **now** (and I am one of them), I believe a better approach is to ask your compiler vendor to implement the TS 

Maybe you know something I don't (actually I'm sure of it) but I'm not too optimistic about concepts support in VS and clang in the near future. And even once the newest versions do, it might take quite some time until we can use them in our projects (in an embedded project I'm still stuck with gcc 4.9).

So for using them NOW, a library might be the better solution. Still, I agree that the gsl is not the place for it.

**Comment by neilmacintosh** [comment]
Thanks for clarifying @MikeGitb! I did slightly misunderstand your original remark, apologies ;-)

Looks like we agree though...this implementation of the GSL doesn't need to offer a concept-like library for now.
