### ISSUE TITLE
Adding a span::data() access function

### ISSUE THREAD

**Issue by viboes** [Microsoft/GSL#347]
I would like to use span to transport a pointer and a length, but at some point in time I need to access the pointer (byte) and the length in bytes to interface with legacy system. 

Is there a way I'm missing to get the pointer to the data?
If not what about adding a function to get it?

**Comment by neilmacintosh** [comment]
@viboes I think you are looking for the `.data()` member function that already exists.

**Comment by viboes** [comment]
Sorry I missed it.
