### ISSUE TITLE
gal::byte operator| is not defined correctly.

### ISSUE THREAD

**Issue by daphnediane** [Microsoft/GSL#350]
operator| is defined as addition(+) instead of bitwise or(|).

See line 78 of gsl/gsl_byte
```
constexpr byte operator|(byte l, byte r) noexcept
{
    return byte(static_cast<unsigned char>(l) + static_cast<unsigned char>(r));
}
```

**Comment by neilmacintosh** [comment]
hahahaha! @daphnediane, nice catch! Those two characters are side-by-side on my keyboard layout. It appears I am clumsy. Feel free to offer a PR if you'd like the "glory" of the fix....otherwise I'll get to it soon.

**Comment by daphnediane** [comment]
Dvorak user here so next to each other on my keyboard as well. Don't really care about glory and would have to double check before with my work before signing the CLA if I want to submit a PR. I don't expect a problem, especially for a one character change but it would take a few days to get permission given the holiday.

**Comment by neilmacintosh** [comment]
@daphnediane hahahaha, so rare to meet another Dvorak user! Ok, then, I'll pop the fix in myself. Thanks for catching this!
