### ISSUE TITLE
Usage documentation for GSL

### ISSUE THREAD

**Issue by nholthaus** [microsoft/GSL#354]
In trying to consume the GSL library in some production code (maybe not really recommended yet?), and I've found that its a lot more difficult than expected due to the lack of documentation.

I think for the most part the intent of classes like `span` and `byte` and things are obvious to those of us interested in `gsl`. The actual implementation and usage in real code is another story though. The C++ Core Guidelines don't provide a succinct summary of the classes that they recommend. For example `span` has 88 mentions, most of which are in "enforcement" blocks, prior to ever defining what a `span` is. Or more importantly, what it is not. `byte` isn't mentioned at all, and I had to read through the issue list pretty closely here to realize there is no practical way to initialize it after beating my head on that problem for a while.

Most of the information on gsl classes _can_ be found, but it's spread across numerous draft papers, and revisions (or proposed or planned revisions) are not transparent to people outside of the c++ working groups.

I think either the Core Guidelines need a preface for new/proposed classes and their usage, or the gsl implementation library does. Maybe a mix of both. It would be especially helpful if it came with known issues or limitations. Even if the gsl is not supposed to be 'production ready' right now, it would be helpful in terms of evaluation and contribution. The answer to #348 may also bring some clarity to this.

**Comment by rianquinn** [comment]
+1

Any reason why doxygen comments are not provided with example usage?

**Comment by neilmacintosh** [comment]
@nholthaus You are not the first person to want more information on usage. As you observe, there are papers for C++ standardization, but they cater to a very specific audience and offer a precise definition of the types...which is very different from "so how should I use this in my day-to-day work?".

I will try to add some basic usage sketches to the CppCoreGuidelines repository in the next month or so. That should provide a nice starting point to grow from.

So I'll leave this issue open until I go do that. ;-)

@rianquinn Doxygen comments are really cumbersome and I find they make reading/maintaining the code painful. I think a more helpful route is to provide an introductory section in the guidelines that describes how we expect these types to be used in code - at least for the most common cases (and certainly the ones that are enforced by the Bounds profile).

**Comment by KindDragon** [comment]
I thinks just copy and update some slides from https://github.com/isocpp/CppCoreGuidelines/blob/master/talks/MacIntosh%20-%20A%20Few%20Good%20Types.pdf to README.md

**Comment by viboes** [comment]
This link should help also

http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#S-gsl

**Comment by Predelnik** [comment]
Can't see much info about multi_span in these links, was it previously part of array_view?

**Comment by pratikpc** [comment]
http://codexpert.ro/blog/2016/03/07/guidelines-support-library-review-spant/
This is for span
http://codexpert.ro/blog/2016/03/21/guidelines-support-library-review-string_span/
This is for string_span

I found some over here. It has some code so it might be helpful to beginners like me.

That said, something is better than nothing.
(Apologies, I am a bit new to the world of GitHub)

**Comment by tjysdsg** [comment]
Can there at least be some references for people not willing to read through the source code?

**Comment by hsutter** [comment]
Maintainers' call: Sorry for the lag in replying. We have since made a number of updates to the README that cover more of the use cases as requested above. If there are specific things you'd like us to cover that we missed, please open a new issue to request. Thanks!
