### ISSUE TITLE
gsl::at in const member functions

### ISSUE THREAD

**Issue by rianquinn** [Microsoft/GSL#357]
The following does not compile because gsl::at does not seem to have a const overload:

```
uintptr_t size(uintptr_t addr) const noexcept
{
    return gsl::at(m_allocated, addr);
}
```

In this example, `m_allocated` is a `std::array< uintptr_t >`. I get this really long winded (and totally useless) error which basically amounts to having to remove `const` from the function. If I do that, it compiles fine. I am using GCC 5.x. 

I tried adding my own, but the constexpr / template insanity 😄 has me a bit confused on how to do it properly.

**Comment by neilmacintosh** [comment]
Do you mean it didn't accept a `const`-qualified argument? If so: yes, it probably should be able to accept `const`-qualified arguments, I agree. Would you like to provide a PR that fixes it?

**Comment by rianquinn** [comment]
Meaning the following compiles fine:
```
uintptr_t size(uintptr_t addr) noexcept
{
    return gsl::at(m_allocated, addr);
}
```

And this does not:
```
uintptr_t size(uintptr_t addr) const noexcept
{
    return gsl::at(m_allocated, addr);
}
```

The only difference is I removed `const` from the member function definition. In this case, m_allocated is not a const member, but I am not modifying it so the function should be able to be labeled const. 

I would provide a PR but I am at a loss as to how to fix this in the code as I gave it a quick try with no success. m_allocated is a std::array, and GCC is actually using the Cont::XXX gsl::at implementation and not the std::array one, and with the extensive use of templates and constexpr I really have no idea where to start. 

Any ideas? If I can figure this out I'll be happy to submit a PR but I think I'll need help getting started 😄

**Comment by rianquinn** [comment]
@neilmacintosh I have working code for this, but I have to extend it to all of the at functions which I will do once I get a chance. My current plans for unit testing the needed changes here is to add a class to the unit tests and access at from const member functions to ensure it compiles and runs properly

**Comment by neilmacintosh** [comment]
@rianquinn ok...sounds good to me.
