### ISSUE TITLE
Don't use std::equal for comparison gsl::span of `char*`/`unsigned char*`

### ISSUE THREAD

**Issue by KindDragon** [Microsoft/GSL#359]
std::equal can use memcmp for comparing `char*`/`unsigned char*`, but this optimization doesn't work for gsl::span

**Comment by gdr-at-ms** [comment]
Hmm, is that be a compiler implementation deficiency?

**Comment by KindDragon** [comment]
I think not. Because MSVC STL use special overload for `inline bool _Equal(const char *_First1, const char *_Last1, const char *_First2)`, but with `gsl::span` it get type `gsl::details::span_iterator<...>` instead.

`std::_Equal<gsl::details::span_iterator<gsl::span<unsigned char const ,-1>,0>,gsl::details::span_iterator<gsl::span<unsigned char const ,-1>,0> >(gsl::details::span_iterator<gsl::span<unsigned char const ,-1>,0> _First1, gsl::details::span_iterator<gsl::span<unsigned char const ,-1>,0> _Last1, gsl::details::span_iterator<gsl::span<unsigned char const ,-1>,0> _First2) Line 2736	C++`

**Comment by gdr-at-ms** [comment]
That is my point, exactly. It isn't an issue with `gsl::span`. This affects any code you would write that has properties similar to `gsl::span`.

**Comment by neilmacintosh** [comment]
@KindDragon I agree with @gdr-at-ms here. Compilers and library vendors are free to recognize and optimize `span` (or not). Whether they do or not is not really our primary concern here, though obviously we would like to see it happen. We focus on correctly implementing the behavior we want for the type.

**Comment by KindDragon** [comment]
Ok, but `gsl` as a third-party library will never have optimizations in STL.
