### ISSUE TITLE
Use an homogeneous naming convention

### ISSUE THREAD

**Issue by viboes** [Microsoft/GSL#36]
It is a good practice to use an homogeneous naming convention. We find classes in lower_case and Lower_case as array_view and Final_act.

**Comment by trebconnell** [comment]
I am working on this

**Comment by neilmacintosh** [comment]
I would suggest the right thing to do is raise an issue over on the Cpp Core Guidelines, where the name Final_act is specified. If it's accepted over there...then the GSL would change to follow.
