### ISSUE TITLE
Feature: Construct span, string_span from iterator range pair (first, last)

### ISSUE THREAD

**Issue by v1bri** [microsoft/GSL#361]
The span classes don't quite integrate with STL without a range constructor from a pair of iterators. I'm trying to do something like the following...

```
auto pos = std::search(span.cbegin(), span.cend(), delim.cbegin(), delim.cend());
gsl::cstring_span<> sub(span.cbegin(), pos);
```

I see that the span classes offer constructors for first and last pointers, but it doesn't seem like iterators automatically convert to pointers. The `subspan()` method also falls short here.

**Comment by ladnir** [comment]
Here is a possible implementation that I applied to my local code base.
```
	template<typename Iter>
	using IsRandomAccessIterator =
		std::is_base_of<
			std::random_access_iterator_tag,
			typename std::iterator_traits<typename Iter>::iterator_category>;

	template<typename Iter>
	constexpr span(typename std::enable_if<IsRandomAccessIterator<Iter>::value,Iter>::type firstElem, Iter lastElem)
        : storage_(firstElem == lastElem ? nullptr: &*firstElem, std::distance(firstElem, lastElem))
    {
    }

```

**Comment by ladnir** [comment]
Here is my implementation of this feature, worked on VS and g++
```
	template<typename Iter>
	using IsRandomAccessIterator =
		std::is_base_of<
			std::random_access_iterator_tag,
			typename std::iterator_traits<Iter>::iterator_category>;

	template<typename Iter>
	constexpr span(typename std::enable_if<IsRandomAccessIterator<Iter>::value,Iter>::type firstElem, Iter lastElem)
        : storage_(firstElem == lastElem ? nullptr: &*firstElem, std::distance(firstElem, lastElem))
    {
    }
```

**Comment by maikel** [comment]
I do not think, that `RandomAccessIterator` as a condition is enough. You somehow has to check if the iterators span a contiguous memory range. Since the current STL lacks the notion of a   ContiguousIterator I think the constructor overload with pointers should be enough.

One should not confuse `span` with some wrapper around any RandomAccess Range.

**Comment by ladnir** [comment]
True, just thought I would share for those who want it.

**Comment by JordanMaples** [comment]
Maintainers' call: Sorry for the delay. Now that span has been standardized, the only delta between gsl::span and std::span is the bounds checking. We are following the standard interface exactly.
