### ISSUE TITLE
Open the Cmake file to be able to compile with the compiler version the user wants

### ISSUE THREAD

**Issue by viboes** [Microsoft/GSL#362]
The CMAKE file lets think that we can compile with C++11, but GSL is a C++14 library.

```
    include(CheckCXXCompilerFlag)
    CHECK_CXX_COMPILER_FLAG("-std=c++14" COMPILER_SUPPORTS_CXX14)
    CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
    if(COMPILER_SUPPORTS_CXX14)
    	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -Wall -Wno-missing-braces")
    elseif(COMPILER_SUPPORTS_CXX11)
    	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -Wno-missing-braces")
    else()
      message(STATUS "The compiler ${CMAKE_CXX_COMPILER} has no C++11 support. Please use a different C++ compiler.")
endif()
```

In addition the CMake file forces the C++ version depending on the compiler ability.
I don't know how to force the compilation with c++1z or even C++11, other than hacking the CMake file.
Any help here will be welcome. 

I believe that it is up to the user to choose with which compiler and with which version the GSL library must be compiled.

BTW, I've started porting GSL to [viboes/GSL C++11](https://github.com/viboes/GSL) and [viboes/GSL C++98](https://github.com/viboes/GSL/tree/cxx98). Any comment on this fork much appreciated.

**Comment by neilmacintosh** [comment]
Hi @viboes, well it is not a completely C++14 or even C++11 library, as it manages to compile with MSVC 2013 today ;-)

I found the CMake file had to force the `-std=c++14` flag for one of the versions of GCC/Clang I was testing against or I saw warnings/errors. I can't remember what they were anymore I'm afraid.

I agree: the user should be able to choose their compiler, flags and version when using GSL. And they can! The CMake scripts are simply a convenient "out-of-the-box" starting place that works with some major compilers. It is important to note that those scripts only build the *test suite* - not the library itself. As it is all contained within headers (and mainly as templates), the library is - by definition - compiled by the user using the compiler and flags they already have set up for the project they are using GSL in.

So the CMake file is fine as-is...it is just there for building and executing tests in a reliable way and it makes some pretty minimal decisions about how to do that.

I understand the thinking behind your forks, and I have sympathy for the idea. I would point out that @martinmoene already has an implementation of the GSL that targets earlier versions of the language that might be worth a look. However, with things like `byte` you are going to face challenges.

We aim for something like C++11 as a minimum with the GSL. C++11 adds so many significant facilities that improve the language (of course, C++14 does as well). We want to encourage people to be as close as possible to the C++ of today. This reflects the aims of the Core Guidelines.

As we make new compiler releases and I can drop support for older ones, this version of the GSL will continue to move forward and require more C++14 and C++17 (and C++20 and so on....) features.

**Comment by viboes** [comment]
I understand that you want to support only the latest versions with the higher C++ version.
When I want to check if the test pass with c++1z I need to change the CMakeLists.txt file manually and this is unfortunate.

If anyone knows how to change the CMakeLists.txt so that the user can set the compiler flags, please replay to this issue (https://github.com/viboes/GSL/issues/2) in my repository.
