### ISSUE TITLE
Getting pointer to char from `span<byte>`

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/GSL#367]
I wonder if there should be an extra member function for `span<byte>` that returns a char pointer to the first element.

Most of the time, when I use that particular specialization, it is because I want to send or receive data from somewhere (disk, network, serial etc.) and most of the time this is done via an API that expects a pointer to char and a length. There are 4 member functions that will give me the length, but in order to get the char pointer I still have to use an ugly cast.

**Comment by gdr-at-ms** [comment]
The ugly cast to `char*` is necessary because it is an artefact of the APIs you're using.  Yes, there are tons of them. The object representation uses `unsigned char` as character type -- and soon `std::byte`. You want to push the ugliness back to where it originates.

**Comment by MikeGitb** [comment]
@gdr-at-ms: So instead of having the ugliness at one point you prefer it to be spread throughout the codebase?

I'm well aware of where the source of this problem lies, but the fact of the matter is that we have to deal with those APIs on a regular basis and imho that won't change in the near future. Making span difficult to interface with those APIs will not speed up the modernization of the api's but rather slow down the adoption rate of span.

Btw.: If you can convince the teams responsible for the Windows and Linux APIs to adopt gsl::byte within the near future (or even provide a c++ interface), I'd be very grateful.

**Comment by gdr-at-ms** [comment]
It all depends on where that point is.  I don't believe it belongs to the GSL.  

We do want to promote an unambiguous interpretation of `char*` or `const char*`.

**Comment by neilmacintosh** [comment]
@MikeGitb I don't want to add this method to `span<byte>` for the same reasons as @gdr-at-ms. This would defeat the point of the design of `std::byte` - to disambiguate characters from numbers from bytes (raw storage).

I don't think you have to spread ugliness throughout the codebase. You can always write a free function wrapper that will give you a converted pointer from `span::data()`, if that's a regular need in a particular codebase. Indeed, given such a pointer is no longer bounds-checked, such a wrapper would be a useful way to identify points of risk.

Legacy APIs like those of Windows and Linux are unlikely to adopt `std::byte` as they are C APIs, not C++. As they are also ABIs, there is very little chance you will seem them "modernize" very fast (if at all).

Luckily, `std::byte` can be readily converted to and from other representations like `char`. Plus, you can safely cast between `byte*` and `char*` when those pointers are being used to view object storage, as both are allowed to alias that storage.

It would not be an unreasonable project to write some simple C++ wrappers that made those sorts of conversions transparent for C++ users of a particular API.

**Comment by MikeGitb** [comment]
Well, I don't quite see why `span::cptr()`/`span::ucptr()` is so much worse than `span::data()` (I'm not suggesting some implicit conversion after all) and it would have the advantage to 
a) be less typing and (imho) easier to read than `data()`+ free function, 
b) to have a more limited scope than a free function that can convert any `byte*` to `char*` and hence
c) to give people an additional incentive to use `gsl::span` instead of raw arrays - or worse - raw pointer representing an array.

But If you two think it shouldn't be in the `gsl::span`, then that is fine with me too.
