### ISSUE TITLE
Don't use extensions if the library should follow the C++14 Core Guidelines

### ISSUE THREAD

**Issue by viboes** [Microsoft/GSL#37]
I believed that this GSL library should use only standers ISO C++ following the C++ Core Guidelines.

I see things like

```c++
#ifdef _MSC_VER
        __assume(ptr_ != nullptr);
#endif
```

Couldn't this be replaced by something else?

**Comment by gdr-at-ms** [comment]
The support library can use constructs that the Core Guidelines suggest to avoid (of course, we want to minimize those) -- that is why it is a support library in the paradigm of "subset of superset".  See Bjarne's keynote.

**Comment by viboes** [comment]
fais ce que je dis, pas ce que je fais ;-)

**Comment by gdr-at-ms** [comment]
@viboes  See rationale here (in addition to watching Bjarne's keynote): http://www.stroustrup.com/SELLrationale.pdf
