### ISSUE TITLE
as_bytes from a single pod object

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/GSL#371]
I hope I haven't overlooked it, but there seems to be no easy way to view a single pod variable as a sequence of bytes. Use case would e.g. be to write a header data structure and the actual payload of a network package into a tx buffer.
- Would you accept an overload of `as_bytes` and `as_writeable_bytes`, that accepts a single pod as a parameter?
- If so, should `as_bytes` accept a temporary?

**Comment by neilmacintosh** [comment]
@MikeGitb this was actually in the original design (you should be able to see it in array_view if you go way back in the history). I agree with the use case, which was why we originally incorporated it.

The design back then was that you should be able to construct a `span` from a single element fairly easily. So calling `as_bytes` or `as_writable_bytes` was automatically then available, which seems the easier/more consistent route.

It should probably accept a temporary for consistency. In saying that, I haven't given much time to thinking through what all the call-resolution conflict possibilities might be though (with or without the temporary option to be honest).

I asked for opinions on re-introducing it at the Oulu WG21 meeting and people were generally favorable. So if you are interested in trying a PR, please feel free.
