### ISSUE TITLE
Header "gsl/byte" should disable warning C26493

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/GSL#372]
The current implementation of `gsl::byte` related operators make heavy use of c-style (function-style) casts from `unsigned char` to `gsl::byte`. This triggers warning C26493 in the CppCoreChecker downloaded via Nuget. 
Imho, either those casts should be replaced by static casts, or the the warning should be turned of in the header. I'd somewhat favor the latter option, as I assume that the function style casts (`return byte(...);`) are meant as surrogates for the almost identical brace initialization syntax (`return byte{...};`) that will come with c++17.

**Comment by KrisTC** [comment]
Have they updated the version used in the nuget package yet? 
Last time I looked it was an old version that didn't compile with MSVC 2013. Headers had .h extensions etc. 
There wasn't any traceability back to the git revisions either. I thought they would update the nuget packages before cppcon.

**Comment by MikeGitb** [comment]
I don't think they did, but I was referring to the corechecker package not the gsl (although there seems to be a dependency so that the nuget gsl is automatically installed alongside).

The version provided by vcpkg (https://github.com/Microsoft/vcpkg) is up to date though.

**Comment by gdr-at-ms** [comment]
@MikeGitb I agree that locally turning off the warning in the header is a better workaround.

We have to remember that the GSL, by its very nature of having to hide constructs banned or discouraged by the Core Guidelines, sometimes has to do things that the consuming code isn't allowed to do.  That is why it is the *support* library :-)

**Comment by MikeGitb** [comment]
> We have to remember that the GSL, by its very nature of having to hide constructs banned or discouraged by the Core Guidelines, sometimes has to do things that the consuming code isn't allowed to do. That is why it is the support library :-) 

That was also my first thought, but on the other side - as far as this particular warning is concerned - I don't think there is any case where the gsl actually has to use function-style casts. Maybe this is also true for other warnings - any thoughts on this?

**Comment by MikeGitb** [comment]
Come to think of it @neilmacintosh: 

The c++corechecker currently warns about this:

    int i = 5;
    auto v = std::vector<Foo>(i);

with the warning

> warning C26493: Don't use C-style casts that would perform a static_cast downcast, const_cast, or reinterpret_cast. (type.4: http://go.microsoft.com/fwlink/p/?LinkID=620420)

This is technically correct, but imho a too strict interpretation of [C++ Core Guidelines' Type.4 rule](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Pro-type-cstylecast). Maybe function style casts that result in an **explicit constructor** being called should be allowed, as they display the intent of calling a parametrized constructor more clearly than a `static_cast`? Although, maybe that should be discussed in the CppCoreGuidelines repo.

For the fun of it I replaced the function style with static cast like this:
    
    auto v = static_cast<std::vector<Foo>>(i);

And got the same warning. Is this a bug?

**Comment by rianquinn** [comment]
@MikeGitb that looks like a bug to me but you might be able to use the new syntax:

```
int i = 5;
auto v = std::vector<Foo>{i};
```

**Comment by MikeGitb** [comment]
@rianquinn & @neilmacintosh : My mistake. The type of `i` should be `size_t` of course and then the core checker doesn't complain anymore (regardless of which version I use). One should trust the tools

**Comment by neilmacintosh** [comment]
@MikeGitb agreed that we should suppress the warnings or change the code (something I meant to do at some point). Apologies for the annoyance. I'm surprised I didn't see the warnings...I thought I had turned up warning volume in compilation of our test suite. I'll use this issue to go back and double-check on that.

Regarding the checker issue you encountered (not really GSL, strictly speaking, but while we're here...). There are a bunch of known issues we have around the cast detection, which we are working through currently. The next release should give more accurate and useful warnings for cases like your example.

**Comment by MikeGitb** [comment]
As there might come some compatibility changes to gsl_byte anyway, my PR takes the easy way for now and just disables the warning. 

What is your preferred feedback channel for cppcorecheck in case I should encounter any real issues in the future?

**Comment by neilmacintosh** [comment]
Thanks @MikeGitb, I appreciate the "short-term fix" PR and it's been accepted.

For feedback around CppCoreCheck, you can always mail cppcorecheck@microsoft.com...that gets to us most directly, or you can raise an issue at http://connect.microsoft.com/VisualStudio.
