### ISSUE TITLE
Should gsl::span constructor check for size overflow?

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/GSL#375]
As shown in issue #322, when I want to construct a span from a container, I have to ensure that the size doesn't exceed `std::numeric_limits<std::ptrdiff_t>::max()`. On 64bit systems this isn't a practical issue and - assuming that the maximum size of any continuous container is `std::numeric_limits<std::size_t>::max() / sizeof(T)` - there are also relatively few instances on other systems where this might be a problem.

Still, I wonder if the constructor should check for such an overflow (taking from @ewil's example):

     Expects(cont.size() <= static_cast<size_t>(std::numeric_limits<index_type>::max()))

**Comment by rianquinn** [comment]
I want to say this was the exact same issue that I had.

**Comment by neilmacintosh** [comment]
@MikeGitb The answer is "yes" ;-)

**Comment by neilmacintosh** [comment]
PR #382 has addressed this problem for construction from containers. Thanks for raising the issue @MikeGitb  and @rianquinn.
