### ISSUE TITLE
I did not find gsl::as_span.

### ISSUE THREAD

**Issue by efinegold** [Microsoft/GSL#380]
I did not find funtion gsl::as_span. ( ...but I am s new user). Did you remove this function from the library?

**Comment by neilmacintosh** [comment]
Hi @efinegold! The function still exists for `multi_span`, but as it is not part of the interface of `span` that is currently proposed for standardization, I left it out of `span`. In theory, there should be enough constructors to achieve what `as_span()` used to do.

**Comment by MikeGitb** [comment]
> In theory, there should be enough constructors to achieve what as_span() used to do. 

Well, the main advantage of `as_span()` would be the automatic type deduction, but with c++17 that might no longer be an issue (haven't yet looked up the type deduction rules for templated constructors of templated classes).

**Comment by rianquinn** [comment]
I think that applies to a lot of things in the GSL, `gsl::finally` being a great example of that.

**Comment by neilmacintosh** [comment]
@MikeGitb, @rianquinn you are both correct on both counts. If there are painful spots, then I think it's best to wait for the template constructor type deduction changes in C++17 which should resolve most (all?) of them.

With that said, I could imagine adding `as_span()` back into a separate header (maybe `gsl_util`) to help people without C++17 support, or who face a persistent problem now and don't want to wait.

**Comment by efinegold** [comment]
Thanks. Yes. It worked in some cases:

void reportInt(gsl::span<int> data)
{
	for (auto const item : data) std::cout << item << ' ';
	std::cout << std::endl;
}

int main()
{
int arr[] = { 100, 200, 300, 400, 500 };

**Comment by MikeGitb** [comment]
@neilmacintosh: Well, it would certainly be handy to have them but imho nothing critical.

**Comment by neilmacintosh** [comment]
Ok. Then I'll close this out for now. Feel free to reopen or open a new issue if someone hits something that is particularly annoying.

**Comment by efinegold** [comment]
Sounds good. Thanks.
Ed.
