### ISSUE TITLE
Provide contract violation response control as suggested in proposal N4415

### ISSUE THREAD

**Issue by martinmoene** [microsoft/GSL#383]
[N4415](http://wg21.link/n4415), Simple Contracts for C++, section 1.5 Control of Contract Assertions suggests:

> First, there ought to be an ability to turn on and off contract checking, or just to enable partial contract checking (e.g. only pre-conditions, or only post-conditions).

I've implemented it in _gsl lite_, see [Contract violation response macros](https://github.com/martinmoene/gsl-lite#contract-violation-response-macros).

**Comment by hsutter** [comment]
Maintainers' call: Thanks for the suggestion. However, C++20 decided not to add contracts yet, so we want to align with the direction for standardization but can't follow a specific existing proposal yet. However, we are actively interested in this area and several of us are now actively looking at contracts design points to propose for standardization consideration and hope to update Expects and Ensures in the general direction of where C++ standard contracts seems to be going.
