### ISSUE TITLE
Intel compiler compilation error

### ISSUE THREAD

**Issue by steinret** [Microsoft/GSL#385]
I tried using gsl with Intel compiler 16 under SUSE Linux Enterprise Server 11 SP4 and got a

    icpc ../main.cpp -o test -std=c++14
    In file included from ../gsl/multi_span(23),
                 from ../gsl/gsl(24),
                 from ../main.cpp(1):
    ../gsl/gsl_byte(78): error #3377: constexpr function return is non-constant
        return l = byte(static_cast<unsigned char>(l) | static_cast<unsigned char>(r));

   (multiple times)

    icpc --version
    icpc (ICC) 16.0.3 20160415
    Copyright (C) 1985-2016 Intel Corporation.  All rights reserved.

    cat ../main.cpp
    #include "gsl/gsl"
    int main(int argc, char* argv[]) {
    }

**Comment by gdr-at-ms** [comment]
Sounds like the version of Intel compiler implements only the C++11 version of `constexpr`?

**Comment by neilmacintosh** [comment]
@steinret you could try turning off the `constexpr` declarations the way we currently do for MSVC when the compiler is ICC. If that works for you I'd be happy to look at a pull request.

**Comment by MFHava** [comment]
I'd recommend introducing a config-header that abstracts away the feature detection, because currently the workaround for VS2013 is already duplicated in multiple files and this problem would increase for the Intel Compiler aswell...

**Comment by neilmacintosh** [comment]
@MFHava We have had this suggestion before. My objections to a config-header are that we want to remove compiler-specific workarounds as soon as we can. The current approach enables us to have some headers that will be "clean" before others and forces us to confront the ugliness. Having a separate header just hides and entrenches the problem.

Hopefully we will get to a place soon where all our target compilers support enough C++14 that they can all disappear. :-)

**Comment by MFHava** [comment]
@neilmacintosh I can totally understand that sentiment, though I doubt that you will be able to drop these workarounds in the near future - unless you drop support for any toolchain (including your own) that is only C++11 and not C++14...

**Comment by gdr-at-ms** [comment]
The Guidelines assume C++14.

**Comment by MFHava** [comment]
Hmm... ok, must have missed that, as https://github.com/isocpp/CppCoreGuidelines explicitly talks about C++11, 14 and 17...

**Comment by neilmacintosh** [comment]
@MFHava You may be right, but a man can dream ;-)

Also, our own toolchain is getting more conformant to C++14 all the time and "real soon now" we should be able to drop the workarounds for MSVC.

**Comment by MFHava** [comment]
@neilmacintosh A man can and SHOULD dream :D

**Comment by gdr-at-ms** [comment]
@MFHava Consider that fixed :-)

**Comment by MikeGitb** [comment]
I guess the main "problem" in the future will be how fast support for older compilers will be dropped. As far as compiler family (VS,gcc,clang) specific code is concerned, I'm hopeful that VS2015 will get the constexpr support currently demonstrated in VS 15 prev 5 in which case I believe you can drop almost all conditional compilations together with support for VS2013 (the only exceptions I can think of right now would be the warning pragmas and the unlikely macros).

However, correct me if I'm wrong, but so far I didn't get the impression that you want to stick to c++14 in the future and then we are back to having conditional compilation depending on what c++17 features and technical specifications the current compiler supports.

**Comment by neilmacintosh** [comment]
@MikeGitb I don't think C++17 contains any features (beyond `std::byte`...which would be a very localized conditional compile) that we plan on using inside the library implementation. Even with `std::byte`, C++17 wouldn't change the library interface.

Which is a long way of saying: "Yes, I think the situation will get better as our compilers get better at C++14. C++17 shouldn't be a big creator-of-config-macros. If it is we'll cross that bridge when we come to it.".

**Comment by rianquinn** [comment]
@neilmacintosh Some of the functions that are in the GSL are only their because we don't have automatic type deduction for constructors, which is coming in C++17. Do you any plans on removing them once we have C++17, or are they going to stay until say... all of the supported compilers have support for them?

**Comment by neilmacintosh** [comment]
@rianquinn They would stay until we decide that C++17 is the baseline language version being targeted.

**Comment by rianquinn** [comment]
@neilmacintosh Ok, that's what I kind of figured. In our repo... that will likely happen once Linux and Cygwin distros come stock with GCC and Clang versions that have support for C++17. Once that happens, we'll make the move to baseline on C++17. 

I'm assuming for the GSL, based on your presentation at CppCon, this switch will likely happen roughly when Visual Studio has 2 versions that support C++17.

**Comment by MikeGitb** [comment]
@neilmacintosh: Unfortunately, your talk from cppcon isn't yet online, but wasn't there something about concepts in your slides? 
Other points are e.g. `gsl::as_span` which was (for now) dropped with a remark to automatic type deduction.

@rianquinn: Are there really that many maker functions? I currently can only think of `finally`, but there are large parts of the gsl I haven't used yet.

**Comment by MikeGitb** [comment]
I think I got derailed a little: Actually, I'm very glad that there is no config header that has to be included in every file. That makes it much easier to reason about a single file and make local adaptions to my specific platform.

**Comment by rianquinn** [comment]
@MikeGitb To be honest, `gsl::finally` is what I was thinking about. In our repo, we are using the `gsl::on_success` and `gsl::on_failure` that were proposed in the C++ Core Guidelines (there hasn't been much conversation on those in a while), but these use the same pattern. I think most people were in agreement that `on_success` and `on_failure` were needed, they just didn't like `dismiss` or the use of inheritance to implement them, which in the end isn't that big of a deal as people who need `dismiss` can always implement their own, or fork the GSL.

**Comment by gdr-at-ms** [comment]
@all: The GSL will use very few and localized C++17 features (`std::byte`) -- so the problem we have today with VC++ principally will be less severe.  Remember, the GSL is supposed to be a "tiny" library, not an ever expanding dumping ground :-)

**Comment by MFHava** [comment]
@MikeGitb only that you will have to make those same adaptions in every header you use, that requires the same workaround instead of having it defined in one central location...

**Comment by rianquinn** [comment]
@gdr-at-ms So at least in the example I was bringing up, C++17 should make the library smaller, but yeah I agree.

**Comment by MikeGitb** [comment]
@MFHava: Yes, but my expectation / experience for now is that most things are only necessary in one or two specific headers. The current state with noexcept and constexpr being conditionally deleted everywhere is (hopefully) only a temporary issue. I can see how such config headers are important for libraries like boost, where you have thousands of files, have to support dozens of compilers and probably exercise about every edge case of the standard there is, but for the gsl it seems like a little overkill to me.

**Comment by neilmacintosh** [comment]
The discussion on this thread has been useful. However, I don't think there's anything more to be discussed here, so I'm closing the issue.

We've established that ICC doesn't quite support the C++14 parts required for GSL to compile "out of the box". If someone wants to bring the necessary changes to make compilation happen for ICC, I'd be happy to look at a PR.
