### ISSUE TITLE
User-defined literals for `gsl::string_span`?

### ISSUE THREAD

**Issue by LYP951018** [Microsoft/GSL#386]

**Comment by neilmacintosh** [comment]
I'm not sure I understand this issue. Can you provide some more details in the description please?

**Comment by LYP951018** [comment]
Sorry... I'm too lazy. I meant stuff like
```cpp 
gsl::string_span<> operator""_ss(const char* str, unsigned long long) noexcept
```

**Comment by MikeGitb** [comment]
nitpicking here, but that would only be usable for `cstring_span` and `cwstring_span` right?
I'd indeed like to see them and had actually hoped that there would be a user defined literal for `std::string_view`.

**Comment by neilmacintosh** [comment]
Both @MikeGitb and @rianquinn will be pleased to know that C++17 will contain a user-defined literal for `std::string_view` thanks to this week's committee meeting :-)

WG21 (the C++ standardization working group) voted to add `sz` as the suffix for `string_view` literals to the draft for the standard that will (assuming all goes to plan) become C++17 soon.

**Comment by neilmacintosh** [comment]
@LYP951018 Thanks, now I get it. I have no objection to adding a user-defined literal for `string_span`. It would need to be within an inline namespace within `gsl`, maybe something like `gsl::literals::string_span_literals` to echo the existing practice of the standard library.

**Comment by neilmacintosh** [comment]
I'm going to assume that this issue is now obsolete. It hasn't resulted in a pull request, and C++17 promises string literals for `std::string_view`, which is likely to prove more popular than `gsl::cstring_span`, leading to `cstring_span`s deprecation in the longer term I suspect.
