### ISSUE TITLE
Dont use #pragma once as it is not standard

### ISSUE THREAD

**Issue by viboes** [Microsoft/GSL#39]

**Comment by trebconnell** [comment]
I think it'd be best to have both #pragma once and header guards, as afaik many compilers optimize for #pragma once.

**Comment by viboes** [comment]
No problem as soon as the file has the guards. Any conforming compiler should ignore the not supported pragmas.

**Comment by michaelbprice** [comment]
I absolutely agree with fixing this issue.  Please fix this one.  In fact, the CppCoreGuidelines that are the primary reference to the GSL states that header files should have include guards.

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rs-guards

This library should at least try to be consistent with the guidelines provided there.

**Comment by neilmacintosh** [comment]
We’d be happy to look at a PR if anyone would like to put one together.

**Comment by neilmacintosh** [comment]
this has now been fixed, thanks Treb Connell!

**Comment by Zardoz89** [comment]
> No problem as soon as the file has the guards. Any conforming compiler should ignore the not supported pragmas.

What compiler don't support #pragma once ? 

I ask because I have curiosity, nothing more. As far I know, G++ , CLang and VStudio support it.
