### ISSUE TITLE
'make install' should not install UnitTest++ headers

### ISSUE THREAD

**Issue by marc-kdab** [Microsoft/GSL#392]

**Comment by neilmacintosh** [comment]
Thanks for the issue @marc-kdab. Interesting! I've never run that target, so I never noticed. Would you like to offer a PR to correct the problem?

**Comment by marc-kdab** [comment]
The GSL 'make install' should just install the gsl headers, and not the UnitTest++ library headers. Current output of make install:

  Install the project...
  -- Install configuration: ""
  -- Installing: /usr/local/include/gsl/gsl
  -- Installing: /usr/local/include/gsl/gsl_assert
  -- Installing: /usr/local/include/gsl/gsl_byte
  -- Installing: /usr/local/include/gsl/gsl_util
  -- Installing: /usr/local/include/gsl/multi_span
  -- Installing: /usr/local/include/gsl/span
  -- Installing: /usr/local/include/gsl/string_span

It should end there, but continues:

  -- Installing: /usr/local/bin/span_tests
  -- Installing: /usr/local/bin/multi_span_tests
  -- Installing: /usr/local/bin/strided_span_tests
  -- Installing: /usr/local/bin/string_span_tests
  -- Installing: /usr/local/bin/at_tests
  -- Installing: /usr/local/bin/bounds_tests
  -- Installing: /usr/local/bin/notnull_tests
  -- Installing: /usr/local/bin/assertion_tests
  -- Installing: /usr/local/bin/utils_tests
  -- Installing: /usr/local/bin/owner_tests
  -- Installing: /usr/local/bin/byte_tests
  -- Installing: /usr/local/lib/libUnitTest++.a
  -- Installing: /usr/local/include/UnitTest++/TestMacros.h
  -- Installing: /usr/local/include/UnitTest++/TestResults.h
  -- Installing: /usr/local/include/UnitTest++/UnitTestPP.h
  -- Installing: /usr/local/include/UnitTest++/HelperMacros.h
  -- Installing: /usr/local/include/UnitTest++/TestRunner.h
  -- Installing: /usr/local/include/UnitTest++/ReportAssert.h
  -- Installing: /usr/local/include/UnitTest++/ExceptionMacros.h
  -- Installing: /usr/local/include/UnitTest++/XmlTestReporter.h
  -- Installing: /usr/local/include/UnitTest++/Config.h
  -- Installing: /usr/local/include/UnitTest++/TestList.h
  -- Installing: /usr/local/include/UnitTest++/TestReporterStdout.h
  -- Installing: /usr/local/include/UnitTest++/ExecuteTest.h
  -- Installing: /usr/local/include/UnitTest++/MemoryOutStream.h
  -- Installing: /usr/local/include/UnitTest++/CompositeTestReporter.h
  -- Installing: /usr/local/include/UnitTest++/Checks.h
  -- Installing: /usr/local/include/UnitTest++/DeferredTestResult.h
  -- Installing: /usr/local/include/UnitTest++/AssertException.h
  -- Installing: /usr/local/include/UnitTest++/DeferredTestReporter.h
  -- Installing: /usr/local/include/UnitTest++/ReportAssertImpl.h
  -- Installing: /usr/local/include/UnitTest++/Test.h
  -- Installing: /usr/local/include/UnitTest++/CheckMacros.h
  -- Installing: /usr/local/include/UnitTest++/TimeConstraint.h
  -- Installing: /usr/local/include/UnitTest++/TestDetails.h
  -- Installing: /usr/local/include/UnitTest++/TestReporter.h
  -- Installing: /usr/local/include/UnitTest++/TestSuite.h
  -- Installing: /usr/local/include/UnitTest++/UnitTest++.h
  -- Installing: /usr/local/include/UnitTest++/CurrentTest.h
  -- Installing: /usr/local/include/UnitTest++/TimeHelpers.h
  -- Installing: /usr/local/include/UnitTest++/Posix/SignalTranslator.h
  -- Installing: /usr/local/include/UnitTest++/Posix/TimeHelpers.h

I have a fix for the test binaries, which I'll clean up and submit, but my cmake-foo isn't great, so I have no idea how to prevent the install command from reaching the unittest-cpp submodule.

**Comment by neilmacintosh** [comment]
Sounds great @marc-kdab. At least fixing one of the problems will be a good start ;-)

**Comment by marc-kdab** [comment]
See PR #393

**Comment by neilmacintosh** [comment]
Fixed by PR #393.
