### ISSUE TITLE
Allow for a custom exception type?

### ISSUE THREAD

**Issue by amzeratul** [Microsoft/GSL#397]
Would it be possible to have a preprocessor define that allows me to choose the type of the exception thrown if GSL_THROW_ON_CONTRACT_VIOLATION is defined?

The use case is, for example, having a custom exception type that captures the stack at the time of throwing.

**Comment by MikeGitb** [comment]
Not sure, if this would actually be a problem here, but the danger I see with any customization points is interoperability. Sooner or later popular libraries will use the gsl and then the question arises if they made conflicting assumptions about the configuration.
Although, a library shouldn't depend on Ensures/Expects throwing an exception anyway..

**Comment by neilmacintosh** [comment]
@amzeratul I wouldn't consider allowing user-defined exceptions to be specified to be thrown on contract violation. As @MikeGitb observes, it would create a lot of uncertainty for users of the library, especially when linking together separately compiled files. Thanks for the suggestion, but I'll close this issue now.

**Comment by amzeratul** [comment]
I would highlight that the behaviour of Expects already depends on the compile-time settings (e.g. whether  GSL_THROW_ON_CONTRACT_VIOLATION is defined), and that, as an assertion-style macro, it shouldn't be relied upon by any users of the library in the first place.

Not having the ability to customise the exception being thrown makes me have to choose to use my own assertion macro, instead of Expects (which means I lose static analysis support), or lose custom stack traces when an assertion does fail (making it more difficult to debug the issue).

I suppose there might be strong reasons to prohibit this, but I don't see them at the moment.

**Comment by neilmacintosh** [comment]
@amzeratul It's a matter of reducing complexity in the library's use, and preventing difficult-to-diagnose mismatches between different translation units. While this is still possible today, I don't want to add to the number of mismatch combinations that are possible.
