### ISSUE TITLE
not_null allows index operator

### ISSUE THREAD

**Issue by BongoVR** [Microsoft/GSL#399]
not_null is supposed to be used for pointers to single objects. Thus, no pointer arithmetic is allowed. However, it is still possible to use the index operator on a not_null<T> object. IMHO, this should also be blocked.

I would therefore like to propose to add
	typename std::remove_pointer<T>::type operator[](size_t) = delete; 
	typename std::remove_pointer<T>::type operator[](int) = delete; 
into the private part of the class definition to make the compiler spit out an error message when the user attempts to use not_null as a pointer to an array.

**Comment by neilmacintosh** [comment]
@BongoVR I am certainly interested in preventing not_null from being used to access multiple objects. While this will prevent people from using the perfectly safe syntax of `&a[0]` I'm not sure that is a particularly large requirement for `not_null`. Feel free to put together a PR and I'll take a look.

**Comment by BongoVR** [comment]
@neilmacintosh You are right. Being not a nullptr and pointing to a single object are two orthogonal requirements. But not_null, as it stands, does not allow pointer arithmetic. Instead of using operator++ to access the next element or operator+ to access an arbitrary element of an array, which are both not allowed, the user may apply the index operator. Prohibiting the index operator thus belongs to the same family.
a[0] and &a[0] are safe to use, that is right. But who would do that on a pointer to a single object? It smells wrong, at least. Such syntax is indicating the intent to access an array.
So, allowing the index operator seems to be a loophole. If you ban pointer arithmetic, you have to ban indexing as well. The more I am thinking about the issue the more I can imagine that it might probably be better to consider to re-enable the pointer arithmetic for not_null since accessing only one object through that pointer has nothing to do with its non-nullness.
