### ISSUE TITLE
Expects(), Ensures(), and noexcept functions

### ISSUE THREAD

**Issue by JimHewes** [Microsoft/GSL#403]
What am I missing?
It seems that Expects() and Ensures() cannot be used in functions that are marked noexcept since they throw exceptions. (or at least, it triggers a warning on VS2015)
I know these are just placeholders until they're added to the standard. But in the meantime how about defining them in terms of system-specific functions, like _wassert() which is what the assert() macro does in VS2015?

**Comment by neilmacintosh** [comment]
@JimHewes they do not have to throw exceptions. They can also call `std::terminate()`, depending on the values of the configuration macro you choose when building your code (see the comments at the top of `gsl_assert` for details).

We try to avoid having platform dependent calls wherever possible, so `std::terminate()` seem like a reasonable choice there.

**Comment by MikeGitb** [comment]
@neilmacintosh: assert is portable too, no?

**Comment by neilmacintosh** [comment]
@MikeGitb but `assert()` has the disadvantage of only existing as long as `NDEBUG` is not defined. I'd rather not have GSL interact with that facility as well.

**Comment by MikeGitb** [comment]
Right, forgot about that :(
