### ISSUE TITLE
string_length is not strict enough

### ISSUE THREAD

**Issue by jstarks** [microsoft/GSL#409]
`string_length` returns 0 if the pointer passed is nullptr or if the length passed is < 0. Based on the principle of being strict about memory safety, it seems like it should terminate if the length is < 0, or if the length is non-zero and the pointer is null.

**Comment by neilmacintosh** [comment]
@jstarks, I absolutely agree. Would you be interested in putting together a PR to correct this?

**Comment by jstarks** [comment]
Sure, I can give this a shot.

**Comment by hsutter** [comment]
Maintainers' call: Sorry for the delay in replying. This is issue is now out of date because the Guidelines have removed all `*string_span` types, and it still has `zstring` and `czstring` as aliases for `char*` and `const char*` which don't have these member/helper functions.
