### ISSUE TITLE
Update the GSL NuGet package?

### ISSUE THREAD

**Issue by LYP951018** [Microsoft/GSL#410]
The latest version of GSL on NuGet doesn't contain `<multi_span>`, which is really useful.

**Comment by neilmacintosh** [comment]
I will get around to updating the Nuget package soon ;-)

I'm glad you find `multi_span` useful, but I will sound a warning that `multi_span` is a part of the GSL that has not received much attention in the past year. Plus, it is a component that may undergo interface change in the future, as there is a multi-dimensional span proposals currently working its way through the standardization process that differs in some respects from `multi_span`.

**Comment by KrisTC** [comment]
It would be really nice to see an update before you drop VS2013 support in the GSL, as mentioned in: https://github.com/Microsoft/GSL/issues/168. It looks like Visual studio 15 is progressing quickly? Also was their improvement to the checker coming along too? https://www.nuget.org/packages/Microsoft.CppCoreCheck/

**Comment by neilmacintosh** [comment]
@KrisTC yes, we'll drop an updated NuGet package of the GSL (and CppCoreCheck) for VS 2015 some time soon (certainly before retiring VS 2013 support).

Improvements to the checkers show up most quickly in Visual Studio "15" - where CppCoreCheck is integrated in-the-box.

**Comment by jozefizso** [comment]
What are the plans to release updated NuGet package with latest gsl code?

**Comment by capsocrates** [comment]
> What are the plans to release updated NuGet package with latest gsl code?

I would like to know as well.

**Comment by MikeGitb** [comment]
@capsocrates: Not directly answering your question, but for everyday use I'd recommend to use the version offered by vcpkg which is at least from October 2016 and it is relatively easy to update the portfile to a newer commit

**Comment by neilmacintosh** [comment]
I'll close this issue out as the NuGet package is no longer maintained to the best of my knowledge.
