### ISSUE TITLE
deleted operator of not_null

### ISSUE THREAD

**Issue by stayprivate** [Microsoft/GSL#412]
```
    not_null<T>& operator+(size_t) = delete;
    not_null<T>& operator-(size_t) = delete;
```

Would it be more precise to not return by reference?  Given the delete that's moot though. I came upon this while running static analysis tool ;-)

```
    not_null<T> operator+(size_t) = delete;
    not_null<T> operator-(size_t) = delete;
```

**Comment by rianquinn** [comment]
There doesn't seem to be any C++ Core Guidelines on the subject (doing a really quick search so i might have missed it), but I was able to fine this which suggests your right:
http://users.cms.caltech.edu/~donnie/cs11/cpp/cpp-ops.html

There probably should be some guidelines written about this (if they are not already there), so it might not be a bad idea to ask the question in general about the "+ / -" overloads here if they are in fact missing:
https://github.com/isocpp/CppCoreGuidelines/issues

**Comment by neilmacintosh** [comment]
@stayprivate you may well be correct. I think it's just laziness on our part because we're deleting them anyway. If it bothers you (or a tool you are running) I'd be happy to take a PR to clean it up.

**Comment by stayprivate** [comment]
Wanted to check if my own interpretation was correct and if that was the case provide an occasion to make it more precise.   It is no causing me any grief, do as you see fit.

Thanks.
