### ISSUE TITLE
Mark invalidating move constructors / assignment operators

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/GSL#420]
One feature I'd like to see is some mechanism (maybe an attribute or a base class) that allows me to tell the compiler/the static analysis tool, that moving an object of this class invalidates the source object. By invalidating I meaning that the only operations that are allowed on an invalid object are assignment and destruction and the compiler would warn when your try to call any other member function. That would simplify some special member function definitions in my code, because  I e.g. don't have to zero out the state of the moved from object.
The same could also be applied to default constructed objects.

**Comment by neilmacintosh** [comment]
@MikeGitb there should be no need for any additional "marking" as move should *not* be invalidating. The correct interpretation of any moved-from object is that it is a valid object that can be used, reassigned or destroyed. It does not necessarily have the same value as before the move, is the only difference. That is the behavior of standard library types when moved-from.

Take a look at [C.64](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c64-a-move-operation-should-move-and-leave-its-source-in-a-valid-state) in the Core Guidelines for more detail.
