### ISSUE TITLE
More algorithms

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/GSL#423]
Now that we have an implementation of `gsl::copy` I wonder, if more standard algorithms should be ported.
The two general advantages I see are:
- More convenient interface 

      gsl::find(my_span, v); //vs
      std::find(my_span.begin(), my_span.end(), v);
- A varying degree of performance benefits 

`Copy` was a pretty clear cut case for me because
- Copying data into a buffer while protecting against buffer-overflow was certainly one of the prime usage examples of `gsl::span`, so the usage should be as simple as possible to further encourage the use of it.
- The performance benefits could be quite noticable (> 10x on microbenchmarks on my system). 

For most other algorithms I don't expect the performance difference being really that noticeable (#376) but the more convenience interface would still be a big win. On the other hand, I'm not sure we should  add a lot of functions that become obsolete, as soon as the ranges TS gets implemented.

If you do decide that at least some additional algorithms should be added, my personal favorites would be
 - `equal`, `transform` and `inner_product` (here the parameter reduction would be most noticeable and I measured similar performance improvements)  
 - `rotate` (The interface would not improve much, but it would also gain similar performance benefits as copy)
 - the sorting ( `sort`, `stable_sort`, `partion` ..) and find algorithms (`find` / `find_if` ... and lower-/upper_bound) - just because I'm using them most often (I didn't make any measurements at all).

**Comment by rianquinn** [comment]
I am always a huge fan of simplifying interfaces, and think this is a good idea, however I would like to play devils advocate with three questions:
- If span is adopted by the STL, do we envision also pitching these new interfaces?
- This would be a lot of additional code to maintain, so is this something that adds enough value to warrant to additional work?
- Do you intend these to always use .begin() and .end() and if so, is it your intention that a user should use subspan to work on a sub portion of the span with these new interfaces?

**Comment by MikeGitb** [comment]
@rianquinn: 
I think, by the time `gsl::span` gets adopted to into the STL (2020?) The ranges TS will (hopefully) also be a part of it. As that proposal already provides the proper interface it would be a matter of internal optimization for span types,

Actually, my Idea would be to use `data()` and `size()` (to get rid of redundant range checking) internally and - yes - `subspan` on the user side if you want your algorithm to operate on a subpart of the span. But to be clear: My Idea was not to replace the more flexible/general iterator based stl interfaces - just to provide a simplified syntax for the most common use-cases.

**Comment by MikeGitb** [comment]
One additional algorithm I would like to have is something like `copy_some` that copies only as many elements as fit into the destination range.

**Comment by neilmacintosh** [comment]
Hi @MikeGitb. I am certainly open to adding more algorithm overloads.

To address the quite reasonable concerns raised by @rianquinn...I see this in the following light. If we could all leap into the future together, right now, then we'd have both `span` and the content of the Ranges TS in the standard and everything would "just work". :-) However, until we reach that glorious future, we need to make it easier for people to use standard algorithms with `span`, and ideally we want to do so in a way that "future-proofs" (as much as you ever can).

So I think the guiding principles here are:

1. People can always use the existing standard library algorithms with `span`.

There may be some slow-down in doing so today over using raw pointers, but I think that should erode over time. We will improve the performance of the `span` implementation and I think that both library and compiler vendors will also start doing better with it (esp. once it becomes standardized). Anyway, slow-down is always relative and should be measured in a specific scenario, with a specific tool set, before people decide it is too costly for them.

2. We can provide overloads for algorithms that take `span` arguments (rather than iterators). *As long as those overloads match the signatures in the Ranges TS*.

That way we are helping people who don't use Ranges yet prepare for the day Ranges make it into the standard, and ultimately, their standard library implementation.

**Comment by MikeGitb** [comment]
Does someone a open source test suite for STL algoritms against which such gsl wrappers could be tested?

**Comment by viboes** [comment]
I have not tried it, but shouldn't the range-v3 or the Range-TS implementations work for span?
What is particular to span that the default algorithms wouldn't be as efficient as we could expect?

**Comment by MikeGitb** [comment]
@viboes: Due to the additional checks, almost any operation on a span_iterator is more expensive than the same operation on a plain pointer. In some cases this difference is noticeable, in some it is not (or just barely). 

Also, not everyone who uses the gsl can or wants to also use the range-V3 library (e.g. VS2013 is currently supported by the gsl, but not by ranges-V3).

**Comment by viboes** [comment]
If the use of `span_iterator` implies a loss of performances, there is IMHO a design issue. `span_iterator` shouldn't be more expensive than a plain pointer. span is an excellent idea. Please, don't kill it forcing users to pay for more than they need.

BTW, I believe that range-v3 is working on an implementation of the proposed span. I hope it will not need to specialize the algorithms.

Does Microsoft has the intention to support Range-v3 in a near future?

**Comment by MikeGitb** [comment]
@viboes: `span_iterator` does more than a plain pointer, so some overhead is inevitable, but in most scenarios that overhead is not really noticeable ( see https://github.com/Microsoft/GSL/issues/376 for some discussions on that topic). 
My motivation for writing wrappers for standard algorithms is primarily the better interface, but also it is also about getting the best of both worlds: The bound checks provided by `gsl::span` and the performance you get by using raw pointers.

**Comment by MikeGitb** [comment]
@viboes : range-v3 (actually a [fork thereof](https://github.com/Microsoft/Range-V3-VS2015)) is already supported by VS2015

**Comment by mmatrosov** [comment]
@MikeGitb 
> `span_iterator` does more than a plain pointer
What is this?

**Comment by MikeGitb** [comment]
@mmatrosov: It performs range checks (for which it has to hold a pointer to the span object it originated from)

**Comment by mmatrosov** [comment]
@MikeGitb Ok, but checks are not done if `GSL_THROW_ON_CONTRACT_VIOLATION` is not defined, checks are not done, so why should one pay for them? Remember the C++ philosophy: you do not pay for what you do not use.

**Comment by MikeGitb** [comment]
@mmatrosov: Sorry to disappoint you. The default behavior - even in release mode - is `GSL_TERMINATE_ON_CONTRACT_VIOLATION` which also does range checking. You have to actively turn off (all) contract checking by defining `GSL_UNENFORCED_ON_CONTRACT_VIOLATION`. Even then, `gsl::span::iterator` has double the size of a normal pointer (because they contain a pointer to the span and an index) and dereferencing requires an additional indirection.

You can discuss those design desicions with the maintainers of this repository and the core guidelines (I'm not in any way connected to either of them). 

As far as I can tell, `gsl::span` is not intended to be a true zero cost abstraction but a very low cost abstraction with the primary purpose to prevent out of bounds errors. Thus they are willing to trade small amounts of performance for added safety if necessary. Most of the time this should not be an issue (measure and find out) and you could probably redesign the implementation to prevent that overhead when `GSL_UNENFORCED_ON_CONTRACT_VIOLATION` is defined, but that is why I said

> `span_iterator` [as currently designed/implemented] does more than a plain pointer, so **some** overhead is inevitable.

**Comment by mmatrosov** [comment]
@MikeGitb 
> You can discuss those design desicions with the maintainers of this repository and the core guidelines (I'm not in any way connected to either of them).

Interesting. Why did you close the issue then? :)

> As far as I can tell, gsl::span is not intended to be a true zero cost abstraction

@annagrin @CaseyCarter I see you among the top contributors for the project. Could you please comment on this claim from @MikeGitb that I cited above?

**Comment by MikeGitb** [comment]
@mmatrosov : I opened that issue some time ago, but by now lost any interest in using the gsl privately or at work and closed any stale issues I created at this repo (didn't seem there was any intention to add additional algorithm wrappers anyway). 

If you are interested in adding more algorithms wrappers yourself you can have a look at a past PR from me and the accompanying discussions (https://github.com/Microsoft/GSL/pull/427).
