### ISSUE TITLE
Should this be hosted under the isocpp organization on GitHub.com instead of Microsoft?

### ISSUE THREAD

**Issue by michaelbprice** [Microsoft/GSL#43]
I think I understand why it is under Microsoft, but it feels weird.  I think it would fit best directly beside https://github.com/isocpp/CppCoreGuidelines

Is this something that Microsoft would be okay transferring ownership over to the Standard C++ Foundation?

**Comment by kylog** [comment]
I wondered the same thing. I'd love to see some discussion around this.

**Comment by galik** [comment]
I think the idea is that isocpp sets the specifications and anyone can provide an implementation. This is Microsoft's effort but there is nothing preventing another project from implementing the specifications. The more the merrier perhaps?

**Comment by gdr-at-ms** [comment]
Yes, this is the reference implementation of the ideas behind GSL as envisioned in the Core Guidelines.  We expected there will be more implementations.
We are considering the suggestion of moving to isocpp.org with great interest and will give you updates.

**Comment by tamaskenez** [comment]
I think a reference specification would be benefitial for other implementors. From this implementation it is not clear which design decisions are mandatory and what details are allowed to vary.

It is also confusing, as others have also noticed, that gsl overlaps and in places contradicts with the publicly available stl proposals (string_view, array_view).

**Comment by viboes** [comment]
I agree. If we expect more implementations we need a specification, which currently is missing in the C++ Core Guidelines.

**Comment by AndrewPardoe** [comment]
This conversation is back to an issue on the isocpp repo: https://github.com/isocpp/CppCoreGuidelines/issues/144
