### ISSUE TITLE
Mismatch/misplaced pragma warning push/pop in file multi_span

### ISSUE THREAD

**Issue by ErnestPenfold** [Microsoft/GSL#431]
The last pragma warning pop in line 2226 is misplaced which leads to a warning C5031. Must be moved to line 2218 or at least outside #if defined(GSL_THROW_ON_CONTRACT_VIOLATION) at the end of the mentioned file.

**Comment by neilmacintosh** [comment]
Thanks for noticing this and raising theissue @ErnestPenfold. Would you like to offer a PR to fix the problem?

**Comment by neilmacintosh** [comment]
Thanks @ErnestPenfold for PR #436 that fixed this!
