### ISSUE TITLE
`gsl::copy` should... return something?

### ISSUE THREAD

**Issue by LYP951018** [Microsoft/GSL#433]
`std::copy` returns the [output iterator to the element in the destination range, one past the last element copied](http://en.cppreference.com/w/cpp/algorithm/copy), which is very convenient for multi-time copy. As for `gsl::copy`, I think it should return the subspan of the dest which is not touched. Usage:
```cpp
const auto rest = gsl::copy(prefix, dest);
gsl::copy(postfix, rest);
```

**Comment by MikeGitb** [comment]
Does PR #422 address your request?

**Comment by LYP951018** [comment]
@MikeGitb YES!

**Comment by ewoudvc** [comment]
This didn't get merged in the end, though a useful feature
