### ISSUE TITLE
Can't Clone Microsoft/GSL Cleanly

### ISSUE THREAD

**Issue by jumonatr** [Microsoft/GSL#438]
The version of unittest-cpp has wiki files that have invalid names for the windows platform.

When cloning the repo the files can't be created on windows which means git reports that the submodule contains changes. This can cause some CI systems to fail as it believes the checkout was unsuccessful. I changed unittest-cpp to have valid wiki page names, but I noticed that the gsl points to the Microsoft/unittest-cpp which is far behind the source repo. I'm not sure what the best way to fix this in the gsl would be, should we just make it point to unittest-cpp/unittest-cpp then advance to the tip? Are there changes in Microsoft/unittest-cpp that are necessary for the gsl? Was it a conscious decision to stay on this specific unittest-cpp hash? 

Thanks,

Julien.

**Comment by neilmacintosh** [comment]
Thanks for raising this issue @jumonatr. Gsl should point to unittest-cpp/unittest-cpp. Originally, we found a small bug and fixed it in unittest-cpp and so pointed to Microsoft/unittest-cpp until the change made it upstream (which it did a long time ago). So there was a good reason originally, but pointing at the old repository is just a bit of "cruft" that has survived in our repo, not a conscious design decision.

Would you like to offer a PR that corrects things for us?

**Comment by jumonatr** [comment]
I haven't gotten to validating across the whole suite yet, but once I do I'll definitely put one up (Don't know when I'll be able to schedule it though). I just wanted to get some insights into how the solve the issue officially. Thanks for the reply.
