### ISSUE TITLE
including GSL also includes GSL/tests

### ISSUE THREAD

**Issue by ascii255** [Microsoft/GSL#441]
There was the issue https://github.com/Microsoft/GSL/issues/277 that was fixed. Now we are supposed to do /I c:\GSL. This also includes everything that is in c:\GSL\tests what you maybe don't want.

I suggest doing deeper nesting: having c:\GSL\include and inside the gsl folder. So you would include c:\GSL\include. See https://github.com/electronicarts/EASTL. They have similar structure which works well.

**Comment by neilmacintosh** [comment]
Thanks for the suggestion @ascii255. I think that's a very reasonable observation, and I really appreciate the link to EA's prior art there. Their structure does look pretty workable. Would you be interested in putting together a PR that makes the change?
