### ISSUE TITLE
span missing array+size constructor

### ISSUE THREAD

**Issue by cubbimew** [microsoft/GSL#442]
The Core Guidelines [P.7: Catch run-time errors early](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#p7-catch-run-time-errors-early) appear to expect that span constructor exists that takes an array and a size, creating a view into the beginning of the array and failing when the size exceeds array extent.

Looks like that constructor is not part of this implementation, could it be added?

**Comment by MikeGitb** [comment]
Not particularly against it, but personally I find this not too readable and would prefer to use the subspan creation to be explicit.

Either via the already supported syntax:

    increment2( gsl::make_span( a ).subspan( 0, m ) );

or via a new utility function:

    increment2( gsl::make_subspan( a, m ) );

**Comment by MikeGitb** [comment]
Ignnore my previous comment: If I'm not mistaken, due to array-to-pointer decay that syntax already works, but doesn't check the length right?

In that case, this should probably be fixed, e.g. by adding 

    template <size_t N>
    constexpr span(element_type (&arr)[N], index_type subspanlength) 

constructor (or deleting the same)

**Comment by cubbimew** [comment]
> If I'm not mistaken, due to array-to-pointer decay that syntax already works, but doesn't check the length right? 

right, and also triggers the array decay warning in both MSVC and clang-tidy's guidelines checkers

**Comment by JonathanDCohen** [comment]
Perhaps defaulting `subspanlength = N` as well, so you can just pass the array and be done with it.

**Comment by MikeGitb** [comment]
@JonathanDCohen: There is already a constructor for that.

**Comment by neilmacintosh** [comment]
@cubbimew there's no reason we couldn't add the constructor from an array plus size. It was actually in earlier implementations. I took it out because none of my internal users actually used it, and I was interested to see if anyone would miss it. No one did until now ;-)

So if we think there is a common enough need in real-world code, then I'd be happy to see it added back in.

@JonathanDCohen made an implementation suggestion that seems a reasonable path that would provide it as a unification with the existing from-array constructors.

**Comment by cubbimew** [comment]
I only ran into it because I was trying out some examples from the Core Guidelines - it wasn't a production need of any kind. If practice shows it unnecessary, an issue should be raised there to remove its usage.

**Comment by neilmacintosh** [comment]
@cubbimew I agree. Though perhaps if we adopt the suggestion from @JonathanDCohen we get it cheaply and it shouldn't be an enormous burden to offer. If @JonathanDCohen or anyone else wants to put together a PR I would be happy to look at it.

**Comment by neilmacintosh** [comment]
Small update here: I just met an internal user who has a valid use case for exactly this. So let's get it added (whether via @JonathanDCohen's approach or just directly.

**Comment by neilmacintosh** [comment]
The idea of this constructor was discussed during standardization of `span` (coming soon in C++20) and rejected. It was seen as being unnecessary. So I'll close this issue out now.

**Comment by hsutter** [comment]
Guidelines editors call: We would like this to be reopened please, the original is cleaner and safer.

Xref: https://github.com/isocpp/CppCoreGuidelines/issues/1306

We should also re-suggest this for `std::span`.

**Comment by hsutter** [comment]
Update: We talked about this again today, and updated [isocpp/CppCoreGuidelines#1306](https://github.com/isocpp/CppCoreGuidelines/issues/1306) with additional next steps.

**Comment by jack17529** [comment]
@annagrin so as soon as the array is passed to span, it should check the range, according to the array's original size?
