### ISSUE TITLE
length_func<CharT>::operator() fails CppCoreCheck

### ISSUE THREAD

**Issue by duncanhorn** [Microsoft/GSL#451]
Running CppCoreCheck with VS2017 RC fails with:

    warning C26461: The pointer argument 'ptr' for function gsl::details::length_func<char>::operator() can be marked as a pointer to const. (con.3: https://go.microsoft.com/fwlink/p/?LinkID=786684)
    warning C26461: The pointer argument 'ptr' for function gsl::details::length_func<wchar_t>::operator() can be marked as a pointer to const. (con.3: https://go.microsoft.com/fwlink/p/?LinkID=786684)

Seems like the placement of `const` is incorrect:

    template <>
    struct length_func<char>
    {
        std::ptrdiff_t operator()(char* const ptr, std::ptrdiff_t length) GSL_NOEXCEPT
        {
            return details::string_length(ptr, length);
        }
    };

Should likely be declared as `const char* ptr` or perhaps `const char* const ptr`.

**Comment by neilmacintosh** [comment]
Nice catch @duncanhorn. Would you like to offer a PR?

**Comment by duncanhorn** [comment]
Sure thing. #458

**Comment by neilmacintosh** [comment]
This was closed thanks to the #458 from @duncanhorn.
