### ISSUE TITLE
what about a not_null(T t) 

### ISSUE THREAD

**Issue by janwilmans** [Microsoft/GSL#455]
Of course this will incur run-time cost, but what I'm wondering if it belongs in the GSL or not?

```
template<class T>
auto not_null(T t) -> T
{
    if (!t) throw std::exception("nullpointer");
    return t;
};
```

usage:
```
void connect()
{
  auto controller = not_null(system.getController()) // getController can return nullptr
}
```
instead of this pattern:
```
void connect()
{
  auto controller = system.getController()
  if (controller)
  {
     throw std::exception("nullpointer");
  }
}
```

**Comment by neilmacintosh** [comment]
Thanks for the issue @janwilmans. Is this not what the existing `gsl::not_null` type does for people? Or am I missing something in your suggestion?

**Comment by janwilmans** [comment]
Well, except that right now not_null is a class template, so you are required to repeat the type like:
```
void connect()
{
  auto controller = gsl::not_null<controller_type>(system.getController());
}
```
which works, but is more verbose and can be very noise with long typenames

**Comment by MikeGitb** [comment]
Maybe I'm reading to much into it, but I think there is also a semantic difference: 
If I understand you correctly, then your not_null function is supposed to check if a pointer is null and throw an error otherwise. So this function would be a replacement for a manual `if ...` statement. Creating a gsl::non_null is more of a promise from the programmer to the rest of the program that this pointer is not null and would usually still require a check beforehand unless you know for some other reason that the pointer will never be null.

**Comment by neilmacintosh** [comment]
@MikeGitb I think the semantic difference exists, but is not support important here. You could use a short-lived or temporary `not_null<T>`, for example to achieve the same effect.

@janwilmans I agree that having to write out the full template instantiation is a little painful. I'm fairly sure that with the new C++17 template constructor argument deduction (probably not the correct name for the feature, I can never remember it) you could just write:

````cpp
gsl::not_null controller = system.getController();
````

But I also understand it will be a while before everyone is on C++17-compliant compilers ;-)

**Comment by MikeGitb** [comment]
@neilmacintosh: Since when is violating a contract (`gsl::not_null must not be contructed from a null pointer) considered acceptable for production code? My understanding was that you should be able to deactivate contract checking without changing the behavior of a bugfree program.

Not to mention the using `gsl::not_null` will - at least with the default contract cheking behavior - terminate the program instead of throwing an exception.

**Comment by neilmacintosh** [comment]
@MikeGitb I'm not sure I agree with your assumption about what the sketches in this thread mean.

Let's go back to the original question that started this thread. It was about how to replace a sketch of a common practice: defending against unwanted `nullptr` in parameters or in returns from function calls. 

The semantics in that sketch appear to be that passing (or returning) `nullptr` would be a violation of the program's expectations: in other words, a bug. In that case, `not_null<T>` is an entirely appropriate mechanism to use. It does not change a bug-free program's semantics in any way.

`not_null<T>` can terminate the program, or throw an exception, or do nothing at all. That choice is left to the user of the library. So the sketch can continue having equivalent behavior (throwing) when using `not_null<T>` if the user so desires.

**Comment by MikeGitb** [comment]
Well, only  @janwilmans can really tell, but I don't think I've ever had a case where a function could accidentially return a nullptr (as opposed to using it deliberately as an mechanism to report a failure). 
In particular, if it is a postcondition of the function that the returned value is non null, shouldn't that be tested in the function itself (either via Ensures or by returning a nullptr)?

The argument that one can configure not_null to throw an exception has a hughe caviat: You can't do that locally for a particular check but only globally for all contracts. So you can't actually say "I want not_null to throw an exception" but rather "I want contract violations in general to be reported by exceptions" (And I think you yourself said that this mechanism was primarily designed for unit tests).

**Comment by MikeGitb** [comment]
Maybe it this is only the case for my particular style of coding, but even before the gsl I never expressed pre- and posconditions with checks and exceptions but with asserts.

`if( cond(param) ) { throw ...}` Is imho more suitable for wide contracts with explicitly defined error handling.

**Comment by janwilmans** [comment]
What I'm trying to do is check the result of a function that has a wide contract and so can sometimes legitimately return nullptr. As @neilmacintosh pointed out, I could to this with a temporary and you are correct, in c++17 class template deduction (as I think it is called) would indeed solve the 're-specifying the type' for me.

If the sole purpose gsl::not_null is to enforce a narrow contract, meaning that a violation _always_ means that there is a bug in the program, then I think I am just misusing it now...

So my question then is: should gsl::not_null be used (is it wise) to check wide contracts or should the usage be strictly the enforcing of narrow contracts.

@MikeGitb brings an interesting point to the table, because using gsl::not_null to check wide contract makes it impossible to change the configuration of not_null later. The code would depend on the not_null throwing an exception.

Given that, in my opinion, I think it is a bad idea to use not_null to check the result of a function with a wide contract, right?
you would better either make the function throw an exception in the first place, or write a small special purpose function template, like the not_null in my initial question, but with a better name like throw_if_nullptr.

Neil, I see you already closed the issue as resolved, but maybe it would be worth mentioning the outcome of this conversation in the documentation of not_null ?

**Comment by neilmacintosh** [comment]
Thanks for the additional context @janwilmans.

It sounds like `gsl::not_null<T>` is the wrong choice for your situation then.

If a `nullptr` is a possible, valid return from a function, or value passed via parameter, then the best approach is to just test the pointer in question.

I think what confused me was the sketch was throwing an exception. If the `nullptr` is an accepted, possible input value (or result in the case of the function call), then it doesn't seem like an exceptional condition, rather an expected one that just requires different handling. Perhaps it signals something useful such as "not found", that's a common usage.

Regardless, if `nullptr` values are likely to occur and do not represent a contract violation, `not_null<T>` is not for you ;-) If you have a certain processing path within a function that never allows accept `nullptr` values, then transferring an already-tested pointer into a local `not_null<T>` might be a valid use.

I like your suggestion of updating the documentation for `not_null<T>` to illustrate this point clearly. As we work on a GSL tutorial, I'll make sure this thinking gets captured.

**Comment by janwilmans** [comment]
As an additional remark, possibly for the documentation update: I was also temped to use gsl::not_null as a way to ensure a member function can still use a member shared_ptr, like so:

```
class Foo
{
  double getValue() 
  {
    return gsl::not_null<Controller>(m_controller).getValue();
  }

  void connectionLost()
  {
   m_controller.reset()
  }

  private:
   std::shared_ptr<Controller> m_controller;
  }
```

In this case, the connectionLost() is rare, but certainly not a bug in software (it happens if you unplug a cable inside our product)

But even then, the fact that the production code relies on the configuration of the gsl::not_null sound like pretty bad idea.
