### ISSUE TITLE
Add an initializer_list constructor to span<>

### ISSUE THREAD

**Issue by KazDragon** [Microsoft/GSL#459]
I am using span<T> as a function argument replacement for std::vector<T>,  on the basis that the interface becomes far more flexible and no longer imposes requirement for a vector on the caller.  Awesome.

However, I want to have test code of the form:

```
    void test_something()
    {
        obj a, b, c; // ... init, perhaps mocks with expectations
        auto result = foo({a, b, c});
    }

```
This is not possible with the current span<>, and makes this sort of code very fiddly when it really shouldn't be.  It would be awesome to have this Just Work.

**Comment by JonathanDCohen** [comment]
This is really reasonable to me, as well.  

We should think about how this interacts with the `const`-ness of `ElementType`.  We *definitely* want this to take `initializer_list<remove_const_t<ElementType>>`, since otherwise this wouldn't work for functions taking a `span<const T>`.  

Similarly, I think the correct call is to only allow this constructor when `ElementType` is` const` -- it makes no sense to mutate the values of an `initializer_list`.

Thoughts?

**Comment by neilmacintosh** [comment]
I would like to understand the scenario better first. @KazDragon using an `initializer_list` in the example you gave might be fine, but only as long as `result` doesn't end up being a subspan, for example. We don't want to encourage people to write functions that refer to an `initializer_list` whose lifetime has already ended.

**Comment by MikeGitb** [comment]
Related: https://github.com/Microsoft/GSL/issues/137

**Comment by KazDragon** [comment]
Sure.  I'm in the process of taking a part of a project I have and splitting it into a separate library that I can use in another project.  Several of the interfaces take vectors of things because they're the best abstraction for an array right now.  Take for example my current plaything:

https://github.com/KazDragon/paradice9/blob/master/munin/include/munin/layout.hpp

which has vectors coming out of its ears in the interface.  In this project, layouts are not stateful, so there's no storage (only calculation/modification of the contents).  Also possibly not the best API, but that's one reason I'm experimenting with spans.  This issue keeps cropping up.

At the moment, If I substitute these for a span, then I lose the dependency on vector, which is great.  However, I lose the ability to pass in an initializer-list shaped piece of code.  Instead, I have to always create a separate named array and then pass that in.  This doesn't generally happen in the production code, but it happens all the time in the tests I'm writing.

In my mind, span<> screams out "temporary" to me in the same way passing const char* into a function does.  If you want that data to stay around, you'd better make a copy.

**Comment by neilmacintosh** [comment]
Thanks @KazDragon, that helps me understand what you're after and why. I can certainly appreciate your argument about the convenience of having an `initializer_list` constructor for `span`. However, I prefer the safety of not adding such a constructor. As @MikeGitb correctly points out, we have considered this aspect of span initialization in the past and decided to avoid it.

I think @gdr-at-ms summed it up nicely in that previous thread: a `span` is a view over a container, simply passing an `initializer_list` to the `span` constructor cannot construct a container, nor is an `initializer_list` a container.

**Comment by expnkx** [comment]
> Thanks @KazDragon, that helps me understand what you're after and why. I can certainly appreciate your argument about the convenience of having an `initializer_list` constructor for `span`. However, I prefer the safety of not adding such a constructor. As @MikeGitb correctly points out, we have considered this aspect of span initialization in the past and decided to avoid it.
> 
> I think @gdr-at-ms summed it up nicely in that previous thread: a `span` is a view over a container, simply passing an `initializer_list` to the `span` constructor cannot construct a container, nor is an `initializer_list` a container.

This is exactly why std::span considered harmful by taking away people's choice.

Safety is the losers' execuse.

You oop losers did everything wrong.

unique_ptr, std::span are all harmful since their runtime overhead is unacceptable.
