### ISSUE TITLE
cygwin compilation issue

### ISSUE THREAD

**Issue by rianquinn** [Microsoft/GSL#463]
UnitTest++ is not compiling on cygwin, and as a result, the GSL also fails to compile on cygwin. I have filed the following bug so that we can track progress on this. I should note that Catch.hpp does not have this issue 😄 

https://github.com/unittest-cpp/unittest-cpp/issues/150

**Comment by rianquinn** [comment]
While we wait for a fix, if you need to __use__ the GSL on cygwin, but don't need to run the tests, here is a patch that seems to work fine. 

replace the following in CMakeLists.txt:
```
enable_testing()
add_subdirectory(tests)
```

with:
```
string(COMPARE EQUAL "${CMAKE_SYSTEM_NAME}" CYGWIN _cmp)
if(NOT _cmp)
    enable_testing()
    add_subdirectory(tests)
endif()
```

**Comment by neilmacintosh** [comment]
I'm leaving this issue open so people can see @rianquinn's helpful workaround. I'll close it once we commit the Catch replacement for unittest-cpp (which should be very soon).

**Comment by neilmacintosh** [comment]
Now Catch is in with #533 we can close this.
