### ISSUE TITLE
Compile without exception support

### ISSUE THREAD

**Issue by LucaFulchir** [Microsoft/GSL#468]
I am trying to use this in an other project which compiles without exception support.  
I would not mind substituting the exceptions with asserts, and let it fire only in debug.

currently I use only the `<gsl/span>` header, my problem lies in `<gsl/gsl_util>`.  
Could we get something like:
```
#if defined ( __cpp_exceptions) || \
        (defined (_MSC_VER) && defined (__CPPUNWIND)) || \
        (defined (__GNUC__) && defined (__EXCEPTIONS))
    #define ABORT_THROW (x) throw x
#else
    #define ABORT_THROW (x) (x, std::abort())
#endif
```
and then use `ABORT_THROW` when needed?

**Comment by neilmacintosh** [comment]
@LucaFulchir can you help me understand why does using the `#define` of `GSL_TERMINATE_ON_CONTRACT_VIOLATION` not achieve what you want?

**Comment by LucaFulchir** [comment]
No real reason, I just did not know enough the codebase, was in a bit of a rush and I assumed that it had not been tested for non-exception.

Sorry, but If I had the code ready I would have used a pull request :p

**Comment by neilmacintosh** [comment]
Ok, thanks. In that case, can I close out this issue as resolved?

Simply build your GSL-using project with `GSL_TERMINATE_ON_CONTRACT_VIOLATION' set and you will get contract-checking that does not use exceptions. (Note: some functions in the GSL like `narrow()` explicitly do throw exceptions, by-design. I would just expect you do not use those in a no-exception environment).

**Comment by LucaFulchir** [comment]
uhm...
That seems to work with g++, I was using clang++ which still gives error just by including `<gsl/span>`

**Comment by neilmacintosh** [comment]
Can you give details of the error?

**Comment by LucaFulchir** [comment]
yeah, sorry.
example file:
```
#define GSL_TERMINATE_ON_CONTRACT_VIOLATION
#include <gsl/span>
int main (void)
{
    return 0;
}
```
`gcc version 6.3.1 20170306 (GCC)`:
g++ -Wall -std=c++14 -fno-exceptions -I ./gsl/include/ span.cpp
all ok. no warning, 
`clang version 3.9.1 (tags/RELEASE_391/final)`
clang++ -Wall -std=c++14 -fno-exceptions -I ./gsl/include/ span.cpp
```
In file included from span.cpp:2:
In file included from ./gsl/include/gsl/span:25:
./gsl/include/gsl/gsl_util:123:33: error: cannot use 'throw' with exceptions disabled
    if (static_cast<U>(t) != u) throw narrowing_error();
                                ^
./gsl/include/gsl/gsl_util:125:9: error: cannot use 'throw' with exceptions disabled
        throw narrowing_error();
        ^
2 errors generated.
```

**Comment by djarek** [comment]
I'm having a simillar issue (using g++ 5.4.0), however mine occurs when attempting to construct a span from a vector [here](https://github.com/Microsoft/GSL/blob/master/include/gsl/span#L408). I'm wondering, perhaps asio's [approach](https://github.com/chriskohlhoff/asio/blob/master/asio/include/asio/detail/throw_exception.hpp#L38-L44) could be considered - in a environment with exceptions disabled it's up to the user to specify an action on an exception(in most cases it would result in a restart of the system or an infinite loop).

**Comment by neilmacintosh** [comment]
@LucaFulchir I regard the clang warning as a bit excessive. If a program doesn't make any calls that require exceptions, warning about their (unreachable) presence in a header file seems unnecessary to me.

@djarek You have identified a specific case where `span` does use `narrow` that restricts use of `span` without exceptions, thanks!

I would be prepared to look at a patch that followed the path of some standard library implementations and have `narrow()` modify its behavior in the case that a "no exceptions" symbol exists and call `std::terminate` instead of throwing. While in general I don't like building C++ without exceptions, this seems like a small accommodation that allows people to still use `span` and friends without compromising their design, and follows a path already used by some standard library implementations.

**Comment by LucaFulchir** [comment]
> I regard the clang warning as a bit excessive. If a program doesn't make any calls that require exceptions, warning about their (unreachable) presence in a header file seems unnecessary to me.

That's an error, not a warning.  
The output is the same whether I use `-Wall` or not.  
It does not generate any binary as output.

Personally I prefer the clang approach, but either way, my problem is that I can't include `gsl` and compile with clang right now.

Both the linked `asio` and the macro approach at the top are possible solutions, used a bit everywhere.  
If you want a patch I'll try something tomorrow. I have never digged in your codebase, though.

**Comment by martinmoene** [comment]
Is there a reason to not also cover narrow's behaviour by `GSL_UNENFORCED_ON_CONTRACT_VIOLATION`, `GSL_THROW_ON_CONTRACT_VIOLATION`, `GSL_TERMINATE_ON_CONTRACT_VIOLATION`?

**Comment by neilmacintosh** [comment]
@martinmoene: nearly, but not quite.

I'm about to make one more comment that will slightly change the behavior. If `GSL_UNENFORCED_ON_CONTRACT_VIOLATION` is defined, then `throw_exception` should still throw. This won't affect `Ensures` and `Expects` but it will mean that `narrow()` always either throws or terminates (and only terminates when the user has said they don't want throwing behavior.

The reasoning here is that guaranteed enforcement is part of the contract of `narrow()`. That is the reason for its existence as a separate function from `narrow_cast()'.

**Comment by martinmoene** [comment]
@neilmacintosh You nicely describe [gsl lite](https://github.com/martinmoene/gsl-lite/blob/v0.21.0/include/gsl/gsl-lite.h#L771)'s behaviour :)

**Comment by ttshughes** [comment]
@martinmoene I think your right, I'm going to look into gsl lite, I'm shocked that a Microsoft provided support library cant even compile on codebase's without exceptions enabled two years after it was intialise produced and Microsoft maintainers are so hostile to fixing user issues which have been open for months. Thumbs down Microsoft.

**Comment by neilmacintosh** [comment]
Thanks for your feedback @ttshughes. I am sorry you think that I've been hostile to fixing user issues. If you can point to examples, I'd appreciate it. I didn't see any hostility on this particular issue thread. In fact, if I read back through it I thought I made it clear that I am happy to see the no-exceptions option adopted. If I understand @martinmoene correctly, it would be in a way that would match the options offered by gsl-lite.

If your complaint is that the PR hasn't gone through yet, then I would encourage you to look at resolving the merge conflicts (and one remaining comment) that prevented its adoption. 

An open source project like this one relies on community contributions to move forward. I have always tried to be clear that Microsoft does not provide any official level of support or funding for this code base (beyond hosting this repository and processing the CLAs for contributors).

**Comment by MikeGitb** [comment]
> I have always tried to be clear that Microsoft does not provide any official level of support or funding for this code base (beyond hosting this repository and processing the CLAs for contributors).

@neilmacintosh: That is actually interesting. Does that mean you guys are not getting payed for the time you spend on this library? If this is not an "official" MS-supported library, then shouldn't this repo be part of the [isocpp](https://github.com/isocpp) organization instead?

**Comment by neilmacintosh** [comment]
@MikeGitb This code was written (originally) by Microsoft employees. Microsoft uses this library internally. Microsoft employees maintain the repo currently, so it belongs where it is.

I get paid a salary to do lots of different things at Microsoft. For now, I can spend some of my time maintaining the repo. But there is no team dedicated to this repository, nor is it ever likely there will be. This is not a product we ship or provide warranty for. That's the point I'm trying to make here. This is an open source library. We find it useful within the company, we share the source freely and we hope others find it useful as well.

**Comment by MikeGitb** [comment]
Thanks for the clarification. I overlooked that "supported" has dual meaning here. Personally I would say that, if a company pays people for time spent on an OS project that company supports/funds the project just like Microsoft supports Linux when integrating hyper-v support into the kernel and just like Google and Apple (and MS?) support llvm.

The other meaning is of course that of e.g. Microsoft's support cycle for their paid products with the guarantee to provide bug fixes or be available for questions or even some legal liability, but that meaning didn't enter my mind for a library whose source files start with the usual disclaimer of

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, ...

Sorry for the OT post.

**Comment by thmxv** [comment]
So, is this a "won't fix" or are we waiting for someone to submit a patch? In case of the second, what solutions would be acceptable:
- Moddify the throw calls to use the current SL_TERMINATE_ON_CONTRACT_VIOLATION mechanism?
- Using macro (yuck) like in the OP or libstdc++?
- Using a template like the following (and like djarek) ?
`template <typename Exception>
[[noreturn]] void throw_or_abort(Exception&& ex)
{
#ifdef __cpp_exceptions
    throw ex;
#else
    printf("%s", ex.what());
    std::abort();
#endif
};`

Any of the case is, I supppose, pretty straightforward to implement and I am getting ready to do the job (I can't really wait anymore, I have to fix it or drop GSL) but would apreciate if I could recieve info on what approach would get a chance of upstream integration.

**Comment by leokolln** [comment]
Thanks for the support @neilmacintosh.
I see that there is a PR to fix this issue but is not merged. Is there something we can do to help fix or merge it?
Thanks again.

**Comment by annagrin** [comment]
Added support for no-exception mode in #640. Would be glad for any comments from folks who use it!

**Comment by TMLWinston** [comment]
Could we get assert() options?  There are cases where we do large data set movements and use legacy code.  Over time want to use narrow() etc to slowly find issues but cannot risk this when exceptions are tossed (no exceptions in system) and need to run, regardless of "bad" data calculations.  asserts would help during development and asserts can easily be disabled. Core files are more useful that exceptions in some cases.

**Comment by neilmacintosh** [comment]
@TMLWinston does building with GSL_TERMINATE_ON_CONTRACT_VIOLATION work for you, or are you asking for something different again?

**Comment by johnmcfarlane** [comment]
Can I ask why `narrow` throws instead of asserting? Surely out-of-bounds error on narrowing is a bug. As such, throwing is maybe not the best solution. Thanks.
