### ISSUE TITLE
empty/not_empty

### ISSUE THREAD

**Issue by NN---** [Microsoft/GSL#469]
Proposal to have the following type definitions:

```cpp
template<typename T> using empty = T;
template<typename T> using not_empty = T;
```

The purpose is to have clear intention for empty and not empty variable.
For instance:

```cpp
vector<int> f(bool fillVector)
{
 vector<int> x;
 if(fillVector) x.push_back(1);
 return x; // Did we forget push_back in 'else' ?
}
```

With 'empty<vector<int>> x;' , we state it to be empty initialized as good return value.
While writing 'not_empty<vector<int>> x;' means that we must do something with it before returning.

**Comment by maikel** [comment]
The "decorators" which you currently find in the GSL, `not_null` and `owner`, shall help for pointer and ownership semantics and are therefore somehow special to the [CppCoreGuidelines](https://github.com/isocpp/CppCoreGuidelines). While I think it is a good practise to state conditions in such decorators, there are hundred of other tags or "constrained value types" you could think of. So I have immediately two questions when I see such a proposal:

1. Why is `not_empty` not constrained as is `not_null`?
2. Why is `not_empty` more important than `not_negative` or many other possible constrains?

There are already several libraries which are made to easily create such types.

This GSL repository is also mainly an implementation of things proposed in the [CppCoreGuidelines](https://github.com/isocpp/CppCoreGuidelines). So if you really want more constrained value types in the GSL my best bet is to propose them to the guidelines instead. But I think the best place is an own dedicated library.

**Comment by NN---** [comment]
I see..
I will propose there.
Thanks.
