### ISSUE TITLE
Use a specific version of unittest-cpp

### ISSUE THREAD

**Issue by kylog** [Microsoft/GSL#47]
Currently the README says to clone https://github.com/Microsoft/unittest-cpp, which means a given SHA of GSL may produce different test results on different days if/as unittest-cpp gets new commits.

Two related questions then:
* can we use a git submodule to pin to a particular SHA of unittest-cpp? Or some other mechanism?
* is Microsoft going to maintain its fork of unittest-cpp or is it upstreaming its changes?

**Comment by neilmacintosh** [comment]
We are upstreaming the changes currently.

Sent from my Windows Phone
________________________________
