### ISSUE TITLE
Alias for  `span<const T>` ?

### ISSUE THREAD

**Issue by LYP951018** [Microsoft/GSL#482]
Many modern programming language chose const by default because we use more const objects than mutable ones. So does `span`. 80% of my usage of `span` are `span<const T>`. Should we introduce some type alias for `span<const T>`, like `cspan<T>` == `span<const T>`?

**Comment by neilmacintosh** [comment]
Thanks for the suggestion @LYP951018. I tend to agree that most span usage will probably follow your experience and involve a `const T` element type. However, I don't like the idea of a `cspan<T>` alias. In my mind, it actually hides the `const`-ness of the `T` and instead, incorrectly suggests it is the `span` that is `const`.

So at least for now, I think we'll let people create their own aliases if they like, but not add this additional one to the `gsl` namespace.
