### ISSUE TITLE
project not formatted as per .clang-format

### ISSUE THREAD

**Issue by tiagomacarios** [Microsoft/GSL#486]
Looks like a lot of the files are not formatted according to the .clang_format. Is this by design?
Some projects prefer to format as they go as not to "pollute" git blame. If this is not the case I can create a PR fixing the formatting issues.

**Comment by neilmacintosh** [comment]
The .clang-format file came along after we already had some source, and not everyone (me included) always remembers to format before check-in.

Personally, I'm ok with things drifting a bit here and there - it's just formatting ;-). If you are the sort of person who would like to see things tidied up, feel free to offer a PR that just fixes the formatting.

**Comment by neilmacintosh** [comment]
Thanks for the PR @tiagomacarios. I think this can now be closed out.
