### ISSUE TITLE
Update to Catch instead of UnitTest-cpp

### ISSUE THREAD

**Issue by rianquinn** [Microsoft/GSL#495]
I have an updated Travis CI script that adds Clang Format, Clang 3.9, Clang 4.0, and Git Check. Apparently, Clang 3.9 and Clang 4.0 have been broken for some time now as UnitTest-cpp segfaults with these compilers on it's own unit tests. 

To add to the issues with UnitTest-cpp, on my own project, UnitTest-cpp cannot compile at all on Cygwin, which means neither can the GSL which prevents automated testing with the GSL on AppVeyor Cygwin builds. We currently patch the GSL to remove UnitTest-cpp so that the GSL works in all environments (GCC, Clang, Cygwin and Windows). 

The simple solution is to move to Catch.hpp which is a simple, header only library that works in all of these environments. Furthermore, the syntax is very similar to UnitTest-cpp, so the diff will not be that large. Catch.hpp is also a much larger project with regular updates, while UnitTest-cpp hasn't been updated in 3 months. 

My Proposal:
- PR#1: Move to Catch.cpp, update unit tests
- PR#2: Update Travis CI script 

I already have PR#2 done, but I don't want to start PR#1 without a blessing from @neilmacintosh

**Comment by neilmacintosh** [comment]
Thanks for the issue @rianquinn! I'll do a little thinking on this and get back to you.

**Comment by CaseyCarter** [comment]
Just for another data point: I can also reproduce unittest's unit tests crashing with a double free for release compiles with clang 3.9, 4, and 5. I haven't had time to investigate the bug and file a proper report, but that is why I didn't enable clang 3.9 and 4 in my most recent update to the Travis CI script.

**Comment by tiagomacarios** [comment]
I faced the same issue last week and opened a ticket on the unittest-cpp github: https://github.com/unittest-cpp/unittest-cpp/issues/154

I thought about suggesting catch too. But restrained myself =)

**Comment by rianquinn** [comment]
yeah, I posted an issue with respect to this same code not compiling on Cygwin, and haven't gotten any feedback yet. The project doesn't seem to be be as supported as Catch.

**Comment by tiagomacarios** [comment]
I tried to figure out why it was crashing and from what I gathered it was crashing on Test::RunImpl(), but I did not figure out why exactly. Anyway, I agree with you. Even if we figured the problem I am not sure the PR process would go through. Seems like there is not much action going on over there.

If we move to a newer clang version I have a PR to add clang-tidy support to the build.

**Comment by rianquinn** [comment]
nice, we use Clang Tidy as well, and the GSL really needs it (minus obviously the core guideline tests). Code coverage would also be a great tool, but that would likely result in bit more work.

**Comment by tiagomacarios** [comment]
I can add coverage on Linux. I'll wait until #493 gets merged and when I have a couple of spare hours I'll do that.

**Comment by MikeGitb** [comment]
> nice, we use Clang Tidy as well, and the GSL really needs it (minus obviously the core guideline tests). 

Actually, I think the GSL should also pass the core guideline tests and only supress specific warnings at specific places.

**Comment by tiagomacarios** [comment]
Yeah if I run it with all checks on "-checks=*" I get two types of messages:

```
mnt/c/Users/Mac/GitHub/GSL/tests/strided_span_tests.cpp:626:40: warning: The right operand of '==' is a garbage value [clang-analyzer-core.UndefinedBinaryOperatorResult]
                    CHECK(section[idx] == expected[2 * i + 2 * j + k]);
                                       ^
/mnt/c/Users/Mac/GitHub/GSL/tests/strided_span_tests.cpp:634:44: note: The right operand of '==' is a garbage value
                    CHECK(section[i][j][k] == expected[2 * i + 2 * j + k]);
                                           ^
```

I think the above is incorrect. I ran it in the debugger and AFAICT it is never out of range, so I don't know why clang is complaining...

The other error is inside the "system" headers:

```
/usr/local/include/c++/v1/regex:5568:17: warning: Called C++ object pointer is null [clang-analyzer-core.CallAndMessage]
                __s.__node_->__exec_split(true, __s);
                ^
/mnt/c/Users/Mac/GitHub/GSL/tests/span_tests.cpp:1546:9: note: Calling 'regex_search'
        std::regex_search(s.begin(), s.end(), match, std::regex("F"));
        ^
```

**Comment by neilmacintosh** [comment]
Ok. Discussion on this thread appears to have wandered somewhat off-topic. clang-tidy and code coverage and other bits and pieces are really separate issues.

I've had a think and I'm definitely open to converting to use Catch. Using unittest-cpp was not driven by anything other than it being the first usable alternative I came across. 

If someone wants to put together a PR so I can understand what the delta to the tests looks like, I would appreciate it.
