### ISSUE TITLE
span.h no object file generated error when using warning treated as error

### ISSUE THREAD

**Issue by SpikeMelbost** [Microsoft/GSL#496]
------------------------------------------------------------
update: I can now see the problem.
including <gsl.h> after windows.h, windows #defines max.

Moving the <gsl.h> include above the windows.h include gets rid of that build error - but not sure if the #define of max will still potentially cause any issue?

-------------------------------------------------------------

I get the following error:
span.h(96): error C2220: warning treated as error - no 'object' file generated

when I include <gsl.h>
gsl is installed via NuGet in VS2015 and is up to date

further info from outputwindow:
packages\microsoft.gsl.0.1.2.1\build\native\include\span.h(96): warning C4003: not enough actual parameters for macro 'max'

**Comment by neilmacintosh** [comment]
Hi @SpikeMelbost, this is a known problem with the Windows SDK headers - they `#define` `min` and `max`.  Please see the answer to #291 for the workaround. I'll have to create a FAQ and add this one ;-)
