### ISSUE TITLE
make_span for array doen't pass N as span template parameter

### ISSUE THREAD

**Issue by ewoudvc** [Microsoft/GSL#497]
This sets span<T,N>::Extent to N, allowing for compile time checks, by for example gsl::copy.

I've created a branch on my fork of the GSL for your reference
https://github.com/ewoudvc/GSL/commit/c56e20907b355c143c7efae2f35e2504f40b3d26

**Comment by rianquinn** [comment]
yeah, that's my bad. Do you want to post a PR. If not, I can fix that.

**Comment by ewoudvc** [comment]
I'd like post a PR; will be my first.
How do I file one on your repo?

**Comment by ewoudvc** [comment]
I'll look into your guidelines for contributions in the morning

**Comment by galik** [comment]
* Create a fork of `GSL`.
* Make a branch for the change and make the change.
* GitHub will automatically present you with the option of creating a PR from your modified branch to the original repo you forked from.

**Comment by ewoudvc** [comment]
pull request accepted
