### ISSUE TITLE
maybe_null_dbg::operator== can be ambiguous in TestMaybeNullCasting

### ISSUE THREAD

**Issue by trebconnell** [Microsoft/GSL#50]
This is a regression caused by my pull request #46.  Can be reproduce by changing 
`template<class T> using maybe_null = maybe_null_ret<T>;`

to `maybe_null_dbg<T>;` and compiling.  TestMaybeNullCasting will fail to compile.

**Comment by trebconnell** [comment]
fixed

**Comment by neilmacintosh** [comment]
Thanks for fixing this.
