### ISSUE TITLE
gsl header missing gsl_algorithm

### ISSUE THREAD

**Issue by rianquinn** [Microsoft/GSL#500]
Is there any reason why the main gsl header is missing the gsl_algorithm header?

**Comment by MikeGitb** [comment]
I don't think so. I just forgot to include it there, when I originally added the header.

As the idea of adding more algorithms didn't really take of, the header could probably even be removed / merged into `span`.

**Comment by neilmacintosh** [comment]
Looks like pure oversight to me @rianquinn. I'd be happy to take a PR to move it (or I can do so when I get a moment).
