### ISSUE TITLE
gsl::dyn_array & gsl::stack_array not found

### ISSUE THREAD

**Issue by aminaramoon** [Microsoft/GSL#505]
Where are gsl::dyn_array, and gsl::stack_array ? I don;t find them in the include files

**Comment by MikeGitb** [comment]
AFAIK they don't exist (yet?).
Here is an older issue where they got mentioned by neilmacintosh as possible future additions:
https://github.com/Microsoft/GSL/issues/348

**Comment by neilmacintosh** [comment]
Hello @aminaramoon, you are correct in noticing that those two types do not have implementations yet in this implementation of the GSL. While they are useful types, we prioritized initial development of the types that are most significant in terms of usage.

I'd be happy to look at PRs to add either or both of these. `stack_array` in particular has some significant challenges for cross-platform implementation.
