### ISSUE TITLE
not_null<T>::operator* returns a copy of pointed object instead of a reference to it

### ISSUE THREAD

**Issue by alexey-malov** [Microsoft/GSL#517]
PR #513 added a dereference operator to not_null

However it returns a value instead of reference. The simplest example is:
```c++
int v = 42;
gsl::not_null<int*> p(&v);
*p = 43; // <========= error C2106: '=': left operand must be l-value
```
I added PR #516 that fixes it

**Comment by neilmacintosh** [comment]
Thanks for catching this @alexey-malov, your PR #516 should have fixed this.
