### ISSUE TITLE
not_null comparison

### ISSUE THREAD

**Issue by Amaroker** [microsoft/GSL#521]
This code causes compiler error C2678 in Visual Studio 2017. Why is that?

```
void test()
{
	struct A {};
	struct B : public A {} b;

	const B* pB{ &b }; 
	gsl::not_null<A*> pA{ &b };
	
	assert(pA == pB);
}
```

**Comment by JordanMaples** [comment]
Maintainers' call: Sorry for the delay. You would write this as `pA.get() == pB`. Thanks

**Comment by JordanMaples** [comment]
I'm providing a workaround. The bug is MSVC specific and isn't a problem with GSL.
