### ISSUE TITLE
Wrong multi_span constructor called when passing const std::array

### ISSUE THREAD

**Issue by VincentZalzal** [Microsoft/GSL#522]
When constructing a multi_span from a const std::array, the constructor for containers is called instead. This actually happens in the unit tests. This is caused by a wrong template parameter used in the function signature (compare it with the non-const std::array version).

**Comment by VincentZalzal** [comment]
Pull request has been submitted.

**Comment by neilmacintosh** [comment]
Thanks for the issue and PR @VincentZalzal!
