### ISSUE TITLE
CMakeLists.txt requires 2.8.7 but uses feature introduced in 3.1.3

### ISSUE THREAD

**Issue by EdgarWahn** [Microsoft/GSL#529]
target_sources is not available in 2.8.7 nor 3.0.2. Either change cmake_minimum_required to 3.1.3 or remove / replace that command.

**Comment by neilmacintosh** [comment]
Thanks for the warning @EdgarWahn, I'll update the minimum requirement text.

**Comment by neilmacintosh** [comment]
Fixed by #533.
