### ISSUE TITLE
Replace `Guide::details::SizeTypeTraits` with std::numeric_limits

### ISSUE THREAD

**Issue by trebconnell** [Microsoft/GSL#53]
array_view.h is already including <limits>, but doesn't seem to use it (string_view.h does).  Is there a reason for this helper?

**Comment by neilmacintosh** [comment]
Working from memory here...at least some of the contexts in which we use SizeTypeTraits in array_view require a compile-time value.

Not all of the currently supported platforms have a numeric_limits capable of providing a constexpr max() function that can meet that requirement.
