### ISSUE TITLE
Can span be put into a container like vector/array?

### ISSUE THREAD

**Issue by tlanc007** [Microsoft/GSL#530]
Is it possible for spans to be put into a vector or array?  Say one wants to do something like:

```
std::vector<int> a {1, 2, 3, 4};
std::vector <int> b {100, 200, 300};

std::vector <gsl::span <int> > range {gsl::make_span (a), gsl::make_span(b) };
```

In my use case, a, b, and range would all be considered immutable.  The intent of range is to perform iterator manipulation to access the underlying values in a particular sequence.

Any suggestions?

**Comment by neilmacintosh** [comment]
@tlanc007  There's no reason why you can't put `span` objects into a `vector` or `array`. The snippet you provided there demonstrates one perfectly reasonable way to do it.

**Comment by tlanc007** [comment]
@neilmacintosh : Yes.  Right you are.  I thought I had tested this particular case already and didn't think even that was working.  Sorry.

I had a more complex use case and the compiler was having trouble finding the right constructor.  But as this simple case works, there is hope and most likely, I am doing something silly on my end.

Thanks.
