### ISSUE TITLE
Useless constructor with const not_null<U>& parameter

### ISSUE THREAD

**Issue by gedamial** [microsoft/GSL#535]
The constructor

`constexpr not_null(const not_null<U>& other) : not_null(other.get())`

was introduced in [this commit](https://github.com/Microsoft/GSL/commit/e3fecbd1c5388a31b7d541009ed6081214458450) with the purpose of facilitating the conversion, and thus avoiding a call to `operator T()`

The problem is the constness of the parameter, which prevents this code from taking advantage of this constructor

```
not_null<Derived*> pd { new Derived{} } ;    
not_null<Base*> pb {pd};

not_null<int*> _i1 { new int{5} };
not_null<int*> _i2 {_i1};

// This will call it
const not_null<Slider*> sl { new Slider{} };
not_null<Box*> box { sl };
```

Is there any reason in particular?

**Comment by xaxxon** [comment]
why does the const cause an issue?   Can you be more specific?

**Comment by xaxxon** [comment]
It seems fine to me: https://godbolt.org/g/zgK7zA

**Comment by hsutter** [comment]
Sorry for the lag... following @xaxxon, I tried this repro and pasing the code seems to work: https://msvc.godbolt.org/z/hPM4E8
I'll close this as no-repro for now, but if I missed anything please let me know and we can reopen it. Thanks!
