### ISSUE TITLE
cppcon2016 gsl talk speaks of tags,releases, milestones

### ISSUE THREAD

**Issue by jdmairs** [Microsoft/GSL#537]
Its not clear to me how to tell if the daily commits have accumulated enough goodness that I should download a new "version" and upgrade.  

Last time I took a snapshot you hadn't moved to Catch...now you have.  Plus how do I tell what is shipping with VS2017 15.2 compared to the github?

Thanks!

**Comment by neilmacintosh** [comment]
I apologize, I am definitely behind on tagging things here. I have a couple of things left I want to fix then I'll declare a tag...real soon now ;-).

No GSL ships in Visual Studio 2017 15.2, so I'm not sure what you mean by wanting to compare that product release with the contents of this repository.

**Comment by jdmairs** [comment]
Sorry Neil I thought I was quoting your intent/direction directly from the CppCon video.  I was probably thinking of the Core Guidelines Checker.  I haven't gone outside my sphere of comfort to deal with Connect.  If I have questions issues regarding Core Guidelines Checker where do I submit those?  Hint: suppressing warnings from Boost headers.  Thanks!  BTW...great cppcon videos you give.  Looking forward to seeing  Beast Mode on Oakland this year on 3rd and 1.

**Comment by MikeGitb** [comment]
There was (is?) a version that could be downloaded via Niger. Is that still up to date?

@jdmairs: On windows I'd recommend using vcpkg instead of downloading it yourself. Unless of course you want to make it a got submodule.

**Comment by jdmairs** [comment]
@MikeGitb: I'm on an offline network so none of these package managers work very well.  I noticed gsl has a CMake dependency on git (to get catch) which prevents me from running the build.  I'm modifying the CMakelists and hand copying the catch.h file.  NodeJS has a package called npmbuild which builds on the node package manager (npm) that allows me to tar/zip up all the dependencies which is very handy.  It works for most things.

**Comment by solvingj** [comment]
Agree with original issue here.  Please implement semver and github releases or at least tags.

**Comment by MikeGitb** [comment]
> NodeJS has a package called npmbuild which builds on the node package manager (npm) that allows me to tar/zip up all the dependencies which is very handy. It works for most things.

I think vcpkg has something similar, but I've never used it: https://blogs.msdn.microsoft.com/vcblog/2017/05/03/vcpkg-introducing-export-command/

Whether that is easier to use than your manual solution is a different question.

**Comment by neilmacintosh** [comment]
I will admit that I have woefully failed to make progress on this front. I'm going to close this issue in favor of #595 so we don't have duplicates tracking what is essentially the same request.
