### ISSUE TITLE
CMake installs catch into top-level source dir

### ISSUE THREAD

**Issue by scurest** [Microsoft/GSL#538]
The `CMAKE_INSTALL_PREFIX` for catch [is set to](https://github.com/Microsoft/GSL/blob/be43c79742dc36ee55b21c5d531a5ff301d0ef8d/tests/CMakeLists.txt#L9) `${CMAKE_SOURCE_DIR}`. I believe the intention is to place the catch/catch.hpp file in the GSL/include directory. However, if GSL is built from another project with eg. `add_subdirectory`, `CMAKE_SOURCE_DIR` is the top-level source directory and not the GSL directory, so catch is installed in the wrong place (and can't be found by the tests, etc).

I'm using `${CMAKE_CURRENT_SOURCE_DIR}/..` instead.

**Comment by tiagomacarios** [comment]
Indeed that is a problem. I also find a bit weird to install a dependency back to the source code tree.
@rianquinn what do you think if we had a folder on the build tree where we would install the catch.cpp file instead?

```
list(APPEND CATCH_CMAKE_ARGS
    "-DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR }/dependencies"
    "-DNO_SELFTEST=true"
)

# add catch
ExternalProject_Add(
    catch
    PREFIX ${CMAKE_BINARY_DIR}/catch
    GIT_REPOSITORY https://github.com/philsquared/Catch.git
    GIT_TAG v1.9.6    
    CMAKE_ARGS ${CATCH_CMAKE_ARGS}
    LOG_DOWNLOAD 1
    UPDATE_DISCONNECTED 1
)

...

target_include_directories(gsl_tests_config INTERFACE
    ${CMAKE_BINARY_DIR }/dependencies
)
```

**Comment by rianquinn** [comment]
@tiagomacarios Yeah, I would definitely change that. That was for my testing when I created the PR and I must have forgot to move it back to the bin dir.  Your patch is very similar to what I normally do which can be seen here:
https://github.com/ainfosec/ci_helloworld/blob/master/CMakeLists.txt#L42
