### ISSUE TITLE
coordinate_facade doesn't verify ValueType is unsigned

### ISSUE THREAD

**Issue by trebconnell** [Microsoft/GSL#54]
coordinate_facade has a static assert with the string: "ValueType must be unsigned integral type!", but it doesn't verify that ValueType is unsigned.  If I change it to verify this it fails because array_view_tests use char.

**Comment by neilmacintosh** [comment]
The text in that static assert is confusing and should be removed. The intent of the design was to allow either signed or unsigned size_type in array_view (and its constituent types). There was a misunderstanding around this in early implementation, and it looks as though an artifact of this remains.
