### ISSUE TITLE
Creating a Span of length 0 is ambiguous

### ISSUE THREAD

**Issue by JonathanDCohen** [Microsoft/GSL#541]
The following code is ambiguous:

```
uint32_t a[] = {1, 2, 3};
span<uint32_t> s(a, 0);
```

Since the literal 0 is also a pointer, the compiler can't disambiguate between the pointer and length constructor and the two-pointer constructor.  The same issue exists, at least in MSVC 2015, even with expressions evaluating to 0 such as `+0` and `1-1`.

A zero-length span over an existing range is something reasonable to want, semantically.  One possible workaround might be to avoid the literal 0:

```
uint32_t a[] = {1, 2, 3};
span<uint32_t> s(a, std::ptrdiff_t{});
```

However this is clunky at best.  There are two solutions I considered here

First:
```
template <typename Pointer, 
          typename std::enable_if_t<std::is_constructible_v<pointer, Pointer>, int> = 0>
span(Pointer lastElem, Pointer lastElem);
``` 

This makes the above example correctly create a 0-length Span pointing to the array. It does, however make `span<int> s(nullptr, nullptr)` fail to compile, since std::distance doesn't work on nullptr_t.

Another solution is 

```
template <typename = void>
span(pointer firstElem, pointer lastElem);
```

This simply ranks the (now template) two-pointer constructor lower than the pointer-length constructor.

**Comment by JonathanDCohen** [comment]
Ping on this :)

**Comment by MikeGitb** [comment]
I'd vote for option two. 
A workaround is to first create a span over the full array and then create a subspan of size 0.

**Comment by CaseyCarter** [comment]
> A workaround is to first create a span over the full array and then create a subspan of size 0.

The workaround for this is to initialize from `(ptr, ptr)` instead of from `(ptr, 0)`. Unless, of course, `ptr` is also a literal `0` - in which case you should simply not do that.

I'm not saying that we *shouldn't* disambiguate these two constructors, I'm only pointing out that it's not terribly important to do so. The ambiguity only occurs when the second argument is a literal `0` which is not a common use case.

**Comment by neilmacintosh** [comment]
I don't really have strong opinions over which is the better SFINAE-path to take, so I'd be happy to look at a PR that tried the simpler of the two options. I certainly think it is reasonable to disambiguate the two (we've known about the ambiguity for a while, but as @CaseyCarter correctly points out, this is not really a frequently-occurring problem).

**Comment by neilmacintosh** [comment]
So, this issue has been open for a while. The ambiguity has been understood for some time (I think @CaseyCarter pointed it out a long time ago), but never considered particularly painful. Unless someone has a pressing need to fix this with some SFINAE magic, I'm going to close the issue...
