### ISSUE TITLE
Decorate function declarations to support their use in CUDA

### ISSUE THREAD

**Issue by eyalroz** [Microsoft/GSL#544]
Most of the GSL code is theoretically and practically usable when writing CUDA C++ code which runs on a GPU. But a function needs to be designated for such use. When compiling C++ as CUDA code, a function is by default CPU-only, having an implicit `__host__` designator; marking it `__device__` makes it on-GPU only, and marking it `__host__ __device__` means dual use (two separate compilations).

GSL Lite already [has decorations for CUDA support](https://github.com/martinmoene/gsl-lite/issues/18); would you consider adding them as well? Basically, it's just a macro which, when not compiling CUDA, expands to nothing. Here's what gsl-lite has:

```
#ifndef   gsl_api
# ifdef   __CUDACC__
#  define gsl_api __host__ __device__
# else
#  define gsl_api /*gsl_api*/
# endif
#endif
```

**Comment by neilmacintosh** [comment]
Thanks for the issue @eyalroz. I love the idea of people using GSL with CUDA, but I'm not crazy about the idea of having to decorate every function in the GSL with another macro. Plus I see that CUDA places restrictions on the use of exceptions. I think it's fair to describe CUDA as a specialized platform that requires use of non-ISO-standard C++. Such a platform is not really a target for this GSL implementation.

**Comment by eyalroz** [comment]
Well, at least for some of the GSL that can't really be the case. I mean, you can't seriously suggest that spans or bytes are not targeted at platforms with no support for exceptions... right?

**Comment by neilmacintosh** [comment]
@eyalroz that's not quite what I said. I pointed out (I think correctly) that CUDA uses both restrictions (and I gave exceptions as an example) and extensions (such as decorations on functions or pointers or data) that mean code written for it ends up as not-standard-C++. Fair enough, it's a specialized platform. My point is simply that specialized platforms that require use of non-standard C++ like that are not a target for this GSL implementation.

**Comment by neilmacintosh** [comment]
Closing this issue, as CUDA decoration is not a target for this GSL implementation at this time.

**Comment by eyalroz** [comment]
Nearly a year has passed, and I'll ask you (@neilmacintosh ) to reconsider.

Also - I'll point out, regarding your last comment before closing this issue, that:

1. GSL already uses macro-based decorations for different variants of the language: `GSL_EXCEPT`. I'd say another one (be it `gsl_api` or `GSL_HD` or what not) should not be that bad.
2. The decorations, do not make the code non-standards-compliant C++, as they translate into attributes which are simply interpreted in a certain way. It's true that CUDA does have non-standard syntax - but it's not relevant in this context. (Ok, I'm fibbing you a bit here; the macros expand to `__attribute__((device))` and `__attribute__((host))`, which is a compiler extension rather than the standardized `[[a]]` form for attributes. But - you have compiler-specific `#ifdef`ed code, so this should still be ok.)

**Comment by neilmacintosh** [comment]
@eyalroz I appreciate the request. The aim in this project is to - over time - reduce the use of macros down to zero. They should be seen as a temporary crutch while the implementation must support older compilers and language versions. So I think supporting CUDA would only be defensible if in the medium- to long-term that can be done without language extensions or macros.

With that said, from my perspective, CUDA is still not a platform target for this GSL implementation. However, I would defer to any of the Microsoft-employed project admins here - given this is a Microsoft repository - in case they think such support is important.
