### ISSUE TITLE
Consider to remove #pragma once, rational: C++ Core Guidlines SF.8

### ISSUE THREAD

**Issue by franzhollerer** [Microsoft/GSL#545]
Please have a look at this discussion:

https://github.com/isocpp/CppCoreGuidelines/issues/1019#issuecomment-320567823

As conclusio it might make sense to remove *#pragma once* from the GSL code.

**Comment by neilmacintosh** [comment]
Sure, sounds reasonable.

**Comment by paulsapps** [comment]
I don't think `#pragma once` should be removed as it helps prevent issues with clashing include guards or mismatched ones. Its also easier to use IMO.

**Comment by OvermindDL1** [comment]
> I don't think #pragma once should be removed as it helps prevent issues with clashing include guards or mismatched ones. Its also easier to use IMO.

Except it is most often used in conjunction with include guards, in addition `#pragma once` fails when the include exists multiple times in an overall build system (which happens far more often than one would really hope...  >.<).  It gains nothing over just using include guards by themselves.

**Comment by neilmacintosh** [comment]
@franzhollerer @paulsapps @OvermindDL1 I think it would be nice if we followed the Core Guidelines here....it just takes somoeone to put together the PR ;-)

**Comment by galik** [comment]
With regard to clashing include guards, I did check and they do not clash with the `Gnu Scientific Library (GSL)` header guards but wouldn't it still be more prudent to have longer names? For example rather than `GSL_BYTE_H` something like `GUIDELINE_SUPPORT_LIBRARY_BYTE_H`?

**Comment by paulsapps** [comment]
IMO requiring the longer names kinda highlights an issue with include guards. Ah well.. I'll just have to hope modules kills off heads ASAP ;)

**Comment by neilmacintosh** [comment]
Thanks everyone, #570  is in now and fixes this issue.
