### ISSUE TITLE
Some files use tabs others use spaces

### ISSUE THREAD

**Issue by trebconnell** [Microsoft/GSL#55]
'array_view.h' uses tabs 'gsl.h' uses spaces.  If my input matters I'd go with spaces :)

**Comment by neilmacintosh** [comment]
Yes, and it is annoying (and probably at least partially my fault).
Personally, I would go with spaces too but I think all that really matters here is that we are consistent.

If you want to submit a PR to correct this (I closed the previous one for an unrelated reason), it would be best to do so separately from any functional changes.

**Comment by tamaskenez** [comment]
What about clangformatting'em all? Maybe the admins could agree on a `.clang-format` file and add it to the repo.

**Comment by trebconnell** [comment]
I agree that an auto formatter would be useful.  I don't have experience with clang format, but have used others in the past with a good experience.

**Comment by neilmacintosh** [comment]
We do need consistency and will get there with future checkins.
