### ISSUE TITLE
not_null<shared_ptr> overhead

### ISSUE THREAD

**Issue by cconverse711** [microsoft/GSL#550]
What is the intended usage of not_null with std::shared_ptr? There is a significant overhead to wrapping std::shared_ptr in not_null because every access results in a costly copy of the shared_ptr.  As not_null cannot be used with unique_ptr, it seems that not_null is not really usable with smart pointers in general.

**Comment by janwilmans** [comment]
@neilmacintosh can this issue #550, #415 and #89 be closed now that not_null<smartptr> works?

**Comment by asfernandes** [comment]
> @neilmacintosh can this issue #550, #415 and #89 be closed now that `not_null<smartptr>` works? or is the support still debated?

Is the problem resolved or not?

**Comment by jwakely** [comment]
Using `shared_ptr` still results in lots of unnecessary copies, so I don't think this is resolved at all.

C++17 guaranteed elision helps with some of them, e.g. `not_null<shared_ptr<T>>::operator->` will be less expensive, but `operator*` still makes an unnecessary copy by calling `get()` (apparently just to avoid repeating the `Expects` check in `operator*`).

**Comment by hsutter** [comment]
Thanks for pinging this old issue, sorry for the lag.

I agree that’s reasonable, though I thought “POD” was deprecated these days in favor of “trivially copyable”? FWIW, personally, if I were writing the code I’d write this general type alias (name can be bikeshedded; this is copied from cppfront where I use this for "in" parameters and it's called [`in<T>`](https://github.com/hsutter/cppfront/blob/main/include/cpp2util.h#L365)):

```
template<typename T>
using value_access_t =
    std::conditional_t <
        sizeof(T) < 2*sizeof(void*) && std::is_trivially_copy_constructible_v<T>,
        T const,
        T const&
    >;
```

which is generally useful, and change `get()`’s return from

```
std::conditional_t<std::is_copy_constructible<T>::value, T, const T&>
```

to 

```
value_access_t<T>
```

Note this also solves the slight incongruence that right now the return value is sometimes `const` and sometimes not... here it's always `const`.

Caveat: I haven't tried it on `not_null`'s `.get()`.

What do you think?

**Comment by daschuer** [comment]
What is your reason for `sizeof(T) < 2*sizeof(void*)` ? 
Or will just `std::is_pointer` work?

**Comment by hsutter** [comment]
@daschuer Good question!

The direct answer is "generality": The decision to return by value or by `const&` here felt the same to me as for parameter passing. So I defaulted to using the same rule, which gives the right/expected result for raw pointers and `shared_ptr`, and didn't see a reason to invent a special rule.

The secondary answer is that I then saw doing it that way had (actual or potential) extra benefits:

- This way, as noted above, we got the `const` right for free. A minor improvement, but a nice one, and makes the use of the returned type more consistent.
- This way, other user-defined pointerlike types that are small and trivially copyable (maybe like `std::experimental::observer_ptr`? (*) ) will also naturally use the cheap copy -- if they happen to be indeed cheap to copy. We'll just do the right thing.

(*) I wonder if `observer_ptr` might go the same route as `string_view`... pre-C++23 `string_view` was not guaranteed to be trivially copyable, in C++23 it will be guaranteed to be trivially copyable. Right now `observer_ptr` is only required to be copyable, but not trivially copyable, so I wonder if it too will go through a similar evolution (if it's ever added to the standard), and this formulation will just do the right thing both ways. Generally, for any user-defined pointerlike type, the above formulation will just automatically do the right thing, and that seemed nice.

**Comment by daschuer** [comment]
Ah, thank you for explaination. 
So will you create a PR with this to solve the issue?

**Comment by dmitrykobets-msft** [comment]
@daschuer sorry for the delay - I'll make a PR to implement Herb's suggestion and resolve this issue.

**Comment by daschuer** [comment]
Cool, thank you.
