### ISSUE TITLE
Compilation errors. Werror=sign-conversion 

### ISSUE THREAD

**Issue by lonelyday** [Microsoft/GSL#553]
There are some sign conversion errors with new default value -Werror=sign-conversion on GCC. I do not know how to turn off this option so please fix it.
```
multi_span:1169:57: error: conversion to ‘long unsigned int’ from ‘long int’ may change the sign of the result [-Werror=sign-conversion]
     struct is_multi_span_oracle<strided_span<ValueType, Rank>> : std::true_type
```

edit:
It can be fixed with:
`-Wno-error=sign-conversion`
but nevertheless, this is something that ought to be fixed.

**Comment by neilmacintosh** [comment]
This is a known issue (see #525) and there is a PR currently open and being worked to fix it. Thanks for using the GSL and thanks for reporting it!
