### ISSUE TITLE
Add an extra details for 'fast_fail'

### ISSUE THREAD

**Issue by vglavnyy** [Microsoft/GSL#555]
Would it be possible to add extra details for 'fast_fail' exception?
Like std::error_code as 'fast_fail' member.
This is easily implemented using variadic macro and a second constructor for ‘fast_fail’.
Example:
`const std::error_code result1 = open();`
`Ensures( result1 == result_condition1, result1 );`
`const int wres = work();`
`Expects(0==wres);`
`const std::error_code result2 = close();`
`Ensures( result2 == false, result2 );`

**Comment by neilmacintosh** [comment]
I am sympathetic to why you woul like to do this. But the `fast_fail` exception is there as a convenience for people in environments that cannot simply `std::terminate()` immediately, or to ease testing. I wouldn't want to modify the `Expects`\`Ensures` interface in a way that makes it start to look more like a signalling than contract mechanism.
