### ISSUE TITLE
make_span error: could not match -1 against 6

### ISSUE THREAD

**Issue by tlanc007** [Microsoft/GSL#556]
```
#include <gsl/gsl>

template <typename T>
int doRangeStuff (const gsl::span<T>& data)
{
    return 0;
}

int main ()
{
    int arr[] {1, 3, 3, 9, 10, 4};
    auto sp {gsl::make_span (arr) };
    auto val {doRangeStuff (sp) };
}
```

The code above is giving the following error message:

```
span.cpp:14:15: error: no matching function for call to 'doRangeStuff'
    auto val {doRangeStuff (sp) };
              ^~~~~~~~~~~~
span.cpp:5:5: note: candidate template ignored: could not match -1 against 6
int doRangeStuff (const gsl::span<T>& data)
    ^
1 error generated.
```

I believe this use to work, but since updating to the latest GSL, I am getting this error under both Clang-5 and Clang-6 (under MacOS)

**Comment by CaseyCarter** [comment]
[`make_span` returns a span with static extent `N` when passed a reference to an array of extent `N`](https://github.com/Microsoft/GSL/blob/master/include/gsl/span#L633). Your `doRangeStuff` function only accepts spans with dynamic extent. If you want it to accept *all* spans, you need to deduce the extent as well as the element type:
```c++
template <typename T, std::ptrdiff_t N>
int doRangeStuff (const gsl::span<T, N>& data)
{
    return 0;
}
```

**Comment by tlanc007** [comment]
Ok.  Thanks for clearing that up.
