### ISSUE TITLE
gsl::span::size returns signed integer

### ISSUE THREAD

**Issue by Lectem** [microsoft/GSL#559]
Is there any rationale behind this ? Right now it returns an `index_type` which is `ptr_diff_t`,a signed type.
It is quite inconsistent with the rest of the standard library where `size()` returns unsigned integers (usually `size_t`), for example `std::vector`.

I know that many in the committee see the use of unsigned as an error of conception, but still I'd prefer it being consistent with the standard library.

**Comment by gdr-at-ms** [comment]
Yes, there is a rationale behind this, and it has been explained numerous times.  Please, use the search facility.

**Comment by Lectem** [comment]
Sorry, should have looked for it before. While I understand why it was chosen, I still think it's a pain.
Yes the standard library was wrong, but isn't the GSL made to work with it ?
If I can not use both together easily, I think it doesn't really make sense to use the GSL.

**Comment by mapron** [comment]
So, if current issue is now reopened, is it possible to reopen gsl::index issues? Not trolling.
I'm pretty annoyed I not able to use gsl::index examples because VC++ complaints for signed/unsigned comparison. And no, I could not just turn off that warning in our codebase.

**Comment by JordanMaples** [comment]
Maintainer's call: gsl::span is now unsigned following #844, so gsl::span::size returns unsigned values. For those who still require signed values, please use gsl::span::ssize.
