### ISSUE TITLE
gsl::span::operator== is not constexpr

### ISSUE THREAD

**Issue by sluser** [microsoft/GSL#560]
I tried to compare two gsl::spans in a static_assert condition, but was met with "non constant condition for static assertion" from GCC 7.2.0. Deeper into the error message, it seems the culprit is "call to non-constexpr function 'bool std::equal...".

gsl::span::operator== is implemented in terms of std::equal, but this is not a constexpr function even in C++17 (which I am using), and so operator== cannot be constexpr until implemented differently.

Edit: I believe the same issue applies to operator!= (obviously), but also operator<, operator<=, operator>, operator>= due to std::lexicographical_compare also being non-constexpr.

**Comment by neilmacintosh** [comment]
I'd be happy to look at a PR to resolve that limitation. We want `span` to behave as-if `std::equal` and `std::lexicographical_compare` are being called for those functions, and if there is a constexpr-friendly implementation that can do that, it would be worth looking at.

**Comment by sluser** [comment]
I agree with that approach. The std algorithms in question are actually proposed for constexpr-ing ([see here](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0202r2.html)), so perhaps it is best to wait for this change. 

Alternatively, I have found several implementations of constexpr forms of the algorithms, a couple are linked at the bottom of that proposal. Duplicating such an implementation inside gsl may not be desirable, though, because although the change to an existing implementation is pretty much "just add constexpr to the algorithm signature",  duplication seems like a good deal of effort.

Perhaps simply marking the affected parts of gsl with a comment would be sensible, particularly once the linked proposal is known to be approved for a particular standard?

**Comment by JordanMaples** [comment]
Closing since `std::lexicographical_compare` and `std::equals`, which are used in the span comparisons are constexpr in C++20.
