### ISSUE TITLE
`constexpr` `span` range access

### ISSUE THREAD

**Issue by johelegp** [Microsoft/GSL#573]
I'd like to mark `span`'s `begin`, `end`, `cbegin` and `cend` member functions with `constexpr` so I can use them in constant expressions.

Additionally, I believe `rbegin`, `rend`, `crbegin` and `crend` can be marked with `constexpr`, too, even though we support C++14, as that shouldn't be ill-formed. That's because, even though `std::reverse_iterator` (reverse.iterator C++14) can't be used in constant expressions as is, we're allowed to specialize `std::`'s templates if they depend on a UDT (namespace.std/1 C++14). As such, we could (for the sake of the explanation only; I'm not suggesting we do this) explicitly specialize it for `span`'s member iterators and make their member functions `constexpr` because we're allowed to (see note in dcl.constexpr C++14, or temp.expl.spec/5 C++14). Because it's possible to make such a specialization, the wording in dcl.constexpr/6 C++14 can never apply and the suggested changes remain well-formed. But maybe this is common knowledge among library developers?

Greetings,
Johel

- References:
  - **temp.expl.spec/5 C++14**: ... The definition of an explicitly specialized class is unrelated to the definition of a generated specialization. That is, its members need not have the same names, types, etc. as the members of a generated specialization. ...
  - **dcl.constexpr/6 C++14**: If the instantiated template specialization of a `constexpr` function template or member function of a class template would fail to satisfy the requirements for a `constexpr` function or `constexpr` constructor, that specialization is still a `constexpr` function or `constexpr` constructor, even though a call to such a function cannot appear in a constant expression. If no specialization of the template would satisfy the requirements for a `constexpr` function or `constexpr` constructor when considered as a non-template function or constructor, the template is ill-formed; no diagnostic required.

**Comment by neilmacintosh** [comment]
@johelegp thanks for the suggestions! They seem perfectly reasonable (in spirit) to me. I always like to see more `constexpr` wherever we can.

As you point out, there may be some standards-compliance issue here.  I'm certainly not an expert in "standardese", but know enough to always be nervous reading it. I'll run your suggestion past some colleagues who are more expert than me regarding the library parts of the standard and then update this issue appropriately.

**Comment by johelegp** [comment]
Sure! I'm looking forward to what they have to say about it, as I'm not sure either, hence saying "I believe..."

**Comment by neilmacintosh** [comment]
@johelegp You'll note that I've updated the span implementation so that they are all now `constexpr`. I checked with library implementers from Microsoft, and there is no standards-compliance problem here. So I'll close out the issue now.
