### ISSUE TITLE
<gsl/string_span> uses std::add_const without including <type_traits>

### ISSUE THREAD

**Issue by LegalizeAdulthood** [Microsoft/GSL#583]
Obviously the implementation is picking up <type_traits> indirectly from another thing that is included, but we should be explicit about including what we use in a header.

**Comment by paweldac** [comment]
maybe it would be a good idea to use https://github.com/include-what-you-use/include-what-you-use in GSL?

**Comment by LegalizeAdulthood** [comment]
That would improve things, but until then this PR fixes the immediate inconsistency.
