### ISSUE TITLE
Remove std::iterator inheritance from multi_span bounds_iterator

### ISSUE THREAD

**Issue by bjude** [Microsoft/GSL#587]
std::iterator has been deprecated with C++17 so compiling the GSL with c++17 enabled on MSVC spews a bunch of deprecation warnings.

All inheriting from std::iterator provides is some typedefs so a fix should be simple to implement.

**Comment by neilmacintosh** [comment]
Thanks for pointing out this issue @bjude. I'd be happy to look at a PR for this change.
