### ISSUE TITLE
Span size() broken on GCC > 5.4

### ISSUE THREAD

**Issue by ggajoch** [microsoft/GSL#590]
Simple failing case:

```
std::array<int, 10> array;
gsl::span<int> test1 = gsl::make_span(array);

static gsl::span<int> test2;
test2 = test1;
std::cout << test1.size() << " " << test2.size();
```

Gives output:
`10 0`

As far as I'm aware, both spans should point to the same `array`, with identical size (which in fact happens on gcc-5.4).

This issue occurs only when using different optimization option than `-O0` (`-Og`, `-O1`, `-O2`, `-O3`).

Tested on GCC 6.1, 6.2, 6.3, 7.1, 7.2, 7.3 (from https://godbolt.org/) - issue is identical.

Link to most-tailored case showing problem: https://godbolt.org/g/5u4XbD

A bit more sophisticated issue, showing that only assigning to static span, created earlier causes problem: https://godbolt.org/g/6AoWG3

I have tested where `begin()` and `end()` of each span was pointing to - they point at the same addresses, so even when size is incorrectly reported as 0, `begin()` and `end()` works fine.

I am aware that gcc >= 6 is not listed in supported platforms, so please close this issue if it is irrelevant.

**Comment by ggajoch** [comment]
For reference, after stripping down this snippet it turns out to be a gcc bug [1], affecting compiler versions from 6.1.0 onwards.
So, this issue can be closed or left open for future reference.

However, I tried and GSL tests passed successfully at gcc-6.3.0 on both `Debug` and `Release` targets.

Maybe it could be worth having test checking for this condition, so when the test pass we know that this is fixed? I could submit a PR if you are OK with that.

[1] - https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83116

**Comment by neilmacintosh** [comment]
Thanks for such a detailed investigation and write-up @ggajoch!

**Comment by ggajoch** [comment]
As a follow-up: this turned out to be a gcc bug, affecting every version above 5.4 - [[1]](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83116).
This bug was fixed now in the trunk, fixing GSL this test case as well [[2]](https://godbolt.org/g/L6uUaZ). Target milestone for gcc is 6.5.

[1] - https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83116
[2] - https://godbolt.org/g/L6uUaZ

**Comment by neilmacintosh** [comment]
I think it would be very useful to have a unit test that noticed whether the bug is present as @ggajoch suggested.

**Comment by Daniel599** [comment]
Hi, I would like to help adding this test.
The test fails on gcc-6.4 + release, should I disable the test for this config, or is there another option?

**Comment by annagrin** [comment]
@Daniel599 You can ifdef the test out based on gcc versions, only for the versions that fail, or better change the tests to expect failure for those versions, with a comment that this is a gcc bug

**Comment by Daniel599** [comment]
@annagrin can you look into my PR please? Is that what you meant?
Thanks.

**Comment by JordanMaples** [comment]
Maintainers' call: We believe this has now been fixed. Sorry about the delay.
