### ISSUE TITLE
Should gsl::span<T, N> (N != -1) be tuple-like like std::array ?

### ISSUE THREAD

**Issue by LYP951018** [microsoft/GSL#592]
1. consistent with `std::array<T, N>`;
2. Enable the usage of structured binding for `gsl::span<T, N>` (N != -1)

**Comment by neilmacintosh** [comment]
Thanks for the issue @LYP951018. I'm not sure exactly what you mean from that brief description. Can you elaborate? 

I suspect the answer in both cases should be "no" as `gsl::span` is a view, `std::array` and `std::tuple` are containers - and you can expect them to have different behaviors (especially with regard to structured bindings).

**Comment by JordanMaples** [comment]
Closing as `gsl::span`'s design is based on `std::span`'s design.
