### ISSUE TITLE
multi_span deprecated std::iterator class template

### ISSUE THREAD

**Issue by rsjaffe** [microsoft/GSL#599]
In the latest version of MS Visual C++, multi_span throws a whole bunch of the following warnings:

> Warning	C4996	'std::iterator<std::random_access_iterator_tag,Span::value_type,ptrdiff_t,_Ty*,_Ty&>': warning STL4015: The std::iterator class template (used as a base class to provide typedefs) is deprecated in C++17. (The <iterator> header is NOT deprecated.) The C++ Standard has never required user-defined iterators to derive from std::iterator. To fix this warning, stop deriving from std::iterator and start providing publicly accessible typedefs named iterator_category, value_type, difference_type, pointer, and reference. Note that value_type is required to be non-const, even for constant iterators. You can define _SILENCE_CXX17_ITERATOR_BASE_CLASS_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.

Does multi_span need revision to avoid using the std::iterator class template?

**Comment by neilmacintosh** [comment]
I thought this was fixed in PR #591. Are you sure you are using the latest GSL sources?

**Comment by rsjaffe** [comment]
**Argh!**

Here's another vote for versioning. I missed that this was fixed recently. I've now updated my copy and it's working fine.

**Comment by JordanMaples** [comment]
Maintainer's call: multi_span is deprecated, closing.
