### ISSUE TITLE
Succesful Build

### ISSUE THREAD

**Issue by z3ndrag0n** [Microsoft/GSL#600]
macOS High Sierra 10.13.2 (17C88)
Apple LLVM version 9.0.0 (clang-900.0.39.2)
(cmake version 3.8.1)

100% tests passed, 0 tests failed out of 12

(No source changes required.)

**Comment by neilmacintosh** [comment]
Thanks for the report @z3ndrag0n! I updated `README.md` to reflect the successful build.
