### ISSUE TITLE
Need help with using span for dynamic array.

### ISSUE THREAD

**Issue by jack17529** [Microsoft/GSL#603]
This comes in question category - 
How to put the parameters("<int, gsl::dynamic_range, 3, 4>") in GSL for this dynamic array -

`
int (*arr)[3][3] = new int[2][3][3];
for (int i = 0; i < 2; ++i)
{
   for (int j = 0; j < 3; j++)
   {
      for (int k = 0; k < 3; ++k)
      {
         arr[i][j][k] = k + j * 3 + i * 9;
      }
   }
}
 
gsl::span<int, gsl::dynamic_range, 3, 4> s1{ arr, 2 };
show(s1);  // prints 0 1 2 3 4 .. 17
 
delete[] arr;
`

**Comment by maikel** [comment]
AFAIK `gsl::span` is a one dimensional view. You might want to try `multi_span` or look for the current `mdspan` proposal. There is also Boost.MultiArray and if you need some linear algebra you could also consider using a specialised library like Eigen oder Blaze.

**Comment by jack17529** [comment]
So before  2016.03.07 multispan didn't existed .

**Comment by neilmacintosh** [comment]
Looks like this issue has been resolved now.
