### ISSUE TITLE
Checks in not_null.

### ISSUE THREAD

**Issue by john-preston** [microsoft/GSL#604]
Current implementation of not_null does checks (by Expects and Ensures):

- in every constructor (even if constructed from other not_null)
- in every dereference using any method (all go through get())

This could be an overhead in case you use not_null quite a lot and pass it everywhere by value and leave the Expects()/Ensures() checks even in the Release build (my case). Is this intended or should the check really be only in raw-pointer constructor?

I don't see any sense in those additional checks for not_null<raw_pointer> types, because they can't suddenly become null in the middle of their lifetime. If this is not intended I can prepare a PR with single check. It also should fix #535 because currently copy constructor is not used for non-const_ref not_null copies.

**Comment by xaxxon** [comment]
This is addressed in this PR https://github.com/Microsoft/GSL/pull/650

**Comment by beinhaerter** [comment]
Is there a reason to keep this open? As far as I can see it is solved.

```
    not_null(const not_null& other) = default;
    constexpr details::value_or_reference_return_t<T> get() const { return ptr_; }
```
