### ISSUE TITLE
Clang build fails with GSL_UNENFORCED_ON_CONTRACT_VIOLATION

### ISSUE THREAD

**Issue by aheysse** [Microsoft/GSL#607]
In our publish builds, we define GSL_UNENFORCED_ON_CONTRACT_VIOLATION. We've updated to the latest GSL and have since been hitting the issue below. I believe the solution is to declare the `span::length()` member function as `__attribute__ ((const))`, but I am not really sure due to me not being familiar with the clang language extensions. I believe this issue is caused by commit 16a6a416. 

We are using Clang 3.8 with the Android r13b NDK. We also have warnings as errors for reference.

[compilerlog.txt](https://github.com/Microsoft/GSL/files/1690385/compilerlog.txt)

**Comment by CaseyCarter** [comment]
"has side effects" in the warning message effectively means "calls a function" (See https://bugs.llvm.org/show_bug.cgi?id=32424). Clang's `__builtin_assume` doesn't seem to be usable as a general optimizer hint.

I think the fix here is to simply remove the `#ifdef __clang__` case from 16a6a41 and let clang use the GCC definition of `GSL_ASSUME`. I'll PR a fix.
