### ISSUE TITLE
Need help understanding.

### ISSUE THREAD

**Issue by jack17529** [Microsoft/GSL#609]
Here - https://github.com/Microsoft/GSL/blob/master/include/gsl/span#L124
What does the "&" do in the end of line ?

**Comment by beinhaerter** [comment]
There is no "&" in line 124, but one in line 123.
It means "reference" to the type on the right side of the "&".
As the type name suggests: it is a reference to an element_type_ or to a const element_type_.

**Comment by jack17529** [comment]
Sorry , but there is nothing on the right of "&".
Did you mean left ?
Did you mean that "reference" gives the reference to the element , which is classified by IsConst ?

**Comment by beinhaerter** [comment]
Yes, I meant "left" and corrected my last comment.
"std::conditional_t<IsConst, const element_type_, element_type_>" gives either "const element_type_" or "element_type_", depending on IsConst. And the trailing "&" adds a reference to the type that the std::conditional_t gave you.

**Comment by neilmacintosh** [comment]
Has this resolved the question for you @jack17529? It looks like we can close the issue now.
