### ISSUE TITLE
Library structure doen't reflect one described in CppCoreGuidelines

### ISSUE THREAD

**Issue by paweldac** [microsoft/GSL#623]
Hi,

in CppCoreGuidelines there is a paragraph about proposed component split for GSL: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#gsl-guideline-support-library

Currently GSL implementation is not following CppCoreGuidelines proposal. What is more current implementation extends CppCoreGuidelines ex. multi_span. Should it be kept in same namespace or maybe add `gsl::extensions` to inform library user that other implementations may lack some of functionality. @neilmacintosh please comment.

**Comment by neilmacintosh** [comment]
The component split described in the Core Guidelines is not necessarily describing a header structure. It describes logical components of the library. We'll probably iterate further on the header structure here in time. Personally, I think the right time to look at more closely adopting that "component structure" in a physical sense is when we get a modules system in the language.

`multi_span` can stay as-is. It is really not an extension. It was renamed to prevent it from conflicting with existing `span` while we concentrated on the single-dimension case (the vast majority of usage). There is nothing preventing a multidimensional span from existing within the GSL. It was always envisioned that there would be support for both kinds of views. Indeed, there is a multidimensional view type currently proposed for standardization and it is broadly compatible with `span`. My feeling is that once that type is finalized (including its name) we will most likely modify multi_span to match it.

**Comment by hsutter** [comment]
Maintainers' call: Sorry for the delay in replying. Yes, we've now deprecated or removed many of these extensions. Thanks!
