### ISSUE TITLE
Using not_null with function pointers

### ISSUE THREAD

**Issue by DrPizza** [microsoft/GSL#626]
Hello.

The Core Guideline checks currently detect if a function pointer is used without being tested for null, as if it were any other kind of pointer. That seems reasonable enough. Using not_null for a function pointer also seems reasonable as a response. After all, if the function pointer is mandatory and truly cannot be null, we should trap that the same way as any other never-null pointer.

There isn't, however, any `operator()` overload to make using the function pointer easy. I think as an improvement, not_null<function pointer> should offer an operator() overload (and possibly remove the -> overload).

Alternatively, not_null should reject attempts to instantiate it with a function pointer.

**Comment by MikeGitb** [comment]
Maybe you could create a partial specialization for function pointer type.

**Comment by xaxxon** [comment]
If people like it I can merge this to my existing PR, but this seems orthogonal enough that I don't want to have it block my currently agreed on changes from getting through.

**Comment by JordanMaples** [comment]
Maintainers' call: Sorry for the delay in replying to this issue. The design of `not_null` is for pointers to objects and for standard smart pointers, which do not support pointers to functions. For any changes to be made to not_null, an extension request for not_null needs to be made in the Core Guidelines. Thanks.
