### ISSUE TITLE
gsl/gsl

### ISSUE THREAD

**Issue by Zari65** [Microsoft/GSL#643]
https://github.com/Microsoft/GSL/blob/d846fe50a3f0bb7767c7e087a05f4be95f4da0ec/GSL.natvis#L98

**Comment by beinhaerter** [comment]
@Zari65 Can you please elaborate!? At least for me neither the title nor the linked line in GSL.natvis are sufficient to understand what the issue is.

**Comment by annagrin** [comment]
closing since there is no clarification
