### ISSUE TITLE
Comparisons between spans of different extents?

### ISSUE THREAD

**Issue by HertzDevil** [microsoft/GSL#648]
Currently, separate extent template parameters are used for the left and right operands of `span`'s `operator==`:

```cpp
template <class ElementType, std::ptrdiff_t FirstExtent, std::ptrdiff_t SecondExtent>
constexpr bool operator==(span<ElementType, FirstExtent> l,
                          span<ElementType, SecondExtent> r);
```

This is not so for `operator!=`:

```cpp
template <class ElementType, std::ptrdiff_t Extent>
constexpr bool operator!=(span<ElementType, Extent> l,
                          span<ElementType, Extent> r);
```

And not so for the remaining comparison operators either:

```cpp
template <class ElementType, std::ptrdiff_t Extent>
constexpr bool operator<(span<ElementType, Extent> l,
                         span<ElementType, Extent> r);
template <class ElementType, std::ptrdiff_t Extent>
constexpr bool operator<=(span<ElementType, Extent> l,
                          span<ElementType, Extent> r);
template <class ElementType, std::ptrdiff_t Extent>
constexpr bool operator>(span<ElementType, Extent> l,
                         span<ElementType, Extent> r);
template <class ElementType, std::ptrdiff_t Extent>
constexpr bool operator>=(span<ElementType, Extent> l,
                          span<ElementType, Extent> r);
```

The [change](https://github.com/Microsoft/GSL/commit/c366f4415d581b03e2a900cf36c40e830cd05bf9#diff-eb77e61d0ec515ec6c4fe1b4e2c07beaL651) to only `operator==` was done over a year ago. [P0122](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0122r6.pdf), which has been voted into C++20, does not have this treatment for `operator==` at all. Was there a rationale behind (not) allowing different extents for the operands?

***

Related: What about separate element types? In particular it is rather cumbersome to compare spans when one of them is `span<T>` and the other is `span<const T>`:

```cpp
std::byte my_buffer[1024] = { };
// std::array<std::byte, 1024> my_buffer = { }; // gsl::make_span will not deduce the extent

void update_my_buffer(gsl::span<const std::byte, 1024> samples)
{
    if (samples != gsl::make_span(std::as_const(my_buffer)))
    {
        gsl::copy(samples, gsl::make_span(my_buffer));
    }
}
```

Compare to:

```cpp
    if (auto my_span = gsl::make_span(my_buffer); samples != my_span)
    {
        gsl::copy(samples, my_span);
    }
```

Or simply repeating the definition of `span`'s comparison operators:

```cpp
    auto my_span = gsl::make_span(my_buffer);
    if (!std::equal(samples.begin(), samples.end(), my_span.begin(), my_span.end()))
    {
        gsl::copy(samples, my_span);
    }
```

Or even:

```cpp
    if (!ranges::equal(samples, my_buffer))
    {
        ranges::copy(samples, my_buffer);
    }
```

If these more generic solutions work and possibly express the intent of the code clearer, does `span` really need the same-type same-extent comparison operators? P0122 makes no mentions of this. Is this an early design decision?

**Comment by robwiss** [comment]
I ran into the same difficulty w/ comparing `span<const T>` and `span<T>`

I'm not sure if this is the best way to do it but it's fairly easy to extend the library to allow the comparison:
```c++
// this is to let operator== compare a span<const T> with a span<T>
namespace gsl {
template <class ElementType, std::ptrdiff_t FirstExtent, std::ptrdiff_t SecondExtent>
constexpr bool operator==(span<ElementType, FirstExtent> l, span<std::remove_const_t<ElementType>, SecondExtent > r) {
  return operator==(l, span<std::add_const_t<ElementType>, SecondExtent>(r));
}
template <class ElementType, std::ptrdiff_t FirstExtent, std::ptrdiff_t SecondExtent>
constexpr bool operator==(span<ElementType, FirstExtent> l, span<std::add_const_t<ElementType>, SecondExtent > r) {
  return operator==(span<std::add_const_t<ElementType>, FirstExtent>(l), r);
}
} // namespace gsl
```

**Comment by jack17529** [comment]
@neilmacintosh can you please link the " post-Jacksonville WG21"?

**Comment by MikeGitb** [comment]
Wasn't the last decision for std::span to not have comparison operators at all (I guess due to perceived ambiguities about the semantics)?

**Comment by neilmacintosh** [comment]
@jack17529 @MikeGitb's comment is correct: there are no comparison operators on `std::span` in the latest draft.

**Comment by jack17529** [comment]
@neilmacintosh then why don't we just close this one and assign this guy named "jack17529" an actual issue on "span" which he can send a PR?

**Comment by MikeGitb** [comment]
Well, I guess, the comparison operators could still use a work over. At least they should be made consistent or outright removed. While the latter may be in line with std::span it is also a breaking change. Not sure what the maintainers view on this is.

**Comment by JordanMaples** [comment]
Maintainers' call: Sorry for the delay. Now that span has been standardized, the only delta between gsl::span and std::span is the bounds checking. We are following the standard interface exactly.
