### ISSUE TITLE
Should not_null act like an alias

### ISSUE THREAD

**Issue by trebconnell** [Microsoft/GSL#65]
Right now it's implemented like a smart pointer, with method like get(), but if I'm reading the isocpp guidelines correctly it should act like an alias.  Given that it's under [GSL.Views](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#gslview-views) with `owner` and not GSL.Owner with the smart pointers.

`template <class T>
using not_null = T;`

**Comment by trebconnell** [comment]
The thinking behind the guideline being that you may want to use these types on an ABI interface.  Having them be a class at all would prohibit this.  Is the plan to replace the dbg checking of these types with the static analysis and change them into aliases in the long-term?

**Comment by gdr-at-ms** [comment]
We actually `not_null` to be a distinct type.  It has an invariant deterministically expressible and cheap to enforce.
