### ISSUE TITLE
warning C26432 for finally

### ISSUE THREAD

**Issue by beinhaerter** [Microsoft/GSL#653]
VS2017 15.6.5 warns on gsl::finally:
>...\gsl\include\gsl\gsl_util(65): warning C26432: If you define or delete any default operation in the type 'class gsl::final_action<class <lambda_b98e0a8125d64b00f0a5ab4dae984c3e> >', define or delete them all (c.21: http://go.microsoft.com/fwlink/?linkid=853922).

The warning goes away when adding

    final_action& operator=(final_action&&) = delete;

Do you want me to create a PR to add this line? Or do you prefer another way of getting rid of this warning?

**Comment by xaxxon** [comment]
Looks reasonable to me, but I'm not a decision maker.   I'd suggest submitting the PR.
