### ISSUE TITLE
Support use as_bytes for basic_string_span

### ISSUE THREAD

**Issue by gicutza** [microsoft/GSL#655]
gsl::cwzstring_span<> v(L"qwerty");
auto r = gsl::as_bytes(v.as_string_span());
doesn't compile on VC++2017 (v141) (/stdc++ 17) version 15.6.5

I think there is no as_bytes implementation for gsl::basic_string_span.

**Comment by beinhaerter** [comment]
It looks like adding these lines would allow your code to compile.

```
template <class ElementType, std::ptrdiff_t Extent>
basic_string_span<const byte, details::calculate_byte_size<ElementType, Extent>::value>
as_bytes(basic_string_span<ElementType, Extent> s) noexcept
{
	return { reinterpret_cast<const byte*>(s.data()), s.size_bytes() };
}
```

@neilmacintosh Is this a desired change? Shall I prepare a PR? If yes I'd also add `as_writeable_bytes`. Side note: for `basic_string_span` there is `to_string` and `to_basic_string`, but not for `basic_zstring_span`. Is that on purpose or should these be added, too?

**Comment by beinhaerter** [comment]
Please see PR #683. I added `as_bytes` and `as_writeable_bytes` and unit-tests for both.
Since there was no comment/answer regarding `to_string` and `to_basic_string`, I did not add them to `basic_zstring_span`.

**Comment by JordanMaples** [comment]
Closing this because `as_bytes` support for `basic_string_span` was added in #683.
