### ISSUE TITLE
`span`'s constructors should use `addressof`

### ISSUE THREAD

**Issue by LYP951018** [microsoft/GSL#661]
I was trying to construct a `span<ComPtr<T>>` from `array<ComPtr<T>, N>` and then I got tons of compilation errors ... Then I found `ComPtr` overloads `operator&` which returns `Details::ComPtrRef<ComPtr<T>>` and `span`'s constructors for arrays rely on `&arr[0]`, which leads to the error.

Maybe I could submit a pr for this? :)

**Comment by LYP951018** [comment]
It seems that `std::data` is enough? But I suspect some versions of VS2015 don't support it.

**Comment by maikel** [comment]
I don't think this library relies on C++17 library features like `std::data`.

And if we keep `constexpr`ness in mind things aren't that easy. Before C++17 `std::addressof` is not `constexpr` but the constructor at question is declared as such. Furthermore, IIRC `addressof` needs compiler intrinsics to be `constexpr` in all cases, which complicates things.  If you make a PR please consider that. A simple possible pre-c++17 patch would be to SFINAE on the `element_type` and declare the conversion constructor non-constexpr for types with an overloaded `operator&` method.

**Comment by LYP951018** [comment]
@maikel It seems that for `std::array`, `std::array::data` is sufficient. As for C array, we could write our `data` like function instead.

**Comment by LYP951018** [comment]
It seems that we could simply decay the C array:
```cpp
    template <std::size_t N>
    constexpr span(element_type (&arr)[N]) noexcept
        : storage_(KnownNotNull{arr}, details::extent_type<N>())
    {
    }
```

**Comment by LYP951018** [comment]
WTF? It seems that `std::array::data` isn't constexpr until C++ 17...

**Comment by annagrin** [comment]
@LYP951018, @maikel Are you interested in submitting a PR?

**Comment by JordanMaples** [comment]
Maintainers' call: Belatedly closing this issue.
