### ISSUE TITLE
Your byte implementation is unsafe under optimisation on GCC and clang

### ISSUE THREAD

**Issue by ned14** [Microsoft/GSL#663]
The C++ 20 standard defines `std::byte*` to have the same may-alias properties as `char*`.

Your byte implementation therefore needs to be marked up with `__attribute__((__may_alias__))` on GCC and clang compilers to tell the compiler that it must not assume that `byte*` cannot alias a pointer to a different type.

**Comment by neilmacintosh** [comment]
Sounds pretty reasonable to me. I'm guessing that's only necessary if someone is running without the `-fno-strict-aliasing` switch? Does anyone want to put together a PR?

**Comment by xaxxon** [comment]
> only necessary if someone is running without the -fno-strict-aliasing switch

What was the point of calling that out?

**Comment by martinmoene** [comment]
@xaxxon See the disscussion at PR #390.

**Comment by xaxxon** [comment]
> a note to the readme, recommending to use the -fno-strict-aliasing flag on gcc and clang.


Just to be clear, we're not suggesting anyone prefer to flags to enable extensions to use non-standard c++, right?

**Comment by martinmoene** [comment]
It's C++17 behaviour, see 
- [N4659 sec 6.10, p8.8, page 84](wg21.link/n4659#page=84)
- [std::byte on cppreference.com](http://en.cppreference.com/w/cpp/types/byte)
- [Has a std::byte pointer the same aliasing implications as char*?](https://stackoverflow.com/questions/43551665/has-a-stdbyte-pointer-the-same-aliasing-implications-as-char) on StackOverflow.

**Comment by martinmoene** [comment]
Ah, had the impression you were referring to `__attribute__((__may_alias__))`.

**Comment by ned14** [comment]
Strict aliasing has been on by default in GCC for a very long time at -O2 and above. clang gained the same maybe four or five years ago. MSVC once had opt-in strict aliasing a long time ago, but they removed it and its magic compiler options.

In any case, on GCC and clang, `__attribute__((__may_alias__))` needs to be applied to the `byte` type, else the compiler will hard assume it will never alias unrelated types, which is exactly what `byte` is for!

**Comment by jack17529** [comment]
@neilmacintosh I think there is some issue regarding your Facebook link on your profile.
I am sorry but this nowhere related to the issue.
I too wanted to talk privately  regarding GSL

**Comment by neilmacintosh** [comment]
@xaxxon I was simply asking a question, not "calling anything out". I wanted to understand the situations that would/wouldn't expose people to the problem that was being reported.

Both `-fno-strict-aliasing` and `__attribute__` are language extensions as far as I am aware.  Both are options for getting something like the behavior of C++17 `std::byte` if you don't yet have native support for it in your toolchain. So far, the attribute sounds like the path with less side-effects.

@jack17529 If you would like to contact me directly, I can be reached at neilmac@fb.com.

**Comment by StephanDollberg** [comment]
Have ported @martinmoene's patch and opened a PR.
