### ISSUE TITLE
not_null used with nullptr leads to empty function with GSL_UNENFORCED_ON_CONTRACT_VIOLATION (gcc)

### ISSUE THREAD

**Issue by kivadiu** [microsoft/GSL#666]
This small program was just to confirm that with macro `GSL_UNENFORCED_ON_CONTRACT_VIOLATION` defined, the behaviour of not_null is transparent. But it has a very strange behaviour on linux x86_64 with g++ 7.3.0: if block 1 is present in the source, main is empty. If block 1 is absent, main contains block 2.
With -O0, it works as expected:
not_null == 0
not_null == 0x655c20

With -O1 or greater, main is empty.

Why?

```
// g++-7.3.0 -o x -DGSL_UNENFORCED_ON_CONTRACT_VIOLATION -std=c++14 -O1 -g3 -I. x.cpp

#include <gsl/pointers>

#include <iostream>
#include <memory>

void f(gsl::not_null<int*> p) { std::cerr << "not_null == " << p << '\n'; }

int main(int argc, char** argv)
{
    { // block 1 -> if uncommented, main is empty, program does not fail but produces nothing
        int* n = nullptr;
        gsl::not_null<int*> not_null = n;
        f(not_null);
    }
    { // block 2
        auto n = std::make_unique<int>(1);
        gsl::not_null<int*> not_null = n.get();
        f(not_null);
    }
    return 0;
}

```
I tested version d25969dbdfc3fe144baf60165d0850861afef45c

**Comment by CaseyCarter** [comment]
`GSL_UNENFORCED_ON_CONTRACT_VIOLATION` doesn't mean the contracts no longer *exist*; it means that they won't be checked. Consequently a program that violates a contract has undefined behavior when `GSL_UNENFORCED_ON_CONTRACT_VIOLATION` is defined.

Since `main` unconditionally executes a construct with undefined behavior in block 1 (`gsl::not_null<int*> not_null = n;`) GCC assumes that it must never be called and optimizes the body away as dead code.

**Comment by kivadiu** [comment]
Is it because of __builtin_unreachable?

**Comment by CaseyCarter** [comment]
Yes, `__builtin_unreachable` is used to implement UB on contract violation on GCC. (MSVC uses `__assume`.)

**Comment by kivadiu** [comment]
I have never had such an issue with assert. Is that different?

**Comment by kivadiu** [comment]
I have never had such an issue with assert. Is that different?

**Comment by CaseyCarter** [comment]
Yes: `assert` is effectively a conditional contract that goes away when `NDEBUG` is defined. This can cause weird performance characteristics when the contract provides information which an optimizer can use to produce better code: it's possible for code to *slow down* when you define `NDEBUG`.

The design intent of C++ contracts as embodied by both the GSL and the ongoing WG21 Contracts proposals is that contracts are always in effect and that a program which violates an unchecked contract has UB exactly as does a program which decides to continue running after discovering violation of a checked contract. This has the desirable effect of reducing variance in the quality of the generated non-contract-checking code.

**Comment by kivadiu** [comment]
I am not fully sure I understand the implications:
For example, in `span<T>::operator[](index_type idx) const`, I find
`Expects(idx >= 0 && idx < storage_.size());`
Are you saying that this condition is always evaluated, even if I define `GSL_UNENFORCED_ON_CONTRACT_VIOLATION`?
This would be a high cost penalty in release mode compared to
`assert(idx >= 0 && idx < storage_.size());`

**Comment by CaseyCarter** [comment]
Yes, the condition is always evaluated, and [no there is no cost](https://godbolt.org/g/kcJRvA) when the compiler can see that the evaluation has no side effects. One nice consequence is that unlike with `assert`, you never need to silence "unused parameter" warnings for parameters that are only used in contracts.

**Comment by kivadiu** [comment]
Your statement seems magic to me. To make it non magic, this is how I understand it:
1. if the compiler can check at compile time the Expects statement, all the code is removed,
2. if the compiler does not know where the index comes from, he cannot evaluate the Expects at compile time and there is a code added for the check which will have some cost associated. This would be the case if the function using the span and the int i is defined in a different translation unit as the one using it.

If this is what happens, there may be some overhead in case 2.

However in the example you show, nothing is done at runtime. Why?
The function does not know anything of i so how can you say the Expects is always checked?
I must have missed something.

**Comment by kivadiu** [comment]
OK, now I see what you mean. Thanks for your patience and kindness.
I am curious to see if this does not prevent vectorization. I will give it a try.

**Comment by JordanMaples** [comment]
Maintainer's call: Closing issue as GSL_UNENFORCED_ON_CONTRACT_VIOLATION no longer exists. Contract violation now only results in termination.
