### ISSUE TITLE
[span] Constructor taking Container const & must not participate in overload resolution for std::array

### ISSUE THREAD

**Issue by martinmoene** [microsoft/GSL#670]
`span`'s [constructor taking a const & container](https://github.com/Microsoft/GSL/blob/2fc94db3ebfb1b066edeafac1837f34d6111bff4/include/gsl/span#L399) does not not (!) participate in overload resolution for `std::array` as the [constructor  taking a non-const & container](https://github.com/Microsoft/GSL/blob/2fc94db3ebfb1b066edeafac1837f34d6111bff4/include/gsl/span#L389) does do.

Solution: add `!details::is_std_array<Container>::value &&` to the condition of `std::enable_if_t`.

See page 16 of proposal [p0122r6](http://wg21.link/p0122r6).

**Comment by martinmoene** [comment]
That condition of `std::enable_if_t` possibly also misses 
```C++
std::is_same<typename Container::value_type, std::remove_const_t<element_type>>::value
```

**Comment by martinmoene** [comment]
To have it explicitly stated, does you remark address 1) GSL's span, 2) proposal p0122r6, 3) both?

**Comment by MikeGitb** [comment]
@martinmoene: I'm talking about the current implementation of microsoft's gsl::span. 
I didn't have a close look at the proposal yet.

**Comment by neilmacintosh** [comment]
@MikeGitb I'm sure there's better ways to express the SFINAE for `span` constructors. However, I think the current goal should be to ensure the behavior of the constructors matches the proposal that was adopted into the C++ Standard Working Draft. That will provide plenty of opportunity to correct/simplify any checks.

**Comment by CaseyCarter** [comment]
P122R6 is out-of-date here: we changed a ton of the constraints in JAX. [P0122R7](https://wg21.link/p0122r7) is what was moved [into the working draft](http://eel.is/c++draft/views).

And yes, GSL hasn't yet implemented all of the R7 changes.

**Comment by martinmoene** [comment]
Thanks @CaseyCarter , missed the advent of r7.

**Comment by JordanMaples** [comment]
Maintainers' call: Sorry for the delay. Now that span has been standardized, the only delta between gsl::span and std::span is the bounds checking. We are following the standard interface exactly.
