### ISSUE TITLE
Broken test for constexpr support

### ISSUE THREAD

**Issue by dcleblanc** [microsoft/GSL#671]
You have this - 

#if _MSC_VER < 1910
#pragma push_macro("constexpr")
#define constexpr /*constexpr*/
#define GSL_USE_STATIC_CONSTEXPR_WORKAROUND
#endif                          // _MSC_VER < 1910
#else                           // _MSC_VER
// See if we have enough C++17 power to use a static constexpr data member
// without needing an out-of-line definition
#if !(defined(__cplusplus) && (__cplusplus >= 201703L))
#define GSL_USE_STATIC_CONSTEXPR_WORKAROUND
#endif // !(defined(__cplusplus) && (__cplusplus >= 201703L))
#endif                          // _MSC_VER

Which will fail, because Visual Studio doesn't correctly set __cplusplus value.

A correct, cross-platform way to do this can be found in https://github.com/dcleblanc/SafeInt/commits/master/SafeInt.hpp from lines 19-128

I don't assert that my approach in SafeInt is ideal, but it definitely works, I've tested it.

**Comment by CaseyCarter** [comment]
There is (or at least "was" and "ought to still be") a `#ifdef _MSC_VER` before that entire block so that it never examines `__cpluspus` when `_MSC_VER` is defined.

**Comment by CaseyCarter** [comment]
* GSL doesn't support VS before 2015

* This:
  ```c++
  // See if we have enough C++17 power to use a static constexpr data member
  // without needing an out-of-line definition
  ```
  indicates that the code in question is only concerned about whether or not it must provide an out-of-class body definition for a `static constexpr` data member. C++17 deprecates such definitions. Consequently, it's not interested in the distinction between `constexpr` in C++11, C++14, and C++17 (which incidentally added `constexpr` lambdas, causing the value of `__cpp_constexpr` in [P0096](https://wg21.link/p0096) to bump to 201603).

**Comment by CaseyCarter** [comment]
Your `_MSC_VER` values are also incorrect:
* 1900 was the value for VS 2015
* 1910 was the VS 2017 release version (aka "15.0")
* 1911 was the toolset in VS 2017 15.3
* 1912 was VS 2017 15.5
* 1913 is VS 2017 15.6
* 1914 will be VS 2017 15.7

**Comment by dcleblanc** [comment]
OK, thanks. Just pushed a fix to SafeInt to bump the required version down to 1910.

Also, to do this properly, you should test for __cpp_constexpr, which should be working soon on Visual Studio, then fall back to coarser measures if that fails. Again, see how it is implemented in SafeInt. Visual Studio’s lack of correctly setting both __cplusplus and letting you see __cpp_constexpr when it wasn’t actually defined cost me a couple of days of dev time. I’m happy to see that __cplusplus has very recently started to be correct, and hopeful (as per stl) that the feature tests should be available soon.

Since this project is attempting to be cross-platform, as is SafeInt, we should use standard-based mechanisms when possible, because the __cplusplus version may not imply the __cpp_[feature] version.

**Comment by CaseyCarter** [comment]
The SD-6 feature test macros are not a "standard-based mechanism" since WG21 has not yet chosen to incorporate them into a standard. `__cplusplus`, on the other hand, *is* a "standard-based mechanism": conforming implementations define `__cplusplus` to the value specified in a C++ standard to indicate conformance to that standard. For example, a conforming implementation that defines `__cplusplus` to `201402` necessarily implements C++14's "relaxed `constexpr`".

The lack of standardization of the SD-6 feature test macros leads to the kind of trouble that you had with Visual Studio. Visual C++ doesn't implement feature test macros, but the EDG compiler front end (which powers Intellisense) does, so Intellisense thinks `__cpp_constexpr` is defined despite that it will not be when running the actual compiler.

It's unlikely that MSVC will be defining any of the SD-6 feature test macros in the near future. The informal position of the Visual C++ group (which is of course subject to future change) is that we will not implement the feature test macros unless they are standardized. Given the recent direction of WG21, some kind of feature test macros will likely be standardized in C++20. I'd hope that MSVC would prospectively implement them once they appear in the working paper for C++20, but can make no promises.

**Comment by neilmacintosh** [comment]
@dcleblanc Would you like to contribute a PR that demonstrates how the test is broken, then fixes it?

**Comment by dcleblanc** [comment]
Sure, be happy to.

**Comment by gdr-at-ms** [comment]
- cross-platform does not necessarily mean that you have to use feature-test macros [ an unfortunate common misconception ]

- keep it simple; focus on the compilers you actually support 

- testing compiler version is just fine! You have a better handle on the issue -- feature test macros don't tell you if the compiler you are targeting is actually usable for that specific feature.

**Comment by dcleblanc** [comment]
In terms of keeping it simple, I think just using the feature test macros when they are present is simplest. Visual Studio just shipped an update that implements these, so it seems like the correct path going forward.

Your alternative would be to do what Boost does, and work off compiler versions. This means constantly testing and updating all the different compilers every time there's a new version of some feature. If we go look at how Boost handles constexpr for the Microsoft compilers, we find that it is actually wrong, and is configuring it not to have support for constexpr when there should be. This also only works if you have access to every possible version, which is daunting for a contributor to set up.

Obviously, some of them have bugs - for example, the Microsoft compiler lies about the __cplusplus value until quite recently, and you can't use that as an indicator.

Ideally, there would be a compile time test suite that exercises each compiler (and version), and makes sure the code compiles correctly in each case. That's what I did for SafeInt - there's a separate project for VS 2015 and 2017, and separate make files for clang and gcc, both of which run with -std=c++11 and c++14. Then you have a way to verify whether any of this actually works.

Also, something else that I noticed is that the logic for feature support and other compiler options, such as warning suppression, is strewn all over the library and happens in as many as 3 places, it would be better to centralize.

**Comment by dcleblanc** [comment]
With respect to constexpr, which is the only one I've worked with so far, and is I think the only feature I've seen tested for in this library, I know that both clang and gcc do correctly set this value based on the value of the -std= argument. So compiler version by itself doesn't help. You could be running a version of clang that does support constexpr lambdas, but it had an argument telling it to use the C++11 standard, so it disables support for that feature, and it won't compile. This is unlike the Visual Studio behavior where it will tell you it doesn't support the C++11 or C++14 standard, but then actually does.

So you'd end up with a matrix of the compiler version and the -std argument. Or you can just ask it what level of that feature it supports, which to me is a lot simpler. If all I were working with were compilers like the Microsoft compiler, then yes, compiler version is the way you have to go because the feature test macros only became available in the last couple of weeks, and the __cplusplus version was also unreliable, so all you're left with is compiler version.

Excepting the Intel compiler, which I haven't tried yet, all your other platforms are variants of clang and gcc. For all of those, I believe simply working off the feature test macros is more direct than compiler version and __cplusplus value paired. For the Microsoft compiler, we obviously have to use compiler version up until the most recent update.

We could also just go trivially test this by creating code snippets that exercise the three levels of that feature, and verify if any of our supported compilers are buggy in this respect.

**Comment by gdr-at-ms** [comment]
Regarding `constexpr`, all this complexity is not needed.  On Windows, GSL is supporting only the last two major releases and there is no way to request C++11 only.  For all other compilers, just assume they support `constexpr`.

**Comment by dcleblanc** [comment]
If you're going to require it, then just require it, don't test for it in 5 different files in two different ways. The tests for it are broken for both clang and gcc, and there is neither a test for compiler version nor the __cplusplus version. If you are going to require it, then it would be great to put a code snippet in a test source file, and fail the build early if there's a lack of support.

In addition, there's no check using any mechanism whether this feature is supported on the Intel compiler.

If Windows is the only target platform, and more precisely, the Microsoft compiler - as we could be targeting the Windows platform with any of gcc, clang, Intel compilers, then why do we have a list of supported compilers, and an ask to add to that list?

If you're going to support these compilers, then provide first class support, not haphazard support. Or if you just want to make the library specific to the Microsoft compiler, then just do that.

**Comment by gdr-at-ms** [comment]
There is indeed room for cleanup.  We are striving for simpler -- and therefore more maintainable -- GSL code.  

MSVC isn't the only target compiler, but we are not aiming compilers that do not support C++14 in general.  

Let's keep it simple.

**Comment by martinmoene** [comment]
In [_gsl lite_](https://github.com/martinmoene/gsl-lite) and other _nonstd lite_ projects I use `_MSVC_LANG` (see below) and derive availability of language and library features of `gsl_CPPxx_OR_GREATER` and compiler versions if necessary, see for example [`constexpr11`](https://github.com/martinmoene/gsl-lite/blob/94e2d2793e8a6af067d32fd3e8ad637b3676db01/include/gsl/gsl-lite.hpp#L247).

Perhaps `_MSVC_LANG` can beof help here too?

```
// C++ language version detection (C++20 is speculative):
// Note: VC14.0/1900 (VS2015) lacks too much from C++14.

#ifndef   gsl_CPLUSPLUS
# ifdef  _MSVC_LANG
#  define gsl_CPLUSPLUS  (_MSC_VER == 1900 ? 201103L : _MSVC_LANG )
# else
#  define gsl_CPLUSPLUS  __cplusplus
# endif
#endif

#define gsl_CPP98_OR_GREATER  ( gsl_CPLUSPLUS >= 199711L )
#define gsl_CPP11_OR_GREATER  ( gsl_CPLUSPLUS >= 201103L )
#define gsl_CPP14_OR_GREATER  ( gsl_CPLUSPLUS >= 201402L )
#define gsl_CPP17_OR_GREATER  ( gsl_CPLUSPLUS >= 201703L )
#define gsl_CPP20_OR_GREATER  ( gsl_CPLUSPLUS >= 202000L )
```

**Comment by dcleblanc** [comment]
I really like what you have there, Martin - it's very comprehensive. It also looks like it is very extensible, and can abstract away compiler differences from the rest of the code.

There is, however, a difference between Gabriel's stated goal of only supporting C++14, and the list of supported compilers. On the supported compiler page is VS2015, which doesn't support C++14, clang is listed as a minimum of 3.6 when they fully implemented C++14 in version 3.4. Similarly, gcc is listed as a minimum of 5.1, but C++14 was implemented there as of 4.9 and 5.0 (depending on which feature you want). For the Intel compiler, C++14 was done in stages, complete in 17, but 18 is stated as supported.

I'm fine with requiring a minimum of C++14, though I think it wouldn't be too onerous to just require C++11. But none of this is enforced by the library, and the versions aren't consistent with the stated goal.

Detection of C++14 has to be done per compiler, though - only gcc, clang, and VS2017 (with patches) are detectible with the __cplusplus value, but it would be easy to first check __cplusplus, then fall back as needed, with a user override to allow unknown compilers to be possible.

**Comment by MikeGitb** [comment]
> I'm fine with requiring a minimum of C++14, though I think it wouldn't be too onerous to just require C++11. But none of this is enforced by the library, and the versions aren't consistent with the stated goal.


IIRC The library reauires a lot of c++14 features (to the extent that they are supported by vs2015), so c++11 is just not enough. 


Someone please correct me if I'm wrong, but I believe in the past the goal was to support the latest two (major) versions of Visual studio and otherwise any conforming c++14 toolchain.

Personally, I wouldn't consider any toolchain supported that is not in the CI matrix. 

And regarding clang 3.4 and c++14: Are you sure that version was accompanied by a complete c++14 standard library?

**Comment by gdr-at-ms** [comment]
@MikeGitb 
> Someone please correct me if I'm wrong, but I believe in the past the goal was to support the latest two (major) versions of Visual studio and otherwise any conforming c++14 toolchain.

You are absolutely correct.  GSL shouldn't lose focus.

**Comment by dcleblanc** [comment]
@MikeGitb  - I'm not sure what C++14 language features are required other than constexpr, but VS 2015 only supports the most basic constexpr (not the relaxed version). If the goal is simplicity, as @gdr-at-ms has stated, then we could avoid the whole feature test problem for the near future by just saying that C++14 is a minimum requirement. But VS2015 support puts us back into the feature test problem.

I agree completely that anything not tested in the CI isn't well supported, just pointing out that if we have a goal of C++14, then our choices of compiler versions are somewhat arbitrary. WRT to clang 3.4, their web site claims full C++14 support - as seen here - http://clang.llvm.org/cxx_status.html#cxx14.

IMHO, if our goal is C++14, then let's get copies of the minimum compilers for each of clang, gcc, Intel, and Microsoft, test them, and then also keep copies of the most recent stable compilers for each, and test those to ensure no regressions. We could then make a central header to manage compiler differences and versions, and put some static_assert statements into place so that if they are using the wrong compiler version, they'll find out about it immediately with an intelligible error message.

**Comment by MikeGitb** [comment]
@dcleblanc: 
By c++14 features I did not just mean language but also library features like e.g. the <type_trait>_t type aliases. I haven't checked what else exactly would have to change to make the library c++11 compatible. 

Regarding constexpr: constexpr is conditionally disabled when the library is compiled with MSVC 2015 (I believe with an MSVC specific pragma). As this library is effectively a microsoft product it is not suprising they special case their compiler.

**Comment by dcleblanc** [comment]
@MikeGitb actually, it isn't anywhere close to that clean. There are checks in 5 different headers to see if relaxed constexpr is supported. In <span>, there is a check for only the Microsoft compiler version to see if this is OK - 

#if defined(GSL_USE_STATIC_CONSTEXPR_WORKAROUND)
    static constexpr const index_type extent { Extent };
#else
    static constexpr index_type extent { Extent };
#endif

If it is not, then it removes constexpr support completely - in just that one header - (including the relaxed usages) and throws out the baby with the bathwater. I can't sort out so far if there's actually any need to check this independently of relaxed support. It also does this badly, by undefining a reserved word as a macro.

If we're really supporting C++14, then none of these checks are needed - any C++14 compiler I've tested so far deals with this.

**Comment by MikeGitb** [comment]
@dcleblanc: No one is arguing that this needs cleanup. The question is in what form and what is the goal.

As far as I can tell, the goal is to support any c++14 and later compliant toolchain and VS2015. 

That means the only check that should be necessary in the code is if it gets compiled with VS2015 - no reason to to check feature macros or other compiler versions.

The second question is what to do with the knowledge that we are dealing with VS2015. One approach is to provide as much functionality and decide on a case by case basis if a function should be marked constexpr or not. The other is to pull the big hammer/ throw out the baby with the bathwater and remove constexpr completely.

My guess is that no one would complain if you provided a PR implementing one strategy or the other consistently. The other possibility is to leave everything as is, wait until the support for VS2015 is dropped and just throw out all the machinery (Disclaimer: I'm not using the gsl either professionally, nor privately, so I don't have any preference).

BTW.: I'd say there is no reason, why you can't add older toolchains to the test matrix if they have indeed complete c++14 support. I think that you'll only get some pushback if support for those compilers would require additional code changes like compilation branches or workarounds.

**Comment by JordanMaples** [comment]
Maintainer's call: closing this as the test for constexpr support has been removed from the source and the focus of GSL has been aligned to only support the N and N-1 release of MSVC, GCC, and Clang.
