### ISSUE TITLE
problematic as_multi_span overload

### ISSUE THREAD

**Issue by ibtaylor** [microsoft/GSL#672]
I've been overloading `as_multi_span` for some custom types and ran into some problems.

I attempted to write a templated overload for `as_multi_span` for some type `T`, but I can't because AFAIK my `T` has `.size()`, `.data()` and the following overload is getting called instead:
https://github.com/Microsoft/GSL/blob/2fc94db3ebfb1b066edeafac1837f34d6111bff4/include/gsl/multi_span#L1730-L1737
This was very surprising to me since, for most types, my overloads work as expected.

My `T` is multi dimensional and has `cols()` and `rows()` too, which is why I wanted to make the overload. 

I think this particular `as_multi_span` method should be removed since the likelihood of it doing the wrong thing is too high. It makes a lot of assumptions based on patterns seen in the stl, but are not necessarily universal.

In the future (or if detected as supported), I could see having such an `as_multi_span` or `as_span` based on the `ContiguousContainer`.

**Comment by sellibitze** [comment]
> I attempted to write a templated overload for as_multi_span for some type T, but I can't

What exactly did you try? I think it would be very helpful if you provided more information such as your namespace hierarchy, using directives & declarations and your function template signature.

**Comment by annagrin** [comment]
@ibtaylor Agree that as_multi_span needs to be removed - we should provide useful constructors instead, and create helpers if needed.

**Comment by ibtaylor** [comment]
@sellibitze 
I ended up side-stepping this issue, but I guess here is how I ran in to it. Tried to set up an example on goldbolt. 
https://godbolt.org/g/5md2Bv

**Comment by JordanMaples** [comment]
multi_span is now deprecated, closing this issue. Thanks.
