### ISSUE TITLE
A typo in .travis.yml

### ISSUE THREAD

**Issue by sizmailov** [Microsoft/GSL#677]
I believe it should be `clang50` instead of `clang40`

https://github.com/Microsoft/GSL/blob/5cbde3008aa43a9c5f6c219ee15b8388336d4433/.travis.yml#L121-L123

https://github.com/Microsoft/GSL/blob/5cbde3008aa43a9c5f6c219ee15b8388336d4433/.travis.yml#L134-L136

**Comment by gdr-at-ms** [comment]
Fixed by #678
