### ISSUE TITLE
Lack of deduction guides for gsl::span and similar types

### ISSUE THREAD

**Issue by effolkronium** [microsoft/GSL#680]
Pls, implement something like that (if C++17 support exist)

```
namespace gsl
{
    template<class T>
    span(T&)->span<typename T::value_type>;

    template<class T, size_t N>
    span(T(&)[N])->span<typename std::remove_all_extents<T>::type>;
}
```

**Comment by annagrin** [comment]
some work for non_null is done in #689

**Comment by johelegp** [comment]
The [standard's](http://eel.is/c++draft/span.overview) has some.

**Comment by annagrin** [comment]
BTW, I laid the grounds for this work to start with my addition of c++17 tests (#692, #697). Gave a starter with  not_null constructor from T and  template arguments deduction tests (#689). PRs are welcome for span deduction guides! We might need to bear in mind that some deduction guides could be just missing constructors...

**Comment by JordanMaples** [comment]
Maintainers' call: Sorry for the delay. Now that span has been standardized, the only delta between gsl::span and std::span is the bounds checking. We are following the standard interface exactly.
