### ISSUE TITLE
gsl:not_null 

### ISSUE THREAD

**Issue by Sweepi** [Microsoft/GSL#681]
I am pretty sure I am missing sth. obvious, but gsl:not_null does not work for me:
```
        int foo = 5;
        gsl::not_null<int*> test = &foo;
        gsl::not_null<int*> test2 = new int;
```

> error C2440: 'initializing': cannot convert from 'int *' to 'gsl::not_null<int *>'
> note: Constructor for class 'gsl::not_null<int *>' is declared 'explicit'
> error C2440: 'initializing': cannot convert from 'int *' to 'gsl::not_null<int *>'
> note: Constructor for class 'gsl::not_null<int *>' is declared 'explicit'

I am using MSVS 2017 15.7.1 and the current master of Microsoft/GSL

**Comment by KVic** [comment]
```
    int foo = 5;
    gsl::not_null<int*> test{&foo};
    gsl::not_null<int*> test2 = gsl::not_null<int*>(new int);
```

**Comment by Sweepi** [comment]
Thanks - so the syntax used on slide 53 of [10 Core Guidelines You Need to Start Using Now by Kate Gregory](https://github.com/CppCon/CppCon2017/blob/master/Presentations/10%20Core%20Guidelines%20You%20Need%20to%20Start%20Using%20Now/10%20Core%20Guidelines%20You%20Need%20to%20Start%20Using%20Now%20-%20Kate%20Gregory%20-%20CppCon%202017.pptx) from [CppCon2017](https://github.com/CppCon/CppCon2017) is a typo and it is not intended to work this way?

**Comment by martinmoene** [comment]
From PR #449 : 

> remove operator=(const T&)
>- it leaves *this in an invalid state if ensure_invariant fails
>- implicitly converting the T to not_null and then assigning is in every way superior.

T t;
not_null&lt;T> nnt &larr;assign&larr; not_null&lt;T> &larr;convert&larr; t;

However, doesn't this not work because it requires two user-defined conversions in a row?

**Comment by KVic** [comment]
> However, doesn't this not work because it requires two user-defined conversions in a row?
```
int foo = 5;
gsl::not_null<int*> test = &foo;
```
This does not work, because the constructor `not_null(U&& u)` is `explicit`.

> So the syntax used on slide 53 of 10 Core Guidelines You Need to Start Using Now by Kate Gregory from CppCon2017 is a typo and it is not intended to work this way?

It was not a typo. The syntax changed 17 days ago: PR #659.

**Comment by Sweepi** [comment]
Thanks!

**Comment by martinmoene** [comment]
Ah thanks,

```C++
struct E {
    template<typename U> explicit E(U &&) {}
};

int main() {
//  E e1 = 1;   // explicit: not a converting c'tor, so no copy-initialization
    E e2(  2 );
    E e3{  3 };
    E e4 = (E) 4;
}
```

**Comment by Farwaykorse** [comment]
Explicit construction is an improvement.

@annagrin Shouldn't #659 have resulted in a version bump, since it does change the API of not_null?
(As stated in  #595 )

**Comment by annagrin** [comment]
@MikeGitb @Farwaykorse @martinmoene 

I am only adding versions to commits that have extra validation by me (= updating our internal submodule of GSL and compiling and testing our code using GSL). I am still working on it - explicit constructor, while and improvement, triggers a lot of code improvements.

As part of it, I added a contructor that helps decution of template arguments - would appreciate  you input - is any bad behaviour allowed by that change? #689

**Comment by annagrin** [comment]
@Sweepi I presume you received an answer. Please reopen if I am wrong.
