### ISSUE TITLE
gsl::span front() and back() methods are missing

### ISSUE THREAD

**Issue by fdwr** [microsoft/GSL#684]
The common `front()` and `back()` methods are absent, which complicates writing generic code accepting containers of the nature like `std::vector`, `std::list`, `std::string`, and `std::array`. This was a rather surprising omission when porting existing code from taking a `const vector&` to `gsl::span`.

- Reasonable work-arounds for `front()` include `*span.begin()` and `span[0]`, but writing `*(span.end()-1)` or `span[span.size() - 1]` are rather awful substitutes for the elegant `back()`.
- Explicit `front()` and `back()` methods may offer minor compile benefits since the index (at least in the case of front) is a constant rather than an index parameter that requires multiplication times the element byte size.
- Increases consistency with the standard contiguous containers vector/string/array (and some non-contiguous ones - std::list) and offers more algorithm genericity.

**Comment by martinmoene** [comment]
See also [p1024 - Usability Enhancements for std::span](http://wg21.link/p1024).

**Comment by mavam** [comment]
@martinmoene Do you happen to know what the committee thinks about p1024? Is it likely going to make it? I am asking because it would add `std::first` and `std::last` as new functions to namespace `std`, which some members may find concerning.

**Comment by martinmoene** [comment]
@marc-kdab , I've the slightest idea. @chris0e3 triggered me as [*span lite* issue 3](https://github.com/martinmoene/span-lite/issues/3) and somewhat later I found p1024.

**Comment by timsong-cpp** [comment]
LEWG liked everything except `at()` and the free subview functions.

**Comment by JordanMaples** [comment]
We need to add front and back to span, if anyone is willing to volunteer to contribute an implementation I'd appreciate it.

**Comment by JordanMaples** [comment]
Maintainer's call: Closing this because front() and back() have been added to span.

**Comment by fdwr** [comment]
Alright. We will switch over to `std::span` once C++20 is published and VS includes it. Will `gsl::span` be retired then, or remain?

**Comment by JordanMaples** [comment]
@fdwr gsl::span will remain, std::span doesn't provide the runtime bounds checks that gsl::span provides. #844 essentially aligned gsl::span's interface with std::span. The goal is that when a user wants the runtime bounds checks you can just use gsl::span and when that's not important to you std::span can be used with no changes to the rest of your code.

**Comment by JordanMaples** [comment]
The only major difference between gsl and std span now is ranges support.
