### ISSUE TITLE
Inconsistency with basic_string_view

### ISSUE THREAD

**Issue by MFHava** [microsoft/GSL#693]
I noticed a (minor) inconsistency in the design of gsl::span:

Per convention all current container-like types in the standard library define both **pointer** and **reference** to be **mutable** (which is natural as containers may not store const types). Additionally two **explicitly const** typedefs are provided as **const_pointer** and **const_reference** are provided.
This design is also used by std::string_view, even though string_views are always const.

gsl::span<Type> however does the following: it only provides **pointer** and **reference** and these are const iff Type is const.

**Comment by JordanMaples** [comment]
Is this regarding string_view or string_span?
@gdr-at-ms: any thoughts on this?

**Comment by JordanMaples** [comment]
Maintainers' call: Sorry for the delay. Now that span has been standardized, the only delta between gsl::span and std::span is the bounds checking. We are following the standard interface exactly.
