### ISSUE TITLE
std::byte not found for clang5.0 anf clang6.0 builds with -std=c++17

### ISSUE THREAD

**Issue by annagrin** [Microsoft/GSL#695]
Tried to add clang5.0 and clang6.0 builds with -std=c++17 in .travil.yml, but the compilation fails due to missing std::byte. Maybe libraries update is needed as well? Would appreciate help with this! see commented out code in clang section of .travil.yml in #692 

Here is the build output snippet:
```
[ 10%] Built target no_exception_throw_tests
Scanning dependencies of target no_exception_ensure_tests
[ 13%] Building CXX object tests/CMakeFiles/no_exception_ensure_tests.dir/no_exception_ensure_tests.cpp.o
In file included from /home/travis/build/Microsoft/GSL/tests/no_exception_ensure_tests.cpp:18:
In file included from /home/travis/build/Microsoft/GSL/include/gsl/span:21:
/home/travis/build/Microsoft/GSL/include/gsl/gsl_byte:72:12: error: no member named 'byte' in namespace 'std'

using std::byte;

      ~~~~~^

/home/travis/build/Microsoft/GSL/include/gsl/gsl_byte:73:12: error: no member named 'to_integer' in namespace 'std'

using std::to_integer;
      ~~~~~^
```

**Comment by johelegp** [comment]
`std::byte` was added in 5.0, says https://libcxx.llvm.org/cxx1z_status.html. For GCC, it was added in 7, says https://gcc.gnu.org/projects/cxx-status.html. A solution would be to install GCC 7 along the affected Clang versions.

**Comment by annagrin** [comment]
thanks @johelegp, will try addinf GCC 7 to my clang 5 & clang 6 configurations.

**Comment by annagrin** [comment]
@johelegp worked like a charm, many thanks!

**Comment by johelegp** [comment]
You are welcome.
