### ISSUE TITLE
Why do some header names contain the gsl_ prefix?

### ISSUE THREAD

**Issue by kivadiu** [microsoft/GSL#700]
Below is the list of include files provided by this library. Could we remove the gsl_ prefix in front of algorithm, assert, byte and util to have a consistent naming? We already have the gsl prefix because we have to include <gsl/header> so <gsl/gsl_util> is redundant.

gsl
gsl_algorithm -> algorithm
gsl_assert -> assert
gsl_byte -> byte
gsl_util -> util
multi_span
pointers
span
string_span

**Comment by beinhaerter** [comment]
I guess that the GSL maintainers thought that developers might not just add `include` to the include path but they might want to add `include/gsl` to the include path. `#include <gsl_assert>` (GSL) will never collide with `#include <assert>` (compiler include), but you would have a collision if GSL exported a file `assert`.

**Comment by neilmacintosh** [comment]
@beinhaerter is correct. We wanted to use the name prefixes to avoid collisions. Of course, `span` has now tripped us up as it appears in C++17 as well. If you felt strongly about the issue you could offer a PR that changed the names, but you'd still need to keep the old ones around for compatibility's sake, I would imagine (even if they just forward to the new-named ones).

**Comment by kivadiu** [comment]
I think we should favor to always use `#include <gsl/...>` instead of `#include <...>`. This would avoid any name clash, also in the future and make clearer that we include a GSL header.
Meanwhile, here is a PR that allows both inclusion methods: #725

**Comment by hsutter** [comment]
Maintainers' call: Sorry for the delay in replying. We agree. The plan is to remove the `gsl_` prefixes from the headers, and then for backward compatibility provide one-line passthrough headers with the original names that `#include` the new names and issue some sort of deprecation warning.
