### ISSUE TITLE
not_null disallows assignments from nullptr, but not comparisons to it

### ISSUE THREAD

**Issue by hostilefork** [microsoft/GSL#701]
Considering the following example:

    #include <iostream>
    #include "include/gsl/gsl"

    int main() {
        int i;
        gsl::not_null<int*> ptr (&i);
        /* gsl::not_null<int*> ptr_error (nullptr); */ // this errors

        if (ptr != nullptr)
            std::cout << "No compile error on compare--this prints\n";
    }

In the case I was trying to apply it to, every such comparison--and taking actions in response to it--would denote a bug.  It seems to me that allowing code to compare against nullptr and then take actions based on that comparison makes denoting things `not_null` somewhat toothless as a tool for making sure authors aren't making semantic mistakes.

*(First posted about as a [StackOverflow question](https://stackoverflow.com/q/51057099/211160))*

**Comment by ar5ham** [comment]
You can lie to compiler and hide stuff in different translation units. For instance, following the example you have above, I can write something like the following:
```
int* GetPtr (int* ptr)
{
    return ptr;
}
```
and then do something stupid like this:
```
ptr = GetPtr(nullptr);  //with GSL you'll get a run time error pointing to this line of code
// Somewhere else in a land far far away (AKA somewhere else in the code). 
ptr ->DoSomething();  
```
In this case, using GSL header, you get a run time error when the `ptr` is set to null, without the  `gsl::not_null<int*> you'd get a nullptr exception where you called `DoSomething` and you'd still need to go figure out where did you set `ptr` to null.

**Comment by beinhaerter** [comment]
VS2019 16.8.1 code analysis emits a warning on the check.

> warning C26431: The type of expression 'ptr' is already gsl::not_null. Do not test it for nullness (f.23).

I think that is really helpful in your case.

I thought about preventing a `gsl::not_null<T>` from being compared to a `nullptr_t` but I am not sure if this is a good idea because it might break generic template code. It would be possible to provide `operator==` and `operator!=` just as constant `return false/true;`, but then in my opinion the GSL should also trigger a warning (for example by marking it deprecated? or is there a better way?).

**Comment by hsutter** [comment]
Maintainers call: We agree the current warning should cover the mistake cases. However, generic code that is correct for both `T*` and `not_null<T*>` can legitimately check for nullness, and we shouldn't break that generic code.
