### ISSUE TITLE
Make final_action move assignment operator non delete

### ISSUE THREAD

**Issue by dureuill** [microsoft/GSL#705]
The move assignment operator for `final_action` has been made `= delete` following #660 (solving #653).

Is there any specific reason why the operator must be deleted rather than defined, since there is a defined move constructor?

This makes any object containing a `final_action` not move-assignable, and the CoreGuidelines [recommends](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#note-382) defining a move assignment operator if there is a move constructor.

The move assignment operator could look like this:
```cpp
final_action& operator=(final_action&& other) {
    // guard against self-assignment
    if (this == &other) return *this;

    // perform final action of the left-side
    if (invoke_) f_();

    // copy final action from the right-side
    invoke_ = other.invoke_;
    f_ = std::move(other.f_);

    // disable final action on the right-side
    other.invoke_ = false;
    return *this;
}
```

**Comment by eric-wieser** [comment]
To me it's not clear that _"perform final action of the left-side"_ is correct behavior, or even what correct behavior looks like.

**Comment by MikeGitb** [comment]
What kind of object needs a final_action as a member variable to begin with?

**Comment by dureuill** [comment]
> To me it's not clear that _"perform final action of the left-side"_ is correct behavior, or even what correct behavior looks like.

This is by analogy with `std::unique_ptr<T>`'s move operator, where if the left-hand already contains a value, it should be deleted before assigning the right-hand.

It is the same with `final_action`, if the left-hand already contains an action, then it should be invoked before assigning the right-hand, otherwise it will never be invoked. If the left-hand doesn't contain an action, then its `invoke_` member should be `false`.

Or is there anything I'm missing here?

> What kind of object needs a final_action as a member variable to begin with?

My use case is implementing the [rule of zero](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c20-if-you-can-avoid-defining-default-operations-do) for non-pointer resources, where `std::unique_ptr<T>` is not usable. An example of this are "integer-like" handles that must be passed to a "free-like" function when the containing object is destructed (these handles come from a C library). Using a  `final_action` in this context avoids the need for an explicit deletion of the copy constructor and an explicit definition of the move constructor. If defined manually, the move constructor would certainly have to use a `bool` to prevent "double free" after moving, exactly like `final_action` already does.

**Comment by PeterFeicht** [comment]
In my mind, `final_action` is an implementation detail of `finally` and you shouldn't really store it anywhere, much less assign it. Normally you don't even mention the type.

**Comment by hsutter** [comment]
Maintainers' call: Thanks for the suggestion. Because the GSL design and feature set is owned by the C++ Core Guidelines, we will follow whatever the Guidelines decide and will await their direction and implement that as soon as we have it. In the meantime we'll close the one here which can then be reopened later when there is guidance. Please reactivate this one when there's a conclusion.

**Comment by hsutter** [comment]
I think I finally (NPI) understand why `finally()` was written as a `const&`/`&&` overload... to eliminate a copy when you invoke it with a temporary such as a lambda. If so, the `&&` was probably never intended to be a forwarder, but was simply tripping over the horrid C++ choice to have a `&&` parameter mean "rvalue reference" when the type doesn't happen to be a template parameter but a "forwarding reference" when the type happens to be a template parameter type. And this is a template, so it started looking like a forwarder, but I'll bet it was never intended to be a forwarder at all.

I'll create a PR to re-simplify this back to what [C++ Core Guidelines C.30](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c30-define-a-destructor-if-a-class-needs-an-explicit-action-at-object-destruction) said which is simple and clear, and then we can discuss whether we like that PR.
