### ISSUE TITLE
Template specialization for ArrayViewTypeTraits uses incorrect static member of is_reference

### ISSUE THREAD

**Issue by kernhanda** [Microsoft/GSL#71]
```C++
struct ArrayViewTypeTraits<Traits, typename std::is_reference<typename Traits::array_view_traits &>::type>
```

```std::is_reference<T>::type``` isn't valid. It should be using ```std::is_reference<T>::value```.

**Comment by neilmacintosh** [comment]
I believe there is a member type on is_reference called "type" (see http://en.cppreference.com/w/cpp/types/is_reference). So the usage looks valid to me.
