### ISSUE TITLE
False positive detection of std::byte for clang and stdlibc++

### ISSUE THREAD

**Issue by ithron** [Microsoft/GSL#713]
In lines 46 to 51 `GSL_USE_STD_BYTE` is defined if `__cplusplus >= 201703L`.
This breaks for the case where the compiler fully supports c++17, but the used STL does not.
For example if you use clang 5.0 and above on a Linux system it uses by default the GNU libstdc++ implementation of the installed GCC. And if the version of libstdc++ is < 7.1 (see [gcc status page](https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html)) GSL assumes `std::byte` exists in the STL but it does not.

One way to fix this would be to check for `__cpp_lib_byte >= 201603`, at least for GCC >= 7.3.

For clang's libc++ `std::byte` is supported since version 5. libc++ can be detected by checking for `_LIBCPP_VERSION`.

**Comment by neilmacintosh** [comment]
Fixed by @ithron in #714.
