### ISSUE TITLE
`gsl::span<const T> == gsl::span<T>` does not work

### ISSUE THREAD

**Issue by LYP951018** [microsoft/GSL#728]
... And it seems that it should work...?
I came up two solutions:
1. A convenient helper function `as_cspan`, which takes a `gsl::span<T>` and returns a `gsl::span<const T>`. Then we could `as_cspan(sp) == sp2`;
2. Modify `span`'s `operator==`.

**Comment by annagrin** [comment]
looks like `operator==` will be removed in c++20 (due to the desire to make span regular), but if feel strongly about your use case, please submit a fox for now. You can move it to your code after it has been removed from the library.

**Comment by jack17529** [comment]
@annagrin , I can submit a PR and @LYP951018 can review it, all right?

**Comment by LYP951018** [comment]
@jack17529 Actually, I'm not responsible for reviewing .... @annagrin does.

**Comment by JordanMaples** [comment]
Maintainers' call: Sorry for the delay. Now that span has been standardized, the only delta between gsl::span and std::span is the bounds checking. We are following the standard interface exactly.
