### ISSUE TITLE
Implicit conversion for array decaying

### ISSUE THREAD

**Issue by matt77hias** [Microsoft/GSL#735]
Why isn't there a templated **implicit** constructor in `gsl::not_null` for constructing `gsl::not_null`s from arrays (i.e. `T(&)[N]` and `const T(&)[N]`)?

```c++
char buffer[100];
gsl::not_null< char* >       b1 = buffer; // no suitable conversion
gsl::not_null< const char* > b2 = buffer; // no suitable conversion
```

**Comment by MikeGitb** [comment]
Not sure if that is the reason, but you should not wrap an array in a pointer to begin with. That's what gsl::span is for (or string_view).

**Comment by matt77hias** [comment]
@MikeGitb True, but the exception imho are C style strings which are still ubiquitous and which are still explicitly considered by the [CppCoreGuidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f25-use-a-zstring-or-a-not_nullzstring-to-designate-a-c-style-string).

**Comment by MikeGitb** [comment]
The guideline you link to explicitly says not to use `not_null<const char*>` but `not_null<zstring>` for that purpose. 

You can create a `not_null<const char*>` from a char array if you really want to, but you have to explicitly call it out in the code and I believe that is a good thing.

**Comment by matt77hias** [comment]
@MikeGitb you're right ;-)

My recurring use case is actually the following:
```
char buffer[MAX_PATH];
// 'buffer' passed as 'char(&)[N]' to have 'N' as well. 
// '\0' will be written a.o. so 'buffer' will contain a null-terminating string.
WriteTo(buffer, ...);
// 'char*' must be explicitly cast to 'gsl::czstring', fair. 
// But it originates from a local array, so I rather like the 'gsl::not_null' construction to be transparent (implicit construction without verification upon construction) to reduce the boiler plate. 
// But I do not really see, how all of this can be achieved.
const auto not_null_buffer = gsl::not_null< gsl::czstring>(buffer); 
// API uses 'gsl::not_null< gsl::czstring>' according to the guidelines.
DoSomething(not_null_buffer);
```
