### ISSUE TITLE
indices/sizes should be unsigned

### ISSUE THREAD

**Issue by stohrendorf** [Microsoft/GSL#736]
`index`, `span::index_type` etc. and several size types are typedefs for `ptrdiff_t`. I don't think that is quite right or reasonable, because of the following reasons:

1. Using `index` to iterate over an `std` container causes signed/unsigned warnings when compared to the container's size. It requires the use of casts or `narrow`, neither of which should be necessary. It is also error-prone to overflows when the index overflows to a negative value, probably resulting in segfaults. (Even if the size is calculated from subtracting pointers, which technically results in a `ptrdiff_t`, it is wrong; having [`l`,`r`) defining an address interval, the result of `r-l` must be non-negative, otherwise the interval is ill-formed.)
2. Negative indices or sizes don't make sense in most cases, especially when using with `span` or `std` containers where a range-based iteration is either not possible or the complexity of implementing a range interface for iteration (e.g. zipping) is not feasible with regard to the loop body's task.
3. On a side note, the type should be named `index_t` to be in line with `size_t`.

**Comment by beinhaerter** [comment]
This question has been asked and answered before multiple times.
As a starting point for your searches:

- https://github.com/Microsoft/GSL/issues?utf8=%E2%9C%93&q=is%3Aissue+index+signed+unsigned

- https://github.com/isocpp/CppCoreGuidelines/issues?utf8=%E2%9C%93&q=is%3Aissue+signed+unsigned+

**Comment by stohrendorf** [comment]
I have read them, but in my opinion it is still better to use unsigned types for values which are - by the definition of a common-sense container index - non-negative. With indices and sizes having signed types, the possibility of accidentally using a negative size/index is far larger than the benefits listed. It introduces another source for errors, additionally to indices being too large or exceptions being thrown, instead of reducing the risk for errors. Indices are not designed for arithmetics, they're identifiers with a specific domain; for offsets on the other hand, `ptrdiff_t` is perfectly valid, but an offset is not an index, and vice versa.

At least I tried to make my point clear, even if it doesn't change anything. Can be closed unless further discussions are wanted.

**Comment by Gh0stBlade** [comment]
I agree.

**Comment by neilmacintosh** [comment]
Thanks @beinhaerter for pointing out that this issue has been discussed many times now. Thanks @stohrendorf for understanding why I'll close out the issue now.
