### ISSUE TITLE
Please make this library available via vcpkg

### ISSUE THREAD

**Issue by FrankHeimes** [Microsoft/GSL#740]
Please add a port for this library to [Microsoft vcpkg](https://github.com/Microsoft/vcpkg). Unfortunately, there is already another library called [gsl](https://github.com/Microsoft/vcpkg/tree/master/ports/gsl), so that name clash needs to be resolved.
Any ideas?

**Comment by Farwaykorse** [comment]
This library is in there under the name [ms-gsl](https://github.com/Microsoft/vcpkg/tree/master/ports/ms-gsl).

**Comment by FrankHeimes** [comment]
Awesome - thanks!
Bummer - I could have guessed that myself.

**Comment by annagrin** [comment]
thanks @FrankHeimes  @Farwaykorse
