### ISSUE TITLE
Travis CI logs wrong compiler and wrong compiler version

### ISSUE THREAD

**Issue by beinhaerter** [microsoft/GSL#749]
While running into issue #745 with PR #748 I saw that the failing build is for G++6 ([see config](https://travis-ci.org/Microsoft/GSL/jobs/458801686/config)) but that the [output](https://travis-ci.org/Microsoft/GSL/jobs/458801686) shows version info for gcc 4.8.4. The same is true when COMPILER is set to clang, then we also get gcc version output. This is a disturbing and makes it hard to tell which compiler version is used (that breaks my PR).

> Setting environment variables from .travis.yml
> $ export COMPILER=g++-6
> $ export BUILD_TYPE=Release
> $ export GSL_CXX_STANDARD=14
> 
> $ export TRAVIS_COMPILER=g++
> $ export CXX=g++
> $ export CC=gcc
> cache.1
> Setting up build cache
> [...]
> $ g++ --version
> g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
> Copyright (C) 2013 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by tiagomacarios** [comment]
AFAIR: Travis boostraps with the default compiler in ubuntu which is the old ubuntu. The build then has to install a more up-to-date version. Lines 607 and 656 of the log report the correct gcc version 6.5.0.
All linux logs will show the old gcc when it starts.

**Comment by johelegp** [comment]
The latter part of your sample log, starting with `TRAVIS_COMPILER`, is Travis CI's own output before one has had the opportunity to install the correct compiler. As you mentioned, and as CMake reports, further down the correct compiler version is used. So this is a non issue.

**Comment by beinhaerter** [comment]
OK. What is the use of "${CXX} --version" then? Shall we just get rid of it? Or is there any use for it?

**Comment by johelegp** [comment]
>is there any use for it?

Doubt it.

**Comment by Farwaykorse** [comment]
> OK. What is the use of "${CXX} --version" then? Shall we just get rid of it? Or is there any use for it?

`${CXX} --version` has been removed with PR #835 

There is currently nothing that can be done about Travis prominently showing the default compiler on the build machine.
If you want to check the version used for the build, look at the CMake generation stage.
````
$ cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE:?} ${CMAKE_GEN_FLAGS[@]:?}
Warn about uninitialized values.
-- The CXX compiler identification is GNU 9.2.1
-- Check for working CXX compiler: /usr/bin/g++-9
-- Check for working CXX compiler: /usr/bin/g++-9 -- works
````
https://travis-ci.org/github/microsoft/GSL/jobs/667345003#L503

**Comment by johelegp** [comment]
It's possible to do: https://travis-ci.com/github/johelegp/jegp/jobs/334329470#L400. Just set the `compiler:` key to the executable, like `clang++-10`. Travis will set `CXX` to `clang++` or `g++`, but that's just the default installed compiler, so I set `CXX` to `$TRAVIS_COMPILER`, which has the value of the `compiler:` key, once under `before_script:` rather than in each job's `env:` to avoid repetition.

**Comment by JordanMaples** [comment]
Maintainers' call: We're currently migrating from using Travis-CI to using Azure DevOps Pipelines for our CI/CD. So I'll close this issue.
