### ISSUE TITLE
Error prone interface of basic_zstring_span

### ISSUE THREAD

**Issue by travnick** [microsoft/GSL#751]
the `basic_zstring_span` interface is error prone which is the opposite to the whole GSL idea.
There are the issues:
1. ctor of `basic_zstring_span` gets *implicitly* the `span<value_type, Extent>` which by default has no knowledge of null termination. This ctor should be explicit because compiler will not warn you when you pass `string_span` to the function which expects `basic_zstring_span` - it simply throws an exception ...
2. there are `ensure_z()` `assume_z()` methods - they have similar name but they return very different type.
In my opinion `ensure_z()` `assume_z()` should return the same type and the only difference is that the first one ensures the null termination and the second does not (assumes that).
these is `as_string_span` so I see no reason to have `ensure_z()` returning `string_span_type` instead of `const_zstring_type`
3. Additionally the free function `gsl::ensure_z()` returns something strange - the simple span of chars which does not care about null termination so I do not see any reason of ensuring null termination. `gsl::ensure_z()` should return `basic_zstring_span`. Then it's clear that it ensures that given value is null terminated and it creates valid `basic_zstring_span` from it.

**Comment by hsutter** [comment]
Maintainers' call: Sorry for the delay in replying. This is issue is now out of date because the Guidelines have removed all `*string_span` types, and it still has `zstring` and `czstring` as aliases for `char*` and `const char*` which don't have member functions.
