### ISSUE TITLE
Finally tries to take ownership of action

### ISSUE THREAD

**Issue by ricab** [microsoft/GSL#752]
The constructor of `final_action` [tries to move](https://github.com/Microsoft/GSL/blob/master/include/gsl/gsl_util#L54) the input action, which (fortunately) [breaks compilation](http://coliru.stacked-crooked.com/a/1d458725d81a28c5) when the input to `finally` is a non-const lvalue:

Replacing `std::move` with `std::forward` fixes the issue.

Related to (but different from) #125.

**Comment by dmitrykobets-msft** [comment]
The broken code sample is using a very outdated version of `gsl::finally` - the code compiles fine on the latest version.
