### ISSUE TITLE
Overload for ensure_z is missing

### ISSUE THREAD

**Issue by frast** [microsoft/GSL#756]
It is not possible to use ensure_z with a const string. For me it would be very useful to have const zero terminated string spans which are constructible from a const string. Is there any reason why this is not possible?

This overload should fix the issue:
```C++
template <class Cont>
span<typename const std::remove_pointer<typename Cont::pointer>::type, dynamic_extent>
ensure_z(const Cont& cont)
{
    return ensure_z(cont.data(), narrow_cast<std::ptrdiff_t>(cont.size()));
}
```

**Comment by JordanMaples** [comment]
Maintainers' call: Would you mind clarifying if you want this to apply to any container or just to a const std::string? If any container, why?

**Comment by frast** [comment]
It could be useful for vector<char> too. For me an overload for string/wstring would be sufficient.

**Comment by hsutter** [comment]
Maintainers' call: Sorry for the delay in replying. This is issue is now out of date because the Guidelines have removed all `*string_span` types, and it still has `zstring` and `czstring` as aliases for `char*` and `const char*` which don't have member functions.
