### ISSUE TITLE
Allow final_action to skip its action

### ISSUE THREAD

**Issue by heilkn** [microsoft/GSL#757]
I was often times in the situation where such a scoped clean-up-object as final_action had to restore class invariants if a failure had occured during a computation. However, in those cases the cleanup code had to be skipped at the end if the computation did not encounter an error. For these scenarios such a clean-up-object should mimic the behavior of unique_ptr which allows to release its resource without running it's custom deleter.

Please consider adding a release method to final_action that sets private member invoke_ to false.

**Comment by MikeGitb** [comment]
Three years ago this was rejected: https://github.com/Microsoft/GSL/issues/231. Opinions do change though.

**Comment by galik** [comment]
Ther is still an open discussion on this topic in the `CppCoreGuidelines` https://github.com/isocpp/CppCoreGuidelines/issues/688

**Comment by MikeGitb** [comment]
@galik: Thanks, that was the issue I was actually looking for, but I searched in the wrong repository.

**Comment by hsutter** [comment]
Maintainers' call: As of now the Guidelines have not added an `ignore` or `dismiss`. If they add it in the future with a description of what to call it and how it works, then this implementation should implement it and we can reopen this issue.
