### ISSUE TITLE
About using Expects in span

### ISSUE THREAD

**Issue by jack17529** [microsoft/GSL#767]
Can someone please help me in finding the clear difference between when one should use Expects() and when one should not?

At these places -
https://github.com/Microsoft/GSL/blob/master/include/gsl/span#L155
to
https://github.com/Microsoft/GSL/blob/master/include/gsl/span#L221

**Comment by rianquinn** [comment]
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#gslassert-assertions

This should help. Expects should be used to assert a contract between the user of the API, and the API itself. There is no need to use these in private logic.

**Comment by JordanMaples** [comment]
Maintainers' call: refer to the Guidelines link provided by @rianquinn.
