### ISSUE TITLE
Extent template parameter for czstring

### ISSUE THREAD

**Issue by unixod** [microsoft/GSL#770]
Hi,
Could you tell me please what is the reason of introducing *Extent* template parameter for *czstring* class?

**Comment by hsutter** [comment]
Maintainers' call: Sorry for the delay in replying. You are correct, it shouldn't have one, this was a design later changed. The Guidelines have removed all `*string_span` types, and it still has `zstring` and `czstring` as aliases for `char*` and `const char*` which don't have member functions.
