### ISSUE TITLE
Implement gsl::ssize() like new std::ssize()

### ISSUE THREAD

**Issue by KindDragon** [microsoft/GSL#771]
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1227r1.html

**Comment by JordanMaples** [comment]
Maintainer's call: we suggest relying on the standards version of std::ssize instead of duplicating the efforts in GSL.

**Comment by KindDragon** [comment]
I just want  `ssize()` in my C++ 14 compiler
