### ISSUE TITLE
C++17 and CI issue

### ISSUE THREAD

**Issue by AaronBlare** [microsoft/GSL#773]
Hi! 

I have a question about c++17 standard and CI (Travis and Appveyor) settings. 
In c++17 filesystem was introdused: 

#include <filesystem> 
namespace fs = std::filesystem; 

I just add this include and simple call to the lib to test how CI settings works with it and with c++17 at all. 
But I obtain errors in all builds in CI: 
fatal error: 'filesystem' file not found 
#include <filesystem> 
               ^ 

I created fork from this repo, added it to my Travis and Appveyor, and added this simple commit to my master with filesystem usage. 
https://github.com/AaronBlare/GSL
https://travis-ci.org/AaronBlare/GSL
https://ci.appveyor.com/project/AaronBlare/gsl

Can someone help me please to fix this issue with CI + c++17 (filesystem)? 

Thanks!

**Comment by hannes-steffenhagen-diffblue** [comment]
Not all the test environments this library is building against support C++17. This is by design, this library is supposed to work on older compilers as well.
