### ISSUE TITLE
make_subspan should be marked noexcept

### ISSUE THREAD

**Issue by dorssel** [microsoft/GSL#775]
Detected by latest VS2019 + "All Rules" analysis. `make_subspan` only calls `size()`, which is `noexcept`.

**Comment by MikeGitb** [comment]
Is there no range check?

**Comment by dorssel** [comment]
Only in the form of `Expects()`, which terminates. It does not throw.

**Comment by maikel** [comment]
What `Expects()` does, depends on the user configuration.

https://github.com/Microsoft/GSL/blob/7d78b743e43ecba06ca47426d03d9d16076dec16/include/gsl/gsl_assert#L53-L60

**Comment by dorssel** [comment]
Then something like this in gsl_assert

```
#if !defined(GSL_THROW_ON_CONTRACT_VIOLATION)
#define GSL_NOEXCEPT_ON_CONTRACT_VIOLATION false
#else
#define GSL_NOEXCEPT_ON_CONTRACT_VIOLATION true
#endif
```

and a `noexpect(GSL_NOEXCEPT_ON_CONTRACT_VIOLATION)` marker?

**Comment by hsutter** [comment]
Or just

~~~
#if defined(GSL_THROW_ON_CONTRACT_VIOLATION)
#define GSL_NOEXCEPT
#else
#define GSL_NOEXCEPT noexcept
#endif
~~~

**Comment by JordanMaples** [comment]
Maintainer's call: `make_subspan` is now `noexcept`. Throwing behaviors have been removed for contract violation.
