### ISSUE TITLE
Successful Build (macOS Mojave 10.14.3, clang 10)

### ISSUE THREAD

**Issue by z3ndrag0n** [microsoft/GSL#777]
macOS Mojave 10.14.3
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
(cmake version 3.14.2)

100% tests passed, 0 tests failed out of 15

(No source changes required.)

**Comment by JordanMaples** [comment]
Maintainers' call: Thanks for this. I've updated the readme.
