### ISSUE TITLE
Successful Build (macOS Mojave 10.14.4, clang 10.0.1)

### ISSUE THREAD

**Issue by z3ndrag0n** [microsoft/GSL#778]
macOS Mojave 10.14.4
Apple LLVM version 10.0.0 (10.0.1.10010046)
(cmake version 3.14.2)

100% tests passed, 0 tests failed out of 15

(No source changes required.)

**Comment by JordanMaples** [comment]
Maintainers' call: Thanks for this. I've updated the readme.
