### ISSUE TITLE
not_null does not work

### ISSUE THREAD

**Issue by Aerma7309** [Microsoft/GSL#781]
it causes core dump in fedora 29 workstation

#include<gsl/gsl>
int main()
{
    int t=10;
    int * a = nullptr;
    gsl::not_null<int*> p=a; ;
    printf("%d %p",t,p);
}

**Comment by beinhaerter** [comment]
What do you expect the code to do?
`a` is a `nullptr` and you try to assign it to a `gsl::not_null` which is designed to guarantee that the pointer it holds is not a `nullptr`. So when you assign `p=a` then the GSL calls `std::terminate` to terminate the process which in your case triggers a core dump.
So your observations show that the class works exactly as it should do.
