### ISSUE TITLE
Make gsl::span::index_type std::size_t

### ISSUE THREAD

**Issue by RedDwarf69** [microsoft/GSL#782]
Currently gsl::span::index_type is std::ptrdiff_t, but C++20 will use std::size_t (https://en.cppreference.com/w/cpp/container/span) and span-lite is planing to do the move (https://github.com/martinmoene/span-lite#select-index-type).

**Comment by anordal** [comment]
Ditto for `size()`: #559

**Comment by JordanMaples** [comment]
See isocpp/CppCoreGuidelines#1511

**Comment by hsutter** [comment]
Guidelines editors' call: Yes, let's change it to unsigned. We'll update the Guidelines.

**Comment by natersoz** [comment]
What do you do with `rend()` which needs to index to -1 ?

**Comment by anordal** [comment]
> rend()

I would turn that question on its head and ask when -1 needs to be < 0.

**Comment by JordanMaples** [comment]
Maintainer's call: Closing this gsl::span is now unsigned.
