### ISSUE TITLE
gsl::contiguous_span_iterator is not default constructible

### ISSUE THREAD

**Issue by nholthaus** [microsoft/GSL#785]
since `gsl::contiguous_span_iterator` for a `multi_span` isn't default constructable, it doesn't meet the basic requirements of a forward iterator and can't be used by stl algorithms like `transform_reduce`.

I understand the private friend construction for valid iterators, but it doesn't seem like a there's a good reason why this iterator can't be default constructed or copied, especially when the upside is compliance with iterator categories and access to standard algorithms.

**Comment by JordanMaples** [comment]
Maintainers' call: Now that the multidimensional version of span was not accepted by the committee from the GSL proposal and is not mentioned in the Core Guidelines, we should probably deprecate multi_span from this GSL implementation.

**Comment by JordanMaples** [comment]
Maintainer's call: multi_span is now deprecated, closing.
