### ISSUE TITLE
multi_span includes cassert although it seems unnecessary.

### ISSUE THREAD

**Issue by hawesy** [microsoft/GSL#788]
I had a quick look through the rest of the code and it doesn't appear any symbols from cassert are necessary. Perhaps I missed something.

I have been able to remove it and test with GCC 7.3.1-5 (RedHat DTS-7) and Visual Studio 2019 (toolset v142) without any issues. I was unable to test other toolchains easily.

**Comment by JordanMaples** [comment]
Maintainer call: You're right @hawesy, it doesn't belong in multi_span. I removed the include during the deprecation of multi_span. https://github.com/microsoft/GSL/commit/e026971c03ea0495f9623d9aad7a9beca24b5692#diff-3936738b18d7dd0f0fb8976e9e752b2e
