### ISSUE TITLE
owner should not be copyable

### ISSUE THREAD

**Issue by marcpawl** [microsoft/GSL#789]
It should not be allowed to have two owners for a pointer.

    int* p = new int(3);
    owner<int*> sut(p);
   
This says sut is the owner and is responsible for deleting p.
   
If we then have:

    owner<int*> usurper(sut);
 
Who is responsible for deleting p?  This should be a compile time failure.

Also for assignment: 

     owner<int*> usurper;
     usurper = sut;

Again I would expect a compile time failure.

**Comment by johelegp** [comment]
If you want a compile-time error for those, then you should use `std:::unique_ptr`. `gsl::owner<T*>` is (intentionally) just an alias for `T*` meant for human readers and static analysers. See [R.3](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-ptr) and [GSL.view](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#SS-views) on the topic.

**Comment by JordanMaples** [comment]
As correctly expressed by @johelegp, owner is just an alias for a ptr so we can't ban copying it.
