### ISSUE TITLE
Why does fail_fast_assert throw and not assert?

### ISSUE THREAD

**Issue by rodiers** [Microsoft/GSL#79]
I know that people have different opinions about this, but in the design by contract community most people seem to adhere to this principle:
Use asserts for invariants, preconditions and postconditions. Use exceptions when user input is involved. 

The purpose is to fail fast, and an assert is a way to fail faster since exceptions can be caught and hence worked around. People should never be able to work-around these invariants. If you fail to comply with the preconditions anything can happen (which I consider a good thing) and the implementations should not continue as if nothing happened.

If you follow this principle, Expects and Ensures should assert and not throw. It also means that you shouldn't put something in an not_null when it directly comes from the user  (for example input data from a text file, something coming from an edit box, ...) since you are not sure that the precondition is fulfilled and hence it doesn't make sense to let not_null throw.

Some people also follow a slightly different variant: Use asserts for logic errors in your own code and exceptions when client code is involved. The different with the previous principle is that here the we are talking about client *code* and not user *input*. Since for example a not_null can be both used internally and at the border of the interface for the client you might want to use exceptions in for not_null when (and only  when) client code is involved. In this case you might want to add a policy to these classes to be able to specify the desired fail behavior.

Anyway, since (some) people would like to be able to use these libraries without having exceptions, but have asserts instead, it makes sense to let the users to this library specify what should happen when the pre- and postconditions are not met. Next to the conceptual reasons there is also a performance reason. If the code is guaranteed not to throw more optimizations can be done.

**Comment by neilmacintosh** [comment]
I suspect you have misunderstood the implementation. The library only throws exceptions if configured to do so for testing (and ONLY for testing according to the design).

When used normally, it "fails fast" (i.e. calls std::terminate()) if a precondition, postcondition or invariant is violated.

**Comment by rodiers** [comment]
My point is actually that I want to be able to specify the behavior in some way. For example I might want to have the behavior of assert and not directly terminate.

**Comment by tamaskenez** [comment]
Reading the specification of **std::assert** and **std::terminate** suggests they are doing the same thing: Provided `#ifdef NDEBUG` and the default terminate handler is active, they both call **std::abort**
The only difference is the diagnostics sent to `stderr`.

**Comment by rodiers** [comment]
@tamaskenez Yes, the diagnostics are a big difference.
Anyway once (if?) we'll have contracts (http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2015/n4415.pdf), I guess that this library will implement that mechanism...

**Comment by tamaskenez** [comment]
You're right, my homebrew implementation of the **fail_fast_assert** concept is also more like an NDEBUG-independent **assert**.

**fail_fast_assert* could issue some assert-like diagnostics before calling std::terminate
