### ISSUE TITLE
borrower wanted

### ISSUE THREAD

**Issue by marcpawl** [microsoft/GSL#790]
When working with legacy code we have the owner class to indicate we are taking care of deleting a resource.  However if we have a class that holds the pointer but is not the owner then we have now way of indicating that we are not going to delete the pointer versus this is old code that we have not changed with respect use of owner, shared_ptr, unique_ptr.

    struct Listener;   
   struct Model {
    Listener* listener_;
    void set_listener(Listener* listener){ listener_ = listener; }
 };

Is it not clear from the API if model is going to take over ownership of the listener.  If however we had a class borrower similar to owner

    struct Listener;   
   struct Model {
    borrower<Listener*> listener_;
    void set_listener(borrower<Listener*> listener){ listener_ = listener; }
 };

it becomes clear that Model will not be taking ownership of listener, and that the object lifetime was specified.  Contrast the core guideline may not apply for legacy code.

Ideally a borrower should be able to be constructed and assigned from:
- owner
- raw pointer
- shared_ptr
- unique_ptr
   
From P.8: Don’t leak any resources
Look at pointers: Classify them into non-owners (the default) and owners. Where feasible, replace owners with standard-library resource handles (as in the example above). Alternatively, mark an owner as such using owner from the GSL.

you do not want to have to repeatedly verify that Model is a non-owner of listener.

**Comment by JordanMaples** [comment]
Maintainers' call: We're just implementing what is specified in the C++ Core Guidelines. If you'd like an extension, please file a new issue [here](https://github.com/isocpp/cppcoreguidelines/issues). Thanks!
