### ISSUE TITLE
Travis CI build fails

### ISSUE THREAD

**Issue by jack17529** [microsoft/GSL#792]
I submitted a PR - https://github.com/microsoft/GSL/pull/791, and this is the log for the unexpected failure - https://travis-ci.org/microsoft/GSL/jobs/543470413

It would be great help if someone could get this fixed.

Thank You

**Comment by JordanMaples** [comment]
I pinged on #791 for additional comments.

**Comment by JordanMaples** [comment]
Maintainer's call: Closing this issue. Travis is currently passing and #791 is closed.
