### ISSUE TITLE
How to understand ower<T>'s definition?

### ISSUE THREAD

**Issue by carson-yang** [microsoft/GSL#793]
template <class T, class = std::enable_if_t<std::is_pointer<T>::value>>
using owner = T;

I search many resources,  I cannot find way of use like "class = XXX"

**Comment by johelegp** [comment]
It's an alias template. See https://en.cppreference.com/w/cpp/language/type_alias.

**Comment by carson-yang** [comment]
thank you, I see that template parameter's name is optional.

**Comment by johelegp** [comment]
Sorry I sent you on a roundabout research. It was late, so I thought your `=` in `class = XXX` meant `owner = T` and not `class = std::enable_if_t<std::is_pointer::value>`.
