### ISSUE TITLE
c.61 unclear semantics

### ISSUE THREAD

**Issue by beinhaerter** [microsoft/GSL#794]
The reason paragraph describes the terms `value semantics` and `pointer semantics`.
The note paragraph says "Prefer copy semantics".
What is meant with "copy semantics"? Wouldn't it be better to say "value semantics" as this term is described in the reason paragraph?

**Comment by johelegp** [comment]
You should open these at https://github.com/isocpp/CppCoreGuidelines.

**Comment by beinhaerter** [comment]
> You should open these at https://github.com/isocpp/CppCoreGuidelines.

Of course. I meant to do so but mixed up two of my GitHub favorite repos :O.
