### ISSUE TITLE
gsl::at seems to trigger bad code generation in x86-Release build

### ISSUE THREAD

**Issue by anticrisis** [microsoft/GSL#796]
Here is a simple minimal project demonstrating the problem: https://github.com/anticrisis/vs-temp-ref-method-invoke. This was reproduced using Visual Studio 2019, and also Preview 3.

In a nutshell, there seems to be some interaction with a call to `gsl::at` invoked earlier in a function which then calls a member function of an object referenced via a temporary, which takes a lambda as an argument. Either replacing `gsl::at` with a direct array reference or avoiding the use of a temporary object avoids the problem.

The assembly language generated in the failing case looks a bit odd to me, but I don't have much experience with assembly-level debugging.

(I haven't tried eliminating the lambda from the test case yet, but I suspect all three factors may be needed: `gsl::at`, a temporary, and a lambda.)

Excerpts from the project:

```cpp
    // this version uses gsl::at, and triggers the later corruption error
    const auto& GetFoo(int i) const noexcept { return gsl::at(foos, i); }

    // use this version to prevent corruption in all cases
    //const auto& GetFoo(int i) const noexcept { return foos[i]; }
```

In this next section, `Check` is a function that will trigger the memory access violation (or throw an exception if its invariant is violated), and `Run` is a function which calls `Check`.

```cpp
    // this call to the gsl::at version of GetFoo causes the corruption
    const auto& foo = GetFoo(2);

    // this next line succeeds in all cases (Check will later trigger memory access violation)
    handle.Get().Check();

    auto count = 0;
    const auto f = [&](int) {
        ++count;
    };

    // this call to VectorOwner::Run succeeds in all cases, because a
    // temporary is not used
    auto& vo = handle.Get();
    vo.Run(f);

    // this next call fails in its call to Check() if GetFoo uses gsl::at
    handle.Get().Run(f);
```

This bug was difficult to isolate from a larger project, so hopefully my test case will help identify the cause. Project at https://github.com/anticrisis/vs-temp-ref-method-invoke.

**Comment by anticrisis** [comment]
Here is a screenshot of what looks like bad code generation. Note the two lines with the red dot in the left margin. Those move instructions are intending to provide the `this` pointer to the called method. In both the good and bad versions, the first call to Run() uses the same convention. But in the bad version, the second call to Run provides `[esp+30h]` as the `this` pointer, which is can be seen to be invalid when stepping through the debugger.

![bad-version-2](https://user-images.githubusercontent.com/20313596/61031011-5d58de00-a35a-11e9-85a8-24b9f894d49e.png)

The good version generates the following calling conventions, which are identical in both calls to the Run() method:

![good-version-2](https://user-images.githubusercontent.com/20313596/61031252-ce989100-a35a-11e9-9209-4718930dbb91.png)

**Comment by anticrisis** [comment]
Running the same code with clang using Visual Studio 2019 Preview's clang support does not generate the bug, so this looks like an MSVC-specific problem.

**Comment by tiagomacarios** [comment]
Please report the issue here: https://developercommunity.visualstudio.com/content/problem/post.html?space=62

**Comment by anticrisis** [comment]
The problem is being tracked here: https://developercommunity.visualstudio.com/content/problem/635684/bad-code-generated-in-x86-release-when-using-gslat.html

**Comment by anticrisis** [comment]
Tested with Version 16.3.0 Preview 1.0: fixed! (code generation has changed)

Tested with Version 16.2.0: problem still occurs

**Comment by anticrisis** [comment]
Tested with Visual Studio 16.2.2: code generation changed, and the problem no longer occurs. Closing this issue.
