### ISSUE TITLE
string_view header includes gsl/pointers, doesn't seem to need it

### ISSUE THREAD

**Issue by eyalroz** [microsoft/GSL#798]
In the [`string_view` header](https://raw.githubusercontent.com/microsoft/GSL/master/include/gsl/string_span), we have the following line:
```
#include <gsl/pointers>   // for not_null
```
The thing is, `string_view` doesn't use `not_null` anywhere. So, is it really needed in there, or can it be dropped?

**Comment by beinhaerter** [comment]
gsl/pointers also exposes `owner`, but that isnt't used either.
If you want to, just prepare a pull request that removes the `#include`. It the maintainers don't like it, they will tell you so in the PR.

**Comment by eyalroz** [comment]
@beinhaerter : Ok, I guess I can do that. I was thinking I might be missing something.

**Comment by beinhaerter** [comment]
Just my two (irrelevant) cents: for very small changes it is less overhead to issue a PR. There can also be discussion in a PR. And if it doesn't fit the maintainer's ideas it can be closed. Of course for more complicated stuff I would open an issue first. But that might only be my opinion (and I am not an open source expert).
