### ISSUE TITLE
Why aren't more functions in string_span constexpr?

### ISSUE THREAD

**Issue by eyalroz** [microsoft/GSL#799]
I'm seeing some functions/methods within [`gsl/string_span`](https://github.com/microsoft/GSL/blob/master/include/gsl/string_span) which seem like they should be `constexpr` - but aren't. For example:

* [`details::string_length`](https://github.com/microsoft/GSL/blob/1212beae777dba02c230ece8c0c0ec12790047ea/include/gsl/string_span#L90)
* [`ensure_z`](https://github.com/microsoft/GSL/blob/1212beae777dba02c230ece8c0c0ec12790047ea/include/gsl/string_span#L138)

Is there a good reason for this? It's not like they use `std::string` or anything... Why not make more functions in that file constexpr?

**Comment by JordanMaples** [comment]
Maintainers' call: Sorry for the delay. Everything is now constexpr that can be.

**Comment by eyalroz** [comment]
@JordanMaples : But the two examples I've given not constexpr. So, clearly not everything is constexpr that can be.

Like with my other issue - please don't rush to close issues that haven't actually been resolved.

**Comment by JordanMaples** [comment]
@eyalroz thanks for pointing that out, I was misremembering other work that I did w/ constexpr in the  area. 

I merged #922 today which added constexpr to more functions in string_span. Please let me know if there are more functions that could be constexpr or feel free to create a PR with any improvements you'd like to see. Thanks.

**Comment by eyalroz** [comment]
I haven't made a careful inspection of everything. But - this at least answers the title of this issue, so, I'm satisfied for now.
