### ISSUE TITLE
Works on FreeBSD 10.x

### ISSUE THREAD

**Issue by davidchisnall** [Microsoft/GSL#80]
As requested, this is a report that the library builds and works with FreeBSD 10.x.  The default system c++ compiler (clang 3.4) is too old, but installing the `clang36`  package and setting `-DCMAKE_CXX_COMPILER=clang++36` or `-DCMAKE_CXX_COMPILER=clang++37` when installing results in all tests passing.

**Comment by gdr-at-ms** [comment]
Thanks David.  README updated.
