### ISSUE TITLE
narrow is too wide

### ISSUE THREAD

**Issue by johnmcfarlane** [microsoft/GSL#802]
Can I ask why `narrow` [throws](https://github.com/microsoft/GSL/blob/master/include/gsl/gsl_util#L116) an exception on information loss? Should that not be considered a programmer bug?

**Comment by johnmcfarlane** [comment]
Alternatively, could `narrow_cast` promise no information loss as part of its contract?

**Comment by JordanMaples** [comment]
isocpp/CppCoreGuidelines#1498

**Comment by mbeutel** [comment]
> Alternatively, could `narrow_cast` promise no information loss as part of its contract?

Currently `narrow_cast<>()` is explicitly specified to tolerate information loss:

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#note-204

> ```c++
> double d = 7.9;
> ```
> ...
> The guidelines support library offers a `narrow_cast` operation for specifying that narrowing is acceptable and a `narrow` ("narrow if") that throws an exception if a narrowing would throw away information:
> 
> ```c++
> i = narrow_cast<int>(d);   // OK (you asked for it): narrowing: i becomes 7
> i = narrow<int>(d);        // OK: throws narrowing_error
> ```

So there is no way to get narrowing with a fail-fast check. I'm in favor of the change you propose, but it will be a big breaking change.

Perhaps it would make sense to add a third option, tentatively named `narrow_or_fail<>()`?

**Comment by johnmcfarlane** [comment]
Thanks for the suggestion. Yes, unless someone is willing to backtrack hugely on this and break a lot of code, I'm inclined to thing that both `narrow` and `narrow_cast` are irrevocably broken. When do we ever want `narrow_cast<char>(1000)` to not be a contract violation? And when is `narrow<char>(1000)` ever not a bug?

Hopefully there'll be something in the standard some day which gets this right. In the mean time, we should consider discouraging use of these wrappers in the Core Guidelines as it sends a bad message.

For more background on why bugs should be treated as contract violations and not exceptions read [P0709R3](https://wg21.link/p0709r3).
