### ISSUE TITLE
does array_view assume "default char unsigned" ?

### ISSUE THREAD

**Issue by jmuffat** [Microsoft/GSL#81]
Problem when using unsigned char:
`array_view.h(495):   const char dynamic_range = -1;`

Problem when using signed char, many of the following:
`array_view.h(xxxx): warning C4245: 'initializing': conversion from 'const char' to 'const size_t', signed/unsigned mismatch`

I'm not too keen on disabling the related warnings...

**Comment by KristofferHenriksson** [comment]
This warning appears when just including array_view.h in VC++ 2015 with the warning level set to 4.

c:\gsl\array_view.h(1228): warning C4245: 'initializing': conversion from 'const char' to 'const size_t', signed/unsigned mismatch (compiling source file App.xaml.cpp)
c:\gsl\array_view.h(1228): warning C4245: 'initializing': conversion from 'const char' to 'size_t', signed/unsigned mismatch (compiling source file App.xaml.cpp)

**Comment by OlafvdSpek** [comment]
char is usually signed but could be unsigned, so using just char to store -1 doesn't seem like a good idea.

**Comment by neilmacintosh** [comment]
The implementation no longer uses char (signed or unsigned) to represent a dynamic range value, so this issue is now obsolete.
