### ISSUE TITLE
Is there a reason there are no free-standing begin() and end() functions for gsl::span?

### ISSUE THREAD

**Issue by omartijn** [microsoft/GSL#810]
I usually use free-standing `begin()` and `end()` for getting iterators on my containers. This has worked fine for me, since it uses ADL to find the function in the relevant namespace, while allowing me to override it locally.

Now these functions aren't defined in the GSL namespace. Is there a specific reason for not doing this? If not, I could easily whip up a PR.

Note about standardization, when `std::span` is standardized it would obviously work with that, since then the span is defined in the std namespace, which has `begin()` and `end()` functions, so adding these functions now will make it behave more like `std::span`.

**Comment by mbeutel** [comment]
Don't you do the two-step dance anyway when writing generic code?

```c++
template <typename R>
    auto myAlgorithm(R&& range)
{
    using std::begin;
    using std::end;
    auto e = end(range);
    for (auto i = begin(range); i != e; ++i) { ... }
}
```

This makes your algorithm work for plain arrays as well as for `gsl::span<>`.

In C++20 you can simplify this by using `ranges::begin()`/`end()`.

**Comment by omartijn** [comment]
@mbeutel I _could_ do that, indeed. I don't normally do that, though. It'd be nice if this would just work with gsl::span.

**Comment by mbeutel** [comment]
I disagree with the idea that custom containers should provide custom freestanding `begin()`, `end()`, `size()`, `ssize()` functions.

What is the benefit of writing `begin(c)` over `c.begin()` in your scenario?

**Comment by JordanMaples** [comment]
Maintainers' call: You're right, we should provide begin, end, size, and ssize functions as non-members.
