### ISSUE TITLE
MSVC min/max macro collision with numeric_limits

### ISSUE THREAD

**Issue by andreduvoisin** [microsoft/GSL#816]
MSVC with windows.h included and without NOMINMAX defined causes a min/max macro collision with numeric_limits in multi_span. For projects with warnings as errors enabled, this breaks the build.

MSVC 14.2 Warning:

```
C:\path\to\GSL\include\gsl\multi_span(86): warning C4003: not enough arguments for function-like macro invocation 'max'
```

Clang Diagnostic:

```
Error while processing RedactedFile.h.
path\to\GSL\include\gsl/multi_span:86:78: error: too few arguments provided to function-like macro invocation [clang-diagnostic-error]
        static const SizeType max_value = std::numeric_limits<SizeType>::max();
                                                                             ^
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared\minwindef.h:193:9: note: macro 'max' defined here
#define max(a,b)            (((a) > (b)) ? (a) : (b))
        ^
```

**Comment by andreduvoisin** [comment]
PR submitted with fix. #817

**Comment by SanderBouwhuis** [comment]
So, is this now fixed? I discovered GSL yesterday and was interested to use it.
I ran into the same issue.

**Comment by andreduvoisin** [comment]
Not yet. The PR is submitted and all tests pass — it just needs to be reviewed by a maintainer and merged. Not sure why it hasn’t been looked at yet, but other PRs submitted after this one also haven’t gained any traction.

Maybe @JordanMaples or @annagrin could help out?

**Comment by SanderBouwhuis** [comment]
Thanks Andre. I simply did the changes you suggested and it seems to work.

Very strange that Microsoft hasn't even tested this in their own compiler.

**Comment by JordanMaples** [comment]
What is the aversion to using NOMINMAX? The problem lies with presence of the min and max macro definitions. I'm hesitant to take this fix because it's not an issue with the implementation of the GSL itself. 

To clarify the lack of traction, generally I only address GSL related issues on Wednesdays, but I was out of the office last week.

Thank you for your patience.

**Comment by JordanMaples** [comment]
@SanderBouwhuis 

GSL itself should be able to compile out of the box to be used in your applications without any sort of an additional overhead. Is it only when you're trying to use it in conjunction with windows.h that you're having issues or are you running into issues in general?

The reason for needing to define `NOMINMAX` is to prevent macro expansion of all instances of the words `min` and `max`. You can think of the preprocessor as a really naive token replacement engine that just says "oh hey, it's that max keyword thing! I better swap it out." without taking any context into consideration. So you'll even see compiler errors if you try invoking std::max from the `algorithm` header. A search on Github finds about 450k instances of `NOMINMAX` either surrounding `Windows.h` includes or as a compile definition, so it's by no means an isolated issue.

I'm not familiar with GSL-lite, though I had a quick look at it and found that they surround the numeric_limits max call with the parentheses just like how @andreduvoisin suggests to fix it in pr #817. I'm not sure how often the maintainer(s) of gsl-lite updates with changes from this repo or how far it's diverged.

**Comment by SanderBouwhuis** [comment]
I indeed use Visual Studio to create Windows compatible desktop applications. I also include Windows.h.

Ok, maybe a stupid question then.
Why is the min/max in there if it seems to cause so much trouble? In all honesty I've been using my own min and max routines and macros without encountering problems with min/max macros from Microsoft or std... until gsl that is.

**Comment by JordanMaples** [comment]
Maintainers' call: GSL is made to work with Standard C++ and we encourage conventional function call syntax. `min` and `max` macros are non-standard so you should use NOMINMAX.

**Comment by ocitrev** [comment]
> What is the aversion to using NOMINMAX? The problem lies with presence of the min and max macro definitions. I'm hesitant to take this fix because it's not an issue with the implementation of the GSL itself.

Gdiplus.h won't compile with NOMINMAX, I get those errors in GdiplusTypes.h:
```
error C3861: 'max': identifier not found
error C3861: 'min': identifier not found
```

**Comment by MikeDai2020** [comment]
Maybe you should define NOMINMAX before the #include head file.@ocitrev

**Comment by ocitrev** [comment]
> Maybe you should define NOMINMAX before the #include head file.@ocitrev

I don't understand, can you give an example ?
