### ISSUE TITLE
throw_exception() is not appropriately defined for GSL_UNENFORCED_ON_CONTRACT_VIOLATION

### ISSUE THREAD

**Issue by alexkaratarakis** [microsoft/GSL#818]
According to the `gsl_assert` header:
```
// There are three configuration options for this GSL implementation's behavior
// when pre/post conditions on the GSL types are violated:
//
// 1. GSL_TERMINATE_ON_CONTRACT_VIOLATION: std::terminate will be called (default)
// 2. GSL_THROW_ON_CONTRACT_VIOLATION: a gsl::fail_fast exception will be thrown
// 3. GSL_UNENFORCED_ON_CONTRACT_VIOLATION: nothing happens
```

When `GSL_UNENFORCED_ON_CONTRACT_VIOLATION` is selected, nothing
should happen, but throw_exception()'s behavior is not consistent
with this.

`throw_exception()` is notably used in `narrow()`, which in turn is used by the `gsl::span(Container)` constructor.

**Comment by JordanMaples** [comment]
Maintainer's call: The Core Guidelines editors have given guidance in the following issue
isocpp/CppCoreGuidelines#1512 that contract violations should not throw, they should terminate.

We need to remove the throwing options entirely, not just when they are unenforced.

**Comment by JordanMaples** [comment]
Maintainer's call: Closing issue as contract violation now only results in termination.
