### ISSUE TITLE
Can we do without the macro _NOEXCEPT?

### ISSUE THREAD

**Issue by gdr-at-ms** [Microsoft/GSL#82]
Most places in `array_view.h` can do just fine with plain `noexcept` even when testing with exceptions on.

**Comment by neilmacintosh** [comment]
But there will still be places we do require it in order to test the library. So then you hit the issue of consistency.

**Comment by gdr-at-ms** [comment]
Yes, but it would be much better to spell those out explicitly.  Especially, given that this is primarily to accommodate the testing framework.
