### ISSUE TITLE
gsl_byte should inspect __cpp_lib_byte in addition to _HAS_STD_BYTE

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/GSL#821]
https://github.com/microsoft/GSL/blob/3d56ba9e7f2d61fd8c9c2a7715b46fde38c00123/include/gsl/gsl_byte#L43-L54

inspects an implementation-specific macro `_HAS_STD_BYTE` defined by MSVC's STL:

https://github.com/microsoft/STL/blob/447f879b136950baf3ca35dfb54c359494fa2a77/stl/inc/yvals_core.h#L475-L477

instead of the Standard feature-test macro `__cpp_lib_byte`:

https://github.com/microsoft/STL/blob/447f879b136950baf3ca35dfb54c359494fa2a77/stl/inc/yvals_core.h#L888-L890

GSL could inspect both, which would make it compatible with:

* VS 2017 15.3 (which added `std::byte` and `_HAS_STD_BYTE`) through 15.7
* VS 2017 15.8 (which added `__cpp_lib_byte`) through VS 2019 today
* Future versions of VS (when GSL stops inspecting `_HAS_STD_BYTE` alone, VS can stop defining it).

**Comment by JordanMaples** [comment]
@StephanTLavavej The changes to gsl_byte are merged.
