### ISSUE TITLE
Need explanation of differences between gsl::span and std::span

### ISSUE THREAD

**Issue by eyalroz** [microsoft/GSL#839]
C++20 will have `std::span` standardized. 

* Does `gsl::span` satisfy the requirements of an `std::span` implementation (other than the different namespace)? If it doesn't, how?
* Does `gsl::span` have standard-compliant behavior or features beyond what's defined for  `std::span`? (Yes, it does, e.g. `::at()`) ? If so, what is it?

Answers to these questions, and an overview of the difference between `gsl::span` and `std::span` implementations (e.g. in libstdc++ and libc++) should be provided somewhere. I believe the wiki is an appropriate place, with a link from `README.md`.

**Comment by JordanMaples** [comment]
Thanks for bringing this up. I'll file a task to write a wiki page for this.

**Comment by JordanMaples** [comment]
Maintainers' call: Sorry for the delay but the only difference is guaranteed bounds checking.

**Comment by eyalroz** [comment]
@JordanMaples : You don't need to explain it to me on this issue page - it needs to be explained visibly so that people using this library will be aware of this.

**Comment by JordanMaples** [comment]
I added a wiki page explaining the differences [here](https://github.com/microsoft/GSL/wiki/gsl::span-and-std::span). The readme's Supported Features mentions that span is "Based on the standardized verison of std::span, however gsl::span enforces bounds checking." I'll append that users can find additional information on the wiki.

**Comment by eyalroz** [comment]
@JordanMaples : So, about that bounds checking: Is it still on even if you're compiling with NDEBUG?

**Comment by JordanMaples** [comment]
@eyalroz Yes, we don't provide a way to disable the bounds checking for gsl::span

**Comment by eyalroz** [comment]
> @eyalroz Yes, we don't provide a way to disable the bounds checking for gsl::span

I didn't even realize that, actually. The core guidelines don't mandate that, right? I think it's important for the wiki page to state that the bounds checking is applied both in debug and non-debug compilation.

Other than that - this bug is now legitimately closed, but I encourage you to add wiki pages with similar information about other GSL types, like `byte` and `string_span`; and perhaps additional descriptions/tips regarding other GSL types.
