### ISSUE TITLE
plan/timetable to deal with warnings when using microsoft all rules VS 2019 C++17

### ISSUE THREAD

**Issue by JackHeeley** [microsoft/GSL#841]
When using Microsoft GSL 0.1.2.1 it seems that we currently need to work around the impact of compiler checking improvements since Microsoft GSL was originally released. 

This could be professionally embarrassing since the whole philosophy being promoted here is that all warnings can and should be addressed by a rework, or expressly accepted/commented and locally accepted once on each line affected. At least that's best practice as I understand it. This is already a hard sell.

So my question is IS THERE A PLAN/TIMETABLE to revise the gsl headers (C++14 days) to pass the current compiler full checks? Otherwise while promoting GSL we have to defend it against accusations of hypocracy.  "Don't do as we do. Do as we say". I appreciate its a constantly moving target but I think its time to consider, and I'd like to know the plans.

Meanwhile (for my code) I've found this to be a practical workround.

[gsl.zip](https://github.com/microsoft/GSL/files/4108025/gsl.zip)

**Comment by hsutter** [comment]
Maintainers' call: We have updated this in newer versions of GSL so that they should not be showing any warnings under full checks. If you see any we missed in the current version of GSL with the current version of full warnings please file issues to let us know specific cases so we can fix any we missed.

**Comment by JackHeeley** [comment]
Any missed? at last check (a month or so ago, with my code base VS v16.7.5 /std:c++17) I still needed these two: 
#define GSL_WARNINGS_SUPPRESSED 26472 26481

**Comment by JackHeeley** [comment]
FYI... MSVC 16.8.3 & GSL 3.1.0 (both latest I think) still gives these... 
C:\Users\jackh\Source\Repos\App3Dev\include\gsl\span(63): warning C26472: Don't use a static_cast for arithmetic conversions. Use brace initialization, gsl::narrow_cast or gsl::narrow (type.1).
C:\Users\jackh\Source\Repos\App3Dev\include\gsl\span(449): warning C26481: Don't use pointer arithmetic. Use span instead (bounds.1).
No impact for me & don't mean to distract you. I just note that a ticket is closed without a fix and being a "quality officer" that raises the hairs on the back of my neck ;-)

**Comment by JordanMaples** [comment]
GSL 3.1.0 would still give you those warnings. They're fixed in the master branch but an updated release hasn't been made yet.

**Comment by JackHeeley** [comment]
Thanks Jordan!
