### ISSUE TITLE
Compilation error with GCC 7.2.1 when GSL_USE_STD_BYTE=1

### ISSUE THREAD

**Issue by ombre5733** [microsoft/GSL#852]
The header `gsl_byte` includes `<cstddef>` in order to detect if `std::byte` is available. However, if the define `GSL_USE_STD_BYTE=1` is set, that header gets not included. This in turn leads to `std::byte` being not defined in the `gsl_byte` header, which results in a compilation error with at least GCC 7.2.1.

A workaround is to always `#include <cstdef>` before `#include <gsl/span>` (or other headers).

A fix has already been submitted in #823.

**Comment by JordanMaples** [comment]
Closing since #823 has been merged.
