### ISSUE TITLE
Compilation errors due to unscoped ptrdiff_t

### ISSUE THREAD

**Issue by masonboswell** [microsoft/GSL#865]
I get build errors in multi_span due to the 3-4 places where ptrdiff_t is used without the namespace in front of it (std::ptrdiff_t).  It seems like the namespace appears in some uses throughout the file but not others.  Adding these I get no build errors.  This is happening with the 3.0 release from an hour ago as well as before.

**Comment by JordanMaples** [comment]
Our implementation of multi_span and strided_span are deprecated and aren't officially supported anymore. There are a few users who have taken copies of the implementation to maintain themselves. 

However, if the change is as trivial as qualifying the std namespace, please create a PR and I'll merge it (provided the tests all pass).

**Comment by JordanMaples** [comment]
@masonboswell did the change in #874 fix your build issue?

**Comment by masonboswell** [comment]
Yes, thank you!  3.0.1 builds clean for me with no changes.
