### ISSUE TITLE
Make a proper "Release" (Package), or at least update the existing NuGet package.

### ISSUE THREAD

**Issue by CodeChief** [microsoft/GSL#866]
The NuGet package added as feature on request of issue #183 has been forgotten since 2016 and the built-in GSL (you find dotted around the MS online documentation) is useless in recent versions because it excluded the appropriate suppression headers needed to work effectively with the GSL code analysis warnings. Since the NuGet package is no longer maintained that meant it has been necessary to manually create scripts to download and update the source "release" here, which you can't really call a release as some sort of package or installable is expected nowadays.

How about leveling this back up to something more usable like we'd expect from Microsoft. At least transfer or take ownership of the NuGet package into the current project team, or was it deliberately forgotten for some other reason. By the way if the NuGet package is definitely end-of-life then you should really go update the package description so developers don't waste time going in the wrong direction (it has 80K downloads so appears at the top of the search).

As NuGet is also available on VS Code and that means potentially cross-platform I suggest NuGet is still the way forward. I can't imagine any other reason why you would not want to update it, because a source ZIP is a bit too crude unless it's just a snapshot for the sake/license of open source, and you really just want to permanently include and maintain this inside of VS. But then if it's VS internal from the user (developer) perspective then we expect full "Visual"-Studio integration which means error window/action=suppression/code-fix (that is very dodgy at the moment and there are no code fixes).

So where's this all going? Can we make this easier to use and keep updated please it will also make it more popular and improve coding standards.  ;-)

**Comment by JordanMaples** [comment]
Ownership of the GSL and the NuGet package has changed hands a few times over the last few years. I was unaware that we even offered NuGet as a method of consuming GSL. Most of the usage I've seen has just been via submodules or vcpkg.

@sunnychatterjee, since you're listed as one of the owners of the nuget.org feed for GSL can you push an update to the feed?

**Comment by sunnychatterjee** [comment]
We no longer maintain the NuGet package. From October 2016, we have been releasing the GSL using vcpkg. Please refer to issue #410  for a discussion on this topic. Closing this issue.
