### ISSUE TITLE
not_null error with pointer with constant memory address

### ISSUE THREAD

**Issue by ScottHutchinson** [microsoft/GSL#871]
The code below results in this compiler error:
`error C2338: T cannot be assigned nullptr.`

```
    int someInt{};
    not_null<int* const> pInt = &someInt;
```
The error comes from this line in the `class not_null`: 
`static_assert(std::is_assignable<T&, std::nullptr_t>::value, "T cannot be assigned nullptr.");`

This happens in general when T is a pointer with constant memory address.

Shouldn't we be able to use `not_null` with a pointer with constant memory address?

Thanks

**Comment by beinhaerter** [comment]
Why not use `const not_null<int*> pInt = &someInt;` in your case? That way it is also more obvious what exactly is `const`.

**Comment by ScottHutchinson** [comment]
@beinhaerter Well, it's not at all obvious to me what that is. I feel that my way is much more obvious. Also, how would you write a not_null pointer that is **both** a pointer with constant memory address and a pointer to constant data? I would want to write it as `not_null<int const * const> pInt = &someInt;`.

**Comment by beinhaerter** [comment]
> how would you write a not_null pointer that is both a pointer with constant memory address and a pointer to constant data?

`const not_null<int const*> pInt = &someInt; `

**Comment by ScottHutchinson** [comment]
That's good enough, now that I know I need to write it like that. It would have saved a lot of time troubleshooting though, if I could have written it the other way too.

**Comment by hsutter** [comment]
Maintainers' call: Thanks! The issue appears to be resolved so we'll close this out. Thanks again.
