### ISSUE TITLE
gsl::narrow() terminates rather than throws

### ISSUE THREAD

**Issue by londey** [microsoft/GSL#872]
gsl::narrow's implementation has been changed to terminate rather than throw as documented in GSL and the C++ Core Guidelines.

The change appears to have been made while changing unit test frameworks here.
https://github.com/microsoft/GSL/commit/2b10729386062479641951e822e4257066655863

https://github.com/microsoft/GSL/blob/9f6a9a5807ad0de9c9c5294ece20639a5538f485/include/gsl/gsl_util#L108-L122

Was this change intentional?

**Comment by JordanMaples** [comment]
Thanks for pointing this out. This was an unintended side-effect of the contract violation behavior work. I'll re-introduce the throwing behavior for gsl::narrow.

**Comment by londey** [comment]
After further investigation it seems to have been broken since https://github.com/microsoft/GSL/commit/d846fe50a3f0bb7767c7e087a05f4be95f4da0ec where narrow was changed to be controlled by the same flag as contract violations.

**Comment by JordanMaples** [comment]
Thanks again for identifying this issue and submitting the fix.
