### ISSUE TITLE
GSL on Android

### ISSUE THREAD

**Issue by dipidoo** [microsoft/GSL#878]
As requested in "Supported Platforms" section in README, I am opening this issue to let you know that I got the tests to run and passing on Android https://github.com/dipidoo/GSL/runs/615740046?check_suite_focus=true built against API 16, tested on API 24.

I might follow up with iOS soon-ish.

**Comment by dipidoo** [comment]
Followed up with iOS in #883

**Comment by JordanMaples** [comment]
Thanks again for your work on this!
