### ISSUE TITLE
GSL on iOS

### ISSUE THREAD

**Issue by dipidoo** [microsoft/GSL#883]
As requested in "Supported Platforms" section in README, I am opening this issue to let you know that I got the tests to run and partially passing on iOS https://github.com/dipidoo/GSL/runs/644183147?check_suite_focus=true#step:7:459 tested on simulator.

However, this requires forcing `GTEST_HAS_DEATH_TEST` definition on the test, see https://github.com/dipidoo/GSL/commit/91858ca3f32c4c7d7704b7ed72043caa451377a3

googletest does not support EXPECT_DEATH in iOS platform, see how it tests for `!GTEST_OS_IOS`: https://github.com/google/googletest/blob/0eea2e9fc63461761dea5f2f517bd6af2ca024fa/googletest/include/gtest/internal/gtest-port.h#L592

By forcing `GTEST_HAS_DEATH_TEST` definition, I found that the test runs normally and successfully. I am unsure what the reasoning behind googletest's Death Test suppression for iOS platform is, but seeing that this is impacts test code only I feel that this definition is within reason. Let me know if you think it is appropriate for me to cherry-pick https://github.com/dipidoo/GSL/commit/91858ca3f32c4c7d7704b7ed72043caa451377a3 into the main fork.

**Comment by JordanMaples** [comment]
Thanks for your work validating iOS and Android. Yes, please submit a PR with the change. Would you mind including the Action workflow that you used to validate with this?

**Comment by dipidoo** [comment]
Sure, should I also edit README.md to reflect this?

**Comment by JordanMaples** [comment]
Yeah, that would be great.

**Comment by JordanMaples** [comment]
Thanks again for your work on this!
