### ISSUE TITLE
missing include directory on Mingw-w64

### ISSUE THREAD

**Issue by jwillikers** [microsoft/GSL#885]
On Mingw-w64, there is a compiler error indicating the GSL include directory is missing.
Specifically, it reports `_deps/gsl-src/include` is missing.

This appears to be caused by the `SYSTEM` keyword used in `target_include_directories` for the `GSL` target in GSL's CMakeLists.txt.
When I remove the `SYSTEM` keyword and reload the CMake project, I can build successfully without the compiler error.

## Configuration

GSL 3.0.1 is included as part of my CMake project using the [FetchContent module](https://cmake.org/cmake/help/latest/module/FetchContent.html).
My project links against the CMake target `Microsoft.GSL::GSL`.

## System

MSYS2 on Windows 10

## Toolchain

Mingw-w64 CMake 3.17.2
Mingw-w64 mingw32-makefiles
Mingw-w64 GCC 10.1.0

**Comment by JordanMaples** [comment]
Hi @jwillikers.  I am trying locally to reproduce the environment that you've described but I've hit a bit of a road block with getting the FetchContent module to behave. 

Which generator are you using for CMake? I'm not that familiar with Mingw, but it looks like issues with the `SYSTEM` keyword in Mingw can be fixed using the "MSYS Makefiles" generator.

**Comment by jwillikers** [comment]
@JordanMaples  I believe I was using the Ninja generator.
