### ISSUE TITLE
operator[] checks whether given index is valid.

### ISSUE THREAD

**Issue by aforster** [microsoft/GSL#889]
I was interested in the reasoning for this bound check here and why that it is not guarded by `#ifdef NDEBUG`:

https://github.com/microsoft/GSL/blob/master/include/gsl/span#L613

This can be quite a big performance hit. Are the maintainers interested in a pull request that changes the Expects/Ensures macros when NDEBUG is defined?

**Comment by grahamreeds** [comment]
Usually it is the at() that does the bound checking.  Does at() do bounds
checking?

**Comment by unixod** [comment]
Hi, 
Alternatively to NDEBUG I suggest to consider also #877 where I proposed to return back the configuration options for Expects/Ensures, which existed before.

**Comment by JordanMaples** [comment]
The intended behavior of gsl::span is to guarantee bounds safety in all access operations, which is why we intentionally do not wrap these checks in NDEBUG.

**Comment by aforster** [comment]
Ok, I guess if this is by design I will close the issue.

**Comment by ericLemanissier** [comment]
well, C++ standards says that it's a precondition that the index is valid https://eel.is/c++draft/span.elem#1
If gsl::span has different assumptions that std::span, it would be wise to use another name for the class, to avoid misleading your users

**Comment by JordanMaples** [comment]
Maintainer's call: We actually are following the span design on purpose, however the only difference is the bounds checking. The intent is to be able to simply using a different namespace and it will still work.
