### ISSUE TITLE
Removed const_iterator caused problems with boost::range

### ISSUE THREAD

**Issue by bishopnator** [microsoft/GSL#895]
Removed const_iterator type from gsl::span causes problems with boost::range - following function is not possible to compile:

#include <boost/adaptors/indexed.hpp>
#include <gsl/span>

```
void printPairs(const gsl::span<int>& nums)
{
   for(const auto& element : nums | boost::adaptors::indexed(0))
   {
       printf_s("%d - %d\n", static_cast<int>(element.index()), element.value());
   }
}
```
I tried several signatures and none of them work:
```
void printPairs(const gsl::span<int>& nums)
void printPairs(gsl::span<int>& nums)
void printPairs(gsl::span<int> nums)
```
It is necessary to construct new range using boost::make_iterator_range(nums.begin(), nums.end()) and then it works .. but it is IMO not nice.

It is sufficient to just add:
```using const_iterator = iterator;``` to the gsl::span declaration and then it works.

**Comment by JordanMaples** [comment]
Hi @bishopnator, thanks for filing this, however we will not be adding back gsl::span::const_iterator or gsl::span::const_reverse_iterator. The goal of gsl::span is to be directly aligned with std::span with the exception that gsl::span has bounds checking. Both const_iterator and const_reverse_iterator were removed from std::span in LWG3320.
