### ISSUE TITLE
Is MSVC 2015 supported?

### ISSUE THREAD

**Issue by WimLeflere** [microsoft/GSL#896]
Is MSVC 2015 supported?
It's not in the list of supported compilers.

From the README
> The implementation generally assumes a platform that implements C++14 support. There are specific workarounds to support MSVC 2015.

What are the required workarounds?

I get the following error when I try to use `gsl::narrow` in MSVC 2015
```
gsl_util: error C3250: 't': declaration is not allowed in 'constexpr' function body
```

**Comment by JordanMaples** [comment]
Hi @WimLeflere, MSVC 2015 is no longer officially supported. I missed cleaning up that from the readme when I removed MSVC 2015 support in #886. I'll create a new PR removing that, but back to the question at hand. 

The root of problem is MSVC 2015's constexpr support. In the [gsl_util changes](https://github.com/microsoft/GSL/pull/886/files#diff-91afae99e7c26887fe50666c6a26b8b4) for 886, you'll see that the MSVC 2015 work around was to remove constexpr with the macro `GSL_CONSTEXPR_NARROW`. If you need to get GSL working in VS2015, just remove the constexpr specifier on `narrow`.

**Comment by WimLeflere** [comment]
Thanks, that's what I expected.

GSL v3.0 or earlier would still support VS2015 I guess.
