### ISSUE TITLE
Namespace "Guide" is ambiguous. Prefer "GSL"

### ISSUE THREAD

**Issue by AndrewPardoe** [Microsoft/GSL#9]
The name of your codebase is GSL. Why do you have a separate abbreviation for the namespace? I'd prefer that your types be under "gsl::"

**Comment by gdr-at-ms** [comment]
Agreed.  Except probably 'gsl' -- lower caps :-)

**Comment by neilmacintosh** [comment]
All seems perfectly sensible to me. I'll prepare a PR in the next day or so.

**Comment by neilmacintosh** [comment]
Fixed by #104.
