### ISSUE TITLE
There should be an aclaration with the conflicting name gsl

### ISSUE THREAD

**Issue by Orion160x** [microsoft/GSL#902]
In the readme should be the aclaration that differentiates the Guidelines Support Library and the Gnu Scientific Library, and also differentiate the headers.

**Comment by JordanMaples** [comment]
Closing as there is no actionable items in this issue. There are no conflicting headers between the GSL and the GNU Scientific Library. It is also very clearly stated in the readme that this library is for the C++ Core Guidelines.
