### ISSUE TITLE
Regression in gsl::narrow - Cannot use GSL with exceptions disabled

### ISSUE THREAD

**Issue by phillipjohnston** [microsoft/GSL#905]
Issue #635 was reported for `gsl::narrow` preventing users from using GSL without exceptions. This was resolved. Commit 61534ca undid this change and made it so `narrow` once again generates a compilation error if exceptions are disabled. 

```
In file included from ../subprojects/GSL-3.1.0/include/gsl/gsl:23:
../subprojects/GSL-3.1.0/include/gsl/gsl_util:110:33: error: cannot use 'throw' with exceptions disabled
    if (static_cast<U>(t) != u) throw narrowing_error{};
                                ^
../subprojects/GSL-3.1.0/include/gsl/gsl_util:112:9: error: cannot use 'throw' with exceptions disabled
        throw narrowing_error{};
        ^
```

Can this be reverted to the `terminate` option, or at least something that works without exceptions?

See also: #468

**Comment by phillipjohnston** [comment]
Looks like this is tied to [release 3.0.1](https://github.com/microsoft/GSL/releases/tag/v3.0.1) which was explicitly made to undo this change...

**Comment by JordanMaples** [comment]
Maintainers' call: I'll refactor gsl::narrow into its own header. Thanks!
