### ISSUE TITLE
Avoiding __FUNCTION__, __FILE__, and __LINE__

### ISSUE THREAD

**Issue by hdf89shfdfs** [microsoft/GSL#918]
It is common in code bases to write a wrapper around the standard C assert.

However one of the common ways C asserts are wrapped is by using the following MACROs

```
__FUNCTION__
__FILE__
__LINE__
```

This is because then the error message will provide where the error occurred.

However, CppCoreGuidelines, are very anti-MACRO (as am I).

To summarize how can this be done in modern C++?

```
#define CustomAssertMacro(predicate, message) \
    CustomAssertFunction(predicate, \
        std::string(message) + std::string(__FILE__) + std::string(__FUNCTION__) + std::string(__LINE__) \
    );
```

**Comment by beinhaerter** [comment]
Starting with C++20 there is [`std::source_location`](https://en.cppreference.com/w/cpp/utility/source_location).

**Comment by hdf89shfdfs** [comment]
My god that is an amazing addition to C++20. I didn't know this existed thank you very much!

**Comment by hdf89shfdfs** [comment]
Sadly this doesn't seem to be available in MSVC yet. But regardless std::source_location is the exact answer to this problem.
