### ISSUE TITLE
Proposal, gsl::range

### ISSUE THREAD

**Issue by hdf89shfdfs** [microsoft/GSL#919]
Example:

I'm writing a window class.
My window class takes inputs for width/height.

```
uint64_t width  = 0;
uint64_t height = 0;

Window wnd(width, height)
```

So what's the problem?

The problem is a width/height of zero makes no sense.

It's very similar to gsl::not_null I think.

I want to make sure my input are valid, and if possible at compile time.

```
# The underlying type, min, max
gsl::range<uint64_t, 200, 10'000> width  = 200;
# FAILS TO COMPILE
gsl::range<uint64_t, 200, 10'000> height = 0;

# Now my inputs are guaranteed to be valid.
Window wnd(width, height)
```

To make it nicer I can just use "using".

```
using WindowDimension = gsl::range<uint64_t, 200, 10'000>;

WindowDimension width  = 200;

WindowDimension height = 0;

# Now my inputs are guaranteed to be valid.
Window wnd(width, height)
```

Apologies if this is an abnormal post/issue. But I thought it had some merit.

**Comment by JordanMaples** [comment]
Hi @hdf89shfdfs, Thanks for filing your proposal. I can see the use case for a type like this and and understand the motivations in creating it. However, this repository only implements types and concepts that are documented in the GSL section of the C++ Core Guidelines. Please post your proposal on the [CppCoreGuidelines](https://github.com/isocpp/cppcoreguidelines).

**Comment by JordanMaples** [comment]
I'm closing this issue for now. If the Core Guidelines accepts your proposal, please reopen the issue. Thanks!

**Comment by hdf89shfdfs** [comment]
Apologies for posting this in the incorrect place. Thank you very much for your prompt response.
