### ISSUE TITLE
Non-optimal code generation for narrow<long long int>(char)

### ISSUE THREAD

**Issue by HFriberg** [microsoft/GSL#926]
A quick test on Godbolt showed that the latest ICC compiler (v19.0.1) does not recognize that `char` can always be converted to `long long int` without loss of precision with the current implementation of `narrow`:
https://godbolt.org/z/73zPhG

I suggest wrapping the current implementation of `narrow` in a compile-time check on types, to see if there is any reason to check the values. Ideas:
1. One suggestion from stackoverflow I haven't tested is this:
```
if constexpr( !std::is_same<T, typename std::common_type<T,U>::type>::value )
```

2. Another suggestion is to use the `is_narrowing_conversion` definition from https://riccibruno.github.io/2018/04/27/c++_is_narrowing_conversion_type_trait/.

**Comment by carsonRadtke** [comment]
@HFriberg Thank you for raising this issue. Apologies for not getting around to it sooner.

At this point, ICX has replaced ICC and I could not find a version of ICX on compiler explorer that suffers from the same issue. Closing as I don't think we will work-around a bug in a deprecated compiler.
