### ISSUE TITLE
gsl::narrowing_error has no helpful what()

### ISSUE THREAD

**Issue by mattgodbolt** [microsoft/GSL#927]
My app has a top-level catch(exception) that prints the e.what(). A narrowing error was thrown and I spent a bunch of time debugging why mode code printed:

```
Unhandled exception: std::exception
```

It seems the `gsl::narrowing_error` derives directly from `std::exception` and inherits its default (rather unhelpful) "what" string. It would be nice if it including at least `narrowing_error`, but ideally would explain the actual failed comparison.

**Comment by JordanMaples** [comment]
Thanks for bringing this to my attention @mattgodbolt.
