### ISSUE TITLE
gsl_narrow cannot be used without exceptions

### ISSUE THREAD

**Issue by mtnpke** [microsoft/GSL#932]
Some targets (e.g., WDK) do not provide C++ exception handling. It would be good to allow the use of narrow() anyhow by terminating the program in case of error instead of throwing an exception.

I have a patch for this ready if the issue is accepted.

**Comment by SloppyJaconda** [comment]
You'll need to raise an issue on the CppCoreGuidelines to change the design of `gsl::narrow`. The GSL spec specifically calls out `narrow` as throwing a `narrowing_error` on failure. It's the only thing in GSL that is specified to throw.

**Comment by mtnpke** [comment]
This is basically isocpp/CppCoreGuidelines#1172, which has been stale for 2 years. Meanwhile, I think it would be justifiable and desirable to offer an option here to use `narrow` without exceptions if the user specifically asks for it. It could also be auto-activated when no exceptions are available, but I can see how that could cause issues in the future in the case that CppCoreGuidelines does define some behavior for this and it differs from aborting. As it stands, `gsl::narrow` just cannot be used in no-exception environments. I can't even include the header.

**Comment by SloppyJaconda** [comment]
> As it stands, gsl::narrow just cannot be used in no-exception environments. I can't even include the header.

Yes, that's why I split narrow into its own file in #910, so that the rest of the GSL can be used in no exception mode. Again, if you want gsl::narrow to be redefined to not throw, raise an issue with the CppCoreGuidelines.
