### ISSUE TITLE
Please add GSL_* prefix to VS_ADD_NATIVE_VISUALIZERS

### ISSUE THREAD

**Issue by hdf89shfdfs** [microsoft/GSL#934]
Without this necessary prefix this cache variable goes to the ungrouped entries category.

Here is an example picture:

![image](https://user-images.githubusercontent.com/31327577/95609028-114c8b80-0a2c-11eb-91a5-1b6647841e1b.png)

This is confusing for cmake-gui/ccmake users.

Instead the issue will be fixed if the cache variable is renamed to GSL_VS_ADD_NATIVE_VISUALIZERS.

**Comment by JordanMaples** [comment]
This seems like a pretty straight forward fix, please file a PR with the fix. Thanks.
