### ISSUE TITLE
gsl/gsl does not include gsl_narrow

### ISSUE THREAD

**Issue by bowie7070** [microsoft/GSL#938]
From the documentation it is intended that the gsl library be used with the following:

`#include <gsl/gsl>`

gsl/gsl includes most of the other gsl include files but it omits gsl/gsl_narrow. Please add an include of gsl/gsl_narrow to gsl/gsl.

**Comment by JordanMaples** [comment]
Please submit a PR adding this change to <gsl/gsl>. 

`gsl_narrow` is only element in GSL that uses exceptions, so please ensure in you PR that it is only included if it is being used in an environment that supports exceptions. Thanks.

**Comment by bowie7070** [comment]
Please see PR https://github.com/microsoft/GSL/pull/939
