### ISSUE TITLE
finally doesn't work properly without rvo optimisations

### ISSUE THREAD

**Issue by AntonBikineev** [Microsoft/GSL#94]
finally function heavily relies on rvo optimisation. If you compile with -fno-elide-constructor, you'll get util_tests errors

**Comment by neilmacintosh** [comment]
This was resolved recently by PR #90.

**Comment by jbcoe** [comment]
I can't reproduce this issue. 

I believe it was fixed by ae24c0fe06f92a2a77fb4dbd0098335519a54390 and earlier commits.

**Comment by AntonBikineev** [comment]
@neilmacintosh @jbcoe Yes, it seems we did the same job at the same time :)
