### ISSUE TITLE
Cmake Deprecation Warning | GoogleTest

### ISSUE THREAD

**Issue by hdf89shfdfs** [microsoft/GSL#952]
I'm currently using cmake 3.19 and am getting these deprecation warnings when configured GSL as a standalone project.

```
CMake Deprecation Warning at build/tests/googletest-src/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

Is there any plan to do something about this?

**Comment by JordanMaples** [comment]
There's currently an issue, google/googletest#3040, and a PR, google/googletest#3094, that would clear this up. Once it's merged, I will update the GoogleTest version.

**Comment by JordanMaples** [comment]
Looks like they merged 3094, so I'll start updating GoogleTest on Monday.
