### ISSUE TITLE
Why are these compile definitions neccessary?

### ISSUE THREAD

**Issue by hdf89shfdfs** [microsoft/GSL#956]
https://github.com/microsoft/GSL/blob/0140ab1d73d833d2b1eca37d1b3b91e52dda4176/CMakeLists.txt#L39-L49

I compiled and ran all tests locally and didn't get any compiler errors? 

Maybe they were necessary in the past?

**Comment by JordanMaples** [comment]
Yeah, the `catch` comment definitely makes me think this can be removed. I'm not sure what the `_SCL_SECURE_NO_WARNINGS` was originally used for. I'll dig into it on Monday and see if we can remove it. Would you mind filing a PR removing these? Thanks.
