### ISSUE TITLE
[cmake] GSL " Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.27.0.windows.1")"

### ISSUE THREAD

**Issue by hdf89shfdfs** [microsoft/GSL#960]
https://github.com/microsoft/GSL/blob/a6cef6bc6c6daa4710cf0b6e5bcfd40a3908baa1/CMakeLists.txt#L9

GSL looks for Git even though it isn't always necessary.

```
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.27.0.windows.1") 
```

A minor optimization for configure time would be to only look for Git when testing is enabled. As a small quality of life for users.

It's good practice to minimize configure time for cmake projects.

**Comment by JordanMaples** [comment]
Are you suggesting that the `find_package` line isn't necessary or that it can be relocated to help configuration time?

**Comment by hdf89shfdfs** [comment]
Correct the call can be relocated to help configuration time:

Try using FetchContent (https://cmake.org/cmake/help/latest/module/FetchContent.html) or Cmake Package Manger (https://github.com/TheLartians/CPM.cmake)

```cmake
    CPMAddPackage(
        NAME GSL
        GITHUB_REPOSITORY "Microsoft/GSL"
        VERSION "3.1.0"
        GIT_SHALLOW ON
    )
```

Here is example output from my project:
```
-- Building for: Visual Studio 16 2019
-- The CXX compiler identification is MSVC 19.28.29333.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
--  adding package GSL@3.1.0 (D:/Git/cpm_source_cache/gsl/0746477a58301b687104ac097be39737dc1ceef3)
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.27.0.windows.1") <-----------------------------------------------------
--  adding package magicEnum@0.7.0 (D:/Git/cpm_source_cache/magicenum/3b7b0ee113d60d2ec0297d4c8d1f628a818b67cf)
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Git/PitoUtility/build
```

**Comment by hdf89shfdfs** [comment]
I believe GSL only uses Git when testing. I'm not sure how much it would really help configuration time. 

But it's good practice to minimize output to STATUS when using cmake's message call.
