### ISSUE TITLE
Investigate iOS failing test

### ISSUE THREAD

**Issue by JordanMaples** [microsoft/GSL#971]
The GitHub Action for iOS is disabled due to failures in `no_exception_ensure_test`. 

The test should have exit code = `0` if the test correctly executes the termination handler. Currently, the test exits with `-1`.

**Comment by rishitc** [comment]
Hi,
I want to help in resolving this issue, but I'm confused on how to setup my local development environment to test my fixes.
To test my fixes locally should I try building the library on Xcode with the build target set to iPhone? 
Any guidance on how I can setup my local environment (system running MacOS) to test my fixes, would be helpful in working on the issue.

Waiting for your feedback,

Thanks.

**Comment by JordanMaples** [comment]
Hi @rishitc, I'm not familiar with how the iOS tests were created and validated. They were contributed by @dipidoo and disabled when the tests started failing. 

@dipidoo, would you mind sharing with @rishitc how to locally set up the environment to validate GSL for iOS? Thanks.
