### ISSUE TITLE
basic_zstring_span::empty() should return true for string ""

### ISSUE THREAD

**Issue by travnick** [microsoft/GSL#973]
In my opinion since `basic_zstring_span` represents a null-terminated string then it's not true that `""` is not empty

it should behave the same as std::string("").empty()

https://github.com/microsoft/GSL/blob/2231d733c6df2f0fe1c9f41460e1997a3f77249a/include/gsl/string_span#L413

**Comment by JordanMaples** [comment]
Thanks for filing this issue. Just so you are aware, `string_span` and all of it's variants have been deprecated from the GSL and removed from the C++ Core Guidelines with isocpp/cppcoreguidelines#1680. Generally we don't take changes to deprecated components unless they're generating warnings or errors in compilation.
