### ISSUE TITLE
Instllation not clear: How to simply install with CMake?

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [microsoft/GSL#979]
### Question

Given a super basic CMake project: [gsl-test.zip](https://github.com/microsoft/GSL/files/6252966/gsl-test.zip)

`main.cpp`:
```cpp
#include <iostream>

// How to make this work?
// #include <gsl/gsl>

int main() {
    std::cout << "Hello World!" <<std::endl;
}
```
`CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.16)

project (hello_cmake)

add_executable(${PROJECT_NAME} main.cpp)
```

What is the simplest way to use GSL in this context?

(I'm pretty stuck here, so would really appreciate an example)

### Attempts

I looked at [Usage in CMake](https://github.com/microsoft/GSL#usage-in-cmake) but this notes `The library provides a Config file for CMake, once installed it can be found via`, emphasis on `once installed`.

So I tried [Building GSL - Using vcpkg](https://github.com/microsoft/GSL#building-gsl---using-vcpkg), but following:
```bash
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.sh
./vcpkg integrate install
vcpkg install ms-gsl
```
Ultimately leads to:
```bash
jonathan@jonathan-MS-7B22:~/vcpkg$ vcpkg install ms-gsl
vcpkg: command not found
jonathan@jonathan-MS-7B22:~/vcpkg$
```
so that isn't right.

Despite the seemingly exclusionary note I looked back at [Usage in CMake](https://github.com/microsoft/GSL#usage-in-cmake) and thought I might as well try [FetchContent](https://github.com/microsoft/GSL#fetchcontent).

So changing my `CMakeLists.txt` to:
```cmake
cmake_minimum_required(VERSION 3.16)

project (hello_cmake)

# add_executable(${PROJECT_NAME} main.cpp)

include(FetchContent)

# In this example we are picking a specific tag.
# You can also pick a specific commit, if you need to.
FetchContent_Declare(GSL
    GIT_REPOSITORY "https://github.com/microsoft/GSL"
    GIT_TAG "v3.1.0"
)

FetchContent_MakeAvailable(GSL)

# Now you can link against the GSL interface library
add_executable(${PROJECT_NAME} main.cpp)

# Link against the interface library (IE header only library)
target_link_libraries(${PROJECT_NAME} PRIVATE GSL)
```
Does seem to allow the project to build with `#include <gsl/gsl>` and not throw any errors.

But replacing `main.cpp` with an example as given at http://www.gnu.org/software/gsl/doc/html/usage.html#an-example-program:
```cpp
#include <stdio.h>
#include <gsl/gsl_sf_bessel.h>

int
main (void)
{
  double x = 5.0;
  double y = gsl_sf_bessel_J0 (x);
  printf ("J0(%g) = %.18e\n", x, y);
  return 0;
}
```
Now leads to:
```
[main] Building folder: gsl-test 
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/jonathan/Projects/gsl-test/build --config Debug --target all -- -j 14
[build] Scanning dependencies of target hello_cmake
[build] [ 50%] Building CXX object CMakeFiles/hello_cmake.dir/main.cpp.o
[build] /home/jonathan/Projects/gsl-test/main.cpp:2:10: fatal error: gsl/gsl_sf_bessel.h: No such file or directory
[build]     2 | #include <gsl/gsl_sf_bessel.h>
[build]       |          ^~~~~~~~~~~~~~~~~~~~~
[build] compilation terminated.
[build] make[2]: *** [CMakeFiles/hello_cmake.dir/build.make:63: CMakeFiles/hello_cmake.dir/main.cpp.o] Error 1
[build] make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/hello_cmake.dir/all] Error 2
[build] make: *** [Makefile:130: all] Error 2
[build] Build finished with exit code 2
```

### A note

Ideally installation instructions would be given like:

##### Method 1: Using x
1. Do a
2. Do b
3. ...
##### Method 2: Using y
1. Do z
2. Do y
3. ...

**Comment by luncliff** [comment]
For vcpkg, you need a relative path to use the `vcpkg` executable. Should be like this.

```console
user@host:~/vcpkg$ ./bootstrap-vcpkg.sh
...
user@host:~/vcpkg$ ./vcpkg install ms-gsl
...
```

Or, for Windows,

```console
PS C:\vcpkg> .\bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-02-24-d67989bce1043b98092ac45996a8230a059a2d7e/vcpkg.exe -> C:\vcpkg/vcpkg.exe
Done.
...
PS C:\vcpkg> .\bootstrap-vcpkg.bat
PS C:\vcpkg> .\vcpkg.exe install --triplet x64-windows ms-gsl     
Computing installation plan...
The following packages will be built and installed:
    ms-gsl[core]:x64-windows -> 3.1.0
...
Installing package ms-gsl[core]:x64-windows... done
Elapsed time for package ms-gsl:x64-windows: 3.79 s

Total elapsed time: 6.506 s

The package ms-gsl:x64-windows provides CMake targets:

    find_package(Microsoft.GSL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Microsoft.GSL::GSL)

```

**Comment by JordanMaples** [comment]
Hi @JonathanWoollett-Light,

Did the response from @luncliff solve your problem configuring ms-gsl with vcpkg?

Following up on a later note in your post:
> But replacing main.cpp with an example as given at http://www.gnu.org/software/gsl/doc/html/usage.html#an-example-program:

The Microsoft GSL is _not_ related to the GNU Scientific Library. This repo is Microsoft's implementation of the [C++ Core Guidelines](github.com/isocpp/cppcoreguidelines), [Guideline Support Library](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#gsl-guidelines-support-library). 
If you need access to the GNU Scientific Library, you can install it via VCPkg with `vcpkg install gsl`.
