### ISSUE TITLE
Add .clang-tidy file to enforce coding conventions

### ISSUE THREAD

**Issue by jbcoe** [microsoft/GSL#98]
A .clang-tidy file would allow checks to be run to ensure that code style is consistent.

**Comment by neilmacintosh** [comment]
Absolutely @jbcoe! We already have a .clang-format file. If you'd like to offer a PR with a .clang-tidy file I'd be happy to look at it.

**Comment by neilmacintosh** [comment]
This still seems like a reasonable idea if anyone would like to contribute the PR. clang does offer a bunch of checks for the C++ Core Guidelines, and it seems reasonable to automatically apply them to this code.

**Comment by JordanMaples** [comment]
Maintainers' call: Sorry we never got around to this.
