### ISSUE TITLE
Support PlatformIO seamlessly

### ISSUE THREAD

**Issue by kroppt** [microsoft/GSL#980]
To begin, [PlatformIO](https://platformio.org/) is a platform for both hobby and professional firmware development. I am currently switching to using it for writing firmware as a way to consolidate the build and development environments for all the microcontrollers I write firmware for. I am not familiar with how many users use GSL in this context.

I am looking to use this library directly in a PlatformIO project. There is currently no package available in the [package registry](https://platformio.org/lib) for this library. When specifying the library's git URL in a project's [`lib_deps`](https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-deps) field, building will produce errors, because PlatformIO will be trying to compile test code.

The two main ways of providing seamless support for users of PlatformIO (as far as I'm aware) are:
- Provide a [`library.json`](https://docs.platformio.org/en/latest/librarymanager/config.html) file, which allows it to be referenced by git URL and release tag
- Upload the library to the package registry as a part of the release process, which can be referenced by package ID

The following are valid workarounds I have thought of:
- Maintain a fork of GSL that contains a PlatformIO library file, and reference the forked library by URL
- Store the library locally with a PlatformIO library file, and reference the library by file path
- Reference the library as a git submodule, and manually include the appropriate directory in the PlatformIO project file's [`build_flags`](https://docs.platformio.org/en/latest/projectconf/section_env_build.html#build-flags) field (most convenient of the three options here)

A minimal example of a [`library.json`](https://docs.platformio.org/en/latest/librarymanager/config.html) is:
```json
{
    "name": "gsl",
    "version": "3.1.0",
    "description": "Guidelines Support Library",
    "keywords": [],
    "export": {
        "include": ["include/*"]
    },
    "build": {
        "includeDir": "include",
        "libArchive": false
    }
}
```
I am currently able to build with this example manifest located in the root folder of a local clone of this repository.

According to the maintainers, PlatformIO uses a native build system, not any external build system (such as CMake).

**Comment by JordanMaples** [comment]
Hi @kroppt, 

Thank you for the interest in making GSL available to PlatformIO users and for your initial investigation. 

Your approach of referencing GSL as a git submodule in your project is probably the best approach for now. I will investigate the changes necessary to add GSL to the package registry for PlatformIO and discuss pursuing that option with the other maintainers the next time we meet. 

In the meantime, can you point me to any onboarding resources to jumpstart the investigation from our side?

-Jordan

**Comment by kroppt** [comment]
The most relevant information appears to be available here: [Library Management](https://docs.platformio.org/en/latest/librarymanager/index.html)
Two notable sections are: [Quick Start](https://docs.platformio.org/en/latest/librarymanager/quickstart.html), [Creating Library](https://docs.platformio.org/en/latest/librarymanager/creating.html)
When more information is available in other portions of the documentation, it's usually linked inline.

**Comment by hsutter** [comment]
Editors call: We didn't get to this, sorry, and if there is still interest in this please reopen.

**Comment by MacDada** [comment]
I don't know if there is a (big/wide) interest, but at least I did subscribe to this issue ;-)

BTW, it is possible to use any gh repo within the `platformio.ini` config:

```ini
lib_deps = 
    https://github.com/microsoft/GSL.git
```

But then, it only the latest master, without any kind of versioning (at least that I know of). Having GSL [in the PIO registry](https://registry.platformio.org/) would be a much better option.

I could figure it out and make a PR if that was desirable.
