### ISSUE TITLE
Cannot create gsl::span<char> from std::string

### ISSUE THREAD

**Issue by stertingen** [microsoft/GSL#987]
One Compiler Explorer says more than a thousand words: https://godbolt.org/z/j4xnvdq8o

(`string_span` works, but since it's deprecated, I would rather not use it.)

**Comment by JordanMaples** [comment]
Thanks for pointing this out. I took a quick look at your repro and have a few notes, some of them should unblock you while a more fix is prepared.
 - The code as provided works in C++17, but not C++14.
 - Changing the type of the span in C++14 from `char` to `const char` makes it compile.
 - Changing the arguments to the span constructor to address + length, also will compile in C++14. `gsl::span<char> bar(&foo[0], foo.size());`

**Comment by stertingen** [comment]
Oh, I get it. In C++17, `std::string::data()` returns `char*`, in C++14 it returns `const char*`.

**Comment by stertingen** [comment]
I would provide a PR with a pre-C++17 workaround for std::basic_string. Would this behavior be desired?

**Comment by JordanMaples** [comment]
Maintainer's call:
We don't want to do something special for c++14, but if you use a `span<const char>` it will work for both 14 and 17 strings for both `gsl::span` and `std::span`.
