### ISSUE TITLE
as_bytes() as implemented is undefined behavior in C++20

### ISSUE THREAD

**Issue by daviddetweiler** [microsoft/GSL#994]
[This](http://open-std.org/JTC1/SC22/WG21/docs/papers/2019/p1839r2.pdf) paper from 2019 seems to show that the `reinterpret_cast<>`-based inspection of the object representation is undefined behavior as of C++20.

**Comment by JordanMaples** [comment]
Thanks, we'll look through the document and make sure this is discussed at the next maintainers sync.

**Comment by cubbimew** [comment]
The EWG poll in that paper is unanimous that it is a defect, thus it will apply retroactively to past C++ revisions when approved.

**Comment by frederick-vs-ja** [comment]
This is a C++ core issue and should be resolved by the final revision of that paper. IMO `as_bytes` is itself OK and can be kept unchanged.

**Comment by dmitrykobets-msft** [comment]
Closing, since as per the above discussion, no changes need to be made.
