### ISSUE TITLE
Warning 26496 query about const pointer

### ISSUE THREAD

**Issue by ajtruckle** [microsoft/GSL#997]
Take this code:

```
#pragma warning(suppress: 26496)
    gsl::not_null<CChristianLifeMinistryEntry*> pReplacement = m_mapSwapWeekendAssignments[nID];
```
Note that I have opted to suppress the warning. The reason being that later in this code I do this:

`setter(pReplacement, strExistingName);`

The `setter` is a templated pfunction parameter to the function. Example:```

```
void CWeekendMeetingDlg::OnSwapWithWTBibleVersesReaderAssignment(UINT nID)
{
	auto getter = [](CChristianLifeMinistryEntry* pReplacement)
	{
		S_TALK_INFO sPTI = pReplacement->GetPublicTalkInfo();
		return sPTI.strBibleVersesReader;
	};
	auto setter = [](CChristianLifeMinistryEntry* pReplacement, CString& strExistingName)
	{
		S_TALK_INFO sPTI = pReplacement->GetPublicTalkInfo();
		sPTI.strBibleVersesReader = strExistingName;
		pReplacement->SetPublicTalkInfo(sPTI);
	};
	CWeekendMeetingDlg::OnSwapWith(
		getter, setter, nID, IDC_COMBO_PT_BIBLE_VERSES_READER, IDS_STR_SWAP_WT_BIBLE_VERSES_READER);
}
```

As you can see, the `setting` modified the contents of the pointer:

`pReplacement->SetPublicTalkInfo(sPTI);`

I am new to this gsl concept so most likely my understanding is flawed. Given the context, should my `pReplacement` point be matked as `const` or not? I felt not.

**Comment by beinhaerter** [comment]
If I understand you right, then the value of `pReplacement` will not change after construction, but the `CChristianLifeMinistryEntry` that `pReplacement` points to might change. That means that the `CChristianLifeMinistryEntry` cannot be `const`:

    gsl::not_null<const CChristianLifeMinistryEntry*> pReplacement = m_mapSwapWeekendAssignments[nID];

but the `pReplacement` can be `const`:

    const gsl::not_null<CChristianLifeMinistryEntry*> pReplacement = m_mapSwapWeekendAssignments[nID];

Which is what the compiler wants to tell you. If you look the exact warning, it should say that `pReplacement` can be marked `const`.

**Comment by ajtruckle** [comment]
Thanks for the explanation.
